# Indian Crime Dataset — Common Schema Integration & EDA

## Objective

This notebook builds a new unified Indian crime dataset from the original
crime-related CSV files stored in:

`data/raw/crime_data/`

The raw source files will remain completely untouched.

The workflow will:

1. Discover and inventory all source CSV files.
2. Inspect their schemas, data types, row counts, and sample records.
3. Determine what each dataset and row represents.
4. Identify semantically comparable features across datasets.
5. Establish a small common schema based on actual evidence from the datasets.
6. Classify datasets according to compatibility with the common schema.
7. Standardize only compatible datasets.
8. Combine compatible records row-wise.
9. Validate the resulting unified dataset.
10. Perform exploratory data analysis (EDA).

### Important principles

- Raw files are never modified.
- No assumptions are made about what a row represents.
- Similar column names are not automatically treated as equivalent.
- Incompatible datasets will not be forced into the unified dataset.
- Missing values will not automatically be replaced with zero.
- The final integration will use row-wise concatenation, not STATE + YEAR merging.
- Every integrated record will retain its source dataset identifier.
- The common schema will be established only after inspecting the actual datasets.

In [3]:
# ============================================================
# CELL 2 — IMPORT LIBRARIES AND DEFINE PROJECT PATHS
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np
import json
import re
import warnings

warnings.filterwarnings("ignore")

# ------------------------------------------------------------
# Locate the project root
# ------------------------------------------------------------
# The notebook is inside:
#
# Crime_Analysis/notebooks/
#
# Therefore the project root is one level above the notebook
# working directory.

CURRENT_DIR = Path.cwd()

if (CURRENT_DIR / "data" / "raw" / "crime_data").exists():

    # If Jupyter is running from Crime_Analysis/
    PROJECT_ROOT = CURRENT_DIR

elif (CURRENT_DIR.parent / "data" / "raw" / "crime_data").exists():

    # If Jupyter is running from Crime_Analysis/notebooks/
    PROJECT_ROOT = CURRENT_DIR.parent

else:

    raise FileNotFoundError(
        "Could not locate the Crime_Analysis project root.\n\n"
        "Expected to find:\n"
        "data/raw/crime_data/\n\n"
        f"Current directory:\n{CURRENT_DIR.resolve()}"
    )

# ------------------------------------------------------------
# Define project directories
# ------------------------------------------------------------

RAW_DATA_DIR = (
    PROJECT_ROOT / "data" / "raw" / "crime_data"
)

PROCESSED_DATA_DIR = (
    PROJECT_ROOT / "data" / "processed"
)

TABLES_DIR = (
    PROJECT_ROOT / "outputs" / "tables"
)

FIGURES_DIR = (
    PROJECT_ROOT / "outputs" / "figures"
)

# ------------------------------------------------------------
# Create output directories if needed
# ------------------------------------------------------------
# This does NOT touch the raw CSV files.

PROCESSED_DATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)

TABLES_DIR.mkdir(
    parents=True,
    exist_ok=True
)

FIGURES_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------

EXPECTED_FILE_COUNT = 76

CSV_ENCODINGS = [
    "utf-8",
    "utf-8-sig",
    "cp1252",
    "latin1"
]

# ------------------------------------------------------------
# Display paths
# ------------------------------------------------------------

print("=" * 70)
print("PROJECT PATH CONFIGURATION")
print("=" * 70)

print("\nCurrent working directory:")
print(CURRENT_DIR.resolve())

print("\nProject root:")
print(PROJECT_ROOT.resolve())

print("\nRaw data directory:")
print(RAW_DATA_DIR.resolve())

print("\nProcessed data directory:")
print(PROCESSED_DATA_DIR.resolve())

print("\nTables directory:")
print(TABLES_DIR.resolve())

print("\nFigures directory:")
print(FIGURES_DIR.resolve())

print("\n✓ Path configuration completed.")

======================================================================
PROJECT PATH CONFIGURATION
======================================================================

Current working directory:
D:\Major_Project\Crime_Analysis\notebooks

Project root:
D:\Major_Project\Crime_Analysis

Raw data directory:
D:\Major_Project\Crime_Analysis\data\raw\crime_data

Processed data directory:
D:\Major_Project\Crime_Analysis\data\processed

Tables directory:
D:\Major_Project\Crime_Analysis\outputs\tables

Figures directory:
D:\Major_Project\Crime_Analysis\outputs\figures

✓ Path configuration completed.

In [4]:
# ============================================================
# CELL 3 — DISCOVER ALL CSV FILES
# ============================================================

# Find every CSV file inside data/raw/crime_data/
# Recursively, without modifying any source file.

csv_files = sorted(
    [
        file_path
        for file_path in RAW_DATA_DIR.rglob("*")
        if file_path.is_file()
        and file_path.suffix.lower() == ".csv"
    ],
    key=lambda x: x.name.lower()
)

print("=" * 70)
print("CSV FILE DISCOVERY")
print("=" * 70)

print(f"\nRaw data directory:")
print(RAW_DATA_DIR.resolve())

print(f"\nNumber of CSV files found: {len(csv_files)}")
print(f"Expected number of CSV files: {EXPECTED_FILE_COUNT}")

if len(csv_files) == EXPECTED_FILE_COUNT:
    print("\nSTATUS: ✓ Exactly 76 CSV files found.")
elif len(csv_files) > EXPECTED_FILE_COUNT:
    print("\nSTATUS: ⚠ More than 76 CSV files found.")
else:
    print("\nSTATUS: ⚠ Fewer than 76 CSV files found.")

print("\n" + "-" * 70)
print("DISCOVERED FILES")
print("-" * 70)

for i, file_path in enumerate(csv_files, start=1):
    print(f"{i:02d}. {file_path.name}")

======================================================================
CSV FILE DISCOVERY
======================================================================

Raw data directory:
D:\Major_Project\Crime_Analysis\data\raw\crime_data

Number of CSV files found: 76
Expected number of CSV files: 76

STATUS: ✓ Exactly 76 CSV files found.

----------------------------------------------------------------------
DISCOVERED FILES
----------------------------------------------------------------------
01. 01_District_wise_crimes_committed_IPC_2001_2012.csv
02. 01_District_wise_crimes_committed_IPC_2013.csv
03. 01_District_wise_crimes_committed_IPC_2014.csv
04. 02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
05. 02_01_District_wise_crimes_committed_against_SC_2013.csv
06. 02_01_District_wise_crimes_committed_against_SC_2014.csv
07. 02_District_wise_crimes_committed_against_ST_2001_2012.csv
08. 02_District_wise_crimes_committed_against_ST_2013.csv
09. 02_District_wise_crimes_committed_against_ST_2014.csv
10. 03_District_wise_crimes_committed_against_children_2001_2012.csv
11. 03_District_wise_crimes_committed_against_children_2013.csv
12. 03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2012.csv
13. 03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2013.csv
14. 03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2014.csv
15. 04_01_Person_arrested_and_their_disposal_by_police_and_court_SLL_crime_2012.csv
16. 04_01_Person_arrested_and_their_disposal_by_police_and_court_SLL_crime_2013.csv
17. 04_01_Person_arrested_and_their_disposal_by_police_and_court_SLL_crime_2014.csv
18. 04_02_Person_arrested_and_their_disposal_by_police_and_court_IPC_crime_2012.csv
19. 04_02_Person_arrested_and_their_disposal_by_police_and_court_IPC_crime_2013.csv
20. 04_02_Person_arrested_and_their_disposal_by_police_and_court_IPC_crime_2014.csv
21. 07_01_Persons_arrested_by_sex_and_age_group_IPC_2012.csv
22. 07_01_Persons_arrested_by_sex_and_age_group_IPC_2013.csv
23. 07_01_Persons_arrested_by_sex_and_age_group_IPC_2014.csv
24. 07_02_Persons_arrested_by_sex_and_age_group_SLL_2012.csv
25. 07_02_Persons_arrested_by_sex_and_age_group_SLL_2013.csv
26. 07_02_Persons_arrested_by_sex_and_age_group_SLL_2014.csv
27. 08_01_Juvenile_apprehended_state_IPC.csv
28. 08_02_Juvenile_apprehended_state_SLL.csv
29. 09_Juveniles_arrested_and_their_disposal.csv
30. 10_Property_stolen_and_recovered.csv
31. 11_Property_stolen_and_recovered_nature_of_property.csv
32. 12_Police_strength_actual_and_sanctioned.csv
33. 13_Police_killed_or_injured_on_duty.csv
34. 14_Age_profile_of_police_personnel_killed_on_duty.csv
35. 15_Police_natural_death_and_suicide.csv
36. 16_Casualties_under_police_firing_and_lathi_charge.csv
37. 17_Case_reported_and_value_of_property_taken_away_by_place_of_occurrence_2001_2012.csv
38. 17_Case_reported_and_value_of_property_taken_away_by_place_of_occurrence_2013.csv
39. 17_Crime_by_place_of_occurrence_2001_2012.csv
40. 17_Crime_by_place_of_occurrence_2013.csv
41. 17_Crime_by_place_of_occurrence_2014.csv
42. 18_01_Juveniles_arrested_Education.csv
43. 18_02_Juveniles_arrested_Economic_setup.csv
44. 18_03_Juveniles_arrested_Family_background.csv
45. 18_04_Juveniles_arrested_Recidivism.csv
46. 19_Motive_or_cause_of_murder_and_culpable_homicide_not_amounting_to_murder.csv
47. 20_Victims_of_rape.csv
48. 21_Offenders_known_to_the_victim.csv
49. 22_Persons_arrested_under_recidivism.csv
50. 23_Anti_corruprion_cases.csv
51. 24_Anti_corruption_arrests.csv
52. 25_Complaints_against_police.csv
53. 27_Nature_of_complaints_received_by_police.csv
54. 28_Trial_of_violent_crimes_by_courts.csv
55. 29_Period_of_trials_by_courts.csv
56. 30_Auto_theft.csv
57. 31_Serious_fraud.csv
58. 32_Murder_victim_age_sex.csv
59. 33_CH_not_murder_victim_age_sex.csv
60. 34_Use_of_fire_arms_in_murder_cases.csv
61. 35_Human_rights_violation_by_police.csv
62. 36_Police_housing.csv
63. 37_Home_guards_and_auxilliary_force.csv
64. 38_Unidentified_dead_bodies_recovered_and_inquest_conducted.csv
65. 39_Specific_purpose_of_kidnapping_and_abduction.csv
66. 40_01_Custodial_death_person_remanded.csv
67. 40_02_Custodial_death_person_not_remanded.csv
68. 40_03_Custodial_death_during_production.csv
69. 40_04_Custodial_death_during_hospitalization_or_treatment.csv
70. 40_05_Custodial_death_others.csv
71. 41_Escapes_from_police_custody.csv
72. 42_Cases_under_crime_against_women.csv
73. 42_District_wise_crimes_committed_against_women_2001_2012.csv
74. 42_District_wise_crimes_committed_against_women_2013.csv
75. 42_District_wise_crimes_committed_against_women_2014.csv
76. 43_Arrests_under_crime_against_women.csv

In [5]:
# ============================================================
# CELL 4 — VERIFY SOURCE FILE LOCATIONS
# ============================================================

print("=" * 70)
print("SOURCE FILE LOCATION VERIFICATION")
print("=" * 70)

outside_expected_folder = []

for file_path in csv_files:

    try:
        file_path.relative_to(RAW_DATA_DIR)
    except ValueError:
        outside_expected_folder.append(file_path)

if len(outside_expected_folder) == 0:

    print("\n✓ All discovered CSV files are inside:")
    print(RAW_DATA_DIR.resolve())

else:

    print(
        f"\n⚠ {len(outside_expected_folder)} files "
        "were found outside the expected directory."
    )

    for file_path in outside_expected_folder:
        print(file_path.resolve())

print("\nRaw files will remain untouched.")

======================================================================
SOURCE FILE LOCATION VERIFICATION
======================================================================

✓ All discovered CSV files are inside:
D:\Major_Project\Crime_Analysis\data\raw\crime_data

Raw files will remain untouched.

In [6]:
# ============================================================
# CELL 5 — ROBUST CSV READER
# ============================================================

def read_csv_for_inspection(file_path):
    """
    Read a CSV for inspection.

    The original file is never modified.

    Reading strategy:
    1. Try normal pandas CSV parsing using several encodings.
    2. If that fails, try the Python parser.
    3. Record malformed rows instead of silently hiding them.

    Returns
    -------
    df : pandas.DataFrame or None

    read_info : dict
        Information about encoding, parser and parsing problems.
    """

    attempts = []

    # --------------------------------------------------------
    # Attempt 1: normal pandas parser
    # --------------------------------------------------------

    for encoding in CSV_ENCODINGS:

        try:

            df = pd.read_csv(
                file_path,
                encoding=encoding,
                low_memory=False
            )

            return df, {
                "status": "success",
                "encoding": encoding,
                "parser": "default",
                "parsing_issue": False,
                "bad_rows": 0,
                "error": ""
            }

        except Exception as e:

            attempts.append(
                f"{encoding} / default parser: "
                f"{type(e).__name__}: {e}"
            )

    # --------------------------------------------------------
    # Attempt 2: Python parser
    # --------------------------------------------------------

    for encoding in CSV_ENCODINGS:

        bad_lines = []

        def collect_bad_line(line):
            bad_lines.append(line)
            return None

        try:

            df = pd.read_csv(
                file_path,
                encoding=encoding,
                engine="python",
                on_bad_lines=collect_bad_line
            )

            return df, {
                "status": "success_with_parsing_issues",
                "encoding": encoding,
                "parser": "python",
                "parsing_issue": True,
                "bad_rows": len(bad_lines),
                "error": (
                    f"{len(bad_lines)} malformed row(s) "
                    f"detected during inspection."
                )
            }

        except Exception as e:

            attempts.append(
                f"{encoding} / python parser: "
                f"{type(e).__name__}: {e}"
            )

    # --------------------------------------------------------
    # All attempts failed
    # --------------------------------------------------------

    return None, {
        "status": "failed",
        "encoding": None,
        "parser": None,
        "parsing_issue": True,
        "bad_rows": None,
        "error": " | ".join(attempts)
    }


print("✓ CSV inspection function created.")

✓ CSV inspection function created.

In [7]:
# ============================================================
# CELL 6 — COLUMN CANDIDATE DETECTION
# ============================================================

def identify_column_candidates(columns):

    candidates = {
        "year_date_columns": [],
        "state_columns": [],
        "location_columns": [],
        "district_columns": [],
        "crime_columns": [],
        "victim_columns": [],
        "count_value_columns": []
    }

    for column in columns:

        original = str(column).strip()

        normalized = re.sub(
            r"[^a-z0-9]+",
            "_",
            original.lower()
        ).strip("_")

        # ----------------------------------------------------
        # Date / time
        # ----------------------------------------------------

        if any(
            keyword in normalized
            for keyword in [
                "year",
                "date",
                "time",
                "month",
                "day",
                "quarter"
            ]
        ):
            candidates["year_date_columns"].append(original)

        # ----------------------------------------------------
        # State
        # ----------------------------------------------------

        if any(
            keyword in normalized
            for keyword in [
                "state",
                "state_ut",
                "state_union_territory",
                "union_territory"
            ]
        ):
            candidates["state_columns"].append(original)

        # ----------------------------------------------------
        # Location
        # ----------------------------------------------------

        if any(
            keyword in normalized
            for keyword in [
                "state",
                "district",
                "city",
                "location",
                "place",
                "region",
                "area",
                "zone",
                "village",
                "town",
                "taluk",
                "tehsil"
            ]
        ):
            candidates["location_columns"].append(original)

        # ----------------------------------------------------
        # District
        # ----------------------------------------------------

        if "district" in normalized:
            candidates["district_columns"].append(original)

        # ----------------------------------------------------
        # Crime-related
        # ----------------------------------------------------

        if any(
            keyword in normalized
            for keyword in [
                "crime",
                "offence",
                "offense",
                "ipc",
                "section",
                "case",
                "incident"
            ]
        ):
            candidates["crime_columns"].append(original)

        # ----------------------------------------------------
        # Victim-related
        # ----------------------------------------------------

        if any(
            keyword in normalized
            for keyword in [
                "victim",
                "age",
                "gender",
                "sex"
            ]
        ):
            candidates["victim_columns"].append(original)

        # ----------------------------------------------------
        # Count / value-related
        # ----------------------------------------------------

        if any(
            keyword in normalized
            for keyword in [
                "count",
                "total",
                "number",
                "value",
                "cases",
                "persons",
                "incidents"
            ]
        ):
            candidates["count_value_columns"].append(original)

    return candidates


print("✓ Candidate-column detector created.")

✓ Candidate-column detector created.

In [8]:
# ============================================================
# CELL 7 — YEAR / DATE CANDIDATE DETECTION
# ============================================================

def get_year_like_columns(df):

    results = []

    for column in df.columns:

        series = df[column]

        normalized = re.sub(
            r"[^a-z0-9]+",
            "_",
            str(column).lower()
        ).strip("_")

        # Name-based detection
        name_candidate = any(
            keyword in normalized
            for keyword in [
                "year",
                "date",
                "month",
                "time"
            ]
        )

        # Value-based detection
        value_candidate = False

        if pd.api.types.is_numeric_dtype(series):

            non_null = series.dropna()

            if len(non_null) > 0:

                numeric_values = pd.to_numeric(
                    non_null,
                    errors="coerce"
                ).dropna()

                if len(numeric_values) > 0:

                    valid_years = (
                        (numeric_values >= 1900) &
                        (numeric_values <= 2100)
                    )

                    if (
                        valid_years.sum() /
                        len(numeric_values)
                    ) >= 0.5:

                        value_candidate = True

        if name_candidate or value_candidate:
            results.append(str(column))

    return results


print("✓ Year/date detector created.")

✓ Year/date detector created.

In [9]:
# ============================================================
# CELL 8 — BUILD COMPLETE 76-FILE INVENTORY
# ============================================================

inventory_records = []

print("=" * 70)
print("BUILDING SOURCE DATA INVENTORY")
print("=" * 70)

for file_number, file_path in enumerate(csv_files, start=1):

    print(
        f"[{file_number:02d}/{len(csv_files):02d}] "
        f"Reading: {file_path.name}"
    )

    df, read_info = read_csv_for_inspection(file_path)

    relative_path = str(
        file_path.relative_to(PROJECT_ROOT)
    )

    # --------------------------------------------------------
    # If file could not be read
    # --------------------------------------------------------

    if df is None:

        inventory_records.append({

            "file_number": file_number,

            "filename": file_path.name,

            "relative_path": relative_path,

            "row_count": np.nan,

            "column_count": np.nan,

            "column_names": "",

            "data_types": "",

            "year_date_columns": "",

            "state_columns": "",

            "location_columns": "",

            "district_columns": "",

            "crime_columns": "",

            "victim_columns": "",

            "count_value_columns": "",

            "read_status": read_info["status"],

            "encoding": read_info["encoding"],

            "parser": read_info["parser"],

            "parsing_issue": read_info["parsing_issue"],

            "bad_rows": read_info["bad_rows"],

            "read_error": read_info["error"]
        })

        continue

    # --------------------------------------------------------
    # Identify candidate columns
    # --------------------------------------------------------

    candidates = identify_column_candidates(
        df.columns
    )

    year_columns = get_year_like_columns(df)

    # --------------------------------------------------------
    # Data type information
    # --------------------------------------------------------

    dtype_summary = {
        str(column): str(dtype)
        for column, dtype in df.dtypes.items()
    }

    # --------------------------------------------------------
    # Store inventory information
    # --------------------------------------------------------

    inventory_records.append({

        "file_number": file_number,

        "filename": file_path.name,

        "relative_path": relative_path,

        "row_count": len(df),

        "column_count": len(df.columns),

        "column_names": json.dumps(
            [str(column) for column in df.columns],
            ensure_ascii=False
        ),

        "data_types": json.dumps(
            dtype_summary,
            ensure_ascii=False
        ),

        "year_date_columns": json.dumps(
            year_columns,
            ensure_ascii=False
        ),

        "state_columns": json.dumps(
            candidates["state_columns"],
            ensure_ascii=False
        ),

        "location_columns": json.dumps(
            candidates["location_columns"],
            ensure_ascii=False
        ),

        "district_columns": json.dumps(
            candidates["district_columns"],
            ensure_ascii=False
        ),

        "crime_columns": json.dumps(
            candidates["crime_columns"],
            ensure_ascii=False
        ),

        "victim_columns": json.dumps(
            candidates["victim_columns"],
            ensure_ascii=False
        ),

        "count_value_columns": json.dumps(
            candidates["count_value_columns"],
            ensure_ascii=False
        ),

        "read_status": read_info["status"],

        "encoding": read_info["encoding"],

        "parser": read_info["parser"],

        "parsing_issue": read_info["parsing_issue"],

        "bad_rows": read_info["bad_rows"],

        "read_error": read_info["error"]
    })


# ------------------------------------------------------------
# Create inventory DataFrame
# ------------------------------------------------------------

inventory_df = pd.DataFrame(
    inventory_records
)

print("\n" + "=" * 70)
print("INVENTORY COMPLETE")
print("=" * 70)

print(
    f"Files inventoried: {len(inventory_df)}"
)

if len(inventory_df) == EXPECTED_FILE_COUNT:
    print("STATUS: ✓ All 76 expected files were inventoried.")
else:
    print(
        "STATUS: ⚠ Inventory count does not equal 76."
    )

======================================================================
BUILDING SOURCE DATA INVENTORY
======================================================================
[01/76] Reading: 01_District_wise_crimes_committed_IPC_2001_2012.csv
[02/76] Reading: 01_District_wise_crimes_committed_IPC_2013.csv
[03/76] Reading: 01_District_wise_crimes_committed_IPC_2014.csv
[04/76] Reading: 02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
[05/76] Reading: 02_01_District_wise_crimes_committed_against_SC_2013.csv
[06/76] Reading: 02_01_District_wise_crimes_committed_against_SC_2014.csv
[07/76] Reading: 02_District_wise_crimes_committed_against_ST_2001_2012.csv
[08/76] Reading: 02_District_wise_crimes_committed_against_ST_2013.csv
[09/76] Reading: 02_District_wise_crimes_committed_against_ST_2014.csv
[10/76] Reading: 03_District_wise_crimes_committed_against_children_2001_2012.csv
[11/76] Reading: 03_District_wise_crimes_committed_against_children_2013.csv
[12/76] Reading: 03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2012.csv
[13/76] Reading: 03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2013.csv
[14/76] Reading: 03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2014.csv
[15/76] Reading: 04_01_Person_arrested_and_their_disposal_by_police_and_court_SLL_crime_2012.csv
[16/76] Reading: 04_01_Person_arrested_and_their_disposal_by_police_and_court_SLL_crime_2013.csv
[17/76] Reading: 04_01_Person_arrested_and_their_disposal_by_police_and_court_SLL_crime_2014.csv
[18/76] Reading: 04_02_Person_arrested_and_their_disposal_by_police_and_court_IPC_crime_2012.csv
[19/76] Reading: 04_02_Person_arrested_and_their_disposal_by_police_and_court_IPC_crime_2013.csv
[20/76] Reading: 04_02_Person_arrested_and_their_disposal_by_police_and_court_IPC_crime_2014.csv
[21/76] Reading: 07_01_Persons_arrested_by_sex_and_age_group_IPC_2012.csv
[22/76] Reading: 07_01_Persons_arrested_by_sex_and_age_group_IPC_2013.csv
[23/76] Reading: 07_01_Persons_arrested_by_sex_and_age_group_IPC_2014.csv
[24/76] Reading: 07_02_Persons_arrested_by_sex_and_age_group_SLL_2012.csv
[25/76] Reading: 07_02_Persons_arrested_by_sex_and_age_group_SLL_2013.csv
[26/76] Reading: 07_02_Persons_arrested_by_sex_and_age_group_SLL_2014.csv
[27/76] Reading: 08_01_Juvenile_apprehended_state_IPC.csv
[28/76] Reading: 08_02_Juvenile_apprehended_state_SLL.csv
[29/76] Reading: 09_Juveniles_arrested_and_their_disposal.csv
[30/76] Reading: 10_Property_stolen_and_recovered.csv
[31/76] Reading: 11_Property_stolen_and_recovered_nature_of_property.csv
[32/76] Reading: 12_Police_strength_actual_and_sanctioned.csv
[33/76] Reading: 13_Police_killed_or_injured_on_duty.csv
[34/76] Reading: 14_Age_profile_of_police_personnel_killed_on_duty.csv
[35/76] Reading: 15_Police_natural_death_and_suicide.csv
[36/76] Reading: 16_Casualties_under_police_firing_and_lathi_charge.csv
[37/76] Reading: 17_Case_reported_and_value_of_property_taken_away_by_place_of_occurrence_2001_2012.csv
[38/76] Reading: 17_Case_reported_and_value_of_property_taken_away_by_place_of_occurrence_2013.csv
[39/76] Reading: 17_Crime_by_place_of_occurrence_2001_2012.csv
[40/76] Reading: 17_Crime_by_place_of_occurrence_2013.csv
[41/76] Reading: 17_Crime_by_place_of_occurrence_2014.csv
[42/76] Reading: 18_01_Juveniles_arrested_Education.csv
[43/76] Reading: 18_02_Juveniles_arrested_Economic_setup.csv
[44/76] Reading: 18_03_Juveniles_arrested_Family_background.csv
[45/76] Reading: 18_04_Juveniles_arrested_Recidivism.csv
[46/76] Reading: 19_Motive_or_cause_of_murder_and_culpable_homicide_not_amounting_to_murder.csv
[47/76] Reading: 20_Victims_of_rape.csv
[48/76] Reading: 21_Offenders_known_to_the_victim.csv
[49/76] Reading: 22_Persons_arrested_under_recidivism.csv
[50/76] Reading: 23_Anti_corruprion_cases.csv
[51/76] Reading: 24_Anti_corruption_arrests.csv
[52/76] Reading: 25_Complaints_against_police.csv
[53/76] Reading: 27_Nature_of_complaints_received_by_police.csv
[54/76] Reading: 28_Trial_of_violent_crimes_by_courts.csv
[55/76] Reading: 29_Period_of_trials_by_courts.csv
[56/76] Reading: 30_Auto_theft.csv
[57/76] Reading: 31_Serious_fraud.csv
[58/76] Reading: 32_Murder_victim_age_sex.csv
[59/76] Reading: 33_CH_not_murder_victim_age_sex.csv
[60/76] Reading: 34_Use_of_fire_arms_in_murder_cases.csv
[61/76] Reading: 35_Human_rights_violation_by_police.csv
[62/76] Reading: 36_Police_housing.csv
[63/76] Reading: 37_Home_guards_and_auxilliary_force.csv
[64/76] Reading: 38_Unidentified_dead_bodies_recovered_and_inquest_conducted.csv
[65/76] Reading: 39_Specific_purpose_of_kidnapping_and_abduction.csv
[66/76] Reading: 40_01_Custodial_death_person_remanded.csv
[67/76] Reading: 40_02_Custodial_death_person_not_remanded.csv
[68/76] Reading: 40_03_Custodial_death_during_production.csv
[69/76] Reading: 40_04_Custodial_death_during_hospitalization_or_treatment.csv
[70/76] Reading: 40_05_Custodial_death_others.csv
[71/76] Reading: 41_Escapes_from_police_custody.csv
[72/76] Reading: 42_Cases_under_crime_against_women.csv
[73/76] Reading: 42_District_wise_crimes_committed_against_women_2001_2012.csv
[74/76] Reading: 42_District_wise_crimes_committed_against_women_2013.csv
[75/76] Reading: 42_District_wise_crimes_committed_against_women_2014.csv
[76/76] Reading: 43_Arrests_under_crime_against_women.csv

======================================================================
INVENTORY COMPLETE
======================================================================
Files inventoried: 76
STATUS: ✓ All 76 expected files were inventoried.

In [10]:
# ============================================================
# CELL 9 — DISPLAY BASIC FILE INVENTORY
# ============================================================

pd.set_option(
    "display.max_columns",
    None
)

pd.set_option(
    "display.max_colwidth",
    120
)

pd.set_option(
    "display.width",
    200
)

inventory_display = inventory_df[
    [
        "file_number",
        "filename",
        "row_count",
        "column_count",
        "read_status",
        "parsing_issue",
        "bad_rows"
    ]
].copy()

display(inventory_display)

    file_number                                                       filename  row_count  column_count                  read_status  parsing_issue  bad_rows
0             1            01_District_wise_crimes_committed_IPC_2001_2012.csv       9017            33                      success          False         0
1             2                 01_District_wise_crimes_committed_IPC_2013.csv        823            33                      success          False         0
2             3                 01_District_wise_crimes_committed_IPC_2014.csv        838            91                      success          False         0
3             4  02_01_District_wise_crimes_committed_against_SC_2001_2012.csv       9018            13                      success          False         0
4             5       02_01_District_wise_crimes_committed_against_SC_2013.csv        823            13                      success          False         0
..          ...                                                            ...        ...           ...                          ...            ...       ...
71           72                         42_Cases_under_crime_against_women.csv       2765            22  success_with_parsing_issues           True      1400
72           73  42_District_wise_crimes_committed_against_women_2001_2012.csv       9017            10                      success          False         0
73           74       42_District_wise_crimes_committed_against_women_2013.csv        823            10                      success          False         0
74           75       42_District_wise_crimes_committed_against_women_2014.csv        837            62                      success          False         0
75           76                       43_Arrests_under_crime_against_women.csv       2765            16  success_with_parsing_issues           True      1400

[76 rows x 7 columns]

In [11]:
# ============================================================
# CELL 10 — TOTAL SOURCE ROW COUNT
# ============================================================

successful_files = inventory_df[
    inventory_df["row_count"].notna()
].copy()

total_source_rows = int(
    successful_files["row_count"].sum()
)

print("=" * 70)
print("SOURCE ROW COUNT")
print("=" * 70)

print(
    f"Files successfully inspected : "
    f"{len(successful_files)}"
)

print(
    f"Total source rows            : "
    f"{total_source_rows:,}"
)

print("\nIMPORTANT:")
print(
    "This is only the sum of rows across the 76 CSV files."
)

print(
    "It is NOT assumed to represent the number of "
    "individual crime incidents."
)

======================================================================
SOURCE ROW COUNT
======================================================================
Files successfully inspected : 76
Total source rows            : 147,753

IMPORTANT:
This is only the sum of rows across the 76 CSV files.
It is NOT assumed to represent the number of individual crime incidents.

In [12]:
# ============================================================
# CELL 11 — COLUMN NAMES OF ALL DATASETS
# ============================================================

print("=" * 70)
print("COLUMN NAMES BY DATASET")
print("=" * 70)

for _, row in inventory_df.iterrows():

    print("\n" + "-" * 70)
    print(f"FILE: {row['filename']}")
    print(f"ROWS: {row['row_count']}")
    print(f"COLUMNS: {row['column_count']}")
    print("-" * 70)

    if row["column_names"]:

        columns = json.loads(
            row["column_names"]
        )

        for i, column in enumerate(
            columns,
            start=1
        ):
            print(
                f"{i:02d}. {column}"
            )

    else:

        print("No column information available.")

======================================================================
COLUMN NAMES BY DATASET
======================================================================

----------------------------------------------------------------------
FILE: 01_District_wise_crimes_committed_IPC_2001_2012.csv
ROWS: 9017
COLUMNS: 33
----------------------------------------------------------------------
01. STATE/UT
02. DISTRICT
03. YEAR
04. MURDER
05. ATTEMPT TO MURDER
06. CULPABLE HOMICIDE NOT AMOUNTING TO MURDER
07. RAPE
08. CUSTODIAL RAPE
09. OTHER RAPE
10. KIDNAPPING & ABDUCTION
11. KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS
12. KIDNAPPING AND ABDUCTION OF OTHERS
13. DACOITY
14. PREPARATION AND ASSEMBLY FOR DACOITY
15. ROBBERY
16. BURGLARY
17. THEFT
18. AUTO THEFT
19. OTHER THEFT
20. RIOTS
21. CRIMINAL BREACH OF TRUST
22. CHEATING
23. COUNTERFIETING
24. ARSON
25. HURT/GREVIOUS HURT
26. DOWRY DEATHS
27. ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY
28. INSULT TO MODESTY OF WOMEN
29. CRUELTY BY HUSBAND OR HIS RELATIVES
30. IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES
31. CAUSING DEATH BY NEGLIGENCE
32. OTHER IPC CRIMES
33. TOTAL IPC CRIMES

----------------------------------------------------------------------
FILE: 01_District_wise_crimes_committed_IPC_2013.csv
ROWS: 823
COLUMNS: 33
----------------------------------------------------------------------
01. STATE/UT
02. DISTRICT
03. YEAR
04. MURDER
05. ATTEMPT TO MURDER
06. CULPABLE HOMICIDE NOT AMOUNTING TO MURDER
07. RAPE
08. CUSTODIAL RAPE
09. OTHER RAPE
10. KIDNAPPING & ABDUCTION
11. KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS
12. KIDNAPPING AND ABDUCTION OF OTHERS
13. DACOITY
14. PREPARATION AND ASSEMBLY FOR DACOITY
15. ROBBERY
16. BURGLARY
17. THEFT
18. AUTO THEFT
19. OTHER THEFT
20. RIOTS
21. CRIMINAL BREACH OF TRUST
22. CHEATING
23. COUNTERFIETING
24. ARSON
25. HURT/GREVIOUS HURT
26. DOWRY DEATHS
27. ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY
28. INSULT TO MODESTY OF WOMEN
29. CRUELTY BY HUSBAND OR HIS RELATIVES
30. IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES
31. CAUSING DEATH BY NEGLIGENCE
32. OTHER IPC CRIMES
33. TOTAL IPC CRIMES

----------------------------------------------------------------------
FILE: 01_District_wise_crimes_committed_IPC_2014.csv
ROWS: 838
COLUMNS: 91
----------------------------------------------------------------------
01. States/UTs
02. District
03. Year
04. Murder
05. Attempt to commit Murder
06. Culpable Homicide not amounting to Murder
07. Attempt to commit Culpable Homicide
08. Rape
09. Custodial Rape
10. Custodial_Gang Rape
11. Custodial_Other Rape
12. Rape other than Custodial
13. Rape_Gang Rape
14. Rape_Others
15. Attempt to commit Rape
16. Kidnapping & Abduction_Total
17. Kidnapping & Abduction
18. Kidnapping & Abduction in order to Murder
19. Kidnapping for Ransom
20. Kidnapping & Abduction of Women to compel her for marriage
21. Other Kidnapping
22. Dacoity
23. Dacoity with Murder
24. Other Dacoity
25. Making Preparation and Assembly for committing Dacoity
26. Robbery
27. Criminal Trespass/Burglary
28. Criminal Trespass or Burglary
29. House Trespass & House Breaking
30. Theft
31. Auto Theft
32. Other Thefts
33. Unlawful Assembly
34. Riots
35. Riots_Communal
36. Riots_Industrial
37. Riots_Political
38. Riots_Caste Conflict
39. Riots_SC/STs Vs Non-SCs/STs
40. Riots_Other Caste Conflict
41. Riots_Agrarian
42. Riots_Students
43. Riots_Sectarian
44. Riots_Others
45. Criminal Breach of Trust
46. Cheating
47. Forgery
48. Counterfeiting
49. Counterfeit Offences related to Counterfeit Coin
50. Counterfeiting Government Stamp
51. Counterfeit currency & Bank notes
52. Counterfeiting currency notes/Bank notes
53. Using forged or counterfeiting currency/Bank notes
54. Possession of forged or counterfeiting currency/Bank notes
55. Making or Possessing materials for forged currency/Bank notes
56. Making or Using documents resembling currency
57. Arson
58. Grievous Hurt
59. Hurt
60. Acid attack
61. Attempt to Acid Attack
62. Dowry Deaths
63. Assault on Women with intent to outrage her Modesty
64. Sexual Harassment
65. Assault or use of criminal force to women with intent to Disrobe
66. Voyeurism
67. Stalking
68. Other Assault on Women
69. Insult to the Modesty of Women
70. At Office premises
71. Other places related to work
72. In Public Transport system
73. Places other than 231, 232 & 233
74. Cruelty by Husband or his Relatives
75. Importation of Girls from Foreign Country
76. Causing Death by Negligence
77. Deaths due to negligent driving/act
78. Deaths due to Other Causes
79. Offences against State
80. Sedition
81. Other offences against State
82. Offences promoting enmity between different groups
83. Promoting enmity between different groups
84. Imputation, assertions prejudicial to national integration
85. Extortion
86. Disclosure of Identity of Victims
87. Incidence of Rash Driving
88. HumanTrafficking
89. Unnatural Offence
90. Other IPC crimes
91. Total Cognizable IPC crimes

----------------------------------------------------------------------
FILE: 02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
ROWS: 9018
COLUMNS: 13
----------------------------------------------------------------------
01. STATE/UT
02. DISTRICT
03. Year
04. Murder
05. Rape
06. Kidnapping and Abduction
07. Dacoity
08. Robbery
09. Arson
10. Hurt
11. Prevention of atrocities (POA) Act
12. Protection of Civil Rights (PCR) Act
13. Other Crimes Against SCs

----------------------------------------------------------------------
FILE: 02_01_District_wise_crimes_committed_against_SC_2013.csv
ROWS: 823
COLUMNS: 13
----------------------------------------------------------------------
01. STATE/UT
02. DISTRICT
03. Year
04. Murder
05. Rape
06. Kidnapping and Abduction
07. Dacoity
08. Robbery
09. Arson
10. Hurt
11. Protection of Civil Rights (PCR) Act
12. Prevention of atrocities (POA) Act
13. Other Crimes Against SCs

----------------------------------------------------------------------
FILE: 02_01_District_wise_crimes_committed_against_SC_2014.csv
ROWS: 837
COLUMNS: 66
----------------------------------------------------------------------
01. States/UTs
02. District
03. Year
04. Protection of Civil Rights Act, 1955
05. POA_Murder
06. POA_Attempt to commit Murder
07. POA_Rape
08. POA_Attempt to commit Rape
09. POA_Assault on women with intent to outrage her Modesty
10. POA_Sexual Harassment
11. POA_Assault on women with intent to Disrobe
12. POA_Voyeurism
13. POA_Stalking
14. POA_Other Sexual Harassment
15. POA_Insult to the Modesty of women
16. POA_Kidnapping & Abduction_GrandTotal
17. POA_Kidnaping & Abduction_Total
18. POA_Kidnaping & Abduction in order to Murder
19. POA_Kidnapping for Ransom
20. POA_Kidnapping & Abduction of Women to compel her for marriage
21. POA_Other Kidnapping
22. POA_Dacoity
23. POA_Dacoity with Murder
24. POA_Other Dacoity
25. POA_Robbery
26. POA_Arson
27. POA_Grievous Hurt
28. POA_Hurt
29. POA_Acid attack
30. POA_Attempt to Acid Attack
31. POA_Riots
32. POA_Other IPC crimes
33. POA_SC / ST (Prevention of Atrocities) Act only
34. Total of SC/ST (Prevention of Atrocities) Act ,1989
35. IPC_Murder
36. IPC_Attempt to commit Murder
37. IPC_Rape
38. IPC_Attempt to commit Rape
39. IPC_Assault on women with intent to outrage her Modesty
40. IPC_Sexual Harassment
41. IPC_Assault on women with intent to Disrobe
42. IPC_Voyeurism
43. IPC_Stalking
44. IPC_Other Sexual Harassment
45. IPC_Insult to the Modesty of women
46. IPC_Kidnapping & Abduction
47. IPC_Kidnaping & Abduction
48. IPC_Kidnaping & Abduction in order to Murder
49. IPC_Kidnapping for Ransom
50. IPC_Kidnapping & Abduction of Women to compel her for marriage
51. IPC_Other Kidnapping
52. IPC_Dacoity
53. IPC_Dacoity with Murder
54. IPC_Other Dacoity
55. IPC_Robbery
56. IPC_Arson
57. IPC_Grievous Hurt
58. IPC_Hurt
59. IPC_Acid attack
60. IPC_Attempt to Acid Attack
61. IPC_Riots
62. IPC_Other IPC crimes
63. Total IPC Crimes against SCs
64. Manual Scavengers and Construction of Dry Latrines (P) Act, 1993
65. Other SLL Crime against SCs
66. Total crimes against SCs

----------------------------------------------------------------------
FILE: 02_District_wise_crimes_committed_against_ST_2001_2012.csv
ROWS: 9018
COLUMNS: 13
----------------------------------------------------------------------
01. STATE/UT
02. DISTRICT
03. Year
04. Murder
05. Rape
06. Kidnapping Abduction
07. Dacoity
08. Robbery
09. Arson
10. Hurt
11. Protection of Civil Rights (PCR) Act
12. Prevention of atrocities (POA) Act
13. Other Crimes Against STs

----------------------------------------------------------------------
FILE: 02_District_wise_crimes_committed_against_ST_2013.csv
ROWS: 823
COLUMNS: 13
----------------------------------------------------------------------
01. STATE/UT
02. DISTRICT
03. Year
04. Murder
05. Rape
06. Kidnapping Abduction
07. Dacoity
08. Robbery
09. Arson
10. Hurt
11. Protection of Civil Rights (PCR) Act
12. Prevention of atrocities (POA) Act
13. Other Crimes Against STs

----------------------------------------------------------------------
FILE: 02_District_wise_crimes_committed_against_ST_2014.csv
ROWS: 837
COLUMNS: 66
----------------------------------------------------------------------
01. States/UTs
02. District
03. Year
04. Protection of Civil Rights Act, 1955
05. POA_Murder
06. POA_Attempt to commit Murder
07. POA_Rape
08. POA_Attempt to commit Rape
09. POA_Assault on women with intent to outrage her Modesty
10. POA_Sexual Harassment
11. POA_Assault on women with intent to Disrobe
12. POA_Voyeurism
13. POA_Stalking
14. POA_Other Sexual Harassment
15. POA_Insult to the Modesty of women
16. POA_Kidnapping & Abduction_GrandTotal
17. POA_Kidnaping & Abduction_Total
18. POA_Kidnaping & Abduction in order to Murder
19. POA_Kidnapping for Ransom
20. POA_Kidnapping & Abduction of Women to compel her for marriage
21. POA_Other Kidnapping
22. POA_Dacoity
23. POA_Dacoity with Murder
24. POA_Other Dacoity
25. POA_Robbery
26. POA_Arson
27. POA_Grievous Hurt
28. POA_Hurt
29. POA_Acid attack
30. POA_Attempt to Acid Attack
31. POA_Riots
32. POA_Other IPC crimes
33. POA_SC / ST (Prevention of Atrocities) Act only
34. Total of SC/ST (Prevention of Atrocities) Act ,1989
35. IPC_Murder
36. IPC_Attempt to commit Murder
37. IPC_Rape
38. IPC_Attempt to commit Rape
39. IPC_Assault on women with intent to outrage her Modesty
40. IPC_Sexual Harassment
41. IPC_Assault on women with intent to Disrobe
42. IPC_Voyeurism
43. IPC_Stalking
44. IPC_Other Sexual Harassment
45. IPC_Insult to the Modesty of women
46. IPC_Kidnapping & Abduction
47. IPC_Kidnaping & Abduction
48. IPC_Kidnaping & Abduction in order to Murder
49. IPC_Kidnapping for Ransom
50. IPC_Kidnapping & Abduction of Women to compel her for marriage
51. IPC_Other Kidnapping
52. IPC_Dacoity
53. IPC_Dacoity with Murder
54. IPC_Other Dacoity
55. IPC_Robbery
56. IPC_Arson
57. IPC_Grievous Hurt
58. IPC_Hurt
59. IPC_Acid attack
60. IPC_Attempt to Acid Attack
61. IPC_Riots
62. IPC_Other IPC crimes
63. Total IPC Crimes against STs
64. Manual Scavengers and Construction of Dry Latrines (P) Act, 1993
65. Other SLL Crime against STs
66. Total crimes against STs

----------------------------------------------------------------------
FILE: 03_District_wise_crimes_committed_against_children_2001_2012.csv
ROWS: 9015
COLUMNS: 15
----------------------------------------------------------------------
01. STATE/UT
02. DISTRICT
03. Year
04. Murder
05. Rape
06. Kidnapping and Abduction
07. Foeticide
08. Abetment of suicide
09. Exposure and abandonment
10. Procuration of minor girls
11. Buying of girls for prostitution
12. Selling of girls for prostitution
13. Prohibition of child marriage act
14. Other Crimes
15. Total

----------------------------------------------------------------------
FILE: 03_District_wise_crimes_committed_against_children_2013.csv
ROWS: 823
COLUMNS: 16
----------------------------------------------------------------------
01. STATE/UT
02. DISTRICT
03. Year
04. Infanticid
05. Other murder
06. Rape
07. Kidnapping and Abduction
08. Foeticide
09. Abetment of suicide
10. Exposure and abandonment
11. Procuration of minor girls
12. Buying of girls for prostitution
13. Selling of girls for prostitution
14. Prohibition of child marriage act
15. Other Crimes
16. Total

----------------------------------------------------------------------
FILE: 03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2012.csv
ROWS: 494
COLUMNS: 14
----------------------------------------------------------------------
01. STATE/UT
02. CRIME HEAD
03. Persons in custody or on bail during the stage of investigation at the beginning of the year
04. Persons arrested during the year
05. Persons released or freed by Police or Magistrate before trial for want of evidence or any other reason
06. Persons in custody or on bail during the stage of investigation at the end of the year
07. Persons in whose cases charge sheets were laid during the year
08. Persons under trial at the beginning of the year
09. Total number of persons under trial during the year
10. Persons against whom cases were compounded or withdrawn
11. Persons in custody or on bail during the stage of trial at the end of the year
12. Persons in whose cases trials were completed during the year
13. Persons convicted
14. Persons acquitted

----------------------------------------------------------------------
FILE: 03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2013.csv
ROWS: 494
COLUMNS: 14
----------------------------------------------------------------------
01. STATE/UT
02. CRIME HEAD
03. Persons in custody or on bail during the stage of investigation at the beginning of the year
04. Persons arrested during the year
05. Persons released or freed by Police or Magistrate before trial for want of evidence or any other reason
06. Persons in custody or on bail during the stage of investigation at the end of the year
07. Persons in whose cases charge sheets were laid during the year
08. Persons under trial at the beginning of the year
09. Total number of persons under trial during the year
10. Persons against whom cases were compounded or withdrawn
11. Persons in custody or on bail during the stage of trial at the end of the year
12. Persons in whose cases trials were completed during the year
13. Persons convicted
14. Persons acquitted

----------------------------------------------------------------------
FILE: 03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2014.csv
ROWS: 2028
COLUMNS: 57
----------------------------------------------------------------------
01. States/UTs
02. Crime Head
03. Year
04. Persons in custody during inv stage at beginning of Year_Male
05. Persons in custody during inv stage at beginning of Year_Female
06. Persons in custody during inv stage at beginning of Year_Total
07. Persons on bail during inv stage at beginning of Year_Male
08. Persons on bail during inv stage at beginning of Year_Female
09. Persons on bail during inv stage at beginning of Year_Total
10. Persons arrested during the year_Male
11. Persons arrested during the year_Female
12. Persons arrested during the year_Total
13. Persons released or freed before trial for want of evidence_Male
14. Persons released or freed before trial for want of evidence_Fem
15. Persons released or freed before trial for want of evidence_Tot
16. Persons in custody during inv stage at year end_Male
17. Persons in custody during inv stage at year end_Female
18. Persons in custody during inv stage at year end_Total
19. Persons on Bail during inv stage at year end_Male
20. Persons on Bail during inv stage at Year end_Female
21. Persons on Bail during inv stage at year end_Total
22. Persons charge sheeted_Male
23. Persons charge sheeted_Female
24. Persons charge sheeted_Total
25. Persons in custody during trial stage at begin of year_Male
26. Persons in custody during trial stage at begin of year_Female
27. Persons in custody during trial stage at begin of year_Total
28. Persons on Bail during trial stage at begin of year_Male
29. Persons on Bail during trial stage at begin of year_Female
30. Persons on Bail during trial stage at begin of year_Total
31. Total number of persons under Trial_Male
32. Total number of persons under Trial_Female
33. Total number of persons under Trial_Total
34. Persons against whom cases were compounded by Courts_Male
35. Persons against whom cases were compounded by Courts_Female
36. Persons against whom cases were compounded by Courts_Total
37. Persons against whom cases were withdrawn_Male
38. Persons against whom cases were withdrawn_Female
39. Persons against whom cases were withdrawn_Total
40. Persons in custody during trial stage at Year end_Male
41. Persons in custody during trial stage at Year end_Female
42. Persons in custody during trial stage at Year end_Total
43. Persons on bail during trial stage at Year End_Male
44. Persons on bail during trial stage at Year End_Female
45. Persons on bail during trial stage at Year End_Total
46. Persons whose cases trials were completed during the year_Male
47. Persons whose cases trials were completed during the year_Female
48. Persons whose cases trials were completed during the year_Total
49. Persons convicted_Male
50. Persons convicted_Female
51. Persons convicted_Total
52. Persons acquitted_Male
53. Persons acquitted_Female
54. Persons acquitted_Total
55. Persons Discharged by Court_Male
56. Persons Discharged by Court_Female
57. Persons Discharged by Court_Total

----------------------------------------------------------------------
FILE: 04_01_Person_arrested_and_their_disposal_by_police_and_court_SLL_crime_2012.csv
ROWS: 1026
COLUMNS: 14
----------------------------------------------------------------------
01. STATE/UT
02. CRIME HEAD
03. Persons in custody or on bail during the stage of investigation at the beginning of the year
04. Persons arrested during the year
05. Persons released or freed by Police or Magistrate before trial for want of evidence or any other reason
06. Persons in custody or on bail during the stage of investigation at the end of the year
07. Persons in whose cases charge sheets were laid during the year
08. Persons under trial at the beginning of the year
09. Total number of persons under trial during the year
10. Persons against whom cases were compounded or withdrawn
11. Persons in custody or on bail during the stage of trial at the end of the year
12. Persons in whose cases trials were completed during the year
13. Persons convicted
14. Persons acquitted

----------------------------------------------------------------------
FILE: 04_01_Person_arrested_and_their_disposal_by_police_and_court_SLL_crime_2013.csv
ROWS: 418
COLUMNS: 14
----------------------------------------------------------------------
01. STATE/UT
02. CRIME HEAD
03. Persons in custody or on bail during the stage of investigation at the beginning of the year
04. Persons arrested during the year
05. Persons released or freed by Police or Magistrate before trial for want of evidence or any other reason
06. Persons in custody or on bail during the stage of investigation at the end of the year
07. Persons in whose cases charge sheets were laid during the year
08. Persons under trial at the beginning of the year
09. Total number of persons under trial during the year
10. Persons against whom cases were compounded or withdrawn
11. Persons in custody or on bail during the stage of trial at the end of the year
12. Persons in whose cases trials were completed during the year
13. Persons convicted
14. Persons acquitted

----------------------------------------------------------------------
FILE: 04_01_Person_arrested_and_their_disposal_by_police_and_court_SLL_crime_2014.csv
ROWS: 2730
COLUMNS: 57
----------------------------------------------------------------------
01. States/UTs
02. Crime Head
03. Year
04. Persons in custody during inv stage at beginning of Year_Male

In [13]:
# ============================================================
# CELL 12 — COLUMN INVENTORY TABLE
# ============================================================

column_records = []

for _, row in inventory_df.iterrows():

    if not row["column_names"]:
        continue

    columns = json.loads(
        row["column_names"]
    )

    for column in columns:

        normalized = re.sub(
            r"[^a-z0-9]+",
            "_",
            str(column).lower()
        ).strip("_")

        column_records.append({

            "filename": row["filename"],

            "column_name": str(column),

            "normalized_column_name": normalized
        })


column_inventory_df = pd.DataFrame(
    column_records
)

print("=" * 70)
print("COLUMN INVENTORY")
print("=" * 70)

print(
    f"Total column occurrences: "
    f"{len(column_inventory_df):,}"
)

print(
    f"Unique column names: "
    f"{column_inventory_df['column_name'].nunique():,}"
)

display(
    column_inventory_df.head(100)
)

======================================================================
COLUMN INVENTORY
======================================================================
Total column occurrences: 1,469
Unique column names: 777

                                               filename        column_name normalized_column_name
0   01_District_wise_crimes_committed_IPC_2001_2012.csv           STATE/UT               state_ut
1   01_District_wise_crimes_committed_IPC_2001_2012.csv           DISTRICT               district
2   01_District_wise_crimes_committed_IPC_2001_2012.csv               YEAR                   year
3   01_District_wise_crimes_committed_IPC_2001_2012.csv             MURDER                 murder
4   01_District_wise_crimes_committed_IPC_2001_2012.csv  ATTEMPT TO MURDER      attempt_to_murder
..                                                  ...                ...                    ...
95       01_District_wise_crimes_committed_IPC_2014.csv              Theft                  theft
96       01_District_wise_crimes_committed_IPC_2014.csv         Auto Theft             auto_theft
97       01_District_wise_crimes_committed_IPC_2014.csv       Other Thefts           other_thefts
98       01_District_wise_crimes_committed_IPC_2014.csv  Unlawful Assembly      unlawful_assembly
99       01_District_wise_crimes_committed_IPC_2014.csv              Riots                  riots

[100 rows x 3 columns]

In [14]:
# ============================================================
# CELL 13 — EXACT COMMON COLUMN NAMES
# ============================================================

column_frequency = (
    column_inventory_df
    .groupby("column_name")["filename"]
    .nunique()
    .reset_index(
        name="dataset_count"
    )
    .sort_values(
        ["dataset_count", "column_name"],
        ascending=[False, True]
    )
)

print("=" * 70)
print("EXACT COLUMN-NAME FREQUENCY")
print("=" * 70)

print(
    "NOTE: Exact name similarity does NOT prove "
    "semantic equivalence."
)

display(
    column_frequency.head(100)
)

======================================================================
EXACT COLUMN-NAME FREQUENCY
======================================================================
NOTE: Exact name similarity does NOT prove semantic equivalence.

                                                         column_name  dataset_count
776                                                             Year             60
82                                                         Area_Name             40
704                                                         STATE/UT             26
710                                                   Sub_Group_Name             24
291                                                       Group_Name             21
..                                                               ...            ...
572      Persons on bail during inv stage at beginning of Year_Total              3
573            Persons on bail during trial stage at Year End_Female              3
574              Persons on bail during trial stage at Year End_Male              3
575             Persons on bail during trial stage at Year End_Total              3
576  Persons released or freed before trial for want of evidence_Fem              3

[100 rows x 2 columns]

In [15]:
# ============================================================
# CELL 14 — PARSING PROBLEM REPORT
# ============================================================

problem_files = inventory_df[
    inventory_df["parsing_issue"] == True
].copy()

failed_files = inventory_df[
    inventory_df["read_status"] == "failed"
].copy()

print("=" * 70)
print("PARSING / READING PROBLEM REPORT")
print("=" * 70)

print(
    f"\nFiles with parsing issues : "
    f"{len(problem_files)}"
)

print(
    f"Files that failed reading : "
    f"{len(failed_files)}"
)

# ------------------------------------------------------------
# Parsing issues
# ------------------------------------------------------------

if len(problem_files) > 0:

    print("\nFiles with parsing issues:")

    display(
        problem_files[
            [
                "filename",
                "read_status",
                "encoding",
                "parser",
                "bad_rows",
                "read_error"
            ]
        ]
    )

else:

    print("\n✓ No parsing issues detected.")

# ------------------------------------------------------------
# Completely failed files
# ------------------------------------------------------------

if len(failed_files) > 0:

    print("\nFiles that could not be read:")

    display(
        failed_files[
            [
                "filename",
                "read_status",
                "read_error"
            ]
        ]
    )

else:

    print("\n✓ No files completely failed to read.")

======================================================================
PARSING / READING PROBLEM REPORT
======================================================================

Files with parsing issues : 3
Files that failed reading : 0

Files with parsing issues:

                                    filename                  read_status encoding  parser  bad_rows                                         read_error
61                     36_Police_housing.csv  success_with_parsing_issues    utf-8  python       348   348 malformed row(s) detected during inspection.
71    42_Cases_under_crime_against_women.csv  success_with_parsing_issues    utf-8  python      1400  1400 malformed row(s) detected during inspection.
75  43_Arrests_under_crime_against_women.csv  success_with_parsing_issues    utf-8  python      1400  1400 malformed row(s) detected during inspection.

✓ No files completely failed to read.

In [16]:
# ============================================================
# CELL 15 — SAVE 76-FILE INVENTORY
# ============================================================

inventory_output_path = (
    TABLES_DIR / "76_file_inventory.csv"
)

inventory_df.to_csv(
    inventory_output_path,
    index=False,
    encoding="utf-8-sig"
)

print("=" * 70)
print("INVENTORY SAVED")
print("=" * 70)

print(
    "\nSaved to:"
)

print(
    inventory_output_path.resolve()
)

print(
    f"\nInventory rows: {len(inventory_df)}"
)

print(
    "\n✓ Original raw CSV files were not modified."
)

======================================================================
INVENTORY SAVED
======================================================================

Saved to:
D:\Major_Project\Crime_Analysis\outputs\tables\76_file_inventory.csv

Inventory rows: 76

✓ Original raw CSV files were not modified.

In [18]:
# ============================================================
# CELL 16 — PHASE 1 + PHASE 2 VERIFICATION
# ============================================================

print("=" * 70)
print("PHASE 1 + PHASE 2 VERIFICATION")
print("=" * 70)

print(
    f"\nCSV files discovered       : "
    f"{len(csv_files)}"
)

print(
    f"Files inventoried          : "
    f"{len(inventory_df)}"
)

print(
    f"Total source rows          : "
    f"{total_source_rows:,}"
)

print(
    f"Unique column names        : "
    f"{column_inventory_df['column_name'].nunique():,}"
)

print(
    f"Files with parsing issues  : "
    f"{inventory_df['parsing_issue'].sum()}"
)

print(
    f"Files completely unreadable: "
    f"{len(failed_files)}"
)

print("\n" + "-" * 70)
print("OUTPUT FILE")
print("-" * 70)

print(
    inventory_output_path.resolve()
)

print("\n" + "-" * 70)
print("STATUS")
print("-" * 70)

if len(csv_files) == 76:
    print("✓ Exactly 76 CSV files discovered")
else:
    print("⚠ CSV file count is not 76")

if len(inventory_df) == 76:
    print("✓ All 76 files inventoried")
else:
    print("⚠ Inventory count is not 76")

if len(failed_files) == 0:
    print("✓ No files completely failed")
else:
    print("⚠ Some files require additional inspection")

======================================================================
PHASE 1 + PHASE 2 VERIFICATION
======================================================================

CSV files discovered       : 76
Files inventoried          : 76
Total source rows          : 147,753
Unique column names        : 777
Files with parsing issues  : 3
Files completely unreadable: 0

----------------------------------------------------------------------
OUTPUT FILE
----------------------------------------------------------------------
D:\Major_Project\Crime_Analysis\outputs\tables\76_file_inventory.csv

----------------------------------------------------------------------
STATUS
----------------------------------------------------------------------
✓ Exactly 76 CSV files discovered
✓ All 76 files inventoried
✓ No files completely failed

# Phase 3 — Understanding Dataset and Row Semantics

Before creating a common schema, each source dataset must be understood
according to what one row represents.

For every CSV, this phase examines:

- number of rows and columns
- column names
- data types
- sample records
- geographic indicators
- temporal indicators
- crime-related fields
- count/measure fields
- victim-related fields
- police/arrest/court/property indicators

The automated analysis below provides evidence and candidate interpretations.

It does NOT automatically declare semantic equivalence between datasets.

Any dataset whose meaning cannot be established reliably from its schema
and sample records will be flagged for manual review.

In [19]:
# ============================================================
# CELL 18 — VERIFY INVENTORY FOR PHASE 3
# ============================================================

print("=" * 70)
print("PHASE 3 — INVENTORY CHECK")
print("=" * 70)

print(f"Inventory files : {len(inventory_df)}")
print(f"Source CSVs     : {len(csv_files)}")

if len(inventory_df) != len(csv_files):
    raise ValueError(
        "Inventory count and discovered CSV count do not match."
    )

print("\n✓ Inventory and discovered files match.")
print("✓ Ready for semantic dataset inspection.")

======================================================================
PHASE 3 — INVENTORY CHECK
======================================================================
Inventory files : 76
Source CSVs     : 76

✓ Inventory and discovered files match.
✓ Ready for semantic dataset inspection.

In [20]:
# ============================================================
# CELL 19 — DATASET PROFILE FUNCTION
# ============================================================

def create_dataset_profile(df, filename):
    """
    Generate evidence about what a dataset may represent.

    IMPORTANT:
    This function creates candidate evidence only.
    It does not establish final semantic compatibility.
    """

    columns = [str(c).strip() for c in df.columns]

    normalized_columns = [
        re.sub(
            r"[^a-z0-9]+",
            "_",
            c.lower()
        ).strip("_")
        for c in columns
    ]

    # --------------------------------------------------------
    # Geographic evidence
    # --------------------------------------------------------

    state_cols = []
    district_cols = []
    location_cols = []

    for original, normalized in zip(
        columns,
        normalized_columns
    ):

        if any(
            key in normalized
            for key in [
                "state",
                "state_ut",
                "states_uts",
                "union_territory"
            ]
        ):
            state_cols.append(original)

        if "district" in normalized:
            district_cols.append(original)

        if any(
            key in normalized
            for key in [
                "location",
                "place",
                "city",
                "region",
                "area",
                "zone",
                "village",
                "town",
                "taluk",
                "tehsil"
            ]
        ):
            location_cols.append(original)

    # --------------------------------------------------------
    # Temporal evidence
    # --------------------------------------------------------

    year_cols = []

    for original, normalized in zip(
        columns,
        normalized_columns
    ):

        if any(
            key in normalized
            for key in [
                "year",
                "date",
                "month",
                "quarter",
                "time"
            ]
        ):
            year_cols.append(original)

    # --------------------------------------------------------
    # Crime evidence
    # --------------------------------------------------------

    crime_cols = []

    for original, normalized in zip(
        columns,
        normalized_columns
    ):

        if any(
            key in normalized
            for key in [
                "crime",
                "offence",
                "offense",
                "ipc",
                "case",
                "incident",
                "murder",
                "rape",
                "robbery",
                "theft",
                "kidnapping"
            ]
        ):
            crime_cols.append(original)

    # --------------------------------------------------------
    # Victim evidence
    # --------------------------------------------------------

    victim_cols = []

    for original, normalized in zip(
        columns,
        normalized_columns
    ):

        if any(
            key in normalized
            for key in [
                "victim",
                "age",
                "gender",
                "sex"
            ]
        ):
            victim_cols.append(original)

    # --------------------------------------------------------
    # Arrest / police evidence
    # --------------------------------------------------------

    arrest_police_cols = []

    for original, normalized in zip(
        columns,
        normalized_columns
    ):

        if any(
            key in normalized
            for key in [
                "arrest",
                "police",
                "custody",
                "investigation",
                "charge_sheet",
                "chargesheet",
                "convicted",
                "acquitted",
                "trial"
            ]
        ):
            arrest_police_cols.append(original)

    # --------------------------------------------------------
    # Property evidence
    # --------------------------------------------------------

    property_cols = []

    for original, normalized in zip(
        columns,
        normalized_columns
    ):

        if any(
            key in normalized
            for key in [
                "property",
                "vehicle",
                "stolen",
                "recovered",
                "loss",
                "value"
            ]
        ):
            property_cols.append(original)

    # --------------------------------------------------------
    # Numeric columns
    # --------------------------------------------------------

    numeric_columns = [
        str(c)
        for c in df.select_dtypes(
            include=np.number
        ).columns
    ]

    # --------------------------------------------------------
    # Candidate subject indicators
    # --------------------------------------------------------

    subject_evidence = []

    if arrest_police_cols:
        subject_evidence.append(
            "police/arrest/justice-related fields"
        )

    if victim_cols:
        subject_evidence.append(
            "victim/demographic-related fields"
        )

    if property_cols:
        subject_evidence.append(
            "property/vehicle/value-related fields"
        )

    if crime_cols:
        subject_evidence.append(
            "crime/case/offence-related fields"
        )

    if not subject_evidence:
        subject_evidence.append(
            "no obvious crime-specific indicator detected"
        )

    # --------------------------------------------------------
    # Candidate geographic level
    # --------------------------------------------------------

    if district_cols:
        geographic_candidate = (
            "district-level information may be present"
        )

    elif state_cols:
        geographic_candidate = (
            "state/UT-level information may be present"
        )

    elif location_cols:
        geographic_candidate = (
            "location information may be present"
        )

    else:
        geographic_candidate = (
            "no obvious geographic field detected"
        )

    # --------------------------------------------------------
    # Candidate temporal level
    # --------------------------------------------------------

    if year_cols:

        if len(year_cols) == 1:
            temporal_candidate = (
                "year/date information may be present"
            )
        else:
            temporal_candidate = (
                "multiple year/date-related fields detected"
            )

    else:

        temporal_candidate = (
            "no obvious time field detected"
        )

    return {

        "filename": filename,

        "row_count": len(df),

        "column_count": len(df.columns),

        "geographic_level_candidate":
            geographic_candidate,

        "time_level_candidate":
            temporal_candidate,

        "crime_information_candidate":
            "; ".join(crime_cols),

        "victim_information_candidate":
            "; ".join(victim_cols),

        "police_arrest_information_candidate":
            "; ".join(arrest_police_cols),

        "property_information_candidate":
            "; ".join(property_cols),

        "state_columns":
            "; ".join(state_cols),

        "district_columns":
            "; ".join(district_cols),

        "location_columns":
            "; ".join(location_cols),

        "year_date_columns":
            "; ".join(year_cols),

        "numeric_columns":
            "; ".join(numeric_columns),

        "subject_evidence":
            "; ".join(subject_evidence),

        # IMPORTANT:
        # These remain blank until manually verified.
        "geographic_level":
            "",

        "time_level":
            "",

        "subject_type":
            "",

        "manual_review_required":
            True,

        "manual_notes":
            ""
    }

In [21]:
# ============================================================
# CELL 20 — BUILD DATASET SEMANTIC PROFILE
# ============================================================

dataset_profiles = []

print("=" * 70)
print("BUILDING SEMANTIC PROFILE FOR ALL 76 DATASETS")
print("=" * 70)

for i, file_path in enumerate(
    csv_files,
    start=1
):

    print(
        f"[{i:02d}/{len(csv_files):02d}] "
        f"Profiling: {file_path.name}"
    )

    df, read_info = read_csv_for_inspection(
        file_path
    )

    if df is None:

        dataset_profiles.append({

            "filename": file_path.name,

            "row_count": np.nan,

            "column_count": np.nan,

            "geographic_level_candidate":
                "FILE COULD NOT BE READ",

            "time_level_candidate":
                "FILE COULD NOT BE READ",

            "crime_information_candidate": "",

            "victim_information_candidate": "",

            "police_arrest_information_candidate": "",

            "property_information_candidate": "",

            "state_columns": "",

            "district_columns": "",

            "location_columns": "",

            "year_date_columns": "",

            "numeric_columns": "",

            "subject_evidence": "",

            "geographic_level": "",

            "time_level": "",

            "subject_type": "",

            "manual_review_required": True,

            "manual_notes":
                "File could not be read."
        })

        continue

    profile = create_dataset_profile(
        df,
        file_path.name
    )

    dataset_profiles.append(profile)


dataset_profile_df = pd.DataFrame(
    dataset_profiles
)

print("\n" + "=" * 70)
print("SEMANTIC PROFILE COMPLETE")
print("=" * 70)

print(
    f"Datasets profiled: "
    f"{len(dataset_profile_df)}"
)

======================================================================
BUILDING SEMANTIC PROFILE FOR ALL 76 DATASETS
======================================================================
[01/76] Profiling: 01_District_wise_crimes_committed_IPC_2001_2012.csv
[02/76] Profiling: 01_District_wise_crimes_committed_IPC_2013.csv
[03/76] Profiling: 01_District_wise_crimes_committed_IPC_2014.csv
[04/76] Profiling: 02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
[05/76] Profiling: 02_01_District_wise_crimes_committed_against_SC_2013.csv
[06/76] Profiling: 02_01_District_wise_crimes_committed_against_SC_2014.csv
[07/76] Profiling: 02_District_wise_crimes_committed_against_ST_2001_2012.csv
[08/76] Profiling: 02_District_wise_crimes_committed_against_ST_2013.csv
[09/76] Profiling: 02_District_wise_crimes_committed_against_ST_2014.csv
[10/76] Profiling: 03_District_wise_crimes_committed_against_children_2001_2012.csv
[11/76] Profiling: 03_District_wise_crimes_committed_against_children_2013.csv
[12/76] Profiling: 03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2012.csv
[13/76] Profiling: 03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2013.csv
[14/76] Profiling: 03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2014.csv
[15/76] Profiling: 04_01_Person_arrested_and_their_disposal_by_police_and_court_SLL_crime_2012.csv
[16/76] Profiling: 04_01_Person_arrested_and_their_disposal_by_police_and_court_SLL_crime_2013.csv
[17/76] Profiling: 04_01_Person_arrested_and_their_disposal_by_police_and_court_SLL_crime_2014.csv
[18/76] Profiling: 04_02_Person_arrested_and_their_disposal_by_police_and_court_IPC_crime_2012.csv
[19/76] Profiling: 04_02_Person_arrested_and_their_disposal_by_police_and_court_IPC_crime_2013.csv
[20/76] Profiling: 04_02_Person_arrested_and_their_disposal_by_police_and_court_IPC_crime_2014.csv
[21/76] Profiling: 07_01_Persons_arrested_by_sex_and_age_group_IPC_2012.csv
[22/76] Profiling: 07_01_Persons_arrested_by_sex_and_age_group_IPC_2013.csv
[23/76] Profiling: 07_01_Persons_arrested_by_sex_and_age_group_IPC_2014.csv
[24/76] Profiling: 07_02_Persons_arrested_by_sex_and_age_group_SLL_2012.csv
[25/76] Profiling: 07_02_Persons_arrested_by_sex_and_age_group_SLL_2013.csv
[26/76] Profiling: 07_02_Persons_arrested_by_sex_and_age_group_SLL_2014.csv
[27/76] Profiling: 08_01_Juvenile_apprehended_state_IPC.csv
[28/76] Profiling: 08_02_Juvenile_apprehended_state_SLL.csv
[29/76] Profiling: 09_Juveniles_arrested_and_their_disposal.csv
[30/76] Profiling: 10_Property_stolen_and_recovered.csv
[31/76] Profiling: 11_Property_stolen_and_recovered_nature_of_property.csv
[32/76] Profiling: 12_Police_strength_actual_and_sanctioned.csv
[33/76] Profiling: 13_Police_killed_or_injured_on_duty.csv
[34/76] Profiling: 14_Age_profile_of_police_personnel_killed_on_duty.csv
[35/76] Profiling: 15_Police_natural_death_and_suicide.csv
[36/76] Profiling: 16_Casualties_under_police_firing_and_lathi_charge.csv
[37/76] Profiling: 17_Case_reported_and_value_of_property_taken_away_by_place_of_occurrence_2001_2012.csv
[38/76] Profiling: 17_Case_reported_and_value_of_property_taken_away_by_place_of_occurrence_2013.csv
[39/76] Profiling: 17_Crime_by_place_of_occurrence_2001_2012.csv
[40/76] Profiling: 17_Crime_by_place_of_occurrence_2013.csv
[41/76] Profiling: 17_Crime_by_place_of_occurrence_2014.csv
[42/76] Profiling: 18_01_Juveniles_arrested_Education.csv
[43/76] Profiling: 18_02_Juveniles_arrested_Economic_setup.csv
[44/76] Profiling: 18_03_Juveniles_arrested_Family_background.csv
[45/76] Profiling: 18_04_Juveniles_arrested_Recidivism.csv
[46/76] Profiling: 19_Motive_or_cause_of_murder_and_culpable_homicide_not_amounting_to_murder.csv
[47/76] Profiling: 20_Victims_of_rape.csv
[48/76] Profiling: 21_Offenders_known_to_the_victim.csv
[49/76] Profiling: 22_Persons_arrested_under_recidivism.csv
[50/76] Profiling: 23_Anti_corruprion_cases.csv
[51/76] Profiling: 24_Anti_corruption_arrests.csv
[52/76] Profiling: 25_Complaints_against_police.csv
[53/76] Profiling: 27_Nature_of_complaints_received_by_police.csv
[54/76] Profiling: 28_Trial_of_violent_crimes_by_courts.csv
[55/76] Profiling: 29_Period_of_trials_by_courts.csv
[56/76] Profiling: 30_Auto_theft.csv
[57/76] Profiling: 31_Serious_fraud.csv
[58/76] Profiling: 32_Murder_victim_age_sex.csv
[59/76] Profiling: 33_CH_not_murder_victim_age_sex.csv
[60/76] Profiling: 34_Use_of_fire_arms_in_murder_cases.csv
[61/76] Profiling: 35_Human_rights_violation_by_police.csv
[62/76] Profiling: 36_Police_housing.csv
[63/76] Profiling: 37_Home_guards_and_auxilliary_force.csv
[64/76] Profiling: 38_Unidentified_dead_bodies_recovered_and_inquest_conducted.csv
[65/76] Profiling: 39_Specific_purpose_of_kidnapping_and_abduction.csv
[66/76] Profiling: 40_01_Custodial_death_person_remanded.csv
[67/76] Profiling: 40_02_Custodial_death_person_not_remanded.csv
[68/76] Profiling: 40_03_Custodial_death_during_production.csv
[69/76] Profiling: 40_04_Custodial_death_during_hospitalization_or_treatment.csv
[70/76] Profiling: 40_05_Custodial_death_others.csv
[71/76] Profiling: 41_Escapes_from_police_custody.csv
[72/76] Profiling: 42_Cases_under_crime_against_women.csv
[73/76] Profiling: 42_District_wise_crimes_committed_against_women_2001_2012.csv
[74/76] Profiling: 42_District_wise_crimes_committed_against_women_2013.csv
[75/76] Profiling: 42_District_wise_crimes_committed_against_women_2014.csv
[76/76] Profiling: 43_Arrests_under_crime_against_women.csv

======================================================================
SEMANTIC PROFILE COMPLETE
======================================================================
Datasets profiled: 76

In [22]:
# ============================================================
# CELL 21 — DISPLAY DATASET PROFILE
# ============================================================

profile_display = dataset_profile_df[
    [
        "filename",
        "row_count",
        "column_count",
        "geographic_level_candidate",
        "time_level_candidate",
        "subject_evidence",
        "manual_review_required"
    ]
].copy()

display(
    profile_display
)

,filename,row_count,column_count,geographic_level_candidate,time_level_candidate,subject_evidence,manual_review_required
0,01_District_wise_crimes_committed_IPC_2001_2012.csv,9017,33,district-level information may be present,year/date information may be present,victim/demographic-related fields; crime/case/offence-related fields,True
1,01_District_wise_crimes_committed_IPC_2013.csv,823,33,district-level information may be present,year/date information may be present,victim/demographic-related fields; crime/case/offence-related fields,True
2,01_District_wise_crimes_committed_IPC_2014.csv,838,91,district-level information may be present,year/date information may be present,police/arrest/justice-related fields; victim/demographic-related fields; crime/case/offence-related fields,True
3,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv,9018,13,district-level information may be present,year/date information may be present,crime/case/offence-related fields,True
4,02_01_District_wise_crimes_committed_against_SC_2013.csv,823,13,district-level information may be present,year/date information may be present,crime/case/offence-related fields,True
...,...,...,...,...,...,...,...
71,42_Cases_under_crime_against_women.csv,2765,22,location information may be present,multiple year/date-related fields detected,police/arrest/justice-related fields; crime/case/offence-related fields,True
72,42_District_wise_crimes_committed_against_women_2001_2012.csv,9017,10,district-level information may be present,year/date information may be present,victim/demographic-related fields; crime/case/offence-related fields,True
73,42_District_wise_crimes_committed_against_women_2013.csv,823,10,district-level information may be present,year/date information may be present,victim/demographic-related fields; crime/case/offence-related fields,True
74,42_District_wise_crimes_committed_against_women_2014.csv,837,62,district-level information may be present,year/date information may be present,victim/demographic-related fields; crime/case/offence-related fields,True
75,43_Arrests_under_crime_against_women.csv,2765,16,location information may be present,multiple year/date-related fields detected,police/arrest/justice-related fields; crime/case/offence-related fields,True

In [23]:
# ============================================================
# CELL 22 — DETAILED DATASET EVIDENCE
# ============================================================

for _, row in dataset_profile_df.iterrows():

    print("\n" + "=" * 80)
    print(f"DATASET: {row['filename']}")
    print("=" * 80)

    print(f"Rows       : {row['row_count']}")
    print(f"Columns    : {row['column_count']}")

    print(
        f"\nGeographic candidate:"
        f"\n{row['geographic_level_candidate']}"
    )

    print(
        f"\nTime candidate:"
        f"\n{row['time_level_candidate']}"
    )

    print(
        f"\nSubject evidence:"
        f"\n{row['subject_evidence']}"
    )

    print(
        f"\nCrime-related columns:"
        f"\n{row['crime_information_candidate'] or 'None detected'}"
    )

    print(
        f"\nVictim-related columns:"
        f"\n{row['victim_information_candidate'] or 'None detected'}"
    )

    print(
        f"\nPolice/arrest/justice columns:"
        f"\n{row['police_arrest_information_candidate'] or 'None detected'}"
    )

    print(
        f"\nProperty-related columns:"
        f"\n{row['property_information_candidate'] or 'None detected'}"
    )

    print(
        f"\nState columns:"
        f"\n{row['state_columns'] or 'None detected'}"
    )

    print(
        f"\nDistrict columns:"
        f"\n{row['district_columns'] or 'None detected'}"
    )

    print(
        f"\nYear/date columns:"
        f"\n{row['year_date_columns'] or 'None detected'}"
    )

================================================================================
DATASET: 01_District_wise_crimes_committed_IPC_2001_2012.csv
================================================================================
Rows       : 9017
Columns    : 33

Geographic candidate:
district-level information may be present

Time candidate:
year/date information may be present

Subject evidence:
victim/demographic-related fields; crime/case/offence-related fields

Crime-related columns:
MURDER; ATTEMPT TO MURDER; CULPABLE HOMICIDE NOT AMOUNTING TO MURDER; RAPE; CUSTODIAL RAPE; OTHER RAPE; KIDNAPPING & ABDUCTION; KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS; KIDNAPPING AND ABDUCTION OF OTHERS; ROBBERY; THEFT; AUTO THEFT; OTHER THEFT; OTHER IPC CRIMES; TOTAL IPC CRIMES

Victim-related columns:
ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY

Police/arrest/justice columns:
None detected

Property-related columns:
None detected

State columns:
STATE/UT

District columns:
DISTRICT

Year/date columns:
YEAR

================================================================================
DATASET: 01_District_wise_crimes_committed_IPC_2013.csv
================================================================================
Rows       : 823
Columns    : 33

Geographic candidate:
district-level information may be present

Time candidate:
year/date information may be present

Subject evidence:
victim/demographic-related fields; crime/case/offence-related fields

Crime-related columns:
MURDER; ATTEMPT TO MURDER; CULPABLE HOMICIDE NOT AMOUNTING TO MURDER; RAPE; CUSTODIAL RAPE; OTHER RAPE; KIDNAPPING & ABDUCTION; KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS; KIDNAPPING AND ABDUCTION OF OTHERS; ROBBERY; THEFT; AUTO THEFT; OTHER THEFT; OTHER IPC CRIMES; TOTAL IPC CRIMES

Victim-related columns:
ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY

Police/arrest/justice columns:
None detected

Property-related columns:
None detected

State columns:
STATE/UT

District columns:
DISTRICT

Year/date columns:
YEAR

================================================================================
DATASET: 01_District_wise_crimes_committed_IPC_2014.csv
================================================================================
Rows       : 838
Columns    : 91

Geographic candidate:
district-level information may be present

Time candidate:
year/date information may be present

Subject evidence:
police/arrest/justice-related fields; victim/demographic-related fields; crime/case/offence-related fields

Crime-related columns:
Murder; Attempt to commit Murder; Culpable Homicide not amounting to Murder; Rape; Custodial Rape; Custodial_Gang Rape; Custodial_Other Rape; Rape other than Custodial; Rape_Gang Rape; Rape_Others; Attempt to commit Rape; Kidnapping & Abduction_Total; Kidnapping & Abduction; Kidnapping & Abduction in order to Murder; Kidnapping for Ransom; Kidnapping & Abduction of Women to compel her for marriage; Other Kidnapping; Dacoity with Murder; Robbery; Theft; Auto Theft; Other Thefts; Counterfeit Offences related to Counterfeit Coin; Offences against State; Other offences against State; Offences promoting enmity between different groups; Unnatural Offence; Other IPC crimes; Total Cognizable IPC crimes

Victim-related columns:
Kidnapping & Abduction of Women to compel her for marriage; Assault on Women with intent to outrage her Modesty; Sexual Harassment; Disclosure of Identity of Victims

Police/arrest/justice columns:
Riots_Industrial

Property-related columns:
None detected

State columns:
States/UTs; Offences against State; Other offences against State

District columns:
District

Year/date columns:
Year

================================================================================
DATASET: 02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
================================================================================
Rows       : 9018
Columns    : 13

Geographic candidate:
district-level information may be present

Time candidate:
year/date information may be present

Subject evidence:
crime/case/offence-related fields

Crime-related columns:
Murder; Rape; Kidnapping and Abduction; Robbery; Other Crimes Against SCs

Victim-related columns:
None detected

Police/arrest/justice columns:
None detected

Property-related columns:
None detected

State columns:
STATE/UT

District columns:
DISTRICT

Year/date columns:
Year

================================================================================
DATASET: 02_01_District_wise_crimes_committed_against_SC_2013.csv
================================================================================
Rows       : 823
Columns    : 13

Geographic candidate:
district-level information may be present

Time candidate:
year/date information may be present

Subject evidence:
crime/case/offence-related fields

Crime-related columns:
Murder; Rape; Kidnapping and Abduction; Robbery; Other Crimes Against SCs

Victim-related columns:
None detected

Police/arrest/justice columns:
None detected

Property-related columns:
None detected

State columns:
STATE/UT

District columns:
DISTRICT

Year/date columns:
Year

================================================================================
DATASET: 02_01_District_wise_crimes_committed_against_SC_2014.csv
================================================================================
Rows       : 837
Columns    : 66

Geographic candidate:
district-level information may be present

Time candidate:
year/date information may be present

Subject evidence:
victim/demographic-related fields; crime/case/offence-related fields

Crime-related columns:
POA_Murder; POA_Attempt to commit Murder; POA_Rape; POA_Attempt to commit Rape; POA_Kidnapping & Abduction_GrandTotal; POA_Kidnaping & Abduction in order to Murder; POA_Kidnapping for Ransom; POA_Kidnapping & Abduction of Women to compel her for marriage; POA_Other Kidnapping; POA_Dacoity with Murder; POA_Robbery; POA_Other IPC crimes; IPC_Murder; IPC_Attempt to commit Murder; IPC_Rape; IPC_Attempt to commit Rape; IPC_Assault on women with intent to outrage her Modesty; IPC_Sexual Harassment; IPC_Assault on women with intent to Disrobe; IPC_Voyeurism; IPC_Stalking; IPC_Other Sexual Harassment; IPC_Insult to the Modesty of women; IPC_Kidnapping & Abduction; IPC_Kidnaping & Abduction; IPC_Kidnaping & Abduction in order to Murder; IPC_Kidnapping for Ransom; IPC_Kidnapping & Abduction of Women to compel her for marriage; IPC_Other Kidnapping; IPC_Dacoity; IPC_Dacoity with Murder; IPC_Other Dacoity; IPC_Robbery; IPC_Arson; IPC_Grievous Hurt; IPC_Hurt; IPC_Acid attack; IPC_Attempt to Acid Attack; IPC_Riots; IPC_Other IPC crimes; Total IPC Crimes against SCs; Other SLL Crime against SCs; Total crimes against SCs

Victim-related columns:
POA_Assault on women with intent to outrage her Modesty; POA_Sexual Harassment; POA_Other Sexual Harassment; POA_Kidnapping & Abduction of Women to compel her for marriage; IPC_Assault on women with intent to outrage her Modesty; IPC_Sexual Harassment; IPC_Other Sexual Harassment; IPC_Kidnapping & Abduction of Women to compel her for marriage

Police/arrest/justice columns:
None detected

Property-related columns:
None detected

State columns:
States/UTs

District columns:
District

Year/date columns:
Year

================================================================================
DATASET: 02_District_wise_crimes_committed_against_ST_2001_2012.csv
================================================================================
Rows       : 9018
Columns    : 13

Geographic candidate:
district-level information may be present

Time candidate:
year/date information may be present

Subject evidence:
crime/case/offence-related fields

Crime-related columns:
Murder; Rape; Kidnapping Abduction; Robbery; Other Crimes Against STs

Victim-related columns:
None detected

Police/arrest/justice columns:
None detected

Property-related columns:
None detected

State columns:
STATE/UT

District columns:
DISTRICT

Year/date columns:
Year

================================================================================
DATASET: 02_District_wise_crimes_committed_against_ST_2013.csv
================================================================================
Rows       : 823
Columns    : 13

Geographic candidate:
district-level information may be present

Time candidate:
year/date information may be present

Subject evidence:
crime/case/offence-related fields

Crime-related columns:
Murder; Rape; Kidnapping Abduction; Robbery; Other Crimes Against STs

Victim-related columns:
None detected

Police/arrest/justice columns:
None detected

Property-related columns:
None detected

State columns:
STATE/UT

District columns:
DISTRICT

Year/date columns:
Year

================================================================================
DATASET: 02_District_wise_crimes_committed_against_ST_2014.csv
================================================================================
Rows       : 837
Columns    : 66

Geographic candidate:
district-level information may be present

Time candidate:
year/date information may be present

Subject evidence:
victim/demographic-related fields; crime/case/offence-related fields

Crime-related columns:
POA_Murder; POA_Attempt to commit Murder; POA_Rape; POA_Attempt to commit Rape; POA_Kidnapping & Abduction_GrandTotal; POA_Kidnaping & Abduction in order to Murder; POA_Kidnapping for Ransom; POA_Kidnapping & Abduction of Women to compel her for marriage; POA_Other Kidnapping; POA_Dacoity with Murder; POA_Robbery; POA_Other IPC crimes; IPC_Murder; IPC_Attempt to commit Murder; IPC_Rape; IPC_Attempt to commit Rape; IPC_Assault on women with intent to outrage her Modesty; IPC_Sexual Harassment; IPC_Assault on women with intent to Disrobe; IPC_Voyeurism; IPC_Stalking; IPC_Other Sexual Harassment; IPC_Insult to the Modesty of women; IPC_Kidnapping & Abduction; IPC_Kidnaping & Abduction; IPC_Kidnaping & Abduction in order to Murder; IPC_Kidnapping for Ransom; IPC_Kidnapping & Abduction of Women to compel her for marriage; IPC_Other Kidnapping; IPC_Dacoity; IPC_Dacoity with Murder; IPC_Other Dacoity; IPC_Robbery; IPC_Arson; IPC_Grievous Hurt; IPC_Hurt; IPC_Acid attack; IPC_Attempt to Acid Attack; IPC_Riots; IPC_Other IPC crimes; Total IPC Crimes against STs; Other SLL Crime against STs; Total crimes against STs

Victim-related columns:
POA_Assault on women with intent to outrage her Modesty; POA_Sexual Harassment; POA_Other Sexual Harassment; POA_Kidnapping & Abduction of Women to compel her for marriage; IPC_Assault on women with intent to outrage her Modesty; IPC_Sexual Harassment; IPC_Other Sexual Harassment; IPC_Kidnapping & Abduction of Women to compel her for marriage

Police/arrest/justice columns:
None detected

Property-related columns:
None detected

State columns:
States/UTs

District columns:
District

Year/date columns:
Year

================================================================================
DATASET: 03_District_wise_crimes_committed_against_children_2001_2012.csv
================================================================================
Rows       : 9015
Columns    : 15

Geographic candidate:
district-level information may be present

Time candidate:
year/date information may be present

Subject evidence:
victim/demographic-related fields; crime/case/offence-related fields

Crime-related columns:
Murder; Rape; Kidnapping and Abduction; Other Crimes

Victim-related columns:
Prohibition of child marriage act

Police/arrest/justice columns:
None detected

Property-related columns:
None detected

State columns:
STATE/UT

District columns:
DISTRICT

Year/date columns:
Year

================================================================================
DATASET: 03_District_wise_crimes_committed_against_children_2013.csv
================================================================================
Rows       : 823
Columns    : 16

Geographic candidate:
district-level information may be present

Time candidate:
year/date information may be present

Subject evidence:
victim/demographic-related fields; crime/case/offence-related fields

Crime-related columns:
Other murder; Rape; Kidnapping and Abduction; Other Crimes

Victim-related columns:
Prohibition of child marriage act

Police/arrest/justice columns:
None detected

Property-related columns:
None detected

State columns:
STATE/UT

District columns:
DISTRICT

Year/date columns:
Year

================================================================================
DATASET: 03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2012.csv
================================================================================
Rows       : 494
Columns    : 14

Geographic candidate:
state/UT-level information may be present

Time candidate:
multiple year/date-related fields detected

Subject evidence:
police/arrest/justice-related fields; victim/demographic-related fields; crime/case/offence-related fields

Crime-related columns:
CRIME HEAD; Persons in whose cases charge sheets were laid during the year; Persons against whom cases were compounded or withdrawn; Persons in whose cases trials were completed during the year

Victim-related columns:
Persons in custody or on bail during the stage of investigation at the beginning of the year; Persons in custody or on bail during the stage of investigation at the end of the year; Persons in custody or on bail during the stage of trial at the end of the year

Police/arrest/justice columns:
Persons in custody or on bail during the stage of investigation at the beginning of the year; Persons arrested during the year; Persons released or freed by Police or Magistrate before trial for want of evidence or any other reason; Persons in custody or on bail during the stage of investigation at the end of the year; Persons in whose cases charge sheets were laid during the year; Persons under trial at the beginning of the year; Total number of persons under trial during the year; Persons in custody or on bail during the stage of trial at the end of the year; Persons in whose cases trials were completed during the year; Persons convicted; Persons acquitted

Property-related columns:
None detected

State columns:
STATE/UT

District columns:
None detected

Year/date columns:
Persons in custody or on bail during the stage of investigation at the beginning of the year; Persons arrested during the year; Persons in custody or on bail during the stage of investigation at the end of the year; Persons in whose cases charge sheets were laid during the year; Persons under trial at the beginning of the year; Total number of persons under trial during the year; Persons in custody or on bail during the stage of trial at the end of the year; Persons in whose cases trials were completed during the year

================================================================================
DATASET: 03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2013.csv
================================================================================
Rows       : 494
Columns    : 14

Geographic candidate:
state/UT-level information may be present

Time candidate:
multiple year/date-related fields detected

Subject evidence:
police/arrest/justice-related fields; victim/demographic-related fields; crime/case/offence-related fields

Crime-related columns:
CRIME HEAD; Persons in whose cases charge sheets were laid during the year; Persons against whom cases were compounded or withdrawn; Persons in whose cases trials were completed during the year

Victim-related columns:
Persons in custody or on bail during the stage of investigation at the beginning of the year; Persons in custody or on bail during the stage of investigation at the end of the year; Persons in custody or on bail during the stage of trial at the end of the year

Police/arrest/justice columns:
Persons in custody or on bail during the stage of investigation at the beginning of the year; Persons arrested during the year; Persons released or freed by Police or Magistrate before trial for want of evidence or any other reason; Persons in custody or on bail during the stage of investigation at the end of the year; Persons in whose cases charge sheets were laid during the year; Persons under trial at the beginning of the year; Total number of persons under trial during the year; Persons in custody or on bail during the stage of trial at the end of the year; Persons in whose cases trials were completed during the year; Persons convicted; Persons acquitted

Property-related columns:
None detected

State columns:
STATE/UT

District columns:
None detected

Year/date columns:
Persons in custody or on bail during the stage of investigation at the beginning of the year; Persons arrested during the year; Persons in custody or on bail during the stage of investigation at the end of the year; Persons in whose cases charge sheets were laid during the year; Persons under trial at the beginning of the year; Total number of persons under trial during the year; Persons in custody or on bail during the stage of trial at the end of the year; Persons in whose cases trials were completed during the year

================================================================================
DATASET: 03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2014.csv
================================================================================
Rows       : 2028
Columns    : 57

Geographic candidate:
state/UT-level information may be present

Time candidate:
multiple year/date-related fields detected

Subject evidence:
police/arrest/justice-related fields; victim/demographic-related fields; crime/case/offence-related fields

Crime-related columns:
Crime Head; Persons against whom cases were compounded by Courts_Male; Persons against whom cases were compounded by Courts_Female; Persons against whom cases were compounded by Courts_Total; Persons against whom cases were withdrawn_Male; Persons against whom cases were withdrawn_Female; Persons against whom cases were withdrawn_Total; Persons whose cases trials were completed during the year_Male; Persons whose cases trials were completed during the year_Female; Persons whose cases trials were completed during the year_Total

Victim-related columns:
Persons in custody during inv stage at beginning of Year_Male; Persons in custody during inv stage at beginning of Year_Female; Persons in custody during inv stage at beginning of Year_Total; Persons on bail during inv stage at beginning of Year_Male; Persons on bail during inv stage at beginning of Year_Female; Persons on bail during inv stage at beginning of Year_Total; Persons in custody during inv stage at year end_Male; Persons in custody during inv stage at year end_Female; Persons in custody during inv stage at year end_Total; Persons on Bail during inv stage at year end_Male; Persons on Bail during inv stage at Year end_Female; Persons on Bail during inv stage at year end_Total; Persons in custody during trial stage at begin of year_Male; Persons in custody during trial stage at begin of year_Female; Persons in custody during trial stage at begin of year_Total; Persons on Bail during trial stage at begin of year_Male; Persons on Bail during trial stage at begin of year_Female; Persons on Bail during trial stage at begin of year_Total; Persons in custody during trial stage at Year end_Male; Persons in custody during trial stage at Year end_Female; Persons in custody during trial stage at Year end_Total; Persons on bail during trial stage at Year End_Male; Persons on bail during trial stage at Year End_Female; Persons on bail during trial stage at Year End_Total

Police/arrest/justice columns:

In [24]:
# ============================================================
# CELL 23 — SAMPLE ROW INSPECTION FOR ALL DATASETS
# ============================================================

SAMPLE_ROWS = 5

for i, file_path in enumerate(
    csv_files,
    start=1
):

    print("\n" + "=" * 90)
    print(
        f"[{i:02d}/{len(csv_files):02d}] "
        f"{file_path.name}"
    )
    print("=" * 90)

    df, read_info = read_csv_for_inspection(
        file_path
    )

    if df is None:

        print("Unable to read this file.")
        continue

    print(
        f"Shape: {df.shape}"
    )

    print("\nColumns:")

    for column in df.columns:
        print(f"  - {column}")

    print("\nSample rows:")

    display(
        df.head(SAMPLE_ROWS)
    )

==========================================================================================
[01/76] 01_District_wise_crimes_committed_IPC_2001_2012.csv
==========================================================================================
Shape: (9017, 33)

Columns:
  - STATE/UT
  - DISTRICT
  - YEAR
  - MURDER
  - ATTEMPT TO MURDER
  - CULPABLE HOMICIDE NOT AMOUNTING TO MURDER
  - RAPE
  - CUSTODIAL RAPE
  - OTHER RAPE
  - KIDNAPPING & ABDUCTION
  - KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS
  - KIDNAPPING AND ABDUCTION OF OTHERS
  - DACOITY
  - PREPARATION AND ASSEMBLY FOR DACOITY
  - ROBBERY
  - BURGLARY
  - THEFT
  - AUTO THEFT
  - OTHER THEFT
  - RIOTS
  - CRIMINAL BREACH OF TRUST
  - CHEATING
  - COUNTERFIETING
  - ARSON
  - HURT/GREVIOUS HURT
  - DOWRY DEATHS
  - ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY
  - INSULT TO MODESTY OF WOMEN
  - CRUELTY BY HUSBAND OR HIS RELATIVES
  - IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES
  - CAUSING DEATH BY NEGLIGENCE
  - OTHER IPC CRIMES
  - TOTAL IPC CRIMES

Sample rows:

,STATE/UT,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS,KIDNAPPING AND ABDUCTION OF OTHERS,DACOITY,PREPARATION AND ASSEMBLY FOR DACOITY,ROBBERY,BURGLARY,THEFT,AUTO THEFT,OTHER THEFT,RIOTS,CRIMINAL BREACH OF TRUST,CHEATING,COUNTERFIETING,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
0,ANDHRA PRADESH,ADILABAD,2001,101,60,17,50,0,50,46,30,16,9,0,41,198,199,22,177,78,16,104,1,30,1131,16,149,34,175,0,181,1518,4154
1,ANDHRA PRADESH,ANANTAPUR,2001,151,125,1,23,0,23,53,30,23,8,0,16,191,366,57,309,168,11,65,8,69,1543,7,118,24,154,0,270,754,4125
2,ANDHRA PRADESH,CHITTOOR,2001,101,57,2,27,0,27,59,34,25,4,0,14,237,723,164,559,156,33,209,9,38,2088,14,112,83,186,0,404,1262,5818
3,ANDHRA PRADESH,CUDDAPAH,2001,80,53,1,20,0,20,25,20,5,1,0,4,98,173,36,137,164,12,37,2,23,795,17,126,38,57,0,233,1181,3140
4,ANDHRA PRADESH,EAST GODAVARI,2001,82,67,1,23,0,23,49,26,23,4,0,25,437,1021,150,871,70,50,220,3,41,1244,12,109,58,247,0,431,2313,6507

==========================================================================================
[02/76] 01_District_wise_crimes_committed_IPC_2013.csv
==========================================================================================
Shape: (823, 33)

Columns:
  - STATE/UT
  - DISTRICT
  - YEAR
  - MURDER
  - ATTEMPT TO MURDER
  - CULPABLE HOMICIDE NOT AMOUNTING TO MURDER
  - RAPE
  - CUSTODIAL RAPE
  - OTHER RAPE
  - KIDNAPPING & ABDUCTION
  - KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS
  - KIDNAPPING AND ABDUCTION OF OTHERS
  - DACOITY
  - PREPARATION AND ASSEMBLY FOR DACOITY
  - ROBBERY
  - BURGLARY
  - THEFT
  - AUTO THEFT
  - OTHER THEFT
  - RIOTS
  - CRIMINAL BREACH OF TRUST
  - CHEATING
  - COUNTERFIETING
  - ARSON
  - HURT/GREVIOUS HURT
  - DOWRY DEATHS
  - ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY
  - INSULT TO MODESTY OF WOMEN
  - CRUELTY BY HUSBAND OR HIS RELATIVES
  - IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES
  - CAUSING DEATH BY NEGLIGENCE
  - OTHER IPC CRIMES
  - TOTAL IPC CRIMES

Sample rows:

,STATE/UT,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS,KIDNAPPING AND ABDUCTION OF OTHERS,DACOITY,PREPARATION AND ASSEMBLY FOR DACOITY,ROBBERY,BURGLARY,THEFT,AUTO THEFT,OTHER THEFT,RIOTS,CRIMINAL BREACH OF TRUST,CHEATING,COUNTERFIETING,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
0,Andhra Pradesh,ADILABAD,2013,96,72,13,61,0,61,65,47,18,2,0,14,274,377,86,291,58,93,254,1,30,2394,12,197,138,464,0,376,1390,6381
1,Andhra Pradesh,ANANTAPUR,2013,156,149,3,28,0,28,110,84,26,5,0,23,279,597,154,443,56,5,160,5,29,2537,23,337,43,161,0,573,1634,6913
2,Andhra Pradesh,CHITTOOR,2013,72,61,2,31,0,31,52,27,25,3,0,11,157,512,158,354,57,17,238,6,18,937,13,119,84,435,0,546,2239,5610
3,Andhra Pradesh,CUDDAPAH,2013,93,107,7,19,0,19,84,50,34,2,0,9,220,702,255,447,156,81,317,5,34,2310,9,318,163,207,0,464,1741,7048
4,Andhra Pradesh,CYBERABAD,2013,162,123,16,138,0,138,192,129,63,15,0,89,1318,4779,1761,3018,34,179,2111,12,40,4284,43,350,338,1526,0,1104,3139,19992

==========================================================================================
[03/76] 01_District_wise_crimes_committed_IPC_2014.csv
==========================================================================================
Shape: (838, 91)

Columns:
  - States/UTs
  - District
  - Year
  - Murder
  - Attempt to commit Murder
  - Culpable Homicide not amounting to Murder
  - Attempt to commit Culpable Homicide
  - Rape
  - Custodial Rape
  - Custodial_Gang Rape
  - Custodial_Other Rape
  - Rape other than Custodial
  - Rape_Gang Rape
  - Rape_Others
  - Attempt to commit Rape
  - Kidnapping & Abduction_Total
  - Kidnapping & Abduction
  - Kidnapping & Abduction in order to Murder
  - Kidnapping for Ransom
  - Kidnapping & Abduction of Women to compel her for marriage
  - Other Kidnapping
  - Dacoity
  - Dacoity with Murder
  - Other Dacoity
  - Making Preparation and Assembly for committing Dacoity
  - Robbery
  - Criminal Trespass/Burglary
  - Criminal Trespass or Burglary
  - House Trespass & House Breaking
  - Theft
  - Auto Theft
  - Other Thefts
  - Unlawful Assembly
  - Riots
  - Riots_Communal
  - Riots_Industrial
  - Riots_Political
  - Riots_Caste Conflict
  - Riots_SC/STs Vs Non-SCs/STs
  - Riots_Other Caste Conflict
  - Riots_Agrarian
  - Riots_Students
  - Riots_Sectarian
  - Riots_Others
  - Criminal Breach of Trust
  - Cheating
  - Forgery
  - Counterfeiting
  - Counterfeit Offences related to Counterfeit Coin
  - Counterfeiting Government Stamp
  - Counterfeit currency & Bank notes
  - Counterfeiting currency notes/Bank notes
  - Using forged or counterfeiting currency/Bank notes
  - Possession of forged or counterfeiting currency/Bank notes
  - Making or Possessing materials for forged currency/Bank notes
  - Making or Using documents resembling currency
  - Arson
  - Grievous Hurt
  - Hurt
  - Acid attack
  - Attempt to Acid Attack
  - Dowry Deaths
  - Assault on Women with intent to outrage her Modesty
  - Sexual Harassment
  - Assault or use of criminal force to women with intent to Disrobe
  - Voyeurism
  - Stalking
  - Other Assault on Women
  - Insult to the Modesty of Women
  - At Office premises
  - Other places related to work
  - In Public Transport system
  - Places other than 231, 232 & 233
  - Cruelty by Husband or his Relatives
  - Importation of Girls from Foreign Country
  - Causing Death by Negligence
  - Deaths due to negligent driving/act
  - Deaths due to Other Causes
  - Offences against State
  - Sedition
  - Other offences against State
  - Offences promoting enmity between different groups
  - Promoting enmity between different groups
  - Imputation, assertions prejudicial to national integration
  - Extortion
  - Disclosure of Identity of Victims
  - Incidence of Rash Driving
  - HumanTrafficking
  - Unnatural Offence
  - Other IPC crimes
  - Total Cognizable IPC crimes

Sample rows:

,States/UTs,District,Year,Murder,Attempt to commit Murder,Culpable Homicide not amounting to Murder,Attempt to commit Culpable Homicide,Rape,Custodial Rape,Custodial_Gang Rape,Custodial_Other Rape,Rape other than Custodial,Rape_Gang Rape,Rape_Others,Attempt to commit Rape,Kidnapping & Abduction_Total,Kidnapping & Abduction,Kidnapping & Abduction in order to Murder,Kidnapping for Ransom,Kidnapping & Abduction of Women to compel her for marriage,Other Kidnapping,Dacoity,Dacoity with Murder,Other Dacoity,Making Preparation and Assembly for committing Dacoity,Robbery,Criminal Trespass/Burglary,Criminal Trespass or Burglary,House Trespass & House Breaking,Theft,Auto Theft,Other Thefts,Unlawful Assembly,Riots,Riots_Communal,Riots_Industrial,Riots_Political,Riots_Caste Conflict,Riots_SC/STs Vs Non-SCs/STs,Riots_Other Caste Conflict,Riots_Agrarian,Riots_Students,Riots_Sectarian,Riots_Others,Criminal Breach of Trust,Cheating,Forgery,Counterfeiting,Counterfeit Offences related to Counterfeit Coin,Counterfeiting Government Stamp,Counterfeit currency & Bank notes,Counterfeiting currency notes/Bank notes,Using forged or counterfeiting currency/Bank notes,Possession of forged or counterfeiting currency/Bank notes,Making or Possessing materials for forged currency/Bank notes,Making or Using documents resembling currency,Arson,Grievous Hurt,Hurt,Acid attack,Attempt to Acid Attack,Dowry Deaths,Assault on Women with intent to outrage her Modesty,Sexual Harassment,Assault or use of criminal force to women with intent to Disrobe,Voyeurism,Stalking,Other Assault on Women,Insult to the Modesty of Women,At Office premises,Other places related to work,In Public Transport system,"Places other than 231, 232 & 233",Cruelty by Husband or his Relatives,Importation of Girls from Foreign Country,Causing Death by Negligence,Deaths due to negligent driving/act,Deaths due to Other Causes,Offences against State,Sedition,Other offences against State,Offences promoting enmity between different groups,Promoting enmity between different groups,"Imputation, assertions prejudicial to national integration",Extortion,Disclosure of Identity of Victims,Incidence of Rash Driving,HumanTrafficking,Unnatural Offence,Other IPC crimes,Total Cognizable IPC crimes
0,Andhra Pradesh,Anantapur,2014,134,171,8,0,35,0,0,0,35,0,35,1,125,0,0,0,88,37,6,0,6,0,30,415,315,100,753,240,513,0,214,0,0,0,0,0,0,0,0,0,214,13,296,0,10,0,0,10,10,0,0,0,0,12,25,24,1,0,25,436,82,34,4,80,236,26,0,0,0,26,165,0,638,638,0,0,0,0,0,0,0,0,0,1038,0,0,3800,8376
1,Andhra Pradesh,Chittoor,2014,84,170,2,0,32,0,0,0,32,1,31,0,38,4,0,3,28,3,12,0,12,0,22,195,154,41,528,192,336,0,134,0,0,0,0,0,0,0,0,0,134,7,207,0,5,0,0,5,0,5,0,0,0,23,18,18,0,0,17,135,0,0,0,0,135,94,0,0,0,94,278,0,538,538,0,0,0,0,0,0,0,19,0,249,0,0,2567,5374
2,Andhra Pradesh,Cuddapah,2014,80,162,1,0,28,0,0,0,28,0,28,4,27,0,0,0,11,16,3,0,3,0,16,144,144,0,638,193,445,0,104,0,0,104,0,0,0,0,0,0,0,86,163,0,5,0,0,5,5,0,0,0,0,0,39,39,0,0,16,215,212,0,0,0,3,12,1,11,0,0,91,0,417,417,0,0,0,0,0,0,0,0,0,948,0,0,2604,5803
3,Andhra Pradesh,East Godavari,2014,64,84,2,0,85,0,0,0,85,0,85,18,66,0,0,0,0,66,3,0,3,0,24,346,295,51,903,347,556,0,27,0,0,0,0,0,0,0,0,0,27,96,214,0,22,0,0,22,0,22,0,0,0,50,44,43,0,1,7,519,159,61,11,55,233,62,0,0,0,62,464,0,668,642,26,0,0,0,0,0,0,32,0,39,0,0,3791,7630
4,Andhra Pradesh,Guntakal Railway,2014,14,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,2,0,4,0,0,0,413,0,413,0,1,0,0,0,0,0,0,0,0,0,1,0,5,0,5,0,0,5,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,4,0,0,0,0,0,0,0,0,1,0,0,37,490

==========================================================================================
[04/76] 02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
==========================================================================================
Shape: (9018, 13)

Columns:
  - STATE/UT
  - DISTRICT
  - Year
  - Murder
  - Rape
  - Kidnapping and Abduction
  - Dacoity
  - Robbery
  - Arson
  - Hurt
  - Prevention of atrocities (POA) Act
  - Protection of Civil Rights (PCR) Act
  - Other Crimes Against SCs

Sample rows:

,STATE/UT,DISTRICT,Year,Murder,Rape,Kidnapping and Abduction,Dacoity,Robbery,Arson,Hurt,Prevention of atrocities (POA) Act,Protection of Civil Rights (PCR) Act,Other Crimes Against SCs
0,ANDHRA PRADESH,ADILABAD,2001,0,1,4,0,0,0,3,0,15,32
1,ANDHRA PRADESH,ANANTAPUR,2001,0,4,0,0,0,0,49,21,0,53
2,ANDHRA PRADESH,CHITTOOR,2001,3,3,0,0,0,0,38,36,0,34
3,ANDHRA PRADESH,CUDDAPAH,2001,0,3,0,0,0,0,20,52,0,25
4,ANDHRA PRADESH,EAST GODAVARI,2001,1,3,0,0,0,0,3,12,63,7

==========================================================================================
[05/76] 02_01_District_wise_crimes_committed_against_SC_2013.csv
==========================================================================================
Shape: (823, 13)

Columns:
  - STATE/UT
  - DISTRICT
  - Year
  - Murder
  - Rape
  - Kidnapping and Abduction
  - Dacoity
  - Robbery
  - Arson
  - Hurt
  - Protection of Civil Rights (PCR) Act
  - Prevention of atrocities (POA) Act
  - Other Crimes Against SCs

Sample rows:

,STATE/UT,DISTRICT,Year,Murder,Rape,Kidnapping and Abduction,Dacoity,Robbery,Arson,Hurt,Protection of Civil Rights (PCR) Act,Prevention of atrocities (POA) Act,Other Crimes Against SCs
0,Andhra Pradesh,ADILABAD,2013,2,3,0,0,0,0,8,0,15,42
1,Andhra Pradesh,ANANTAPUR,2013,2,4,0,0,0,0,37,0,18,56
2,Andhra Pradesh,CHITTOOR,2013,2,3,0,0,0,1,27,0,9,55
3,Andhra Pradesh,CUDDAPAH,2013,2,2,0,0,0,0,78,0,22,72
4,Andhra Pradesh,CYBERABAD,2013,2,8,0,0,0,0,15,1,61,58

==========================================================================================
[06/76] 02_01_District_wise_crimes_committed_against_SC_2014.csv
==========================================================================================
Shape: (837, 66)

Columns:
  - States/UTs
  - District
  - Year
  - Protection of Civil Rights Act, 1955
  - POA_Murder
  - POA_Attempt to commit Murder
  - POA_Rape
  - POA_Attempt to commit Rape
  - POA_Assault on women with intent to outrage her Modesty
  - POA_Sexual Harassment
  - POA_Assault on women with intent to Disrobe
  - POA_Voyeurism
  - POA_Stalking
  - POA_Other Sexual Harassment
  - POA_Insult to the Modesty of women
  - POA_Kidnapping & Abduction_GrandTotal
  - POA_Kidnaping & Abduction_Total
  - POA_Kidnaping & Abduction in order to Murder
  - POA_Kidnapping for Ransom
  - POA_Kidnapping & Abduction of Women to compel her for marriage
  - POA_Other Kidnapping
  - POA_Dacoity
  - POA_Dacoity with Murder
  - POA_Other Dacoity
  - POA_Robbery
  - POA_Arson
  - POA_Grievous Hurt
  - POA_Hurt
  - POA_Acid attack
  - POA_Attempt to Acid Attack
  - POA_Riots
  - POA_Other IPC crimes
  - POA_SC / ST (Prevention of Atrocities) Act only
  - Total of SC/ST (Prevention of Atrocities) Act ,1989
  - IPC_Murder
  - IPC_Attempt to commit Murder
  - IPC_Rape
  - IPC_Attempt to commit Rape
  - IPC_Assault on women with intent to outrage her Modesty
  - IPC_Sexual Harassment
  - IPC_Assault on women with intent to Disrobe
  - IPC_Voyeurism
  - IPC_Stalking
  - IPC_Other Sexual Harassment
  - IPC_Insult to the Modesty of women
  - IPC_Kidnapping & Abduction
  - IPC_Kidnaping & Abduction
  - IPC_Kidnaping & Abduction in order to Murder
  - IPC_Kidnapping for Ransom
  - IPC_Kidnapping & Abduction of Women to compel her for marriage
  - IPC_Other Kidnapping
  - IPC_Dacoity
  - IPC_Dacoity with Murder
  - IPC_Other Dacoity
  - IPC_Robbery
  - IPC_Arson
  - IPC_Grievous Hurt
  - IPC_Hurt
  - IPC_Acid attack
  - IPC_Attempt to Acid Attack
  - IPC_Riots
  - IPC_Other IPC crimes
  - Total IPC Crimes against SCs
  - Manual Scavengers and Construction of Dry Latrines (P) Act, 1993
  - Other SLL Crime against SCs
  - Total crimes against SCs

Sample rows:

,States/UTs,District,Year,"Protection of Civil Rights Act, 1955",POA_Murder,POA_Attempt to commit Murder,POA_Rape,POA_Attempt to commit Rape,POA_Assault on women with intent to outrage her Modesty,POA_Sexual Harassment,POA_Assault on women with intent to Disrobe,POA_Voyeurism,POA_Stalking,POA_Other Sexual Harassment,POA_Insult to the Modesty of women,POA_Kidnapping & Abduction_GrandTotal,POA_Kidnaping & Abduction_Total,POA_Kidnaping & Abduction in order to Murder,POA_Kidnapping for Ransom,POA_Kidnapping & Abduction of Women to compel her for marriage,POA_Other Kidnapping,POA_Dacoity,POA_Dacoity with Murder,POA_Other Dacoity,POA_Robbery,POA_Arson,POA_Grievous Hurt,POA_Hurt,POA_Acid attack,POA_Attempt to Acid Attack,POA_Riots,POA_Other IPC crimes,POA_SC / ST (Prevention of Atrocities) Act only,"Total of SC/ST (Prevention of Atrocities) Act ,1989",IPC_Murder,IPC_Attempt to commit Murder,IPC_Rape,IPC_Attempt to commit Rape,IPC_Assault on women with intent to outrage her Modesty,IPC_Sexual Harassment,IPC_Assault on women with intent to Disrobe,IPC_Voyeurism,IPC_Stalking,IPC_Other Sexual Harassment,IPC_Insult to the Modesty of women,IPC_Kidnapping & Abduction,IPC_Kidnaping & Abduction,IPC_Kidnaping & Abduction in order to Murder,IPC_Kidnapping for Ransom,IPC_Kidnapping & Abduction of Women to compel her for marriage,IPC_Other Kidnapping,IPC_Dacoity,IPC_Dacoity with Murder,IPC_Other Dacoity,IPC_Robbery,IPC_Arson,IPC_Grievous Hurt,IPC_Hurt,IPC_Acid attack,IPC_Attempt to Acid Attack,IPC_Riots,IPC_Other IPC crimes,Total IPC Crimes against SCs,"Manual Scavengers and Construction of Dry Latrines (P) Act, 1993",Other SLL Crime against SCs,Total crimes against SCs
0,Andhra Pradesh,Anantapur,2014,0,3,0,1,0,5,0,0,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,145,16,170,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,170
1,Andhra Pradesh,Chittoor,2014,0,2,3,1,0,5,0,0,0,0,5,1,1,0,0,0,0,1,0,0,0,0,3,0,0,0,0,7,88,7,118,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,118
2,Andhra Pradesh,Cuddapah,2014,0,4,5,5,1,3,0,0,0,0,3,0,2,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,107,135,262,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,262
3,Andhra Pradesh,East Godavari,2014,6,0,2,4,0,22,8,3,0,1,10,1,0,0,0,0,0,0,0,0,0,0,0,25,25,0,0,0,98,19,171,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,178
4,Andhra Pradesh,Guntakal Railway,2014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

==========================================================================================
[07/76] 02_District_wise_crimes_committed_against_ST_2001_2012.csv
==========================================================================================
Shape: (9018, 13)

Columns:
  - STATE/UT
  - DISTRICT
  - Year
  - Murder
  - Rape
  - Kidnapping Abduction
  - Dacoity
  - Robbery
  - Arson
  - Hurt
  - Protection of Civil Rights (PCR) Act
  - Prevention of atrocities (POA) Act
  - Other Crimes Against STs

Sample rows:

,STATE/UT,DISTRICT,Year,Murder,Rape,Kidnapping Abduction,Dacoity,Robbery,Arson,Hurt,Protection of Civil Rights (PCR) Act,Prevention of atrocities (POA) Act,Other Crimes Against STs
0,ANDHRA PRADESH,ADILABAD,2001,0,1,2,0,0,0,2,0,0,13
1,ANDHRA PRADESH,ANANTAPUR,2001,0,0,0,0,0,0,7,0,1,6
2,ANDHRA PRADESH,CHITTOOR,2001,0,0,0,0,0,0,2,0,0,0
3,ANDHRA PRADESH,CUDDAPAH,2001,0,0,0,0,0,0,2,0,2,0
4,ANDHRA PRADESH,EAST GODAVARI,2001,0,0,0,0,0,0,0,0,0,14

==========================================================================================
[08/76] 02_District_wise_crimes_committed_against_ST_2013.csv
==========================================================================================
Shape: (823, 13)

Columns:
  - STATE/UT
  - DISTRICT
  - Year
  - Murder
  - Rape
  - Kidnapping Abduction
  - Dacoity
  - Robbery
  - Arson
  - Hurt
  - Protection of Civil Rights (PCR) Act
  - Prevention of atrocities (POA) Act
  - Other Crimes Against STs

Sample rows:

,STATE/UT,DISTRICT,Year,Murder,Rape,Kidnapping Abduction,Dacoity,Robbery,Arson,Hurt,Protection of Civil Rights (PCR) Act,Prevention of atrocities (POA) Act,Other Crimes Against STs
0,Andhra Pradesh,ADILABAD,2013,0,7,0,0,0,0,2,0,6,25
1,Andhra Pradesh,ANANTAPUR,2013,0,0,0,0,0,0,3,0,1,9
2,Andhra Pradesh,CHITTOOR,2013,0,0,0,0,0,0,0,0,0,0
3,Andhra Pradesh,CUDDAPAH,2013,0,1,0,0,0,0,17,0,2,10
4,Andhra Pradesh,CYBERABAD,2013,1,2,0,0,0,0,1,0,19,18

==========================================================================================
[09/76] 02_District_wise_crimes_committed_against_ST_2014.csv
==========================================================================================
Shape: (837, 66)

Columns:
  - States/UTs
  - District
  - Year
  - Protection of Civil Rights Act, 1955
  - POA_Murder
  - POA_Attempt to commit Murder
  - POA_Rape
  - POA_Attempt to commit Rape
  - POA_Assault on women with intent to outrage her Modesty
  - POA_Sexual Harassment
  - POA_Assault on women with intent to Disrobe
  - POA_Voyeurism
  - POA_Stalking
  - POA_Other Sexual Harassment
  - POA_Insult to the Modesty of women
  - POA_Kidnapping & Abduction_GrandTotal
  - POA_Kidnaping & Abduction_Total
  - POA_Kidnaping & Abduction in order to Murder
  - POA_Kidnapping for Ransom
  - POA_Kidnapping & Abduction of Women to compel her for marriage
  - POA_Other Kidnapping
  - POA_Dacoity
  - POA_Dacoity with Murder
  - POA_Other Dacoity
  - POA_Robbery
  - POA_Arson
  - POA_Grievous Hurt
  - POA_Hurt
  - POA_Acid attack
  - POA_Attempt to Acid Attack
  - POA_Riots
  - POA_Other IPC crimes
  - POA_SC / ST (Prevention of Atrocities) Act only
  - Total of SC/ST (Prevention of Atrocities) Act ,1989
  - IPC_Murder
  - IPC_Attempt to commit Murder
  - IPC_Rape
  - IPC_Attempt to commit Rape
  - IPC_Assault on women with intent to outrage her Modesty
  - IPC_Sexual Harassment
  - IPC_Assault on women with intent to Disrobe
  - IPC_Voyeurism
  - IPC_Stalking
  - IPC_Other Sexual Harassment
  - IPC_Insult to the Modesty of women
  - IPC_Kidnapping & Abduction
  - IPC_Kidnaping & Abduction
  - IPC_Kidnaping & Abduction in order to Murder
  - IPC_Kidnapping for Ransom
  - IPC_Kidnapping & Abduction of Women to compel her for marriage
  - IPC_Other Kidnapping
  - IPC_Dacoity
  - IPC_Dacoity with Murder
  - IPC_Other Dacoity
  - IPC_Robbery
  - IPC_Arson
  - IPC_Grievous Hurt
  - IPC_Hurt
  - IPC_Acid attack
  - IPC_Attempt to Acid Attack
  - IPC_Riots
  - IPC_Other IPC crimes
  - Total IPC Crimes against STs
  - Manual Scavengers and Construction of Dry Latrines (P) Act, 1993
  - Other SLL Crime against STs
  - Total crimes against STs

Sample rows:

,States/UTs,District,Year,"Protection of Civil Rights Act, 1955",POA_Murder,POA_Attempt to commit Murder,POA_Rape,POA_Attempt to commit Rape,POA_Assault on women with intent to outrage her Modesty,POA_Sexual Harassment,POA_Assault on women with intent to Disrobe,POA_Voyeurism,POA_Stalking,POA_Other Sexual Harassment,POA_Insult to the Modesty of women,POA_Kidnapping & Abduction_GrandTotal,POA_Kidnaping & Abduction_Total,POA_Kidnaping & Abduction in order to Murder,POA_Kidnapping for Ransom,POA_Kidnapping & Abduction of Women to compel her for marriage,POA_Other Kidnapping,POA_Dacoity,POA_Dacoity with Murder,POA_Other Dacoity,POA_Robbery,POA_Arson,POA_Grievous Hurt,POA_Hurt,POA_Acid attack,POA_Attempt to Acid Attack,POA_Riots,POA_Other IPC crimes,POA_SC / ST (Prevention of Atrocities) Act only,"Total of SC/ST (Prevention of Atrocities) Act ,1989",IPC_Murder,IPC_Attempt to commit Murder,IPC_Rape,IPC_Attempt to commit Rape,IPC_Assault on women with intent to outrage her Modesty,IPC_Sexual Harassment,IPC_Assault on women with intent to Disrobe,IPC_Voyeurism,IPC_Stalking,IPC_Other Sexual Harassment,IPC_Insult to the Modesty of women,IPC_Kidnapping & Abduction,IPC_Kidnaping & Abduction,IPC_Kidnaping & Abduction in order to Murder,IPC_Kidnapping for Ransom,IPC_Kidnapping & Abduction of Women to compel her for marriage,IPC_Other Kidnapping,IPC_Dacoity,IPC_Dacoity with Murder,IPC_Other Dacoity,IPC_Robbery,IPC_Arson,IPC_Grievous Hurt,IPC_Hurt,IPC_Acid attack,IPC_Attempt to Acid Attack,IPC_Riots,IPC_Other IPC crimes,Total IPC Crimes against STs,"Manual Scavengers and Construction of Dry Latrines (P) Act, 1993",Other SLL Crime against STs,Total crimes against STs
0,Andhra Pradesh,Anantapur,2014,0,1,2,0,1,2,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,2,23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,23
1,Andhra Pradesh,Chittoor,2014,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,1,0,0,1,13,0,17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,17
2,Andhra Pradesh,Cuddapah,2014,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,13,17,33,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,33
3,Andhra Pradesh,East Godavari,2014,0,1,0,7,0,3,0,0,0,0,3,2,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,12,9,35,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,35
4,Andhra Pradesh,Guntakal Railway,2014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

==========================================================================================
[10/76] 03_District_wise_crimes_committed_against_children_2001_2012.csv
==========================================================================================
Shape: (9015, 15)

Columns:
  - STATE/UT
  - DISTRICT
  - Year
  - Murder
  - Rape
  - Kidnapping and Abduction
  - Foeticide
  - Abetment of suicide
  - Exposure and abandonment
  - Procuration of minor girls
  - Buying of girls for prostitution
  - Selling of girls for prostitution
  - Prohibition of child marriage act
  - Other Crimes
  - Total

Sample rows:

,STATE/UT,DISTRICT,Year,Murder,Rape,Kidnapping and Abduction,Foeticide,Abetment of suicide,Exposure and abandonment,Procuration of minor girls,Buying of girls for prostitution,Selling of girls for prostitution,Prohibition of child marriage act,Other Crimes,Total
0,ANDHRA PRADESH,ADILABAD,2001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,ANDHRA PRADESH,ANANTAPUR,2001,19.0,12.0,29.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,66
2,ANDHRA PRADESH,CHITTOOR,2001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,ANDHRA PRADESH,CUDDAPAH,2001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,ANDHRA PRADESH,EAST GODAVARI,2001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

==========================================================================================
[11/76] 03_District_wise_crimes_committed_against_children_2013.csv
==========================================================================================
Shape: (823, 16)

Columns:
  - STATE/UT
  - DISTRICT
  - Year
  - Infanticid
  - Other murder
  - Rape
  - Kidnapping and Abduction
  - Foeticide
  - Abetment of suicide
  - Exposure and abandonment
  - Procuration of minor girls
  - Buying of girls for prostitution
  - Selling of girls for prostitution
  - Prohibition of child marriage act
  - Other Crimes
  - Total

Sample rows:

,STATE/UT,DISTRICT,Year,Infanticid,Other murder,Rape,Kidnapping and Abduction,Foeticide,Abetment of suicide,Exposure and abandonment,Procuration of minor girls,Buying of girls for prostitution,Selling of girls for prostitution,Prohibition of child marriage act,Other Crimes,Total
0,Andhra Pradesh,ADILABAD,2013,0,1,21,9,0,0,0,0,0,0,1,1,33
1,Andhra Pradesh,ANANTAPUR,2013,0,1,15,68,0,3,0,0,0,0,0,0,87
2,Andhra Pradesh,CHITTOOR,2013,0,6,1,0,0,0,0,0,0,0,0,0,7
3,Andhra Pradesh,CUDDAPAH,2013,2,0,14,32,0,0,0,0,0,0,1,0,49
4,Andhra Pradesh,CYBERABAD,2013,1,8,45,69,2,0,2,9,0,0,1,19,156

==========================================================================================
[12/76] 03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2012.csv
==========================================================================================
Shape: (494, 14)

Columns:
  - STATE/UT
  - CRIME HEAD
  - Persons in custody or on bail during the stage of investigation at the beginning of the year
  - Persons arrested during the year
  - Persons released or freed by Police or Magistrate before trial for want of evidence or any other reason
  - Persons in custody or on bail during the stage of investigation at the end of the year
  - Persons in whose cases charge sheets were laid during the year
  - Persons under trial at the beginning of the year
  - Total number of persons under trial during the year
  - Persons against whom cases were compounded or withdrawn
  - Persons in custody or on bail during the stage of trial at the end of the year
  - Persons in whose cases trials were completed during the year
  - Persons convicted
  - Persons acquitted

Sample rows:

,STATE/UT,CRIME HEAD,Persons in custody or on bail during the stage of investigation at the beginning of the year,Persons arrested during the year,Persons released or freed by Police or Magistrate before trial for want of evidence or any other reason,Persons in custody or on bail during the stage of investigation at the end of the year,Persons in whose cases charge sheets were laid during the year,Persons under trial at the beginning of the year,Total number of persons under trial during the year,Persons against whom cases were compounded or withdrawn,Persons in custody or on bail during the stage of trial at the end of the year,Persons in whose cases trials were completed during the year,Persons convicted,Persons acquitted
0,ANDHRA PRADESH,INFANTICIDE (SECTION 315 IPC),0,6,0,5,1,4,5,0,5,0,0,0
1,ARUNACHAL PRADESH,INFANTICIDE (SECTION 315 IPC),0,0,0,0,0,0,0,0,0,0,0,0
2,ASSAM,INFANTICIDE (SECTION 315 IPC),0,0,0,0,0,0,0,0,0,0,0,0
3,BIHAR,INFANTICIDE (SECTION 315 IPC),0,2,0,0,2,7,9,0,6,3,1,2
4,CHHATTISGARH,INFANTICIDE (SECTION 315 IPC),0,5,0,0,5,16,21,0,17,4,2,2

==========================================================================================
[13/76] 03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2013.csv
==========================================================================================
Shape: (494, 14)

Columns:
  - STATE/UT
  - CRIME HEAD
  - Persons in custody or on bail during the stage of investigation at the beginning of the year
  - Persons arrested during the year
  - Persons released or freed by Police or Magistrate before trial for want of evidence or any other reason
  - Persons in custody or on bail during the stage of investigation at the end of the year
  - Persons in whose cases charge sheets were laid during the year
  - Persons under trial at the beginning of the year
  - Total number of persons under trial during the year
  - Persons against whom cases were compounded or withdrawn
  - Persons in custody or on bail during the stage of trial at the end of the year
  - Persons in whose cases trials were completed during the year
  - Persons convicted
  - Persons acquitted

Sample rows:

,STATE/UT,CRIME HEAD,Persons in custody or on bail during the stage of investigation at the beginning of the year,Persons arrested during the year,Persons released or freed by Police or Magistrate before trial for want of evidence or any other reason,Persons in custody or on bail during the stage of investigation at the end of the year,Persons in whose cases charge sheets were laid during the year,Persons under trial at the beginning of the year,Total number of persons under trial during the year,Persons against whom cases were compounded or withdrawn,Persons in custody or on bail during the stage of trial at the end of the year,Persons in whose cases trials were completed during the year,Persons convicted,Persons acquitted
0,Andhra Pradesh,Abetment of Suicide,0,25,0,7,18,26,44,0,44,0,0,0
1,Arunachal Pradesh,Abetment of Suicide,0,0,0,0,0,0,0,0,0,0,0,0
2,Assam,Abetment of Suicide,2,0,2,0,0,4,4,0,0,4,0,4
3,Bihar,Abetment of Suicide,0,0,0,0,0,0,0,0,0,0,0,0
4,Chhattisgarh,Abetment of Suicide,0,7,0,0,7,18,25,0,19,6,3,3

==========================================================================================
[14/76] 03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2014.csv
==========================================================================================
Shape: (2028, 57)

Columns:
  - States/UTs
  - Crime Head
  - Year
  - Persons in custody during inv stage at beginning of Year_Male
  - Persons in custody during inv stage at beginning of Year_Female
  - Persons in custody during inv stage at beginning of Year_Total
  - Persons on bail during inv stage at beginning of Year_Male
  - Persons on bail during inv stage at beginning of Year_Female
  - Persons on bail during inv stage at beginning of Year_Total
  - Persons arrested during the year_Male
  - Persons arrested during the year_Female
  - Persons arrested during the year_Total
  - Persons released or freed before trial for want of evidence_Male
  - Persons released or freed before trial for want of evidence_Fem
  - Persons released or freed before trial for want of evidence_Tot
  - Persons in custody during inv stage at year end_Male
  - Persons in custody during inv stage at year end_Female
  - Persons in custody during inv stage at year end_Total
  - Persons on Bail during inv stage at year end_Male
  - Persons on Bail during inv stage at Year end_Female
  - Persons on Bail during inv stage at year end_Total
  - Persons charge sheeted_Male
  - Persons charge sheeted_Female
  - Persons charge sheeted_Total
  - Persons in custody during trial stage at begin of year_Male
  - Persons in custody during trial stage at begin of year_Female
  - Persons in custody during trial stage at begin of year_Total
  - Persons on Bail during trial stage at begin of year_Male
  - Persons on Bail during trial stage at begin of year_Female
  - Persons on Bail during trial stage at begin of year_Total
  - Total number of persons under Trial_Male
  - Total number of persons under Trial_Female
  - Total number of persons under Trial_Total
  - Persons against whom cases were compounded by Courts_Male
  - Persons against whom cases were compounded by Courts_Female
  - Persons against whom cases were compounded by Courts_Total
  - Persons against whom cases were withdrawn_Male
  - Persons against whom cases were withdrawn_Female
  - Persons against whom cases were withdrawn_Total
  - Persons in custody during trial stage at Year end_Male
  - Persons in custody during trial stage at Year end_Female
  - Persons in custody during trial stage at Year end_Total
  - Persons on bail during trial stage at Year End_Male
  - Persons on bail during trial stage at Year End_Female
  - Persons on bail during trial stage at Year End_Total
  - Persons whose cases trials were completed during the year_Male
  - Persons whose cases trials were completed during the year_Female
  - Persons whose cases trials were completed during the year_Total
  - Persons convicted_Male
  - Persons convicted_Female
  - Persons convicted_Total
  - Persons acquitted_Male
  - Persons acquitted_Female
  - Persons acquitted_Total
  - Persons Discharged by Court_Male
  - Persons Discharged by Court_Female
  - Persons Discharged by Court_Total

Sample rows:

,States/UTs,Crime Head,Year,Persons in custody during inv stage at beginning of Year_Male,Persons in custody during inv stage at beginning of Year_Female,Persons in custody during inv stage at beginning of Year_Total,Persons on bail during inv stage at beginning of Year_Male,Persons on bail during inv stage at beginning of Year_Female,Persons on bail during inv stage at beginning of Year_Total,Persons arrested during the year_Male,Persons arrested during the year_Female,Persons arrested during the year_Total,Persons released or freed before trial for want of evidence_Male,Persons released or freed before trial for want of evidence_Fem,Persons released or freed before trial for want of evidence_Tot,Persons in custody during inv stage at year end_Male,Persons in custody during inv stage at year end_Female,Persons in custody during inv stage at year end_Total,Persons on Bail during inv stage at year end_Male,Persons on Bail during inv stage at Year end_Female,Persons on Bail during inv stage at year end_Total,Persons charge sheeted_Male,Persons charge sheeted_Female,Persons charge sheeted_Total,Persons in custody during trial stage at begin of year_Male,Persons in custody during trial stage at begin of year_Female,Persons in custody during trial stage at begin of year_Total,Persons on Bail during trial stage at begin of year_Male,Persons on Bail during trial stage at begin of year_Female,Persons on Bail during trial stage at begin of year_Total,Total number of persons under Trial_Male,Total number of persons under Trial_Female,Total number of persons under Trial_Total,Persons against whom cases were compounded by Courts_Male,Persons against whom cases were compounded by Courts_Female,Persons against whom cases were compounded by Courts_Total,Persons against whom cases were withdrawn_Male,Persons against whom cases were withdrawn_Female,Persons against whom cases were withdrawn_Total,Persons in custody during trial stage at Year end_Male,Persons in custody during trial stage at Year end_Female,Persons in custody during trial stage at Year end_Total,Persons on bail during trial stage at Year End_Male,Persons on bail during trial stage at Year End_Female,Persons on bail during trial stage at Year End_Total,Persons whose cases trials were completed during the year_Male,Persons whose cases trials were completed during the year_Female,Persons whose cases trials were completed during the year_Total,Persons convicted_Male,Persons convicted_Female,Persons convicted_Total,Persons acquitted_Male,Persons acquitted_Female,Persons acquitted_Total,Persons Discharged by Court_Male,Persons Discharged by Court_Female,Persons Discharged by Court_Total
0,Andhra Pradesh,1 - Murder (Section 302 and 303 IPC),2014,1,0,1,28,0,28,68,5,73,0,0,0,8,1,9,43,3,46,46,1,47,5,0,5,120,1,121,171,2,173,0,0,0,0,0,0,4,0,4,135,1,136,32,1,33,3,0,3,29,1,30,0,0,0
1,Andhra Pradesh,2 - Infanticide (Section 315 IPC),2014,0,0,0,2,0,2,3,0,3,0,0,0,0,0,0,4,0,4,1,0,1,0,0,0,2,0,2,3,0,3,0,0,0,0,0,0,0,0,0,2,0,2,1,0,1,0,0,0,1,0,1,0,0,0
2,Andhra Pradesh,3 - Rape,2014,21,0,21,187,0,187,617,21,638,0,0,0,17,0,17,410,15,425,398,6,404,15,0,15,572,9,581,985,15,1000,0,0,0,0,0,0,47,0,47,703,14,717,235,1,236,13,0,13,222,1,223,0,0,0
3,Andhra Pradesh,4 - Assault on women with intent to outrage her Modesty (Section 354 IPC),2014,0,0,0,79,4,83,281,4,285,0,0,0,1,0,1,128,2,130,231,6,237,0,0,0,141,0,141,372,6,378,7,0,7,0,0,0,0,0,0,296,6,302,69,0,69,7,0,7,62,0,62,0,0,0
4,Andhra Pradesh,4.1 - Sexual Harassment (Section 354A IPC),2014,0,0,0,6,0,6,69,0,69,0,0,0,0,0,0,30,0,30,45,0,45,0,0,0,16,0,16,61,0,61,0,0,0,0,0,0,0,0,0,53,0,53,8,0,8,0,0,0,8,0,8,0,0,0

==========================================================================================
[15/76] 04_01_Person_arrested_and_their_disposal_by_police_and_court_SLL_crime_2012.csv
==========================================================================================
Shape: (1026, 14)

Columns:
  - STATE/UT
  - CRIME HEAD
  - Persons in custody or on bail during the stage of investigation at the beginning of the year
  - Persons arrested during the year
  - Persons released or freed by Police or Magistrate before trial for want of evidence or any other reason
  - Persons in custody or on bail during the stage of investigation at the end of the year
  - Persons in whose cases charge sheets were laid during the year
  - Persons under trial at the beginning of the year
  - Total number of persons under trial during the year
  - Persons against whom cases were compounded or withdrawn
  - Persons in custody or on bail during the stage of trial at the end of the year
  - Persons in whose cases trials were completed during the year
  - Persons convicted
  - Persons acquitted

Sample rows:

,STATE/UT,CRIME HEAD,Persons in custody or on bail during the stage of investigation at the beginning of the year,Persons arrested during the year,Persons released or freed by Police or Magistrate before trial for want of evidence or any other reason,Persons in custody or on bail during the stage of investigation at the end of the year,Persons in whose cases charge sheets were laid during the year,Persons under trial at the beginning of the year,Total number of persons under trial during the year,Persons against whom cases were compounded or withdrawn,Persons in custody or on bail during the stage of trial at the end of the year,Persons in whose cases trials were completed during the year,Persons convicted,Persons acquitted
0,ANDHRA PRADESH,"ARMS ACT, 1959",301,549,0,295,555,1153,1708,0,1324,384,46,338
1,ARUNACHAL PRADESH,"ARMS ACT, 1959",3,14,0,5,12,194,206,0,199,7,4,3
2,ASSAM,"ARMS ACT, 1959",1705,575,114,1934,232,2483,2715,0,2498,217,31,186
3,BIHAR,"ARMS ACT, 1959",1761,2479,14,1383,2843,26223,29066,0,27108,1958,681,1277
4,CHHATTISGARH,"ARMS ACT, 1959",6,914,0,6,914,3869,4783,237,3695,851,236,615

==========================================================================================
[16/76] 04_01_Person_arrested_and_their_disposal_by_police_and_court_SLL_crime_2013.csv
==========================================================================================
Shape: (418, 14)

Columns:
  - STATE/UT
  - CRIME HEAD
  - Persons in custody or on bail during the stage of investigation at the beginning of the year
  - Persons arrested during the year
  - Persons released or freed by Police or Magistrate before trial for want of evidence or any other reason
  - Persons in custody or on bail during the stage of investigation at the end of the year
  - Persons in whose cases charge sheets were laid during the year
  - Persons under trial at the beginning of the year
  - Total number of persons under trial during the year
  - Persons against whom cases were compounded or withdrawn
  - Persons in custody or on bail during the stage of trial at the end of the year
  - Persons in whose cases trials were completed during the year
  - Persons convicted
  - Persons acquitted

Sample rows:

,STATE/UT,CRIME HEAD,Persons in custody or on bail during the stage of investigation at the beginning of the year,Persons arrested during the year,Persons released or freed by Police or Magistrate before trial for want of evidence or any other reason,Persons in custody or on bail during the stage of investigation at the end of the year,Persons in whose cases charge sheets were laid during the year,Persons under trial at the beginning of the year,Total number of persons under trial during the year,Persons against whom cases were compounded or withdrawn,Persons in custody or on bail during the stage of trial at the end of the year,Persons in whose cases trials were completed during the year,Persons convicted,Persons acquitted
0,Andhra Pradesh,Arson,4,8,0,7,5,35,40,0,38,2,0,2
1,Arunachal Pradesh,Arson,0,0,0,0,0,0,0,0,0,0,0,0
2,Assam,Arson,2,0,2,0,0,6,6,0,0,6,0,6
3,Bihar,Arson,32,73,0,22,83,222,305,0,277,28,0,28
4,Chhattisgarh,Arson,0,1,0,0,1,1,2,0,2,0,0,0

==========================================================================================
[17/76] 04_01_Person_arrested_and_their_disposal_by_police_and_court_SLL_crime_2014.csv
==========================================================================================
Shape: (2730, 57)

Columns:
  - States/UTs
  - Crime Head
  - Year
  - Persons in custody during inv stage at beginning of Year_Male
  - Persons in custody during inv stage at beginning of Year_Female
  - Persons in custody during inv stage at beginning of Year_Total
  - Persons on bail during inv stage at beginning of Year_Male
  - Persons on bail during inv stage at beginning of Year_Female
  - Persons on bail during inv stage at beginning of Year_Total
  - Persons arrested during the year_Male
  - Persons arrested during the year_Female
  - Persons arrested during the year_Total
  - Persons released or freed before trial for want of evidence_Male
  - Persons released or freed before trial for want of evidence_Fem
  - Persons released or freed before trial for want of evidence_Tot
  - Persons in custody during inv stage at year end_Male
  - Persons in custody during inv stage at year end_Female
  - Persons in custody during inv stage at year end_Total
  - Persons on Bail during inv stage at year end_Male
  - Persons on Bail during inv stage at Year end_Female
  - Persons on Bail during inv stage at year end_Total
  - Persons charge sheeted_Male
  - Persons charge sheeted_Female
  - Persons charge sheeted_Total
  - Persons in custody during trial stage at begin of year_Male
  - Persons in custody during trial stage at begin of year_Female
  - Persons in custody during trial stage at begin of year_Total
  - Persons on Bail during trial stage at begin of year_Male
  - Persons on Bail during trial stage at begin of year_Female
  - Persons on Bail during trial stage at begin of year_Total
  - Total number of persons under Trial_Male
  - Total number of persons under Trial_Female
  - Total number of persons under Trial_Total
  - Persons against whom cases were compounded by Courts_Male
  - Persons against whom cases were compounded by Courts_Female
  - Persons against whom cases were compounded by Courts_Total
  - Persons against whom cases were withdrawn_Male
  - Persons against whom cases were withdrawn_Female
  - Persons against whom cases were withdrawn_Total
  - Persons in custody during trial stage at Year end_Male
  - Persons in custody during trial stage at Year end_Female
  - Persons in custody during trial stage at Year end_Total
  - Persons on bail during trial stage at Year End_Male
  - Persons on bail during trial stage at Year End_Female
  - Persons on bail during trial stage at Year End_Total
  - Persons whose cases trials were completed during the year_Male
  - Persons whose cases trials were completed during the year_Female
  - Persons whose cases trials were completed during the year_Total
  - Persons convicted_Male
  - Persons convicted_Female
  - Persons convicted_Total
  - Persons acquitted_Male
  - Persons acquitted_Female
  - Persons acquitted_Total
  - Persons Discharged by Court_Male
  - Persons Discharged by Court_Female
  - Persons Discharged by Court_Total

Sample rows:

,States/UTs,Crime Head,Year,Persons in custody during inv stage at beginning of Year_Male,Persons in custody during inv stage at beginning of Year_Female,Persons in custody during inv stage at beginning of Year_Total,Persons on bail during inv stage at beginning of Year_Male,Persons on bail during inv stage at beginning of Year_Female,Persons on bail during inv stage at beginning of Year_Total,Persons arrested during the year_Male,Persons arrested during the year_Female,Persons arrested during the year_Total,Persons released or freed before trial for want of evidence_Male,Persons released or freed before trial for want of evidence_Fem,Persons released or freed before trial for want of evidence_Tot,Persons in custody during inv stage at year end_Male,Persons in custody during inv stage at year end_Female,Persons in custody during inv stage at year end_Total,Persons on Bail during inv stage at year end_Male,Persons on Bail during inv stage at Year end_Female,Persons on Bail during inv stage at year end_Total,Persons charge sheeted_Male,Persons charge sheeted_Female,Persons charge sheeted_Total,Persons in custody during trial stage at begin of year_Male,Persons in custody during trial stage at begin of year_Female,Persons in custody during trial stage at begin of year_Total,Persons on Bail during trial stage at begin of year_Male,Persons on Bail during trial stage at begin of year_Female,Persons on Bail during trial stage at begin of year_Total,Total number of persons under Trial_Male,Total number of persons under Trial_Female,Total number of persons under Trial_Total,Persons against whom cases were compounded by Courts_Male,Persons against whom cases were compounded by Courts_Female,Persons against whom cases were compounded by Courts_Total,Persons against whom cases were withdrawn_Male,Persons against whom cases were withdrawn_Female,Persons against whom cases were withdrawn_Total,Persons in custody during trial stage at Year end_Male,Persons in custody during trial stage at Year end_Female,Persons in custody during trial stage at Year end_Total,Persons on bail during trial stage at Year End_Male,Persons on bail during trial stage at Year End_Female,Persons on bail during trial stage at Year End_Total,Persons whose cases trials were completed during the year_Male,Persons whose cases trials were completed during the year_Female,Persons whose cases trials were completed during the year_Total,Persons convicted_Male,Persons convicted_Female,Persons convicted_Total,Persons acquitted_Male,Persons acquitted_Female,Persons acquitted_Total,Persons Discharged by Court_Male,Persons Discharged by Court_Female,Persons Discharged by Court_Total
0,Andhra Pradesh,"1 - Arms Act, 1959",2014,4,0,4,96,0,96,261,3,264,0,0,0,8,0,8,187,3,190,166,0,166,55,0,55,364,0,364,585,0,585,0,0,0,0,0,0,22,0,22,435,0,435,128,0,128,39,0,39,89,0,89,0,0,0
1,Andhra Pradesh,"2 - Narcotic Drugs & Psychotropic Substances Act, 1985",2014,26,0,26,447,17,464,739,42,781,6,0,6,25,0,25,698,47,745,483,12,495,134,0,134,1102,22,1124,1719,34,1753,0,0,0,9,0,9,45,0,45,1424,32,1456,241,2,243,32,0,32,209,2,211,0,0,0
2,Andhra Pradesh,"3 - Gambling Act, 1867",2014,15,0,15,907,0,907,24119,0,24119,0,0,0,18,0,18,1025,0,1025,23998,0,23998,223,0,223,1441,0,1441,25662,0,25662,279,0,279,0,0,0,2,0,2,3516,0,3516,21865,0,21865,21135,0,21135,730,0,730,0,0,0
3,Andhra Pradesh,"4 - Excise Act, 1944",2014,103,0,103,877,32,909,5599,155,5754,1581,24,1605,24,2,26,1171,23,1194,3803,138,3941,204,0,204,1358,32,1390,5365,170,5535,704,23,727,22,0,22,59,0,59,2544,41,2585,2036,106,2142,722,8,730,1314,98,1412,0,0,0
4,Andhra Pradesh,5 - Prohibition Act,2014,31,0,31,286,24,310,1710,46,1756,0,0,0,37,0,37,279,17,296,1711,53,1764,108,0,108,417,3,420,2236,56,2292,535,7,542,0,0,0,56,0,56,658,12,670,987,37,1024,431,12,443,556,25,581,0,0,0

==========================================================================================
[18/76] 04_02_Person_arrested_and_their_disposal_by_police_and_court_IPC_crime_2012.csv
==========================================================================================
Shape: (1140, 14)

Columns:
  - STATE/UT
  - CRIME HEAD
  - Persons in custody or on bail during the stage of investigation at the beginning of the year
  - Persons arrested during the year
  - Persons released or freed by Police or Magistrate before trial for want of evidence or any other reason
  - Persons in custody or on bail during the stage of investigation at the end of the year
  - Persons in whose cases charge sheets were laid during the year
  - Persons under trial at the beginning of the year
  - Total number of persons under trial during the year
  - Persons against whom cases were compounded or withdrawn
  - Persons in custody or on bail during the stage of trial at the end of the year
  - Persons in whose cases trials were completed during the year
  - Persons convicted
  - Persons acquitted

Sample rows:

,STATE/UT,CRIME HEAD,Persons in custody or on bail during the stage of investigation at the beginning of the year,Persons arrested during the year,Persons released or freed by Police or Magistrate before trial for want of evidence or any other reason,Persons in custody or on bail during the stage of investigation at the end of the year,Persons in whose cases charge sheets were laid during the year,Persons under trial at the beginning of the year,Total number of persons under trial during the year,Persons against whom cases were compounded or withdrawn,Persons in custody or on bail during the stage of trial at the end of the year,Persons in whose cases trials were completed during the year,Persons convicted,Persons acquitted
0,ANDHRA PRADESH,MURDER (SECTION 302 IPC),3263,5509,0,3138,5634,12111,17745,2,13142,4601,754,3847
1,ARUNACHAL PRADESH,MURDER (SECTION 302 IPC),85,113,28,109,61,1108,1169,0,1161,8,2,6
2,ASSAM,MURDER (SECTION 302 IPC),4628,1650,466,4756,1056,8040,9096,0,8183,913,308,605
3,BIHAR,MURDER (SECTION 302 IPC),7459,7198,51,7399,7207,52966,60173,0,54985,5188,1450,3738
4,CHHATTISGARH,MURDER (SECTION 302 IPC),188,1490,0,158,1520,7803,9323,1221,6661,1441,590,851

==========================================================================================
[19/76] 04_02_Person_arrested_and_their_disposal_by_police_and_court_IPC_crime_2013.csv
==========================================================================================
Shape: (1140, 14)

Columns:
  - STATE/UT
  - CRIME HEAD
  - Persons in custody or on bail during the stage of investigation at the beginning of the year
  - Persons arrested during the year
  - Persons released or freed by Police or Magistrate before trial for want of evidence or any other reason
  - Persons in custody or on bail during the stage of investigation at the end of the year
  - Persons in whose cases charge sheets were laid during the year
  - Persons under trial at the beginning of the year
  - Total number of persons under trial during the year
  - Persons against whom cases were compounded or withdrawn
  - Persons in custody or on bail during the stage of trial at the end of the year
  - Persons in whose cases trials were completed during the year
  - Persons convicted
  - Persons acquitted

Sample rows:

,STATE/UT,CRIME HEAD,Persons in custody or on bail during the stage of investigation at the beginning of the year,Persons arrested during the year,Persons released or freed by Police or Magistrate before trial for want of evidence or any other reason,Persons in custody or on bail during the stage of investigation at the end of the year,Persons in whose cases charge sheets were laid during the year,Persons under trial at the beginning of the year,Total number of persons under trial during the year,Persons against whom cases were compounded or withdrawn,Persons in custody or on bail during the stage of trial at the end of the year,Persons in whose cases trials were completed during the year,Persons convicted,Persons acquitted
0,Andhra Pradesh,Arson,411,820,13,404,814,1878,2692,87,1815,790,63,727
1,Arunachal Pradesh,Arson,9,17,3,12,11,124,135,0,135,0,0,0
2,Assam,Arson,1214,771,405,1205,375,1674,2049,0,1795,254,29,225
3,Bihar,Arson,807,1342,89,653,1407,5821,7228,188,6033,1007,100,907
4,Chhattisgarh,Arson,0,252,0,0,252,1036,1288,17,979,292,49,243

==========================================================================================
[20/76] 04_02_Person_arrested_and_their_disposal_by_police_and_court_IPC_crime_2014.csv
==========================================================================================
Shape: (3432, 57)

Columns:
  - States/UTs
  - Crime Head
  - Year
  - Persons in custody during inv stage at beginning of Year_Male
  - Persons in custody during inv stage at beginning of Year_Female
  - Persons in custody during inv stage at beginning of Year_Total
  - Persons on bail during inv stage at beginning of Year_Male
  - Persons on bail during inv stage at beginning of Year_Female
  - Persons on bail during inv stage at beginning of Year_Total
  - Persons arrested during the year_Male
  - Persons arrested during the year_Female
  - Persons arrested during the year_Total
  - Persons released or freed before trial for want of evidence_Male
  - Persons released or freed before trial for want of evidence_Fem
  - Persons released or freed before trial for want of evidence_Tot
  - Persons in custody during inv stage at year end_Male
  - Persons in custody during inv stage at year end_Female
  - Persons in custody during inv stage at year end_Total
  - Persons on Bail during inv stage at year end_Male
  - Persons on Bail during inv stage at Year end_Female
  - Persons on Bail during inv stage at year end_Total
  - Persons charge sheeted_Male
  - Persons charge sheeted_Female
  - Persons charge sheeted_Total
  - Persons in custody during trial stage at begin of year_Male
  - Persons in custody during trial stage at begin of year_Female
  - Persons in custody during trial stage at begin of year_Total
  - Persons on Bail during trial stage at begin of year_Male
  - Persons on Bail during trial stage at begin of year_Female
  - Persons on Bail during trial stage at begin of year_Total
  - Total number of persons under Trial_Male
  - Total number of persons under Trial_Female
  - Total number of persons under Trial_Total
  - Persons against whom cases were compounded by Courts_Male
  - Persons against whom cases were compounded by Courts_Female
  - Persons against whom cases were compounded by Courts_Total
  - Persons against whom cases were withdrawn_Male
  - Persons against whom cases were withdrawn_Female
  - Persons against whom cases were withdrawn_Total
  - Persons in custody during trial stage at Year end_Male
  - Persons in custody during trial stage at Year end_Female
  - Persons in custody during trial stage at Year end_Total
  - Persons on bail during trial stage at Year End_Male
  - Persons on bail during trial stage at Year End_Female
  - Persons on bail during trial stage at Year End_Total
  - Persons whose cases trials were completed during the year_Male
  - Persons whose cases trials were completed during the year_Female
  - Persons whose cases trials were completed during the year_Total
  - Persons convicted_Male
  - Persons convicted_Female
  - Persons convicted_Total
  - Persons acquitted_Male
  - Persons acquitted_Female
  - Persons acquitted_Total
  - Persons Discharged by Court_Male
  - Persons Discharged by Court_Female
  - Persons Discharged by Court_Total

Sample rows:

,States/UTs,Crime Head,Year,Persons in custody during inv stage at beginning of Year_Male,Persons in custody during inv stage at beginning of Year_Female,Persons in custody during inv stage at beginning of Year_Total,Persons on bail during inv stage at beginning of Year_Male,Persons on bail during inv stage at beginning of Year_Female,Persons on bail during inv stage at beginning of Year_Total,Persons arrested during the year_Male,Persons arrested during the year_Female,Persons arrested during the year_Total,Persons released or freed before trial for want of evidence_Male,Persons released or freed before trial for want of evidence_Fem,Persons released or freed before trial for want of evidence_Tot,Persons in custody during inv stage at year end_Male,Persons in custody during inv stage at year end_Female,Persons in custody during inv stage at year end_Total,Persons on Bail during inv stage at year end_Male,Persons on Bail during inv stage at Year end_Female,Persons on Bail during inv stage at year end_Total,Persons charge sheeted_Male,Persons charge sheeted_Female,Persons charge sheeted_Total,Persons in custody during trial stage at begin of year_Male,Persons in custody during trial stage at begin of year_Female,Persons in custody during trial stage at begin of year_Total,Persons on Bail during trial stage at begin of year_Male,Persons on Bail during trial stage at begin of year_Female,Persons on Bail during trial stage at begin of year_Total,Total number of persons under Trial_Male,Total number of persons under Trial_Female,Total number of persons under Trial_Total,Persons against whom cases were compounded by Courts_Male,Persons against whom cases were compounded by Courts_Female,Persons against whom cases were compounded by Courts_Total,Persons against whom cases were withdrawn_Male,Persons against whom cases were withdrawn_Female,Persons against whom cases were withdrawn_Total,Persons in custody during trial stage at Year end_Male,Persons in custody during trial stage at Year end_Female,Persons in custody during trial stage at Year end_Total,Persons on bail during trial stage at Year End_Male,Persons on bail during trial stage at Year End_Female,Persons on bail during trial stage at Year End_Total,Persons whose cases trials were completed during the year_Male,Persons whose cases trials were completed during the year_Female,Persons whose cases trials were completed during the year_Total,Persons convicted_Male,Persons convicted_Female,Persons convicted_Total,Persons acquitted_Male,Persons acquitted_Female,Persons acquitted_Total,Persons Discharged by Court_Male,Persons Discharged by Court_Female,Persons Discharged by Court_Total
0,Andhra Pradesh,1 - Murder (Section 302 IPC),2014,281,8,289,1529,125,1654,2111,223,2334,0,0,0,259,22,281,1699,143,1842,1963,191,2154,535,12,547,6401,330,6731,8899,533,9432,3,0,3,2,0,2,906,18,924,6412,412,6824,1576,103,1679,252,18,270,1320,85,1405,4,0,4
1,Andhra Pradesh,2 - Attempt to commit Murder (Section 307 IPC),2014,152,0,152,1232,155,1387,2578,97,2675,18,0,18,583,9,592,1680,106,1786,1681,137,1818,191,0,191,5560,199,5759,7432,336,7768,175,0,175,17,0,17,233,1,234,4917,219,5136,2090,116,2206,184,2,186,1897,114,2011,9,0,9
2,Andhra Pradesh,3 - Culpable Homicide not amounting to Murder (Section 304 IPC),2014,7,0,7,68,2,70,94,7,101,0,0,0,1,1,2,68,3,71,100,5,105,26,3,29,232,10,242,358,18,376,0,0,0,0,0,0,15,0,15,247,12,259,96,6,102,6,0,6,90,6,96,0,0,0
3,Andhra Pradesh,4 - Attempt to commit Culpable Homicide (Section 308 IPC),2014,0,0,0,0,0,0,4,0,4,0,0,0,4,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Andhra Pradesh,5 - Rape (Section 376 IPC),2014,71,0,71,586,11,597,1191,46,1237,1,0,1,71,0,71,809,35,844,967,22,989,137,0,137,1852,36,1888,2956,58,3014,11,0,11,0,0,0,180,0,180,2085,46,2131,680,12,692,70,0,70,610,12,622,0,0,0

==========================================================================================
[21/76] 07_01_Persons_arrested_by_sex_and_age_group_IPC_2012.csv
==========================================================================================
Shape: (1140, 15)

Columns:
  - STATE/UT
  - CRIME HEAD
  - Male Below 18 Years
  - Female Below 18 Years
  - Male Between 18-30 Years
  - Female Between 18-30 Years
  - Male Between 30-45 Years
  - Female Between 30-45 Years
  - Male Between 45-60 Years
  - Female Between 45-60 Years
  - Male Above 60 Years
  - Female Above 60 Years
  - Male Total
  - Female Total
  - Grand Total

Sample rows:

,STATE/UT,CRIME HEAD,Male Below 18 Years,Female Below 18 Years,Male Between 18-30 Years,Female Between 18-30 Years,Male Between 30-45 Years,Female Between 30-45 Years,Male Between 45-60 Years,Female Between 45-60 Years,Male Above 60 Years,Female Above 60 Years,Male Total,Female Total,Grand Total
0,ANDHRA PRADESH,MURDER (SECTION 302 IPC),65,3,2054,187,1866,216,919,104,85,10,4989,520,5509
1,ARUNACHAL PRADESH,MURDER (SECTION 302 IPC),0,0,53,0,52,2,6,0,0,0,111,2,113
2,ASSAM,MURDER (SECTION 302 IPC),38,0,584,23,738,19,238,2,8,0,1606,44,1650
3,BIHAR,MURDER (SECTION 302 IPC),60,5,2983,108,2462,145,1202,82,147,4,6854,344,7198
4,CHHATTISGARH,MURDER (SECTION 302 IPC),64,5,560,43,487,46,228,13,36,8,1375,115,1490

==========================================================================================
[22/76] 07_01_Persons_arrested_by_sex_and_age_group_IPC_2013.csv
==========================================================================================
Shape: (1140, 15)

Columns:
  - STATE/UT
  - CRIME HEAD
  - Male Below 18 Years
  - Female Below 18 Years
  - Male Between 18-30 Years
  - Female Between 18-30 Years
  - Male Between 30-45 Years
  - Female Between 30-45 Years
  - Male Between 45-60 Years
  - Female Between 45-60 Years
  - Male Above 60 Years
  - Female Above 60 Years
  - Male Total
  - Female Total
  - Grand Total

Sample rows:

,STATE/UT,CRIME HEAD,Male Below 18 Years,Female Below 18 Years,Male Between 18-30 Years,Female Between 18-30 Years,Male Between 30-45 Years,Female Between 30-45 Years,Male Between 45-60 Years,Female Between 45-60 Years,Male Above 60 Years,Female Above 60 Years,Male Total,Female Total,Grand Total
0,Andhra Pradesh,Arson,4,0,298,11,359,11,116,4,16,1,793,27,820
1,Arunachal Pradesh,Arson,0,0,7,0,10,0,0,0,0,0,17,0,17
2,Assam,Arson,9,0,291,0,421,0,50,0,0,0,771,0,771
3,Bihar,Arson,1,0,687,7,487,7,131,0,22,0,1328,14,1342
4,Chhattisgarh,Arson,2,2,127,4,92,1,22,1,1,0,244,8,252

==========================================================================================
[23/76] 07_01_Persons_arrested_by_sex_and_age_group_IPC_2014.csv
==========================================================================================
Shape: (3432, 18)

Columns:
  - States/UTs
  - Crime Head
  - Year
  - 18 and above and below 30 years_Male
  - 18 and above and below 30 years_Female
  - 18 and above and below 30 years_Total
  - 30 and above and below 45 years_Male
  - 30 and above and below 45 years_Female
  - 30 and above and below 45 years_Total
  - 45 and above and below 60 years_Male
  - 45 and above and below 60 years_Female
  - 45 and above and below 60 years_Total
  - 60 years and above_Male
  - 60 years and above_Female
  - 60 years and above_Total
  - Total Male
  - Total Female
  - Total Persons Arrested by age and Sex

Sample rows:

,States/UTs,Crime Head,Year,18 and above and below 30 years_Male,18 and above and below 30 years_Female,18 and above and below 30 years_Total,30 and above and below 45 years_Male,30 and above and below 45 years_Female,30 and above and below 45 years_Total,45 and above and below 60 years_Male,45 and above and below 60 years_Female,45 and above and below 60 years_Total,60 years and above_Male,60 years and above_Female,60 years and above_Total,Total Male,Total Female,Total Persons Arrested by age and Sex
0,Andhra Pradesh,1 - Murder (Section 302 IPC),2014,754,59,813,772,113,885,517,48,565,48,0,48,2091,220,2311
1,Andhra Pradesh,2 - Attempt to commit Murder (Section 307 IPC),2014,1175,38,1213,920,43,963,448,16,464,22,0,22,2565,97,2662
2,Andhra Pradesh,3 - Culpable Homicide not amounting to Murder (Section 304 IPC),2014,16,2,18,64,4,68,13,1,14,0,0,0,93,7,100
3,Andhra Pradesh,4 - Attempt to commit Culpable Homicide (Section 308 IPC),2014,0,0,0,2,0,2,2,0,2,0,0,0,4,0,4
4,Andhra Pradesh,5 - Rape (Section 376 IPC),2014,708,7,715,341,28,369,88,10,98,11,1,12,1148,46,1194

==========================================================================================
[24/76] 07_02_Persons_arrested_by_sex_and_age_group_SLL_2012.csv
==========================================================================================
Shape: (1026, 15)

Columns:
  - STATE/UT
  - CRIME HEAD
  - Male Below 18 Years
  - Female Below 18 Years
  - Male Between 18-30 Years
  - Female Between 18-30 Years
  - Male Between 30-45 Years
  - Female Between 30-45 Years
  - Male Between 45-60 Years
  - Female Between 45-60 Years
  - Male Above 60 Years
  - Female Above 60 Years
  - Male Total
  - Female Total
  - Grand Total

Sample rows:

,STATE/UT,CRIME HEAD,Male Below 18 Years,Female Below 18 Years,Male Between 18-30 Years,Female Between 18-30 Years,Male Between 30-45 Years,Female Between 30-45 Years,Male Between 45-60 Years,Female Between 45-60 Years,Male Above 60 Years,Female Above 60 Years,Male Total,Female Total,Grand Total
0,ANDHRA PRADESH,ARMS ACT,4,0,262,0,231,0,46,0,6,0,549,0,549
1,ARUNACHAL PRADESH,ARMS ACT,0,0,10,0,4,0,0,0,0,0,14,0,14
2,ASSAM,ARMS ACT,2,0,290,2,249,1,31,0,0,0,572,3,575
3,BIHAR,ARMS ACT,25,0,1483,17,788,2,164,0,0,0,2460,19,2479
4,CHHATTISGARH,ARMS ACT,17,0,527,0,312,0,58,0,0,0,914,0,914

==========================================================================================
[25/76] 07_02_Persons_arrested_by_sex_and_age_group_SLL_2013.csv
==========================================================================================
Shape: (1026, 15)

Columns:
  - STATE/UT
  - CRIME HEAD
  - Male Below 18 Years
  - Female Below 18 Years
  - Male Between 18-30 Years
  - Female Between 18-30 Years
  - Male Between 30-45 Years
  - Female Between 30-45 Years
  - Male Between 45-60 Years
  - Female Between 45-60 Years
  - Male Above 60 Years
  - Female Above 60 Years
  - Male Total
  - Female Total
  - Grand Total

Sample rows:

,STATE/UT,CRIME HEAD,Male Below 18 Years,Female Below 18 Years,Male Between 18-30 Years,Female Between 18-30 Years,Male Between 30-45 Years,Female Between 30-45 Years,Male Between 45-60 Years,Female Between 45-60 Years,Male Above 60 Years,Female Above 60 Years,Male Total,Female Total,Grand Total
0,Andhra Pradesh,"Antiquity & Art Treasures Act, 1972",0,0,7,0,16,0,5,1,0,0,28,1,29
1,Arunachal Pradesh,"Antiquity & Art Treasures Act, 1972",0,0,0,0,0,0,0,0,0,0,0,0,0
2,Assam,"Antiquity & Art Treasures Act, 1972",0,0,0,0,0,0,0,0,0,0,0,0,0
3,Bihar,"Antiquity & Art Treasures Act, 1972",0,0,4,0,0,0,0,0,0,0,4,0,4
4,Chhattisgarh,"Antiquity & Art Treasures Act, 1972",0,0,0,0,0,0,0,0,0,0,0,0,0

==========================================================================================
[26/76] 07_02_Persons_arrested_by_sex_and_age_group_SLL_2014.csv
==========================================================================================
Shape: (2730, 18)

Columns:
  - States/UTs
  - Crime Head
  - Year
  - 18 and above and below 30 years_Male
  - 18 and above and below 30 years_Female
  - 18 and above and below 30 years_Total
  - 30 and above and below 45 years_Male
  - 30 and above and below 45 years_Female
  - 30 and above and below 45 years_Total
  - 45 and above and below 60 years_Male
  - 45 and above and below 60 years_Female
  - 45 and above and below 60 years_Total
  - 60 years and above_Male
  - 60 years and above_Female
  - 60 years and above_Total
  - Total Male
  - Total Female
  - Total Persons Arrested by age and Sex

Sample rows:

,States/UTs,Crime Head,Year,18 and above and below 30 years_Male,18 and above and below 30 years_Female,18 and above and below 30 years_Total,30 and above and below 45 years_Male,30 and above and below 45 years_Female,30 and above and below 45 years_Total,45 and above and below 60 years_Male,45 and above and below 60 years_Female,45 and above and below 60 years_Total,60 years and above_Male,60 years and above_Female,60 years and above_Total,Total Male,Total Female,Total Persons Arrested by age and Sex
0,Andhra Pradesh,"1 - Arms Act, 1959",2014,73,3,76,155,0,155,27,0,27,6,0,6,261,3,264
1,Andhra Pradesh,"2 - Narcotic Drugs & Psychotropic Substances Act, 1985",2014,303,14,317,310,15,325,118,8,126,7,3,10,738,40,778
2,Andhra Pradesh,"3 - Gambling Act, 1867",2014,12473,0,12473,7860,0,7860,3672,0,3672,114,0,114,24119,0,24119
3,Andhra Pradesh,"4 - Excise Act, 1944",2014,2142,38,2180,2270,61,2331,953,54,1007,232,2,234,5597,155,5752
4,Andhra Pradesh,5 - Prohibition Act,2014,300,2,302,968,26,994,426,18,444,12,0,12,1706,46,1752

==========================================================================================
[27/76] 08_01_Juvenile_apprehended_state_IPC.csv
==========================================================================================
Shape: (10500, 12)

Columns:
  - STATE/UT
  - Year
  - CRIME
  - Boys 7-12 Years
  - Girls 7-12 Years
  - Boys 12-16 Years
  - Girls 12-16 Years
  - Boys 16-18 Years
  - Girls 16-18 Years
  - Total for boys all Age Groups
  - Total for girls all Age Groups
  - Grand total

Sample rows:

,STATE/UT,Year,CRIME,Boys 7-12 Years,Girls 7-12 Years,Boys 12-16 Years,Girls 12-16 Years,Boys 16-18 Years,Girls 16-18 Years,Total for boys all Age Groups,Total for girls all Age Groups,Grand total
0,Andhra Pradesh,2001,Murder,3,0,7,0,5,0,15,0,15
1,Andhra Pradesh,2001,Attempt to Commit Murder,2,0,0,0,11,0,13,0,13
2,Andhra Pradesh,2001,C H Not amounting to Murder,0,0,0,0,0,0,0,0,0
3,Andhra Pradesh,2001,Rape,2,0,15,0,2,1,19,1,20
4,Andhra Pradesh,2001,Custodial Rape,0,0,0,0,0,0,0,0,0

==========================================================================================
[28/76] 08_02_Juvenile_apprehended_state_SLL.csv
==========================================================================================
Shape: (9450, 12)

Columns:
  - STATE/UT
  - Year
  - CRIME
  - Boys 7-12 Years
  - Girls 7-12 Years
  - Boys 12-16 Years
  - Girls 12-16 Years
  - Boys 16-18 Years
  - Girls 16-18 Years
  - Total for boys all Age Groups
  - Total for girls all Age Groups
  - Grand total

Sample rows:

,STATE/UT,Year,CRIME,Boys 7-12 Years,Girls 7-12 Years,Boys 12-16 Years,Girls 12-16 Years,Boys 16-18 Years,Girls 16-18 Years,Total for boys all Age Groups,Total for girls all Age Groups,Grand total
0,Andhra Pradesh,2001,"Arms Act, 1959",0,0,2,0,0,0,2,0,2
1,Andhra Pradesh,2001,Narcotic Drugs and Psychotropic Substanc,0,0,0,0,0,0,0,0,0
2,Andhra Pradesh,2001,Gambling Act,0,0,6,0,0,0,6,0,6
3,Andhra Pradesh,2001,Excise Act,0,0,7,0,0,0,7,0,7
4,Andhra Pradesh,2001,Prohibition Act,0,0,37,0,0,0,37,0,37

==========================================================================================
[29/76] 09_Juveniles_arrested_and_their_disposal.csv
==========================================================================================
Shape: (349, 10)

Columns:
  - Area_Name
  - Year
  - Juveniles_Acquitted_or_Otherwise_Disposed_of
  - Juveniles_Arrested
  - Juveniles_Dealt_with_Fine
  - Juveniles_Released_on_Probation_and_placed_under_the_Care_of_Fit_Institutions
  - Juveniles_Released_on_Probation_and_placed_under_the_Care_of_Parent_Guardian
  - Juveniles_Sent_Home_after_Advice_or_Admonition
  - Juveniles_Sent_to_Special_Home
  - Juveniles_whose_Cases_Pending_Disposal

Sample rows:

,Area_Name,Year,Juveniles_Acquitted_or_Otherwise_Disposed_of,Juveniles_Arrested,Juveniles_Dealt_with_Fine,Juveniles_Released_on_Probation_and_placed_under_the_Care_of_Fit_Institutions,Juveniles_Released_on_Probation_and_placed_under_the_Care_of_Parent_Guardian,Juveniles_Sent_Home_after_Advice_or_Admonition,Juveniles_Sent_to_Special_Home,Juveniles_whose_Cases_Pending_Disposal
0,Madhya Pradesh,2002,435,8536,388,329,3774,1239,515,1856
1,Madhya Pradesh,2003,304,7672,512,364,2587,1011,403,2491
2,Madhya Pradesh,2004,605,7433,398,161,1435,1642,572,2620
3,Madhya Pradesh,2007,401,7350,929,343,810,1466,533,2868
4,Madhya Pradesh,2001,180,7328,322,181,1425,1917,1361,1942

==========================================================================================
[30/76] 10_Property_stolen_and_recovered.csv
==========================================================================================
Shape: (2449, 8)

Columns:
  - Area_Name
  - Year
  - Group_Name
  - Sub_Group_Name
  - Cases_Property_Recovered
  - Cases_Property_Stolen
  - Value_of_Property_Recovered
  - Value_of_Property_Stolen

Sample rows:

                   Area_Name  Year           Group_Name Sub_Group_Name  Cases_Property_Recovered  Cases_Property_Stolen  Value_of_Property_Recovered  Value_of_Property_Stolen
0  Andaman & Nicobar Islands  2001  Burglary - Property    3. Burglary                        27                     64                       755858                   1321961
1             Andhra Pradesh  2001  Burglary - Property    3. Burglary                      3321                   7134                     51483437                 147019348
2          Arunachal Pradesh  2001  Burglary - Property    3. Burglary                        66                    248                       825115                   4931904
3                      Assam  2001  Burglary - Property    3. Burglary                       539                   2423                      3722850                  21466955
4                      Bihar  2001  Burglary - Property    3. Burglary                       367                   3231                      2327135                  17023937

==========================================================================================
[31/76] 11_Property_stolen_and_recovered_nature_of_property.csv
==========================================================================================
Shape: (4550, 8)

Columns:
  - Area_Name
  - Year
  - Group_Name
  - Sub_Group_Name
  - Cases_Property_Recovered
  - Cases_Property_Stolen
  - Value_of_Property_Recovered
  - Value_of_Property_Stolen

Sample rows:

                   Area_Name  Year         Group_Name Sub_Group_Name  Cases_Property_Recovered  Cases_Property_Stolen  Value_of_Property_Recovered  Value_of_Property_Stolen
0  Andaman & Nicobar Islands  2001  Cattle - Property      2. Cattle                         0                      1                            0                      1000
1             Andhra Pradesh  2001  Cattle - Property      2. Cattle                       448                    580                      6490596                   7233876
2          Arunachal Pradesh  2001  Cattle - Property      2. Cattle                        22                     34                       135500                    704500
3                      Assam  2001  Cattle - Property      2. Cattle                       149                    322                       683350                   1816386
4                      Bihar  2001  Cattle - Property      2. Cattle                       144                    334                       896019                   1911068

==========================================================================================
[32/76] 12_Police_strength_actual_and_sanctioned.csv
==========================================================================================
Shape: (4188, 16)

Columns:
  - Area_Name
  - Year
  - Group_Name
  - Sub_Group_Name
  - Rank_All_Ranks_Total
  - Rank_ASI_Equivalent
  - Rank_ASPDySPAssttCommandant
  - Rank_Below_HC_and_Above_Constables
  - Rank_Constables
  - Rank_DGAddl_DG
  - Rank_DIG
  - Rank_Head_Constables
  - Rank_IGSplIG
  - Rank_Inspectors_Equivalent
  - Rank_SI_Equivalent
  - Rank_SSPSPAddlSPCommandant

Sample rows:

,Area_Name,Year,Group_Name,Sub_Group_Name,Rank_All_Ranks_Total,Rank_ASI_Equivalent,Rank_ASPDySPAssttCommandant,Rank_Below_HC_and_Above_Constables,Rank_Constables,Rank_DGAddl_DG,Rank_DIG,Rank_Head_Constables,Rank_IGSplIG,Rank_Inspectors_Equivalent,Rank_SI_Equivalent,Rank_SSPSPAddlSPCommandant
0,Andaman & Nicobar Islands,2001,Actual Police Strength - Armed Police,A2. Acual Armed Police (Incl. Women Police),766,7,2,0,646,0,1,84,0,6,20,0
1,Andhra Pradesh,2001,Actual Police Strength - Armed Police,A2. Acual Armed Police (Incl. Women Police),12510,433,56,0,8742,0,0,2864,0,132,270,13
2,Arunachal Pradesh,2001,Actual Police Strength - Armed Police,A2. Acual Armed Police (Incl. Women Police),2232,14,15,169,1645,0,0,322,0,19,45,3
3,Assam,2001,Actual Police Strength - Armed Police,A2. Acual Armed Police (Incl. Women Police),23963,36,135,2347,16591,0,0,3868,0,235,699,52
4,Bihar,2001,Actual Police Strength - Armed Police,A2. Acual Armed Police (Incl. Women Police),373,0,0,0,326,0,0,41,0,2,4,0

==========================================================================================
[33/76] 13_Police_killed_or_injured_on_duty.csv
==========================================================================================
Shape: (2450, 18)

Columns:
  - Area_Name
  - Year
  - Group_Name
  - Sub_Group_Name
  - Police_Injured_By_Criminals
  - Police_Injured_By_Riotous_Mobs
  - Police_Injured_In_Accidents
  - Police_Injured_In_Dacoity_OperationsOther_raids
  - Police_Injured_In_TerroristsExtremists_Operations
  - Police_Injured_On_Border_Duties
  - Police_Injured_Total_Policemen
  - Police_Killed_By_Criminals
  - Police_Killed_By_Riotous_Mobs
  - Police_Killed_In_Accidents
  - Police_Killed_In_Dacoity_OperationsOther_raids
  - Police_Killed_In_TerroristsExtremists_Operations
  - Police_Killed_On_Border_Duties
  - Police_Killed_Total_Policemen

Sample rows:

,Area_Name,Year,Group_Name,Sub_Group_Name,Police_Injured_By_Criminals,Police_Injured_By_Riotous_Mobs,Police_Injured_In_Accidents,Police_Injured_In_Dacoity_OperationsOther_raids,Police_Injured_In_TerroristsExtremists_Operations,Police_Injured_On_Border_Duties,Police_Injured_Total_Policemen,Police_Killed_By_Criminals,Police_Killed_By_Riotous_Mobs,Police_Killed_In_Accidents,Police_Killed_In_Dacoity_OperationsOther_raids,Police_Killed_In_TerroristsExtremists_Operations,Police_Killed_On_Border_Duties,Police_Killed_Total_Policemen
0,Andaman & Nicobar Islands,2001,Police - Assistant Sub-Inspectors,3. Assistant Sub-Inspectos,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Andhra Pradesh,2001,Police - Assistant Sub-Inspectors,3. Assistant Sub-Inspectos,0,3,4,1,3,0,11,0,0,2,0,3,0,5
2,Arunachal Pradesh,2001,Police - Assistant Sub-Inspectors,3. Assistant Sub-Inspectos,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Assam,2001,Police - Assistant Sub-Inspectors,3. Assistant Sub-Inspectos,0,0,0,0,1,0,1,0,0,1,0,0,0,1
4,Bihar,2001,Police - Assistant Sub-Inspectors,3. Assistant Sub-Inspectos,1,0,0,0,2,0,3,0,0,0,0,2,0,2

==========================================================================================
[34/76] 14_Age_profile_of_police_personnel_killed_on_duty.csv
==========================================================================================
Shape: (350, 8)

Columns:
  - Area_Name
  - Year
  - Age_18_25_Yrs
  - Age_25_35_Yrs
  - Age_35_45_Yrs
  - Age_45_55_Yrs
  - Age_Above_55_Yrs
  - Age_Total

Sample rows:

         Area_Name  Year  Age_18_25_Yrs  Age_25_35_Yrs  Age_35_45_Yrs  Age_45_55_Yrs  Age_Above_55_Yrs  Age_Total
0  Jammu & Kashmir  2001             52             67             24              7                 0        150
1     Chhattisgarh  2010              8             54             18              2                 0         82
2  Jammu & Kashmir  2004              4             48              9              4                 0         65
3  Jammu & Kashmir  2002             27             43             18              8                 0         96
4     Chhattisgarh  2007             10             38             27              4                 1         80

==========================================================================================
[35/76] 15_Police_natural_death_and_suicide.csv
==========================================================================================
Shape: (700, 9)

Columns:
  - Area_Name
  - Year
  - Group_Name
  - Age_18_25_Yrs
  - Age_25_35_Yrs
  - Age_35_45_Yrs
  - Age_45_55_Yrs
  - Age_Above_55_Yrs
  - Age_Total

Sample rows:

                   Area_Name  Year                                    Group_Name  Age_18_25_Yrs  Age_25_35_Yrs  Age_35_45_Yrs  Age_45_55_Yrs  Age_Above_55_Yrs  Age_Total
0  Andaman & Nicobar Islands  2001  Natural Deaths of Policemen while in Service              0              0              0              0                 1          1
1             Andhra Pradesh  2001  Natural Deaths of Policemen while in Service              7             39            100             76                11        233
2          Arunachal Pradesh  2001  Natural Deaths of Policemen while in Service              0              2              0              0                 0          2
3                      Assam  2001  Natural Deaths of Policemen while in Service              0              2              4              8                 3         17
4                      Bihar  2001  Natural Deaths of Policemen while in Service              0              7             22             27                13         69

==========================================================================================
[36/76] 16_Casualties_under_police_firing_and_lathi_charge.csv
==========================================================================================
Shape: (1749, 8)

Columns:
  - Area_Name
  - Year
  - Group_Name
  - Civilians_Injured
  - Civilians_Killed
  - No_of_Firings
  - Policemen_Injured
  - Policemen_Killed

Sample rows:

                   Area_Name  Year                       Group_Name  Civilians_Injured  Civilians_Killed  No_of_Firings  Policemen_Injured  Policemen_Killed
0  Andaman & Nicobar Islands  2001  Against Extremists & Terrorists                  0                 0              0                  0                 0
1             Andhra Pradesh  2001  Against Extremists & Terrorists                  4               105            108                 14                 8
2          Arunachal Pradesh  2001  Against Extremists & Terrorists                  0                 0              0                  0                 0
3                      Assam  2001  Against Extremists & Terrorists                  4                26             37                  3                 9
4                      Bihar  2001  Against Extremists & Terrorists                  0                 7             12                 13                 5

==========================================================================================
[37/76] 17_Case_reported_and_value_of_property_taken_away_by_place_of_occurrence_2001_2012.csv
==========================================================================================
Shape: (4344, 11)

Columns:
  - STATE/UT
  - YEAR
  - Place Of Occurrence
  - Dacoity (Section 395-398 IPC) - Number of cases registered
  - Dacoity (Section 395-398 IPC) - Value Of Property Stolen (in rupees)
  - Robbery(Section 392-394, 397, 398 IPC) - Number of cases registered
  - Robbery(Section 392-394, 397, 398 IPC) - Value Of Property Stolen (in rupees)
  - Burglary(Section 449-452, 454, 455, 457-460 IPC) - Number of cases registered
  - Burglary(Section 449-452, 454, 455, 457-460 IPC) - Value Of Property Stolen (in rupees)
  - Theft (Section 379-382 IPC) - Number of cases registered
  - Theft (Section 379-382 IPC) - Value Of Property Stolen (in rupees)

Sample rows:

,STATE/UT,YEAR,Place Of Occurrence,Dacoity (Section 395-398 IPC) - Number of cases registered,Dacoity (Section 395-398 IPC) - Value Of Property Stolen (in rupees),"Robbery(Section 392-394, 397, 398 IPC) - Number of cases registered","Robbery(Section 392-394, 397, 398 IPC) - Value Of Property Stolen (in rupees)","Burglary(Section 449-452, 454, 455, 457-460 IPC) - Number of cases registered","Burglary(Section 449-452, 454, 455, 457-460 IPC) - Value Of Property Stolen (in rupees)",Theft (Section 379-382 IPC) - Number of cases registered,Theft (Section 379-382 IPC) - Value Of Property Stolen (in rupees)
0,Andhra Pradesh,2001,RESIDENTIAL PREMISES,100,4446961,177,5962460,5158,105324332,4257,53517835
1,Andhra Pradesh,2001,HIGH-WAY,57,5340335,172,6364866,31,2000574,74,1593092
2,Andhra Pradesh,2001,RIVER & SEA,2,145345,11,209330,101,1412516,110,1610200
3,Andhra Pradesh,2001,RAILWAYS,8,1750800,19,304336,6,24392,943,16418110
4,Andhra Pradesh,2001,RUNNING TRAINS,5,75000,3,164000,0,0,296,6170175

==========================================================================================
[38/76] 17_Case_reported_and_value_of_property_taken_away_by_place_of_occurrence_2013.csv
==========================================================================================
Shape: (385, 11)

Columns:
  - STATE/UT
  - YEAR
  - Place Of Occurrence
  - Dacoity (Section 395-398 IPC) - Number of cases registered
  - Dacoity (Section 395-398 IPC) - Value Of Property Stolen (in rupees)
  - Robbery(Section 392-394, 397, 398 IPC) - Number of cases registered
  - Robbery(Section 392-394, 397, 398 IPC) - Value Of Property Stolen (in rupees)
  - Burglary(Section 449-452, 454, 455, 457-460 IPC) - Number of cases registered
  - Burglary(Section 449-452, 454, 455, 457-460 IPC) - Value Of Property Stolen (in rupees)
  - Theft (Section 379-382 IPC) - Number of cases registered
  - Theft (Section 379-382 IPC) - Value Of Property Stolen (in rupees)

Sample rows:

,STATE/UT,YEAR,Place Of Occurrence,Dacoity (Section 395-398 IPC) - Number of cases registered,Dacoity (Section 395-398 IPC) - Value Of Property Stolen (in rupees),"Robbery(Section 392-394, 397, 398 IPC) - Number of cases registered","Robbery(Section 392-394, 397, 398 IPC) - Value Of Property Stolen (in rupees)","Burglary(Section 449-452, 454, 455, 457-460 IPC) - Number of cases registered","Burglary(Section 449-452, 454, 455, 457-460 IPC) - Value Of Property Stolen (in rupees)",Theft (Section 379-382 IPC) - Number of cases registered,Theft (Section 379-382 IPC) - Value Of Property Stolen (in rupees)
0,Andhra Pradesh,2013,RESIDENTIAL PREMISES,43,21295800,229,23719985,7264,409568072,10539,470463463
1,Andhra Pradesh,2013,HIGH-WAY,31,6713585,109,11701238,0,0,528,24368531
2,Andhra Pradesh,2013,RIVER & SEA,0,0,1,8000,0,0,58,6612000
3,Andhra Pradesh,2013,RAILWAYS,3,37500,14,246920,0,0,1627,75617986
4,Andhra Pradesh,2013,RUNNING TRAINS,2,4000,4,58000,0,0,818,33655111

==========================================================================================
[39/76] 17_Crime_by_place_of_occurrence_2001_2012.csv
==========================================================================================
Shape: (456, 34)

Columns:
  - STATE/UT
  - YEAR
  - RESIDENTIAL PREMISES - Dacoity
  - RESIDENTIAL PREMISES - Robbery
  - RESIDENTIAL PREMISES - Burglary
  - RESIDENTIAL PREMISES - Theft
  - HIGHWAYS - Dacoity
  - HIGHWAYS - Robbery
  - HIGHWAYS - Burglary
  - HIGHWAYS - Theft
  - RIVER and SEA - Dacoity
  - RIVER and SEA - Robbery
  - RIVER and SEA - Burglary
  - RIVER and SEA - Theft
  - RAILWAYS - Dacoity
  - RAILWAYS - Robbery
  - RAILWAYS - Burglary
  - RAILWAYS - Theft
  - BANKS - Dacoity
  - BANKS - Robbery
  - BANKS - Burglary
  - BANKS - Theft
  - COMMERCIAL ESTABLISHMENTS - Dacoity
  - COMMERCIAL ESTABLISHMENTS - Robbery
  - COMMERCIAL ESTABLISHMENTS - Burglary
  - COMMERCIAL ESTABLISHMENTS - Theft
  - OTHER PLACES - Dacoity
  - OTHER PLACES - Robbery
  - OTHER PLACES - Burglary
  - OTHER PLACES - Theft
  - TOTAL - Dacoity
  - TOTAL - Robbery
  - TOTAL - Burglary
  - TOTAL - Theft

Sample rows:

,STATE/UT,YEAR,RESIDENTIAL PREMISES - Dacoity,RESIDENTIAL PREMISES - Robbery,RESIDENTIAL PREMISES - Burglary,RESIDENTIAL PREMISES - Theft,HIGHWAYS - Dacoity,HIGHWAYS - Robbery,HIGHWAYS - Burglary,HIGHWAYS - Theft,RIVER and SEA - Dacoity,RIVER and SEA - Robbery,RIVER and SEA - Burglary,RIVER and SEA - Theft,RAILWAYS - Dacoity,RAILWAYS - Robbery,RAILWAYS - Burglary,RAILWAYS - Theft,BANKS - Dacoity,BANKS - Robbery,BANKS - Burglary,BANKS - Theft,COMMERCIAL ESTABLISHMENTS - Dacoity,COMMERCIAL ESTABLISHMENTS - Robbery,COMMERCIAL ESTABLISHMENTS - Burglary,COMMERCIAL ESTABLISHMENTS - Theft,OTHER PLACES - Dacoity,OTHER PLACES - Robbery,OTHER PLACES - Burglary,OTHER PLACES - Theft,TOTAL - Dacoity,TOTAL - Robbery,TOTAL - Burglary,TOTAL - Theft
0,ANDHRA PRADESH,2001,100,177,5158,4257,57,172,31,74,2,11,101,110,8,19,6,943,0,2,21,16,10,16,1041,2502,37,232,862,8849,214,629,7220,16751
1,ARUNACHAL PRADESH,2001,9,26,99,131,0,0,0,8,0,0,0,1,0,0,0,0,0,0,0,0,5,18,84,54,8,40,65,249,22,84,248,443
2,ASSAM,2001,381,191,1695,2901,46,136,7,87,1,0,0,8,4,5,3,39,1,11,5,23,22,83,442,967,77,261,271,1342,532,687,2423,5367
3,BIHAR,2001,818,326,2486,4741,162,826,0,257,1,0,0,0,50,52,0,1432,23,11,11,3,27,108,231,686,210,880,505,2582,1291,2203,3233,9701
4,CHHATTISGARH,2001,54,42,3336,1417,10,38,12,72,0,0,0,2,2,9,0,179,2,1,6,8,4,9,370,299,15,239,420,2835,87,338,4144,4812

==========================================================================================
[40/76] 17_Crime_by_place_of_occurrence_2013.csv
==========================================================================================
Shape: (38, 34)

Columns:
  - STATE/UT
  - YEAR
  - RESIDENTIAL PREMISES - Dacoity
  - RESIDENTIAL PREMISES - Robbery
  - RESIDENTIAL PREMISES - Burglary
  - RESIDENTIAL PREMISES - Theft
  - HIGHWAYS - Dacoity
  - HIGHWAYS - Robbery
  - HIGHWAYS - Burglary
  - HIGHWAYS - Theft
  - RIVER and SEA - Dacoity
  - RIVER and SEA - Robbery
  - RIVER and SEA - Burglary
  - RIVER and SEA - Theft
  - RAILWAYS - Dacoity
  - RAILWAYS - Robbery
  - RAILWAYS - Burglary
  - RAILWAYS - Theft
  - BANKS - Dacoity
  - BANKS - Robbery
  - BANKS - Burglary
  - BANKS - Theft
  - COMMERCIAL ESTABLISHMENTS - Dacoity
  - COMMERCIAL ESTABLISHMENTS - Robbery
  - COMMERCIAL ESTABLISHMENTS - Burglary
  - COMMERCIAL ESTABLISHMENTS - Theft
  - OTHER PLACES - Dacoity
  - OTHER PLACES - Robbery
  - OTHER PLACES - Burglary
  - OTHER PLACES - Theft
  - TOTAL - Dacoity
  - TOTAL - Robbery
  - TOTAL - Burglary
  - TOTAL - Theft

Sample rows:

,STATE/UT,YEAR,RESIDENTIAL PREMISES - Dacoity,RESIDENTIAL PREMISES - Robbery,RESIDENTIAL PREMISES - Burglary,RESIDENTIAL PREMISES - Theft,HIGHWAYS - Dacoity,HIGHWAYS - Robbery,HIGHWAYS - Burglary,HIGHWAYS - Theft,RIVER and SEA - Dacoity,RIVER and SEA - Robbery,RIVER and SEA - Burglary,RIVER and SEA - Theft,RAILWAYS - Dacoity,RAILWAYS - Robbery,RAILWAYS - Burglary,RAILWAYS - Theft,BANKS - Dacoity,BANKS - Robbery,BANKS - Burglary,BANKS - Theft,COMMERCIAL ESTABLISHMENTS - Dacoity,COMMERCIAL ESTABLISHMENTS - Robbery,COMMERCIAL ESTABLISHMENTS - Burglary,COMMERCIAL ESTABLISHMENTS - Theft,OTHER PLACES - Dacoity,OTHER PLACES - Robbery,OTHER PLACES - Burglary,OTHER PLACES - Theft,TOTAL - Dacoity,TOTAL - Robbery,TOTAL - Burglary,TOTAL - Theft
0,Andhra Pradesh,2013,43,229,7264,10539,31,109,0,528,0,1,0,58,3,14,0,1627,0,4,20,32,3,27,796,2578,45,325,1740,15670,125,709,9820,31032
1,Arunachal Pradesh,2013,6,19,85,138,3,12,0,7,0,1,0,1,0,0,0,0,0,2,0,0,0,13,54,168,15,28,57,200,24,75,196,514
2,Assam,2013,133,313,2652,6449,12,92,17,22,0,0,0,0,0,0,7,21,1,1,1,3,8,80,542,797,92,437,1072,3223,246,923,4291,10515
3,Bihar,2013,260,85,3084,9360,240,1244,9,588,0,0,0,0,9,33,3,1350,9,2,0,7,19,38,312,2129,42,119,777,7989,579,1521,4185,21423
4,Chhattisgarh,2013,7,15,2759,1356,7,51,67,37,1,0,0,1,0,3,2,193,0,2,10,0,1,9,313,402,31,271,376,3200,47,351,3527,5189

==========================================================================================
[41/76] 17_Crime_by_place_of_occurrence_2014.csv
==========================================================================================
Shape: (39, 82)

Columns:
  - States/UTs
  - Year
  - Residence_Dacoity_Cases reported
  - Residence_Dacoity_Value of property stolen
  - Residence_Robbery_Cases reported
  - Residence_Robbery_Value of property stolen
  - Residence_Burglary_Cases reported
  - Residence_Burglary_Value of property stolen
  - Residence_Theft_Cases reported
  - Residence_Theft_Value of property stolen
  - Highways_Dacoity_Cases reported
  - Highways_Dacoity_Value of property stolen
  - Highways_Robbery_Cases reported
  - Highways_Robbery_Value of property stolen
  - Highways_Burglary_Cases reported
  - Highways_Burglary_Value of property stolen
  - Highways_Theft_Cases reported
  - Highways_Theft_Value of property stolen
  - RiverOrSea_Dacoity_Cases reported
  - RiverOrSea_Dacoity_Value of property stolen
  - RiverOrSea_Robbery_Cases reported
  - RiverOrSea_Robbery_Value of property stolen
  - RiverOrSea_Burglary_Cases reported
  - RiverOrSea_Burglary_Value of property stolen
  - RiverOrSea_Theft_Cases reported
  - RiverOrSea_Theft_Value of property stolen
  - Railways_Dacoity_Cases reported
  - Railways_Dacoity_Value of property stolen
  - Railways_Robbery_Cases reported
  - Railways_Robbery_Value of property stolen
  - Railways_Burglary_Cases reported
  - Railways_Burglary_Value of property stolen
  - Railways_Theft_Cases reported
  - Railways_Theft_Value of property stolen
  - Religious Places_Dacoity_Cases reported
  - Religious Places_Dacoity_Value of property stolen
  - Religious Places_Robbery_Cases reported
  - Religious Places_Robbery_Value of property stolen
  - Religious Places_Burglary_Cases reported
  - Religious Places_Burglary_Value of property stolen
  - Religious Places_Theft_Cases reported
  - Religious Places_Theft_Value of property stolen
  - ATM_Dacoity_Cases reported
  - ATM_Dacoity_Value of property stolen
  - ATM_Robbery_Cases reported
  - ATM_Robbery_Value of property stolen
  - ATM_Burglary_Cases reported
  - ATM_Burglary_Value of property stolen
  - ATM_Theft_Cases reported
  - ATM_Theft_Value of property stolen
  - Bank_Dacoity_Cases reported
  - Bank_Dacoity_Value of property stolen
  - Bank_Robbery_Cases reported
  - Bank_Robbery_Value of property stolen
  - Bank_Burglary_Cases reported
  - Bank_Burglary_Value of property stolen
  - Bank_Theft_Cases reported
  - Bank_Theft_Value of property stolen
  - CommEst_Dacoity_Cases reported
  - CommEst_Dacoity_Value of property stolen
  - CommEst_Robbery_Cases reported
  - CommEst_Robbery_Value of property stolen
  - CommEst_Burglary_Cases reported
  - CommEst_Burglary_Value of property stolen
  - CommEst_Theft_Cases reported
  - CommEst_Theft_Value of property stolen
  - OtherPlaces_Dacoity_Cases reported
  - OtherPlaces_Dacoity_Value of property stolen
  - OtherPlaces_Robbery_Cases reported
  - OtherPlaces_Robbery_Value of property stolen
  - OtherPlaces_Burglary_Cases reported
  - OtherPlaces_Burglary_Value of property stolen
  - OtherPlaces_Theft_Cases reported
  - OtherPlaces_Theft_Value of property stolen
  - Total_Dacoity_Cases reported
  - Total_Dacoity_Value of property stolen
  - Total_Robbery_Cases reported
  - Total_Robbery_Value of property stolen
  - Total_Burglary_Cases reported
  - Total_Burglary_Value of property stolen
  - Total_Theft_Cases reported
  - Total_Theft_Value of property stolen

Sample rows:

,States/UTs,Year,Residence_Dacoity_Cases reported,Residence_Dacoity_Value of property stolen,Residence_Robbery_Cases reported,Residence_Robbery_Value of property stolen,Residence_Burglary_Cases reported,Residence_Burglary_Value of property stolen,Residence_Theft_Cases reported,Residence_Theft_Value of property stolen,Highways_Dacoity_Cases reported,Highways_Dacoity_Value of property stolen,Highways_Robbery_Cases reported,Highways_Robbery_Value of property stolen,Highways_Burglary_Cases reported,Highways_Burglary_Value of property stolen,Highways_Theft_Cases reported,Highways_Theft_Value of property stolen,RiverOrSea_Dacoity_Cases reported,RiverOrSea_Dacoity_Value of property stolen,RiverOrSea_Robbery_Cases reported,RiverOrSea_Robbery_Value of property stolen,RiverOrSea_Burglary_Cases reported,RiverOrSea_Burglary_Value of property stolen,RiverOrSea_Theft_Cases reported,RiverOrSea_Theft_Value of property stolen,Railways_Dacoity_Cases reported,Railways_Dacoity_Value of property stolen,Railways_Robbery_Cases reported,Railways_Robbery_Value of property stolen,Railways_Burglary_Cases reported,Railways_Burglary_Value of property stolen,Railways_Theft_Cases reported,Railways_Theft_Value of property stolen,Religious Places_Dacoity_Cases reported,Religious Places_Dacoity_Value of property stolen,Religious Places_Robbery_Cases reported,Religious Places_Robbery_Value of property stolen,Religious Places_Burglary_Cases reported,Religious Places_Burglary_Value of property stolen,Religious Places_Theft_Cases reported,Religious Places_Theft_Value of property stolen,ATM_Dacoity_Cases reported,ATM_Dacoity_Value of property stolen,ATM_Robbery_Cases reported,ATM_Robbery_Value of property stolen,ATM_Burglary_Cases reported,ATM_Burglary_Value of property stolen,ATM_Theft_Cases reported,ATM_Theft_Value of property stolen,Bank_Dacoity_Cases reported,Bank_Dacoity_Value of property stolen,Bank_Robbery_Cases reported,Bank_Robbery_Value of property stolen,Bank_Burglary_Cases reported,Bank_Burglary_Value of property stolen,Bank_Theft_Cases reported,Bank_Theft_Value of property stolen,CommEst_Dacoity_Cases reported,CommEst_Dacoity_Value of property stolen,CommEst_Robbery_Cases reported,CommEst_Robbery_Value of property stolen,CommEst_Burglary_Cases reported,CommEst_Burglary_Value of property stolen,CommEst_Theft_Cases reported,CommEst_Theft_Value of property stolen,OtherPlaces_Dacoity_Cases reported,OtherPlaces_Dacoity_Value of property stolen,OtherPlaces_Robbery_Cases reported,OtherPlaces_Robbery_Value of property stolen,OtherPlaces_Burglary_Cases reported,OtherPlaces_Burglary_Value of property stolen,OtherPlaces_Theft_Cases reported,OtherPlaces_Theft_Value of property stolen,Total_Dacoity_Cases reported,Total_Dacoity_Value of property stolen,Total_Robbery_Cases reported,Total_Robbery_Value of property stolen,Total_Burglary_Cases reported,Total_Burglary_Value of property stolen,Total_Theft_Cases reported,Total_Theft_Value of property stolen
0,Andhra Pradesh,2014,27,7983001,124,10577950,3530,226363051,5757,199348324,25,11356187,155,9135413,1,65000,2063,133931812,0,0,1,25000,0,0,6,48500,2,15000,11,4015320,0,0,1499,57043722,1,30000,48,7813627,137,5771775.0,121,4044289,0,0,0,0,11,1216300,57,1565651,0,0,0,0,4,215000,70,2597500,2,5656000,4,1537200,453,58698377,1047,44014781,18,2112180,90,8044133,583,29022813,4997,199285711,75,27152368,433,41148643,4719,321352316.0,15617,641880290
1,Arunachal Pradesh,2014,3,67500,8,86350,103,6637940,173,15422078,2,160000,23,2041480,0,0,84,11213650,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,35000,0,0,0,0,0,0.0,21,969280,0,0,0,0,2,50000,0,0,0,0,1,4200000,1,30000,0,0,2,23500,6,126500,51,3678635,61,13901750,5,226000,23,2264600,67,1928240,158,37247470,12,477000,61,8718930,224,12324815.0,498,78789228
2,Assam,2014,144,10693775,315,4191631,2293,26376373,4503,131897564,25,517160,74,887600,65,277000,317,3798500,0,0,1,150000,0,0,0,0,0,0,0,0,0,0,12,91000,0,0,9,35000,57,11700.0,5,205000,5,1475000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24,587900,110,1458386,647,5167008,1919,45335294,69,3329396,529,11398536,1892,17537489,5981,130654964,267,16603231,1038,18121153,4954,49369570.0,12737,311982322
3,Bihar,2014,174,27725940,117,6558972,3693,262152615,6655,116467719,213,59028180,1224,57521104,29,1190150,1849,46605294,0,0,12,109800,0,0,51,156000,12,729832,22,343236,8,31000,1182,17575022,0,0,0,0,1,350000.0,99,1663235,1,400000,2,135000,1,20000,97,5185000,8,49338970,9,914395,2,18000,165,5973000,12,2413730,14,970960,594,11825555,1916,83127467,118,11880081,200,7459492,346,3885065,10874,416911296,538,151516733,1600,74012959,4674,279472385.0,22888,693664033
4,Chhattisgarh,2014,27,3076170,25,1137900,1985,85802275,1235,53896428,5,154300,92,2947100,374,10388186,477,21201575,0,0,0,0,0,0,1,800000,0,0,5,108860,0,0,181,10032481,0,0,2,31100,15,364510.0,2,1350,0,0,1,122350,3,361000,2,136698,0,0,4,490359,7,515410,415,13018374,2,157883,60,698427,275,11094928,728,41883909,24,907713067,216,20941730,588,41656363,3057,125524854,58,911101420,405,26477826,3247,150182672.0,6098,266495669

==========================================================================================
[42/76] 18_01_Juveniles_arrested_Education.csv
==========================================================================================
Shape: (350, 8)

Columns:
  - Area_Name
  - Year
  - Sub_Group_Name
  - Education_Above_Primary_but_below_Matric_or_Higher_Secondary
  - Education_Illiterate
  - Education_Matric_or_Higher_Secondary_&_above
  - Education_Total
  - Education_Upto_primary

Sample rows:

,Area_Name,Year,Sub_Group_Name,Education_Above_Primary_but_below_Matric_or_Higher_Secondary,Education_Illiterate,Education_Matric_or_Higher_Secondary_&_above,Education_Total,Education_Upto_primary
0,Andaman & Nicobar Islands,2001,1. Education,12,0,0,16,4
1,Andhra Pradesh,2001,1. Education,178,640,64,1565,683
2,Arunachal Pradesh,2001,1. Education,39,16,12,137,70
3,Assam,2001,1. Education,74,91,0,253,88
4,Bihar,2001,1. Education,87,190,56,586,253

==========================================================================================
[43/76] 18_02_Juveniles_arrested_Economic_setup.csv
==========================================================================================
Shape: (350, 10)

Columns:
  - Area_Name
  - Year
  - Sub_Group_Name
  - Economic_Set_up_Annual_Income_250001_to_50000
  - Economic_Set_up_Annual_Income_upto_Rs_25000
  - Economic_Set_up_Middle_income_from_100001_to_200000
  - Economic_Set_up_Middle_income_from_50001_to_100000
  - Economic_Set_up_Total
  - Economic_Set_up_Upper_income_above_Rs_300000
  - Economic_Set_up_Upper_middle_income_from_200001_to_300000

Sample rows:

,Area_Name,Year,Sub_Group_Name,Economic_Set_up_Annual_Income_250001_to_50000,Economic_Set_up_Annual_Income_upto_Rs_25000,Economic_Set_up_Middle_income_from_100001_to_200000,Economic_Set_up_Middle_income_from_50001_to_100000,Economic_Set_up_Total,Economic_Set_up_Upper_income_above_Rs_300000,Economic_Set_up_Upper_middle_income_from_200001_to_300000
0,Andaman & Nicobar Islands,2001,2. Economic Setup,12,4,0,0,16,0,0
1,Andhra Pradesh,2001,2. Economic Setup,104,1421,9,27,1565,4,0
2,Arunachal Pradesh,2001,2. Economic Setup,38,99,0,0,137,0,0
3,Assam,2001,2. Economic Setup,47,177,13,16,253,0,0
4,Bihar,2001,2. Economic Setup,213,303,12,58,586,0,0

==========================================================================================
[44/76] 18_03_Juveniles_arrested_Family_background.csv
==========================================================================================
Shape: (350, 7)

Columns:
  - Area_Name
  - Year
  - Sub_Group_Name
  - Family_back_ground_Homeless
  - Family_back_ground_Living_with_guardian
  - Family_back_ground_Living_with_parents
  - Family_back_ground_Total

Sample rows:

                   Area_Name  Year        Sub_Group_Name  Family_back_ground_Homeless  Family_back_ground_Living_with_guardian  Family_back_ground_Living_with_parents  Family_back_ground_Total
0  Andaman & Nicobar Islands  2001  3. Family Background                            0                                        0                                      16                        16
1             Andhra Pradesh  2001  3. Family Background                          552                                      287                                     726                      1565
2          Arunachal Pradesh  2001  3. Family Background                            0                                       58                                      79                       137
3                      Assam  2001  3. Family Background                           21                                       74                                     158                       253
4                      Bihar  2001  3. Family Background                           43                                      101                                     442                       586

==========================================================================================
[45/76] 18_04_Juveniles_arrested_Recidivism.csv
==========================================================================================
Shape: (350, 6)

Columns:
  - Area_Name
  - Year
  - Sub_Group_Name
  - Recidivism_New_Delinquent
  - Recidivism_Old_Delinquent
  - Recidivism_Total

Sample rows:

                   Area_Name  Year Sub_Group_Name  Recidivism_New_Delinquent  Recidivism_Old_Delinquent  Recidivism_Total
0  Andaman & Nicobar Islands  2001  4. Recidivism                         16                          0                16
1             Andhra Pradesh  2001  4. Recidivism                       1392                        173              1565
2          Arunachal Pradesh  2001  4. Recidivism                        130                          7               137
3                      Assam  2001  4. Recidivism                        248                          5               253
4                      Bihar  2001  4. Recidivism                        576                         10               586

==========================================================================================
[46/76] 19_Motive_or_cause_of_murder_and_culpable_homicide_not_amounting_to_murder.csv
==========================================================================================
Shape: (350, 30)

Columns:
  - Area_Name
  - Year
  - CHNAMurder_Cause_By_TerroristExtremist
  - CHNAMurder_Cause_Casteism
  - CHNAMurder_Cause_Class_Conflict
  - CHNAMurder_Cause_Communalism
  - CHNAMurder_Cause_Dowry
  - CHNAMurder_Cause_For_Political_reason
  - CHNAMurder_Cause_Gain
  - CHNAMurder_Cause_Love_AffairsSexual_Relations
  - CHNAMurder_Cause_Lunacy
  - CHNAMurder_Cause_Other_Causes_or_Motives
  - CHNAMurder_Cause_Personal_Vendetta_or_Enmity
  - CHNAMurder_Cause_Property_Dispute
  - CHNAMurder_Cause_Total
  - CHNAMurder_Cause_Witchcraft
  - Murder_Cause_By_TerroristExtremist
  - Murder_Cause_Casteism
  - Murder_Cause_Class_Conflict
  - Murder_Cause_Communalism
  - Murder_Cause_Dowry
  - Murder_Cause_For_Political_reason
  - Murder_Cause_Gain
  - Murder_Cause_Love_AffairsSexual_Relations
  - Murder_Cause_Lunacy
  - Murder_Cause_Other_Causes_or_Motives
  - Murder_Cause_Personal_Vendetta_or_Enmity
  - Murder_Cause_Property_Dispute
  - Murder_Cause_Total
  - Murder_Cause_Witchcraft

Sample rows:

,Area_Name,Year,CHNAMurder_Cause_By_TerroristExtremist,CHNAMurder_Cause_Casteism,CHNAMurder_Cause_Class_Conflict,CHNAMurder_Cause_Communalism,CHNAMurder_Cause_Dowry,CHNAMurder_Cause_For_Political_reason,CHNAMurder_Cause_Gain,CHNAMurder_Cause_Love_AffairsSexual_Relations,CHNAMurder_Cause_Lunacy,CHNAMurder_Cause_Other_Causes_or_Motives,CHNAMurder_Cause_Personal_Vendetta_or_Enmity,CHNAMurder_Cause_Property_Dispute,CHNAMurder_Cause_Total,CHNAMurder_Cause_Witchcraft,Murder_Cause_By_TerroristExtremist,Murder_Cause_Casteism,Murder_Cause_Class_Conflict,Murder_Cause_Communalism,Murder_Cause_Dowry,Murder_Cause_For_Political_reason,Murder_Cause_Gain,Murder_Cause_Love_AffairsSexual_Relations,Murder_Cause_Lunacy,Murder_Cause_Other_Causes_or_Motives,Murder_Cause_Personal_Vendetta_or_Enmity,Murder_Cause_Property_Dispute,Murder_Cause_Total,Murder_Cause_Witchcraft
0,Odisha,2007,0,11,0,0,2,0,0,0,0,4,1,4,22,0,6,1,0,0,138,4,60,61,1,755,113,43,1210,28
1,Jharkhand,2002,0,3,2,2,13,3,7,9,3,61,1,9,115,2,22,9,3,0,70,25,103,158,3,599,242,228,1488,26
2,Jharkhand,2004,0,3,2,2,13,3,7,9,3,61,1,9,115,2,22,9,3,0,70,25,103,158,3,599,242,228,1488,26
3,Bihar,2010,0,2,2,0,11,0,47,35,0,120,30,97,344,0,22,11,6,0,168,24,352,187,5,1228,441,916,3362,2
4,Karnataka,2002,0,1,0,0,0,0,0,1,0,53,0,0,55,0,0,1,0,4,52,6,55,130,0,1093,188,98,1627,0

==========================================================================================
[47/76] 20_Victims_of_rape.csv
==========================================================================================
Shape: (1050, 11)

Columns:
  - Area_Name
  - Year
  - Subgroup
  - Rape_Cases_Reported
  - Victims_Above_50_Yrs
  - Victims_Between_10-14_Yrs
  - Victims_Between_14-18_Yrs
  - Victims_Between_18-30_Yrs
  - Victims_Between_30-50_Yrs
  - Victims_of_Rape_Total
  - Victims_Upto_10_Yrs

Sample rows:

,Area_Name,Year,Subgroup,Rape_Cases_Reported,Victims_Above_50_Yrs,Victims_Between_10-14_Yrs,Victims_Between_14-18_Yrs,Victims_Between_18-30_Yrs,Victims_Between_30-50_Yrs,Victims_of_Rape_Total,Victims_Upto_10_Yrs
0,Andaman & Nicobar Islands,2001,Total Rape Victims,3,0,0,3,0,0,3,0
1,Andaman & Nicobar Islands,2001,Victims of Incest Rape,1,0,0,1,0,0,1,0
2,Andaman & Nicobar Islands,2001,Victims of Other Rape,2,0,0,2,0,0,2,0
3,Andaman & Nicobar Islands,2002,Total Rape Victims,2,0,0,1,1,0,2,0
4,Andaman & Nicobar Islands,2002,Victims of Incest Rape,0,0,0,0,0,0,0,0

==========================================================================================
[48/76] 21_Offenders_known_to_the_victim.csv
==========================================================================================
Shape: (350, 7)

Columns:
  - Area_Name
  - Year
  - No_of_Cases_in_which_offenders_were_known_to_the_Victims
  - No_of_Cases_in_which_offenders_were_Neighbours
  - No_of_Cases_in_which_offenders_were_Other_Known_persons
  - No_of_Cases_in_which_offenders_were_Parentsclose_family_members
  - No_of_Cases_in_which_offenders_were_Relatives

Sample rows:

,Area_Name,Year,No_of_Cases_in_which_offenders_were_known_to_the_Victims,No_of_Cases_in_which_offenders_were_Neighbours,No_of_Cases_in_which_offenders_were_Other_Known_persons,No_of_Cases_in_which_offenders_were_Parentsclose_family_members,No_of_Cases_in_which_offenders_were_Relatives
0,Madhya Pradesh,2007,3010,1397,1384,49,180
1,Madhya Pradesh,2008,2937,1279,1433,52,173
2,Madhya Pradesh,2009,2998,1254,1528,14,202
3,Madhya Pradesh,2010,3135,1223,1659,21,232
4,West Bengal,2010,2134,1037,987,4,106

==========================================================================================
[49/76] 22_Persons_arrested_under_recidivism.csv
==========================================================================================
Shape: (350, 7)

Columns:
  - Area_Name
  - Year
  - Offenders_Arrested
  - Offenders_Arrested_for_the_First_time
  - Offenders_Conviction_in_the_past_Once
  - Offenders_Conviction_in_the_past_Three_times_or_More
  - Offenders_Conviction_in_the_past_Twice

Sample rows:

,Area_Name,Year,Offenders_Arrested,Offenders_Arrested_for_the_First_time,Offenders_Conviction_in_the_past_Once,Offenders_Conviction_in_the_past_Three_times_or_More,Offenders_Conviction_in_the_past_Twice
0,Uttar Pradesh,2001,314055,305811,6528,305,1411
1,Maharashtra,2008,311598,304892,5622,246,838
2,Maharashtra,2010,305629,301091,3139,375,1024
3,Madhya Pradesh,2010,343192,294222,37544,3119,8307
4,Uttar Pradesh,2010,292050,289905,1562,76,507

==========================================================================================
[50/76] 23_Anti_corruprion_cases.csv
==========================================================================================
Shape: (346, 29)

Columns:
  - Area_Name
  - Year
  - AC01_No_of_cases_pending_investigation_from_previous_year
  - AC02_No_of_cases_registered_during_the_year
  - AC03_Total_No_of_cases_for_investigation_during_the_year
  - AC04_No_of_cases_investigated_during_the_year
  - AC05_No_of_cases_not_investigatedor_in_which_investigation_was_dropped_due_to_any_reason_during_the_year
  - AC06_No_of_cases_transferred_to_local_police_during_the_year
  - AC07_No_of_cases_declared_false_mistake_of_fact_or_of_law_or_non_cognizable_or_civil_in_nature
  - AC08_No_of_cases_in_which_charge_sheets_were_laid_during_the_year
  - AC09_No_of_cases_pending_departmental_sanction_for_prosecution_during_the_year
  - AC10_No_of_cases_sent_up_for_trial_and_also_reported_for_departmental_action_during_the_year
  - AC11_No_of_cases_reported_for_regular_departmental_action_during_the_year
  - AC12_No_of_cases_reported_for_suitable_action_during_the_year
  - AC13_No_of_cases_in_which_charge_sheets_were_not_laid_but_final_report_submitted_during_the_year
  - AC14_No_of_cases_pending_investigation_at_the_end_of_the_year
  - AC15_No_of_cases_resulted_in_recoveries_or_seizures_during_the_year
  - AC16_Value_of_property_recoveredseized_during_the_year_in_Rs
  - AC17_Percentage_of_cases_charge_sheeted_to_total_cases_investigated
  - AC18_No_of_cases_pending_trial_from_the_previous_year
  - AC19_No_of_cases_sent_up_for_trial_during_the_year
  - AC20_Total_No_of_cases_for_trial_during_the_year
  - AC21_No_of_cases_withdrawn_or_other_wise_disposed_off_on_account_of_death_of_the_accused_during_the_year
  - AC22_No_of_cases_in_which_trials_were_completed_during_the_year
  - AC23_No_of_cases_convicted_during_the_year
  - AC24_No_of_cases_acquitted_or_discharged_during_the_year
  - AC25_No_of_cases_pending_trial_at_the_end_of_the_year
  - AC26_Percentage_of_cases_convicted_to_cases_in_which_trials_were_completed_during_the_year
  - AC27_Total_amount_of_fine_imposed_during_the_year_in_Rs

Sample rows:

,Area_Name,Year,AC01_No_of_cases_pending_investigation_from_previous_year,AC02_No_of_cases_registered_during_the_year,AC03_Total_No_of_cases_for_investigation_during_the_year,AC04_No_of_cases_investigated_during_the_year,AC05_No_of_cases_not_investigatedor_in_which_investigation_was_dropped_due_to_any_reason_during_the_year,AC06_No_of_cases_transferred_to_local_police_during_the_year,AC07_No_of_cases_declared_false_mistake_of_fact_or_of_law_or_non_cognizable_or_civil_in_nature,AC08_No_of_cases_in_which_charge_sheets_were_laid_during_the_year,AC09_No_of_cases_pending_departmental_sanction_for_prosecution_during_the_year,AC10_No_of_cases_sent_up_for_trial_and_also_reported_for_departmental_action_during_the_year,AC11_No_of_cases_reported_for_regular_departmental_action_during_the_year,AC12_No_of_cases_reported_for_suitable_action_during_the_year,AC13_No_of_cases_in_which_charge_sheets_were_not_laid_but_final_report_submitted_during_the_year,AC14_No_of_cases_pending_investigation_at_the_end_of_the_year,AC15_No_of_cases_resulted_in_recoveries_or_seizures_during_the_year,AC16_Value_of_property_recoveredseized_during_the_year_in_Rs,AC17_Percentage_of_cases_charge_sheeted_to_total_cases_investigated,AC18_No_of_cases_pending_trial_from_the_previous_year,AC19_No_of_cases_sent_up_for_trial_during_the_year,AC20_Total_No_of_cases_for_trial_during_the_year,AC21_No_of_cases_withdrawn_or_other_wise_disposed_off_on_account_of_death_of_the_accused_during_the_year,AC22_No_of_cases_in_which_trials_were_completed_during_the_year,AC23_No_of_cases_convicted_during_the_year,AC24_No_of_cases_acquitted_or_discharged_during_the_year,AC25_No_of_cases_pending_trial_at_the_end_of_the_year,AC26_Percentage_of_cases_convicted_to_cases_in_which_trials_were_completed_during_the_year,AC27_Total_amount_of_fine_imposed_during_the_year_in_Rs
0,Rajasthan,2010,740.0,576.0,1316.0,1316.0,0.0,0.0,0.0,281.0,196.0,126.0,126.0,48.0,70.0,965.0,225.0,1481450.0,0.0,1817.0,281.0,2098.0,8.0,57.0,11.0,46.0,2033.0,0.0,33750.0
1,Maharashtra,2010,724.0,528.0,1252.0,1252.0,2.0,0.0,4.0,446.0,250.0,1.0,37.0,0.0,26.0,780.0,155.0,28841870.0,0.0,2042.0,446.0,2488.0,5.0,366.0,68.0,298.0,2117.0,0.0,383000.0
2,Maharashtra,2003,509.0,521.0,1030.0,1030.0,3.0,3.0,1.0,479.0,237.0,0.0,2.0,0.0,44.0,520.0,154.0,9114731.0,0.0,2602.0,479.0,3081.0,5.0,396.0,113.0,283.0,2680.0,0.0,404600.0
3,Tamil Nadu,2009,347.0,498.0,845.0,845.0,0.0,0.0,0.0,156.0,90.0,67.0,115.0,19.0,243.0,492.0,182.0,10466646.0,0.0,308.0,156.0,464.0,13.0,52.0,26.0,26.0,399.0,0.0,149300.0
4,Maharashtra,2001,505.0,497.0,1002.0,1002.0,2.0,6.0,6.0,472.0,199.0,1.0,8.0,0.0,27.0,491.0,32.0,7993106.0,0.0,2321.0,472.0,2793.0,3.0,287.0,97.0,190.0,2503.0,0.0,1061500.0

==========================================================================================
[51/76] 24_Anti_corruption_arrests.csv
==========================================================================================
Shape: (347, 24)

Columns:
  - Area_Name
  - Year
  - ACA01_No_of_persons_in_custody_or_on_bail_during_the_stage_of_investigation_at_the_beginning_of_the_year
  - ACA02_No_of_persons_arrested_during_the_year
  - ACA04_No_of_persons_in_custody_or_on_bail_during_the_stage_of_investigation_at_the_end_of_the_year
  - ACA05_No_of_persons_in_whose_cases_charge_sheets_were_laid_during_the_year
  - ACA06_No_of_persons_under_trial_at_the_beginning_of_the_year
  - ACA07_Total_No_of_persons_under_trial_during_the_year
  - ACA08_No_of_persons_whose_cases_were_withdrawn_or_otherwise_disposed_off_during_the_year
  - ACA09_No_of_persons_in_custody_or_on_bail_during_the_stage_of_trial_at_the_end_of_the_year
  - ACA10_No_of_persons_in_whose_cases_trials_were_completed_during_the_year
  - ACA11_No_of_persons_convicted_during_the_year
  - ACA12_No_of_persons_acquitted_during_the_year
  - ACA13_Percentage_of_persons_convicted_to_total_persons_in_whose_cases_trials_were_completed_during_the_year
  - ACA14_No_of_persons_involved_in_the_cases_reported_for_Regular_Departmental_Action_during_the_year
  - ACA15_No_of_persons_involved_in_the_cases_reported_for_suitable_action_during_the_year
  - ACA16_No_of_persons_punished_departmentally_during_the_year:
  - ACA161_No_of_persons_dismissed_from_Service_during_the_year
  - ACA162_No_of_persons_removed_from_service_during_the_year
  - ACA163_No_of_persons_awarded_other_major_punishments_during_the_year
  - ACA164_No_of_persons_awarded_minor_punishments_during_the_year
  - ACA171_No_of_Group_`A'_Officers_out_of_above
  - ACA172_No_of_Group_`B'_Officers_out_of_above
  - ACA19_No_of_private_persons_involved_during_the_year

Sample rows:

,Area_Name,Year,ACA01_No_of_persons_in_custody_or_on_bail_during_the_stage_of_investigation_at_the_beginning_of_the_year,ACA02_No_of_persons_arrested_during_the_year,ACA04_No_of_persons_in_custody_or_on_bail_during_the_stage_of_investigation_at_the_end_of_the_year,ACA05_No_of_persons_in_whose_cases_charge_sheets_were_laid_during_the_year,ACA06_No_of_persons_under_trial_at_the_beginning_of_the_year,ACA07_Total_No_of_persons_under_trial_during_the_year,ACA08_No_of_persons_whose_cases_were_withdrawn_or_otherwise_disposed_off_during_the_year,ACA09_No_of_persons_in_custody_or_on_bail_during_the_stage_of_trial_at_the_end_of_the_year,ACA10_No_of_persons_in_whose_cases_trials_were_completed_during_the_year,ACA11_No_of_persons_convicted_during_the_year,ACA12_No_of_persons_acquitted_during_the_year,ACA13_Percentage_of_persons_convicted_to_total_persons_in_whose_cases_trials_were_completed_during_the_year,ACA14_No_of_persons_involved_in_the_cases_reported_for_Regular_Departmental_Action_during_the_year,ACA15_No_of_persons_involved_in_the_cases_reported_for_suitable_action_during_the_year,ACA16_No_of_persons_punished_departmentally_during_the_year:,ACA161_No_of_persons_dismissed_from_Service_during_the_year,ACA162_No_of_persons_removed_from_service_during_the_year,ACA163_No_of_persons_awarded_other_major_punishments_during_the_year,ACA164_No_of_persons_awarded_minor_punishments_during_the_year,ACA171_No_of_Group_`A'_Officers_out_of_above,ACA172_No_of_Group_`B'_Officers_out_of_above,ACA19_No_of_private_persons_involved_during_the_year
0,Bihar,2007,13.0,950.0,20.0,943.0,0.0,0.0,4.0,0.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,246.0,150.0,215.0
1,Gujarat,2010,144.0,947.0,449.0,642.0,959.0,1601.0,0.0,1378.0,223.0,51.0,172.0,0.0,5.0,35.0,6.0,1.0,0.0,2.0,3.0,9.0,46.0,35.0
2,Maharashtra,2007,775.0,870.0,1188.0,453.0,3588.0,4041.0,21.0,3553.0,467.0,97.0,370.0,0.0,10.0,0.0,3.0,1.0,0.0,1.0,1.0,88.0,72.0,73.0
3,Maharashtra,2003,825.0,792.0,869.0,730.0,3717.0,4447.0,14.0,3929.0,504.0,131.0,373.0,0.0,5.0,0.0,3.0,0.0,0.0,0.0,3.0,54.0,81.0,93.0
4,Punjab,2005,338.0,748.0,523.0,529.0,1037.0,1566.0,35.0,1244.0,287.0,95.0,192.0,0.0,0.0,26.0,8.0,8.0,0.0,0.0,0.0,79.0,0.0,115.0

==========================================================================================
[52/76] 25_Complaints_against_police.csv
==========================================================================================
Shape: (350, 22)

Columns:
  - Area_Name
  - Year
  - Sub_group
  - CPA_-_Cases_Registered
  - CPA_-_Cases_Reported_for_Dept._Action
  - CPA_-_Complaints/Cases_Declared_False/Unsubstantiated
  - CPA_-_Complaints_Received/Alleged
  - CPA_-_No_of_Departmental_Enquiries
  - CPA_-_No_of_Magisterial_Enquiries
  - CPA-_Cases_Sent_for_Trials/Charge-sheeted
  - CPA-_No_of_Judicial_Enquiries
  - CPB_-_Police_Personnel_Acquitted
  - CPB_-_Police_Personnel_Convicted
  - CPB_-_Police_Personnel_sent_up_for_Trial
  - CPB_-_Police_Personnel_Trial_Completed
  - CPB-_Police_Personnel_Cases_Withdrawn_or_Otherwise_disposed_of
  - CPC_-_Police_personnel_Cases_Trial_Completed
  - CPC_-_Police_Personnel_Cases_Withdrawn_or_Otherwise_disposed_of
  - CPC_-_Police_Personnel_Disciplinary_Action_Initiated
  - CPC_-_Police_Personnel_Dismissal/Removal_from_Service
  - CPC_-_Police_Personnel_Major_Punishment_awarded
  - CPC_-_Police_Personnel_Minor_Punishment_awarded

Sample rows:

,Area_Name,Year,Sub_group,CPA_-_Cases_Registered,CPA_-_Cases_Reported_for_Dept._Action,CPA_-_Complaints/Cases_Declared_False/Unsubstantiated,CPA_-_Complaints_Received/Alleged,CPA_-_No_of_Departmental_Enquiries,CPA_-_No_of_Magisterial_Enquiries,CPA-_Cases_Sent_for_Trials/Charge-sheeted,CPA-_No_of_Judicial_Enquiries,CPB_-_Police_Personnel_Acquitted,CPB_-_Police_Personnel_Convicted,CPB_-_Police_Personnel_sent_up_for_Trial,CPB_-_Police_Personnel_Trial_Completed,CPB-_Police_Personnel_Cases_Withdrawn_or_Otherwise_disposed_of,CPC_-_Police_personnel_Cases_Trial_Completed,CPC_-_Police_Personnel_Cases_Withdrawn_or_Otherwise_disposed_of,CPC_-_Police_Personnel_Disciplinary_Action_Initiated,CPC_-_Police_Personnel_Dismissal/Removal_from_Service,CPC_-_Police_Personnel_Major_Punishment_awarded,CPC_-_Police_Personnel_Minor_Punishment_awarded
0,Andaman & Nicobar Islands,2001,Complaints Against Police Personnel,10,4,0,10,4,0,5,0,1,0,5,1,0,6,25,73,2,11,20
1,Andhra Pradesh,2001,Complaints Against Police Personnel,3078,72,109,3229,160,2969,3039,23,12,3,92,15,16,23,476,1506,47,248,1085
2,Arunachal Pradesh,2001,Complaints Against Police Personnel,24,39,5,54,44,0,17,0,0,0,17,0,1,8,43,107,4,17,15
3,Assam,2001,Complaints Against Police Personnel,17,3,1,52,52,3,9,1,1,0,7,1,1,0,7,144,5,61,102
4,Bihar,2001,Complaints Against Police Personnel,1,1,12,125,3,15,18,81,0,0,81,0,6,537,141,1385,33,470,1557

==========================================================================================
[53/76] 27_Nature_of_complaints_received_by_police.csv
==========================================================================================
Shape: (349, 10)

Columns:
  - Area_Name
  - Year
  - PC1_Oral_Complaints
  - PC2_Written_Complaints
  - PC3_Distress_call_over_phoneNo_100_etc
  - PC4_Complaints_initiated_sue_motto_by_Police
  - PC5_Total_Complaints_Sum_of_1_4_Above
  - PC6_Total_Complaints_as_recorded_in_GD
  - PC7_IPC_Cases_Registered
  - PC8_SLL_Cases_Registered

Sample rows:

,Area_Name,Year,PC1_Oral_Complaints,PC2_Written_Complaints,PC3_Distress_call_over_phoneNo_100_etc,PC4_Complaints_initiated_sue_motto_by_Police,PC5_Total_Complaints_Sum_of_1_4_Above,PC6_Total_Complaints_as_recorded_in_GD,PC7_IPC_Cases_Registered,PC8_SLL_Cases_Registered
0,Maharashtra,2010,239448.0,561217,13049.0,549410.0,1363124,1106219.0,208168,127940
1,Maharashtra,2009,242585.0,525157,7697.0,436688.0,1212127,979735.0,199598,135418
2,Maharashtra,2008,233929.0,499832,7307.0,404182.0,1145250,1019301.0,206243,120138
3,Maharashtra,2005,221580.0,474289,5013.0,209806.0,910688,811193.0,187027,142293
4,Maharashtra,2007,209595.0,470614,6479.0,203440.0,890128,696871.0,195707,120310

==========================================================================================
[54/76] 28_Trial_of_violent_crimes_by_courts.csv
==========================================================================================
Shape: (4473, 7)

Columns:
  - Area_Name
  - Year
  - Group_Name
  - Sub_Group_Name
  - Trial_of_Violent_Crimes_by_Courts_By_Confession
  - Trial_of_Violent_Crimes_by_Courts_By_trial
  - Trial_of_Violent_Crimes_by_Courts_Total

Sample rows:

           Area_Name  Year  Group_Name Sub_Group_Name  Trial_of_Violent_Crimes_by_Courts_By_Confession  Trial_of_Violent_Crimes_by_Courts_By_trial  Trial_of_Violent_Crimes_by_Courts_Total
0     Andhra Pradesh  2001  TVC- Arson      10. Arson                                             20.0                                       517.0                                    537.0
1  Arunachal Pradesh  2001  TVC- Arson      10. Arson                                              0.0                                         3.0                                      3.0
2              Assam  2001  TVC- Arson      10. Arson                                              5.0                                       142.0                                    147.0
3              Bihar  2001  TVC- Arson      10. Arson                                              0.0                                       208.0                                    208.0
4         Chandigarh  2001  TVC- Arson      10. Arson                                              0.0                                         3.0                                      3.0

==========================================================================================
[55/76] 29_Period_of_trials_by_courts.csv
==========================================================================================
Shape: (1786, 11)

Columns:
  - Area_Name
  - Year
  - Group_Name
  - Sub_Group_Name
  - PT_1_3_Years
  - PT_3_5_Years
  - PT_5_10_Years
  - PT_6_12_Months
  - PT_Less_than_6_Months
  - PT_Over_10_Years
  - PT_Total

Sample rows:

           Area_Name  Year                   Group_Name             Sub_Group_Name  PT_1_3_Years  PT_3_5_Years  PT_5_10_Years  PT_6_12_Months  PT_Less_than_6_Months  PT_Over_10_Years  PT_Total
0     Andhra Pradesh  2004  PT1. District/Session Judge  1. District/Session Judge        1931.0         805.0          196.0           293.0                   44.0              57.0    3326.0
1  Arunachal Pradesh  2004  PT1. District/Session Judge  1. District/Session Judge          13.0           6.0            0.0             5.0                    0.0               0.0      24.0
2              Assam  2004  PT1. District/Session Judge  1. District/Session Judge         582.0         444.0          170.0           127.0                   69.0              22.0    1414.0
3              Bihar  2004  PT1. District/Session Judge  1. District/Session Judge         297.0         590.0          594.0            11.0                    0.0             233.0    1725.0
4       Chhattisgarh  2004  PT1. District/Session Judge  1. District/Session Judge         239.0         171.0           72.0           222.0                  271.0              17.0     992.0

==========================================================================================
[56/76] 30_Auto_theft.csv
==========================================================================================
Shape: (1865, 7)

Columns:
  - Area_Name
  - Year
  - Group_Name
  - Sub_Group_Name
  - Auto_Theft_Coordinated/Traced
  - Auto_Theft_Recovered
  - Auto_Theft_Stolen

Sample rows:

                   Area_Name  Year                  Group_Name             Sub_Group_Name  Auto_Theft_Coordinated/Traced  Auto_Theft_Recovered  Auto_Theft_Stolen
0  Andaman & Nicobar Islands  2001  AT1-Motor Cycles/ Scooters  1. Motor Cycles/ Scooters                            NaN                   4.0                  4
1             Andhra Pradesh  2001  AT1-Motor Cycles/ Scooters  1. Motor Cycles/ Scooters                          136.0                1311.0               2725
2          Arunachal Pradesh  2001  AT1-Motor Cycles/ Scooters  1. Motor Cycles/ Scooters                            0.0                  21.0                 27
3                      Assam  2001  AT1-Motor Cycles/ Scooters  1. Motor Cycles/ Scooters                            0.0                  94.0                205
4                      Bihar  2001  AT1-Motor Cycles/ Scooters  1. Motor Cycles/ Scooters                           44.0                 205.0                946

==========================================================================================
[57/76] 31_Serious_fraud.csv
==========================================================================================
Shape: (448, 9)

Columns:
  - Area_Name
  - Year
  - Group_Name
  - Sub_Group_Name
  - Loss_of_Property_1_10_Crores
  - Loss_of_Property_10_25_Crores
  - Loss_of_Property_25_50_Crores
  - Loss_of_Property_50_100_Crores
  - Loss_of_Property_Above_100_Crores

Sample rows:

,Area_Name,Year,Group_Name,Sub_Group_Name,Loss_of_Property_1_10_Crores,Loss_of_Property_10_25_Crores,Loss_of_Property_25_50_Crores,Loss_of_Property_50_100_Crores,Loss_of_Property_Above_100_Crores
0,Andhra Pradesh,2001,Serious Fraud - Cheating,2. Cheating,4.0,0.0,0.0,0.0,0.0
1,Arunachal Pradesh,2001,Serious Fraud - Cheating,2. Cheating,0.0,0.0,0.0,0.0,0.0
2,Assam,2001,Serious Fraud - Cheating,2. Cheating,0.0,0.0,0.0,0.0,0.0
3,Bihar,2001,Serious Fraud - Cheating,2. Cheating,0.0,0.0,0.0,0.0,0.0
4,Chandigarh,2001,Serious Fraud - Cheating,2. Cheating,0.0,0.0,0.0,0.0,0.0

==========================================================================================
[58/76] 32_Murder_victim_age_sex.csv
==========================================================================================
Shape: (1018, 11)

Columns:
  - Area_Name
  - Year
  - Group_Name
  - Sub_Group_Name
  - Victims_Above_50_Yrs
  - Victims_Total
  - Victims_Upto_10_15_Yrs
  - Victims_Upto_10_Yrs
  - Victims_Upto_15_18_Yrs
  - Victims_Upto_18_30_Yrs
  - Victims_Upto_30_50_Yrs

Sample rows:

,Area_Name,Year,Group_Name,Sub_Group_Name,Victims_Above_50_Yrs,Victims_Total,Victims_Upto_10_15_Yrs,Victims_Upto_10_Yrs,Victims_Upto_15_18_Yrs,Victims_Upto_18_30_Yrs,Victims_Upto_30_50_Yrs
0,Andaman & Nicobar Islands,2001,Murder - Female Victims,2. Female Victims,NaN,6,NaN,NaN,NaN,4.0,2.0
1,Andhra Pradesh,2001,Murder - Female Victims,2. Female Victims,67.0,607,15.0,38.0,43.0,269.0,175.0
2,Arunachal Pradesh,2001,Murder - Female Victims,2. Female Victims,2.0,16,0.0,0.0,0.0,10.0,4.0
3,Assam,2001,Murder - Female Victims,2. Female Victims,11.0,128,8.0,4.0,23.0,45.0,37.0
4,Bihar,2001,Murder - Female Victims,2. Female Victims,12.0,366,0.0,0.0,40.0,191.0,123.0

==========================================================================================
[59/76] 33_CH_not_murder_victim_age_sex.csv
==========================================================================================
Shape: (936, 10)

Columns:
  - Area_Name
  - Year
  - Sub_Group_Name
  - Victims_Above_50_Yrs
  - Victims_Total
  - Victims_Upto_10_15_Yrs
  - Victims_Upto_10_Yrs
  - Victims_Upto_15_18_Yrs
  - Victims_Upto_18_30_Yrs
  - Victims_Upto_30_50_Yrs

Sample rows:

           Area_Name  Year   Sub_Group_Name  Victims_Above_50_Yrs  Victims_Total  Victims_Upto_10_15_Yrs  Victims_Upto_10_Yrs  Victims_Upto_15_18_Yrs  Victims_Upto_18_30_Yrs  Victims_Upto_30_50_Yrs
0     Andhra Pradesh  2001  1. Male Victims                  17.0          144.0                     3.0                  1.0                     5.0                    54.0                    64.0
1  Arunachal Pradesh  2001  1. Male Victims                   1.0            6.0                     0.0                  0.0                     0.0                     3.0                     2.0
2              Assam  2001  1. Male Victims                   2.0           38.0                     0.0                  0.0                     0.0                    20.0                    16.0
3              Bihar  2001  1. Male Victims                  20.0          232.0                     3.0                  0.0                    19.0                   116.0                    74.0
4         Chandigarh  2001  1. Male Victims                   0.0            6.0                     NaN                  0.0                     NaN                     6.0                     0.0

==========================================================================================
[60/76] 34_Use_of_fire_arms_in_murder_cases.csv
==========================================================================================
Shape: (284, 5)

Columns:
  - Area_Name
  - Year
  - Victims_of_Murder_by_Fire_arms
  - Victims_of_Murder_by_Licensed_arms
  - Victims_of_Murder_by_Un_licensedImprovisedCrudeCountry_made_Arms_Etc

Sample rows:

       Area_Name  Year  Victims_of_Murder_by_Fire_arms  Victims_of_Murder_by_Licensed_arms  Victims_of_Murder_by_Un_licensedImprovisedCrudeCountry_made_Arms_Etc
0  Uttar Pradesh  2004                            4969                               437.0                                                                4532.0
1  Uttar Pradesh  2002                            4098                               403.0                                                                3695.0
2  Uttar Pradesh  2006                            2565                               330.0                                                                2235.0
3  Uttar Pradesh  2003                            3855                               317.0                                                                3538.0
4  Uttar Pradesh  2008                            1470                               261.0                                                                1209.0

==========================================================================================
[61/76] 35_Human_rights_violation_by_police.csv
==========================================================================================
Shape: (2267, 7)

Columns:
  - Area_Name
  - Year
  - Group_Name
  - Sub_Group_Name
  - Cases_Registered_under_Human_Rights_Violations
  - Policemen_Chargesheeted
  - Policemen_Convicted

Sample rows:

           Area_Name  Year                   Group_Name                Sub_Group_Name  Cases_Registered_under_Human_Rights_Violations  Policemen_Chargesheeted  Policemen_Convicted
0     Andhra Pradesh  2001  HR_Disappearance of Persons  01. Disappearance of Persons                                             0.0                      0.0                  0.0
1  Arunachal Pradesh  2001  HR_Disappearance of Persons  01. Disappearance of Persons                                             0.0                      0.0                  0.0
2              Assam  2001  HR_Disappearance of Persons  01. Disappearance of Persons                                             0.0                      0.0                  0.0
3              Bihar  2001  HR_Disappearance of Persons  01. Disappearance of Persons                                             0.0                      0.0                  0.0
4         Chandigarh  2001  HR_Disappearance of Persons  01. Disappearance of Persons                                             0.0                      0.0                  0.0

==========================================================================================
[62/76] 36_Police_housing.csv
==========================================================================================
Shape: (696, 7)

Columns:
  - Area_Name
  - Year
  - Group_Name
  - Sub_Group_Name
  - PH_Houses_Provided_by_Department
  - PH_Houses_provided_on_LeaseRentGPRA
  - PH_Sanctioned_Strength

Sample rows:

                   Area_Name  Year                  Group_Name                   Sub_Group_Name  PH_Houses_Provided_by_Department  PH_Houses_provided_on_LeaseRentGPRA  PH_Sanctioned_Strength
0  Andaman & Nicobar Islands  2001  PH_Officers (DySP & Above)  1. For Officers (Dy.SP & Above)                               7.0                                  NaN                      17
1             Andhra Pradesh  2001  PH_Officers (DySP & Above)  1. For Officers (Dy.SP & Above)                             102.0                                189.0                     569
2          Arunachal Pradesh  2001  PH_Officers (DySP & Above)  1. For Officers (Dy.SP & Above)                              81.0                                 11.0                      92
3                      Assam  2001  PH_Officers (DySP & Above)  1. For Officers (Dy.SP & Above)                               0.0                                  0.0                     531
4                      Bihar  2001  PH_Officers (DySP & Above)  1. For Officers (Dy.SP & Above)                             130.0                                 89.0                     222

==========================================================================================
[63/76] 37_Home_guards_and_auxilliary_force.csv
==========================================================================================
Shape: (333, 8)

Columns:
  - Area_Name
  - Year
  - HG_Lower_Subordinates_Actual_Strength
  - HG_Lower_Subordinates_Sanctioned_Strength
  - HG_Officers_Actual_Strength
  - HG_Officers_Sanctioned_Strength
  - HG_Upper_Subordinates_Actual_Strength
  - HG_Upper_Subordinates_Sanctioned_Strength

Sample rows:

,Area_Name,Year,HG_Lower_Subordinates_Actual_Strength,HG_Lower_Subordinates_Sanctioned_Strength,HG_Officers_Actual_Strength,HG_Officers_Sanctioned_Strength,HG_Upper_Subordinates_Actual_Strength,HG_Upper_Subordinates_Sanctioned_Strength
0,Gujarat,2001,39236.0,45595.0,104.0,155.0,1366.0,1568.0
1,Gujarat,2002,40098.0,43630.0,105.0,150.0,1350.0,1500.0
2,Gujarat,2003,39834.0,43630.0,102.0,150.0,1283.0,1500.0
3,Gujarat,2004,36740.0,43630.0,82.0,150.0,1199.0,1500.0
4,Gujarat,2005,39123.0,43630.0,75.0,150.0,1159.0,1500.0

==========================================================================================
[64/76] 38_Unidentified_dead_bodies_recovered_and_inquest_conducted.csv
==========================================================================================
Shape: (314, 3)

Columns:
  - Area_Name
  - Year
  - Unidentified_Dead_bodies_Recovered_Inquest_Conducted

Sample rows:

           Area_Name  Year  Unidentified_Dead_bodies_Recovered_Inquest_Conducted
0     Andhra Pradesh  2001                                                  5290
1  Arunachal Pradesh  2001                                                     0
2              Assam  2001                                                    14
3              Bihar  2001                                                  1438
4         Chandigarh  2001                                                    18

==========================================================================================
[65/76] 39_Specific_purpose_of_kidnapping_and_abduction.csv
==========================================================================================
Shape: (3569, 20)

Columns:
  - Area_Name
  - Year
  - Group_Name
  - Sub_Group_Name
  - K_A_Cases_Reported
  - K_A_Female_10_15_Years
  - K_A_Female_15_18_Years
  - K_A_Female_18_30_Years
  - K_A_Female_30_50_Years
  - K_A_Female_Above_50_Years
  - K_A_Female_Total
  - K_A_Female_Upto_10_Years
  - K_A_Grand_Total
  - K_A_Male_10_15_Years
  - K_A_Male_15_18_Years
  - K_A_Male_18_30_Years
  - K_A_Male_30_50_Years
  - K_A_Male_Above_50_Years
  - K_A_Male_Total
  - K_A_Male_Upto_10_Years

Sample rows:

,Area_Name,Year,Group_Name,Sub_Group_Name,K_A_Cases_Reported,K_A_Female_10_15_Years,K_A_Female_15_18_Years,K_A_Female_18_30_Years,K_A_Female_30_50_Years,K_A_Female_Above_50_Years,K_A_Female_Total,K_A_Female_Upto_10_Years,K_A_Grand_Total,K_A_Male_10_15_Years,K_A_Male_15_18_Years,K_A_Male_18_30_Years,K_A_Male_30_50_Years,K_A_Male_Above_50_Years,K_A_Male_Total,K_A_Male_Upto_10_Years
0,Andhra Pradesh,2001,Kidnap - For Adoption,01. For Adoption,8.0,0.0,0.0,4.0,0.0,0.0,5.0,1.0,8.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0
1,Arunachal Pradesh,2001,Kidnap - For Adoption,01. For Adoption,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Assam,2001,Kidnap - For Adoption,01. For Adoption,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Bihar,2001,Kidnap - For Adoption,01. For Adoption,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.0,0.0,0.0,15.0,3.0,0.0,18.0,0.0
4,Chandigarh,2001,Kidnap - For Adoption,01. For Adoption,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

==========================================================================================
[66/76] 40_01_Custodial_death_person_remanded.csv
==========================================================================================
Shape: (211, 11)

Columns:
  - Area_Name
  - Year
  - Group_Name
  - Sub_Group_Name
  - CD_Deaths_Reported
  - CD_No_of_Autopsy_conducted
  - CD_No_of_Cases_registered_in_connection_with_deaths
  - CD_No_of_Judicial_enquiry_orderedconducted
  - CD_No_of_Magisterial_enquiry_orderedconducted
  - CD_No_of_Policemen_Charge_sheeted
  - CD_No_of_Policemen_Convicted

Sample rows:

,Area_Name,Year,Group_Name,Sub_Group_Name,CD_Deaths_Reported,CD_No_of_Autopsy_conducted,CD_No_of_Cases_registered_in_connection_with_deaths,CD_No_of_Judicial_enquiry_orderedconducted,CD_No_of_Magisterial_enquiry_orderedconducted,CD_No_of_Policemen_Charge_sheeted,CD_No_of_Policemen_Convicted
0,Andhra Pradesh,2001,Persons Remand to Police Custody by Court,1. Deaths in Custody/Lockup of Persons Remanded to Police Custody by Court,5.0,5.0,2.0,2.0,2.0,0.0,0.0
1,Arunachal Pradesh,2001,Persons Remand to Police Custody by Court,1. Deaths in Custody/Lockup of Persons Remanded to Police Custody by Court,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Assam,2001,Persons Remand to Police Custody by Court,1. Deaths in Custody/Lockup of Persons Remanded to Police Custody by Court,1.0,1.0,0.0,0.0,1.0,0.0,0.0
3,Bihar,2001,Persons Remand to Police Custody by Court,1. Deaths in Custody/Lockup of Persons Remanded to Police Custody by Court,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Chandigarh,2001,Persons Remand to Police Custody by Court,1. Deaths in Custody/Lockup of Persons Remanded to Police Custody by Court,0.0,0.0,0.0,0.0,0.0,0.0,0.0

==========================================================================================
[67/76] 40_02_Custodial_death_person_not_remanded.csv
==========================================================================================
Shape: (228, 11)

Columns:
  - Area_Name
  - Year
  - Group_Name
  - Sub_Group_Name
  - CD_Deaths_Reported
  - CD_No_of_Autopsy_conducted
  - CD_No_of_Cases_registered_in_connection_with_deaths
  - CD_No_of_Judicial_enquiry_orderedconducted
  - CD_No_of_Magisterial_enquiry_orderedconducted
  - CD_No_of_Policemen_Charge_sheeted
  - CD_No_of_Policemen_Convicted

Sample rows:

,Area_Name,Year,Group_Name,Sub_Group_Name,CD_Deaths_Reported,CD_No_of_Autopsy_conducted,CD_No_of_Cases_registered_in_connection_with_deaths,CD_No_of_Judicial_enquiry_orderedconducted,CD_No_of_Magisterial_enquiry_orderedconducted,CD_No_of_Policemen_Charge_sheeted,CD_No_of_Policemen_Convicted
0,Andhra Pradesh,2001,Persons Not Remand to Police Custody by Court,2. Deaths in Custody/Lockup of Persons Not Remanded to Police Custody by Court,8,8.0,2.0,1.0,5.0,1.0,0.0
1,Arunachal Pradesh,2001,Persons Not Remand to Police Custody by Court,2. Deaths in Custody/Lockup of Persons Not Remanded to Police Custody by Court,0,0.0,0.0,0.0,0.0,0.0,0.0
2,Assam,2001,Persons Not Remand to Police Custody by Court,2. Deaths in Custody/Lockup of Persons Not Remanded to Police Custody by Court,2,2.0,0.0,0.0,2.0,0.0,0.0
3,Bihar,2001,Persons Not Remand to Police Custody by Court,2. Deaths in Custody/Lockup of Persons Not Remanded to Police Custody by Court,0,0.0,0.0,0.0,0.0,0.0,0.0
4,Chandigarh,2001,Persons Not Remand to Police Custody by Court,2. Deaths in Custody/Lockup of Persons Not Remanded to Police Custody by Court,0,0.0,0.0,NaN,0.0,0.0,0.0

==========================================================================================
[68/76] 40_03_Custodial_death_during_production.csv
==========================================================================================
Shape: (204, 11)

Columns:
  - Area_Name
  - Year
  - Group_Name
  - Sub_Group_Name
  - CD_Deaths_Reported
  - CD_No_of_Autopsy_conducted
  - CD_No_of_Cases_registered_in_connection_with_deaths
  - CD_No_of_Judicial_enquiry_orderedconducted
  - CD_No_of_Magisterial_enquiry_orderedconducted
  - CD_No_of_Policemen_Charge_sheeted
  - CD_No_of_Policemen_Convicted

Sample rows:

,Area_Name,Year,Group_Name,Sub_Group_Name,CD_Deaths_Reported,CD_No_of_Autopsy_conducted,CD_No_of_Cases_registered_in_connection_with_deaths,CD_No_of_Judicial_enquiry_orderedconducted,CD_No_of_Magisterial_enquiry_orderedconducted,CD_No_of_Policemen_Charge_sheeted,CD_No_of_Policemen_Convicted
0,Andhra Pradesh,2001,During Production/Process in Courts/Journey Connected with Investigation,3. Deaths in Custody during production/process in courts/journey connected with investigation,3,3.0,3.0,1.0,1.0,0.0,0.0
1,Arunachal Pradesh,2001,During Production/Process in Courts/Journey Connected with Investigation,3. Deaths in Custody during production/process in courts/journey connected with investigation,0,0.0,0.0,0.0,0.0,0.0,0.0
2,Assam,2001,During Production/Process in Courts/Journey Connected with Investigation,3. Deaths in Custody during production/process in courts/journey connected with investigation,0,0.0,0.0,0.0,0.0,0.0,0.0
3,Bihar,2001,During Production/Process in Courts/Journey Connected with Investigation,3. Deaths in Custody during production/process in courts/journey connected with investigation,0,0.0,0.0,0.0,0.0,0.0,0.0
4,Chandigarh,2001,During Production/Process in Courts/Journey Connected with Investigation,3. Deaths in Custody during production/process in courts/journey connected with investigation,0,0.0,0.0,0.0,0.0,0.0,0.0

==========================================================================================
[69/76] 40_04_Custodial_death_during_hospitalization_or_treatment.csv
==========================================================================================
Shape: (213, 5)

Columns:
  - Area_Name
  - Year
  - Group_Name
  - Sub_Group_Name
  - CD_Hospitalisation_Treatment

Sample rows:

           Area_Name  Year                                      Group_Name                              Sub_Group_Name  CD_Hospitalisation_Treatment
0     Andhra Pradesh  2001  During Hospitalisation/Treatment/Other Reasons  4. Deaths during Hospitalisation/Treatment                            15
1  Arunachal Pradesh  2001  During Hospitalisation/Treatment/Other Reasons  4. Deaths during Hospitalisation/Treatment                             1
2              Bihar  2001  During Hospitalisation/Treatment/Other Reasons  4. Deaths during Hospitalisation/Treatment                             0
3         Chandigarh  2001  During Hospitalisation/Treatment/Other Reasons  4. Deaths during Hospitalisation/Treatment                             0
4       Chhattisgarh  2001  During Hospitalisation/Treatment/Other Reasons  4. Deaths during Hospitalisation/Treatment                             0

==========================================================================================
[70/76] 40_05_Custodial_death_others.csv
==========================================================================================
Shape: (233, 10)

Columns:
  - Area_Name
  - Year
  - Group_Name
  - Sub_Group_Name
  - CD_Accidents
  - CD_By_Mob_AttackRiots
  - CD_By_other_Criminals
  - CD_By_Suicide
  - CD_IllnessNatural_Death
  - CD_While_Escaping_from_Custody

Sample rows:

,Area_Name,Year,Group_Name,Sub_Group_Name,CD_Accidents,CD_By_Mob_AttackRiots,CD_By_other_Criminals,CD_By_Suicide,CD_IllnessNatural_Death,CD_While_Escaping_from_Custody
0,Andhra Pradesh,2001,During Hospitalisation/Treatment/Other Reasons,5. Deaths due to Other Reasons,0.0,0.0,0.0,2.0,1.0,2.0
1,Arunachal Pradesh,2001,During Hospitalisation/Treatment/Other Reasons,5. Deaths due to Other Reasons,0.0,0.0,0.0,0.0,0.0,0.0
2,Bihar,2001,During Hospitalisation/Treatment/Other Reasons,5. Deaths due to Other Reasons,0.0,0.0,0.0,0.0,0.0,0.0
3,Chandigarh,2001,During Hospitalisation/Treatment/Other Reasons,5. Deaths due to Other Reasons,0.0,0.0,1.0,0.0,0.0,0.0
4,Chhattisgarh,2001,During Hospitalisation/Treatment/Other Reasons,5. Deaths due to Other Reasons,0.0,0.0,0.0,1.0,0.0,0.0

==========================================================================================
[71/76] 41_Escapes_from_police_custody.csv
==========================================================================================
Shape: (311, 21)

Columns:
  - Area_Name
  - Year
  - EPC_Cases_Cases_Acquitted
  - EPC_Cases_Cases_Convicted
  - EPC_Cases_Cases_Pending_for_Trial
  - EPC_Cases_Registered
  - EPC_Cases_Trial_Completed
  - EPC_Escapees_Re_Arrested_from_Lockup
  - EPC_Escapees_Re_Arrested_from_Others
  - EPC_FR_Submitted
  - EPC_Persons_Awarded_more_than_3_Years_Imprisonment
  - EPC_Persons_Awarded_upto_3_Years_Imprisonment
  - EPC_Persons_Cases_Acquitted
  - EPC_Persons_Cases_Convicted
  - EPC_Persons_Cases_Pending_for_Trial
  - EPC_Persons_Chargesheeted_for_Escape
  - EPC_Persons_Escaped
  - EPC_Persons_Escaped_from_Lockup
  - EPC_Persons_Escaped_Outside_the_Lockup
  - EPC_Persons_Escaped_Total
  - EPC_Persons_Trial_Completed

Sample rows:

,Area_Name,Year,EPC_Cases_Cases_Acquitted,EPC_Cases_Cases_Convicted,EPC_Cases_Cases_Pending_for_Trial,EPC_Cases_Registered,EPC_Cases_Trial_Completed,EPC_Escapees_Re_Arrested_from_Lockup,EPC_Escapees_Re_Arrested_from_Others,EPC_FR_Submitted,EPC_Persons_Awarded_more_than_3_Years_Imprisonment,EPC_Persons_Awarded_upto_3_Years_Imprisonment,EPC_Persons_Cases_Acquitted,EPC_Persons_Cases_Convicted,EPC_Persons_Cases_Pending_for_Trial,EPC_Persons_Chargesheeted_for_Escape,EPC_Persons_Escaped,EPC_Persons_Escaped_from_Lockup,EPC_Persons_Escaped_Outside_the_Lockup,EPC_Persons_Escaped_Total,EPC_Persons_Trial_Completed
0,Jharkhand,2005,235.0,66.0,1853.0,17.0,301.0,1747.0,7.0,188.0,3.0,2.0,671.0,236.0,3238.0,1252.0,12.0,5.0,7.0,12.0,907.0
1,Assam,2006,30.0,24.0,19.0,81.0,54.0,21.0,3.0,19.0,0.0,8.0,27.0,14.0,19.0,15.0,99.0,11.0,88.0,99.0,41.0
2,Andhra Pradesh,2009,68.0,22.0,38.0,96.0,90.0,13.0,51.0,18.0,5.0,2.0,146.0,32.0,30.0,45.0,96.0,8.0,88.0,96.0,178.0
3,Haryana,2006,7.0,20.0,76.0,33.0,27.0,7.0,26.0,9.0,0.0,8.0,15.0,26.0,172.0,21.0,36.0,8.0,28.0,36.0,41.0
4,Assam,2005,30.0,19.0,15.0,70.0,49.0,17.0,1.0,16.0,0.0,6.0,22.0,12.0,16.0,12.0,88.0,10.0,78.0,88.0,34.0

==========================================================================================
[72/76] 42_Cases_under_crime_against_women.csv
==========================================================================================
Shape: (2765, 22)

Columns:
  - Area_Name
  - Year
  - Group_Name
  - Sub_Group_Name
  - Cases_Acquitted_or_Discharged
  - Cases_charge_sheets_were_not_laid_but_Final_Report_submitted
  - Cases_Chargesheeted
  - Cases_Compounded_or_Withdrawn
  - Cases_Convicted
  - Cases_Declared_False_on_Account_of_Mistake_of_Fact_or_of_Law
  - Cases_Investigated_Chargesheets+FR_Submitted
  - Cases_not_Investigated_or_in_which_investigation_was_refused
  - Cases_Pending_Investigation_at_Year_End
  - Cases_Pending_Investigation_from_previous_year
  - Cases_Pending_Trial_at_Year_End
  - Cases_Pending_Trial_from_the_previous_year
  - Cases_Reported
  - Cases_Sent_for_Trial
  - Cases_Trials_Completed
  - Cases_Withdrawn_by_the_Govt
  - Cases_withdrawn_by_the_Govt_during_investigation
  - Total_Cases_for_Trial

Sample rows:

,Area_Name,Year,Group_Name,Sub_Group_Name,Cases_Acquitted_or_Discharged,Cases_charge_sheets_were_not_laid_but_Final_Report_submitted,Cases_Chargesheeted,Cases_Compounded_or_Withdrawn,Cases_Convicted,Cases_Declared_False_on_Account_of_Mistake_of_Fact_or_of_Law,Cases_Investigated_Chargesheets+FR_Submitted,Cases_not_Investigated_or_in_which_investigation_was_refused,Cases_Pending_Investigation_at_Year_End,Cases_Pending_Investigation_from_previous_year,Cases_Pending_Trial_at_Year_End,Cases_Pending_Trial_from_the_previous_year,Cases_Reported,Cases_Sent_for_Trial,Cases_Trials_Completed,Cases_Withdrawn_by_the_Govt,Cases_withdrawn_by_the_Govt_during_investigation,Total_Cases_for_Trial
0,Andaman & Nicobar Islands,2001,Rape,01. Rape,5,2,3,0,0,0,5,0,1,3,34,36,3,3,5,0,0,39
1,Andhra Pradesh,2001,Rape,01. Rape,731,22,769,35,197,74,791,3,393,390,1974,2170,871,769,928,2,0,2937
2,Arunachal Pradesh,2001,Rape,01. Rape,1,2,25,0,2,0,27,0,18,12,282,260,33,25,3,0,0,285
3,Assam,2001,Rape,01. Rape,334,95,495,10,101,45,590,0,1045,863,1964,1914,817,495,435,0,0,2409
4,Bihar,2001,Rape,01. Rape,406,141,685,0,155,105,826,0,488,531,3185,3061,888,685,561,0,0,3746

==========================================================================================
[73/76] 42_District_wise_crimes_committed_against_women_2001_2012.csv
==========================================================================================
Shape: (9017, 10)

Columns:
  - STATE/UT
  - DISTRICT
  - Year
  - Rape
  - Kidnapping and Abduction
  - Dowry Deaths
  - Assault on women with intent to outrage her modesty
  - Insult to modesty of Women
  - Cruelty by Husband or his Relatives
  - Importation of Girls

Sample rows:

,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
0,ANDHRA PRADESH,ADILABAD,2001,50,30,16,149,34,175,0
1,ANDHRA PRADESH,ANANTAPUR,2001,23,30,7,118,24,154,0
2,ANDHRA PRADESH,CHITTOOR,2001,27,34,14,112,83,186,0
3,ANDHRA PRADESH,CUDDAPAH,2001,20,20,17,126,38,57,0
4,ANDHRA PRADESH,EAST GODAVARI,2001,23,26,12,109,58,247,0

==========================================================================================
[74/76] 42_District_wise_crimes_committed_against_women_2013.csv
==========================================================================================
Shape: (823, 10)

Columns:
  - STATE/UT
  - DISTRICT
  - Year
  - Rape
  - Kidnapping and Abduction
  - Dowry Deaths
  - Assault on women with intent to outrage her modesty
  - Insult to modesty of Women
  - Cruelty by Husband or his Relatives
  - Importation of Girls

Sample rows:

,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
0,Andhra Pradesh,ADILABAD,2013,61,47,12,197,138,464,0
1,Andhra Pradesh,ANANTAPUR,2013,28,84,23,337,43,161,0
2,Andhra Pradesh,CHITTOOR,2013,31,27,13,119,84,435,0
3,Andhra Pradesh,CUDDAPAH,2013,19,50,9,318,163,207,0
4,Andhra Pradesh,CYBERABAD,2013,138,129,43,350,338,1526,0

==========================================================================================
[75/76] 42_District_wise_crimes_committed_against_women_2014.csv
==========================================================================================
Shape: (837, 62)

Columns:
  - States/UTs
  - District
  - Year
  - Rape
  - Custodial Rape
  - Custodial_Gang Rape
  - Custodial_Other Rape
  - Rape other than Custodial
  - Rape_Gang Rape
  - Rape_Others
  - Attempt to commit Rape
  - Kidnapping & Abduction_Total
  - Kidnaping & Abduction
  - Kidnaping & Abduction in order to Murder
  - Kidnapping for Ransom
  - Kidnapping & Abduction of Women to compel her for marriage
  - Kidnaping & Abduction_Others
  - Dowry Deaths
  - Assault on Women with intent to outrage her Modesty_Total
  - Sexual Harassment
  - Assault on women with intent to Disrobe
  - Voyeurism
  - Stalking
  - Others
  - Insult to the Modesty of Women_Total
  - At Office premises
  - In places related to work
  - In Public Transport system
  - In other Places
  - Cruelty by Husband or his Relatives
  - Importation of Girls from Foreign Country
  - Murder
  - Attempt to commit Murder
  - Culpable Homicide not amounting to Murder
  - Attempt to commit Culpable Homicide
  - Grievous Hurt
  - Hurt
  - Acid attack
  - Attempt to Acid Attack
  - Deaths caused with intent to cause miscarriage
  - Causing miscarriage without consent of women
  - Dacoity_Total
  - Dacoity with Murder
  - Other Dacoity
  - Robbery
  - Arson
  - HumanTrafficking
  - Abetment of Suicides of Women
  - UnNatural Offences
  - Other IPC Crimes
  - Dowry Prohibition Act, 1961
  - Indecent Representation of Women (P) Act, 1986
  - Commission of Sati Prevention Act, 1987
  - Protection of Women from Domestic Violence Act, 2005
  - Immoral Traffic Prevention Act
  - ITP Under Section 5
  - ITP Under Section 6
  - ITP Under Section 7
  - ITP Under Section 8
  - ITP Under Other Sections
  - Other SLL Crimes against Women
  - Total Crimes against Women

Sample rows:

,States/UTs,District,Year,Rape,Custodial Rape,Custodial_Gang Rape,Custodial_Other Rape,Rape other than Custodial,Rape_Gang Rape,Rape_Others,Attempt to commit Rape,Kidnapping & Abduction_Total,Kidnaping & Abduction,Kidnaping & Abduction in order to Murder,Kidnapping for Ransom,Kidnapping & Abduction of Women to compel her for marriage,Kidnaping & Abduction_Others,Dowry Deaths,Assault on Women with intent to outrage her Modesty_Total,Sexual Harassment,Assault on women with intent to Disrobe,Voyeurism,Stalking,Others,Insult to the Modesty of Women_Total,At Office premises,In places related to work,In Public Transport system,In other Places,Cruelty by Husband or his Relatives,Importation of Girls from Foreign Country,Murder,Attempt to commit Murder,Culpable Homicide not amounting to Murder,Attempt to commit Culpable Homicide,Grievous Hurt,Hurt,Acid attack,Attempt to Acid Attack,Deaths caused with intent to cause miscarriage,Causing miscarriage without consent of women,Dacoity_Total,Dacoity with Murder,Other Dacoity,Robbery,Arson,HumanTrafficking,Abetment of Suicides of Women,UnNatural Offences,Other IPC Crimes,"Dowry Prohibition Act, 1961","Indecent Representation of Women (P) Act, 1986","Commission of Sati Prevention Act, 1987","Protection of Women from Domestic Violence Act, 2005",Immoral Traffic Prevention Act,ITP Under Section 5,ITP Under Section 6,ITP Under Section 7,ITP Under Section 8,ITP Under Other Sections,Other SLL Crimes against Women,Total Crimes against Women
0,Andhra Pradesh,Anantapur,2014,35,0,0,0,35,0,35,1,106,0,0,0,88,18,25,436,82,34,4,80,236,26,0,0,0,26,165,0,50,20,1,0,3,2,1,0,0,0,0,0,0,0,0,0,0,0,0,229,0,0,0,0,0,0,0,0,0,0,1097
1,Andhra Pradesh,Chittoor,2014,32,0,0,0,32,1,31,0,34,3,0,1,28,2,17,135,0,0,0,0,135,94,0,0,0,94,278,0,11,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,4,0,0,0,0,0,607
2,Andhra Pradesh,Cuddapah,2014,28,0,0,0,28,0,28,4,16,0,0,0,11,5,16,215,212,0,0,0,3,12,1,11,0,0,91,0,27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20,0,0,175,0,0,0,5,0,0,0,0,5,0,609
3,Andhra Pradesh,East Godavari,2014,85,0,0,0,85,0,85,18,25,0,0,0,0,25,7,519,159,61,11,55,233,62,0,0,0,62,464,0,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,27,0,0,22,0,0,0,16,0,0,0,0,16,0,1277
4,Andhra Pradesh,Guntakal Railway,2014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4

==========================================================================================
[76/76] 43_Arrests_under_crime_against_women.csv
==========================================================================================
Shape: (2765, 16)

Columns:
  - Area_Name
  - Year
  - Group_Name
  - Sub_Group_Name
  - Persons_Acquitted
  - Persons_against_whom_cases_Compounded_or_Withdrawn
  - Persons_Arrested
  - Persons_Chargesheeted
  - Persons_Convicted
  - Persons_in_Custody_or_on_Bail_during_Investigation_at_Year_beginning
  - Persons_in_Custody_or_on_Bail_during_Investigation_at_Year_end
  - Persons_in_Custody_or_on_Bail_during_Trial_at_Year_End
  - Persons_Released_or_Freed_by_Police_or_Magistrate_before_Trial_for_want_of_evidence_or_any_other_reason
  - Persons_Trial_Completed
  - Persons_under_Trial_at_Year_beginning
  - Total_Persons_under_Trial

Sample rows:

,Area_Name,Year,Group_Name,Sub_Group_Name,Persons_Acquitted,Persons_against_whom_cases_Compounded_or_Withdrawn,Persons_Arrested,Persons_Chargesheeted,Persons_Convicted,Persons_in_Custody_or_on_Bail_during_Investigation_at_Year_beginning,Persons_in_Custody_or_on_Bail_during_Investigation_at_Year_end,Persons_in_Custody_or_on_Bail_during_Trial_at_Year_End,Persons_Released_or_Freed_by_Police_or_Magistrate_before_Trial_for_want_of_evidence_or_any_other_reason,Persons_Trial_Completed,Persons_under_Trial_at_Year_beginning,Total_Persons_under_Trial
0,Andaman & Nicobar Islands,2001,Rape,01. Rape,6,0,3,3,0,6,6,45,0,6,48,51
1,Andhra Pradesh,2001,Rape,01. Rape,1168,13,1150,1021,246,450,545,2191,34,1414,2597,3618
2,Arunachal Pradesh,2001,Rape,01. Rape,1,0,51,31,2,25,30,347,15,3,319,350
3,Assam,2001,Rape,01. Rape,403,14,928,585,120,806,959,2331,190,523,2283,2868
4,Bihar,2001,Rape,01. Rape,756,0,1400,1302,217,719,576,5963,241,973,5634,6936

In [25]:
# ============================================================
# CELL 24 — COMPACT SAMPLE EVIDENCE TABLE
# ============================================================

sample_evidence_records = []

for file_path in csv_files:

    df, read_info = read_csv_for_inspection(
        file_path
    )

    if df is None:
        continue

    # Take up to 3 rows
    sample_df = df.head(3)

    sample_records = []

    for _, sample_row in sample_df.iterrows():

        row_dict = {}

        for column in df.columns:

            value = sample_row[column]

            if pd.isna(value):
                value = None

            else:
                value = str(value)

            row_dict[str(column)] = value

        sample_records.append(row_dict)

    sample_evidence_records.append({

        "filename": file_path.name,

        "columns": json.dumps(
            [str(c) for c in df.columns],
            ensure_ascii=False
        ),

        "sample_rows": json.dumps(
            sample_records,
            ensure_ascii=False
        )
    })


sample_evidence_df = pd.DataFrame(
    sample_evidence_records
)

print("=" * 70)
print("COMPACT SAMPLE EVIDENCE")
print("=" * 70)

print(
    f"Datasets with sample evidence: "
    f"{len(sample_evidence_df)}"
)

display(
    sample_evidence_df.head(10)
)

======================================================================
COMPACT SAMPLE EVIDENCE
======================================================================
Datasets with sample evidence: 76

,filename,columns,sample_rows
0,01_District_wise_crimes_committed_IPC_2001_2012.csv,"[""STATE/UT"", ""DISTRICT"", ""YEAR"", ""MURDER"", ""ATTEMPT TO MURDER"", ""CULPABLE HOMICIDE NOT AMOUNTING TO MURDER"", ""RAPE"",...","[{""STATE/UT"": ""ANDHRA PRADESH"", ""DISTRICT"": ""ADILABAD"", ""YEAR"": ""2001"", ""MURDER"": ""101"", ""ATTEMPT TO MURDER"": ""60"", ..."
1,01_District_wise_crimes_committed_IPC_2013.csv,"[""STATE/UT"", ""DISTRICT"", ""YEAR"", ""MURDER"", ""ATTEMPT TO MURDER"", ""CULPABLE HOMICIDE NOT AMOUNTING TO MURDER"", ""RAPE"",...","[{""STATE/UT"": ""Andhra Pradesh"", ""DISTRICT"": ""ADILABAD"", ""YEAR"": ""2013"", ""MURDER"": ""96"", ""ATTEMPT TO MURDER"": ""72"", ""..."
2,01_District_wise_crimes_committed_IPC_2014.csv,"[""States/UTs"", ""District"", ""Year"", ""Murder"", ""Attempt to commit Murder"", ""Culpable Homicide not amounting to Murder""...","[{""States/UTs"": ""Andhra Pradesh"", ""District"": ""Anantapur"", ""Year"": ""2014"", ""Murder"": ""134"", ""Attempt to commit Murde..."
3,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv,"[""STATE/UT"", ""DISTRICT"", ""Year"", ""Murder"", ""Rape"", ""Kidnapping and Abduction"", ""Dacoity"", ""Robbery"", ""Arson"", ""Hurt""...","[{""STATE/UT"": ""ANDHRA PRADESH"", ""DISTRICT"": ""ADILABAD"", ""Year"": ""2001"", ""Murder"": ""0"", ""Rape"": ""1"", ""Kidnapping and ..."
4,02_01_District_wise_crimes_committed_against_SC_2013.csv,"[""STATE/UT"", ""DISTRICT"", ""Year"", ""Murder"", ""Rape"", ""Kidnapping and Abduction"", ""Dacoity"", ""Robbery"", ""Arson"", ""Hurt""...","[{""STATE/UT"": ""Andhra Pradesh"", ""DISTRICT"": ""ADILABAD"", ""Year"": ""2013"", ""Murder"": ""2"", ""Rape"": ""3"", ""Kidnapping and ..."
5,02_01_District_wise_crimes_committed_against_SC_2014.csv,"[""States/UTs"", ""District"", ""Year"", ""Protection of Civil Rights Act, 1955"", ""POA_Murder"", ""POA_Attempt to commit Murd...","[{""States/UTs"": ""Andhra Pradesh"", ""District"": ""Anantapur"", ""Year"": ""2014"", ""Protection of Civil Rights Act, 1955"": ""..."
6,02_District_wise_crimes_committed_against_ST_2001_2012.csv,"[""STATE/UT"", ""DISTRICT"", ""Year"", ""Murder"", ""Rape"", ""Kidnapping Abduction"", ""Dacoity"", ""Robbery"", ""Arson"", ""Hurt"", ""P...","[{""STATE/UT"": ""ANDHRA PRADESH"", ""DISTRICT"": ""ADILABAD"", ""Year"": ""2001"", ""Murder"": ""0"", ""Rape"": ""1"", ""Kidnapping Abdu..."
7,02_District_wise_crimes_committed_against_ST_2013.csv,"[""STATE/UT"", ""DISTRICT"", ""Year"", ""Murder"", ""Rape"", ""Kidnapping Abduction"", ""Dacoity"", ""Robbery"", ""Arson"", ""Hurt"", ""P...","[{""STATE/UT"": ""Andhra Pradesh"", ""DISTRICT"": ""ADILABAD"", ""Year"": ""2013"", ""Murder"": ""0"", ""Rape"": ""7"", ""Kidnapping Abdu..."
8,02_District_wise_crimes_committed_against_ST_2014.csv,"[""States/UTs"", ""District"", ""Year"", ""Protection of Civil Rights Act, 1955"", ""POA_Murder"", ""POA_Attempt to commit Murd...","[{""States/UTs"": ""Andhra Pradesh"", ""District"": ""Anantapur"", ""Year"": ""2014"", ""Protection of Civil Rights Act, 1955"": ""..."
9,03_District_wise_crimes_committed_against_children_2001_2012.csv,"[""STATE/UT"", ""DISTRICT"", ""Year"", ""Murder"", ""Rape"", ""Kidnapping and Abduction"", ""Foeticide"", ""Abetment of suicide"", ""...","[{""STATE/UT"": ""ANDHRA PRADESH"", ""DISTRICT"": ""ADILABAD"", ""Year"": ""2001"", ""Murder"": ""0.0"", ""Rape"": ""0.0"", ""Kidnapping ..."

In [26]:
# ============================================================
# CELL 25 — INSPECT FILES WITH PARSING PROBLEMS
# ============================================================

parsing_problem_names = (
    inventory_df.loc[
        inventory_df["parsing_issue"] == True,
        "filename"
    ]
    .tolist()
)

print("=" * 70)
print("FILES WITH PARSING PROBLEMS")
print("=" * 70)

print(
    f"Number of affected files: "
    f"{len(parsing_problem_names)}"
)

for filename in parsing_problem_names:

    print("\n" + "-" * 70)
    print(filename)
    print("-" * 70)

    row = inventory_df[
        inventory_df["filename"] == filename
    ].iloc[0]

    print(
        f"Rows retained by inspection parser: "
        f"{row['row_count']}"
    )

    print(
        f"Reported malformed rows: "
        f"{row['bad_rows']}"
    )

    print(
        f"Encoding used: "
        f"{row['encoding']}"
    )

    print(
        f"Parser used: "
        f"{row['parser']}"
    )

    print(
        f"Status: "
        f"{row['read_status']}"
    )

======================================================================
FILES WITH PARSING PROBLEMS
======================================================================
Number of affected files: 3

----------------------------------------------------------------------
36_Police_housing.csv
----------------------------------------------------------------------
Rows retained by inspection parser: 696
Reported malformed rows: 348
Encoding used: utf-8
Parser used: python
Status: success_with_parsing_issues

----------------------------------------------------------------------
42_Cases_under_crime_against_women.csv
----------------------------------------------------------------------
Rows retained by inspection parser: 2765
Reported malformed rows: 1400
Encoding used: utf-8
Parser used: python
Status: success_with_parsing_issues

----------------------------------------------------------------------
43_Arrests_under_crime_against_women.csv
----------------------------------------------------------------------
Rows retained by inspection parser: 2765
Reported malformed rows: 1400
Encoding used: utf-8
Parser used: python
Status: success_with_parsing_issues

In [27]:
# ============================================================
# CELL 26 — RAW STRUCTURE CHECK FOR MALFORMED FILES
# ============================================================

import csv

for filename in parsing_problem_names:

    file_path = RAW_DATA_DIR / filename

    print("\n" + "=" * 90)
    print(f"RAW STRUCTURE CHECK: {filename}")
    print("=" * 90)

    # --------------------------------------------------------
    # Read first 15 physical lines exactly as text
    # --------------------------------------------------------

    print("\nFirst 15 physical lines:")
    print("-" * 90)

    with open(
        file_path,
        "r",
        encoding="latin1",
        errors="replace"
    ) as f:

        for line_number in range(15):

            line = f.readline()

            if not line:
                break

            print(
                f"{line_number + 1:03d}: "
                f"{line.rstrip()[:500]}"
            )

    # --------------------------------------------------------
    # Inspect comma-separated field counts
    # --------------------------------------------------------

    print("\nField-count inspection:")
    print("-" * 90)

    field_counts = {}

    with open(
        file_path,
        "r",
        encoding="latin1",
        errors="replace",
        newline=""
    ) as f:

        reader = csv.reader(f)

        for line_number, row in enumerate(
            reader,
            start=1
        ):

            count = len(row)

            field_counts[count] = (
                field_counts.get(count, 0) + 1
            )

            # Stop after enough physical rows for inspection
            if line_number >= 1000:
                break

    print(
        "Observed field-count frequencies "
        "in first 1000 physical rows:"
    )

    for count, frequency in sorted(
        field_counts.items()
    ):
        print(
            f"  {count} fields : "
            f"{frequency} rows"
        )

==========================================================================================
RAW STRUCTURE CHECK: 36_Police_housing.csv
==========================================================================================

First 15 physical lines:
------------------------------------------------------------------------------------------
001: ï»¿Area_Name,Year,Group_Name,Sub_Group_Name,PH_Houses_Provided_by_Department,PH_Houses_provided_on_LeaseRentGPRA,PH_Sanctioned_Strength
002: Andaman & Nicobar Islands,2001,PH_Officers (DySP & Above),1. For Officers (Dy.SP & Above),7,NULL,17
003: Andhra Pradesh,2001,PH_Officers (DySP & Above),1. For Officers (Dy.SP & Above),102,189,569
004: Arunachal Pradesh,2001,PH_Officers (DySP & Above),1. For Officers (Dy.SP & Above),81,11,92
005: Assam,2001,PH_Officers (DySP & Above),1. For Officers (Dy.SP & Above),0,0,531
006: Bihar,2001,PH_Officers (DySP & Above),1. For Officers (Dy.SP & Above),130,89,222
007: Chandigarh,2001,PH_Officers (DySP & Above),1. For Officers (Dy.SP & Above),10,0,17
008: Chhattisgarh,2001,PH_Officers (DySP & Above),1. For Officers (Dy.SP & Above),70,168,140
009: Dadra & Nagar Haveli,2001,PH_Officers (DySP & Above),1. For Officers (Dy.SP & Above),NULL,2,2
010: Delhi,2001,PH_Officers (DySP & Above),1. For Officers (Dy.SP & Above),168,NULL,371
011: Goa,2001,PH_Officers (DySP & Above),1. For Officers (Dy.SP & Above),8,8,34
012: Gujarat,2001,PH_Officers (DySP & Above),1. For Officers (Dy.SP & Above),111,23,374
013: Haryana,2001,PH_Officers (DySP & Above),1. For Officers (Dy.SP & Above),136,14,243
014: Himachal Pradesh,2001,PH_Officers (DySP & Above),1. For Officers (Dy.SP & Above),30,9,207
015: Jammu & Kashmir,2001,PH_Officers (DySP & Above),1. For Officers (Dy.SP & Above),73,0,569

Field-count inspection:
------------------------------------------------------------------------------------------
Observed field-count frequencies in first 1000 physical rows:
  7 fields : 697 rows
  9 fields : 303 rows

==========================================================================================
RAW STRUCTURE CHECK: 42_Cases_under_crime_against_women.csv
==========================================================================================

First 15 physical lines:
------------------------------------------------------------------------------------------
001: ï»¿Area_Name,Year,Group_Name,Sub_Group_Name,Cases_Acquitted_or_Discharged,Cases_charge_sheets_were_not_laid_but_Final_Report_submitted,Cases_Chargesheeted,Cases_Compounded_or_Withdrawn,Cases_Convicted,Cases_Declared_False_on_Account_of_Mistake_of_Fact_or_of_Law,Cases_Investigated_Chargesheets+FR_Submitted,Cases_not_Investigated_or_in_which_investigation_was_refused,Cases_Pending_Investigation_at_Year_End,Cases_Pending_Investigation_from_previous_year,Cases_Pending_Trial_at_Year_End,Cases_Pending
002: Andaman & Nicobar Islands,2001,Rape,01. Rape,5,2,3,0,0,0,5,0,1,3,34,36,3,3,5,0,0,39
003: Andhra Pradesh,2001,Rape,01. Rape,731,22,769,35,197,74,791,3,393,390,1974,2170,871,769,928,2,0,2937
004: Arunachal Pradesh,2001,Rape,01. Rape,1,2,25,0,2,0,27,0,18,12,282,260,33,25,3,0,0,285
005: Assam,2001,Rape,01. Rape,334,95,495,10,101,45,590,0,1045,863,1964,1914,817,495,435,0,0,2409
006: Bihar,2001,Rape,01. Rape,406,141,685,0,155,105,826,0,488,531,3185,3061,888,685,561,0,0,3746
007: Chandigarh,2001,Rape,01. Rape,9,0,16,0,2,2,16,0,1,1,34,29,18,16,11,0,0,45
008: Chhattisgarh,2001,Rape,01. Rape,520,15,976,1,158,11,991,1,86,130,3966,3669,959,976,678,0,0,4645
009: Dadra & Nagar Haveli,2001,Rape,01. Rape,0,0,8,0,1,0,8,0,1,3,21,14,6,8,1,0,0,22
010: Daman & Diu,2001,Rape,01. Rape,3,0,1,0,0,0,1,0,0,1,1,3,0,1,3,0,0,4
011: Delhi,2001,Rape,01. Rape,80,65,361,0,29,1,426,0,197,243,1651,1399,381,361,109,0,0,1760
012: Goa,2001,Rape,01. Rape,10,1,14,0,10,0,15,0,5,8,47,53,12,14,20,0,0,67
013: Gujarat,2001,Rape,01. Rape,150,10,288,7,26,10,298,1,24,47,1948,1843,286,288,176,0,0,2131
014: Haryana,2001,Rape,01. Rape,291,6,341,1,94,54,347,0,22,25,636,681,398,341,385,0,0,1022
015: Himachal Pradesh,2001,Rape,01. Rape,75,0,110,0,30,25,110,0,35,46,389,384,124,110,105,0,0,494

Field-count inspection:
------------------------------------------------------------------------------------------
Observed field-count frequencies in first 1000 physical rows:
  22 fields : 1000 rows

==========================================================================================
RAW STRUCTURE CHECK: 43_Arrests_under_crime_against_women.csv
==========================================================================================

First 15 physical lines:
------------------------------------------------------------------------------------------
001: ï»¿Area_Name,Year,Group_Name,Sub_Group_Name,Persons_Acquitted,Persons_against_whom_cases_Compounded_or_Withdrawn,Persons_Arrested,Persons_Chargesheeted,Persons_Convicted,Persons_in_Custody_or_on_Bail_during_Investigation_at_Year_beginning,Persons_in_Custody_or_on_Bail_during_Investigation_at_Year_end,Persons_in_Custody_or_on_Bail_during_Trial_at_Year_End,Persons_Released_or_Freed_by_Police_or_Magistrate_before_Trial_for_want_of_evidence_or_any_other_reason,Persons_Trial_Completed,Persons_under_T
002: Andaman & Nicobar Islands,2001,Rape,01. Rape,6,0,3,3,0,6,6,45,0,6,48,51
003: Andhra Pradesh,2001,Rape,01. Rape,1168,13,1150,1021,246,450,545,2191,34,1414,2597,3618
004: Arunachal Pradesh,2001,Rape,01. Rape,1,0,51,31,2,25,30,347,15,3,319,350
005: Assam,2001,Rape,01. Rape,403,14,928,585,120,806,959,2331,190,523,2283,2868
006: Bihar,2001,Rape,01. Rape,756,0,1400,1302,217,719,576,5963,241,973,5634,6936
007: Chandigarh,2001,Rape,01. Rape,12,0,32,31,2,0,0,59,1,14,42,73
008: Chhattisgarh,2001,Rape,01. Rape,636,67,1134,1213,276,116,37,4918,0,912,4684,5897
009: Dadra & Nagar Haveli,2001,Rape,01. Rape,9,0,10,11,1,2,1,32,0,10,31,42
010: Daman & Diu,2001,Rape,01. Rape,3,0,0,1,0,1,0,1,0,3,3,4
011: Delhi,2001,Rape,01. Rape,166,0,454,394,157,114,159,2597,15,323,2526,2920
012: Goa,2001,Rape,01. Rape,12,0,14,15,22,9,7,55,1,34,74,89
013: Gujarat,2001,Rape,01. Rape,223,10,401,411,32,41,31,3211,0,255,3065,3476
014: Haryana,2001,Rape,01. Rape,443,1,539,519,126,17,35,1020,2,569,1071,1590
015: Himachal Pradesh,2001,Rape,01. Rape,110,0,152,146,36,49,51,675,4,146,675,821

Field-count inspection:
------------------------------------------------------------------------------------------
Observed field-count frequencies in first 1000 physical rows:
  16 fields : 1000 rows

In [28]:
# ============================================================
# CELL 27 — SAVE PHASE 3 DATASET PROFILE
# ============================================================

profile_output_path = (
    TABLES_DIR / "dataset_semantic_profile.csv"
)

dataset_profile_df.to_csv(
    profile_output_path,
    index=False,
    encoding="utf-8-sig"
)

sample_evidence_output_path = (
    TABLES_DIR / "dataset_sample_evidence.csv"
)

sample_evidence_df.to_csv(
    sample_evidence_output_path,
    index=False,
    encoding="utf-8-sig"
)

print("=" * 70)
print("PHASE 3 PROFILE REPORTS SAVED")
print("=" * 70)

print("\nSemantic profile:")
print(
    profile_output_path.resolve()
)

print("\nSample evidence:")
print(
    sample_evidence_output_path.resolve()
)

print("\n✓ Raw source CSV files remain untouched.")

======================================================================
PHASE 3 PROFILE REPORTS SAVED
======================================================================

Semantic profile:
D:\Major_Project\Crime_Analysis\outputs\tables\dataset_semantic_profile.csv

Sample evidence:
D:\Major_Project\Crime_Analysis\outputs\tables\dataset_sample_evidence.csv

✓ Raw source CSV files remain untouched.

In [29]:
# ============================================================
# CELL 28 — PHASE 3 STATUS SUMMARY
# ============================================================

print("=" * 70)
print("PHASE 3 STATUS")
print("=" * 70)

print(
    f"\nDatasets inspected          : "
    f"{len(dataset_profile_df)}"
)

print(
    f"Datasets requiring review  : "
    f"{dataset_profile_df['manual_review_required'].sum()}"
)

print(
    f"Files with parsing issues  : "
    f"{len(parsing_problem_names)}"
)

print(
    f"Total source rows observed : "
    f"{total_source_rows:,}"
)

print("\nReports created:")

print(
    f"  {profile_output_path.resolve()}"
)

print(
    f"  {sample_evidence_output_path.resolve()}"
)

print("\n" + "-" * 70)
print("IMPORTANT")
print("-" * 70)

print(
    "No final geographic, temporal, or subject classification "
    "has been assigned automatically."
)

print(
    "No common schema has been created."
)

print(
    "No datasets have been integrated."
)

print(
    "No raw source files have been modified."
)

print("\n✓ Phase 3 evidence collection complete.")

======================================================================
PHASE 3 STATUS
======================================================================

Datasets inspected          : 76
Datasets requiring review  : 76
Files with parsing issues  : 3
Total source rows observed : 147,753

Reports created:
  D:\Major_Project\Crime_Analysis\outputs\tables\dataset_semantic_profile.csv
  D:\Major_Project\Crime_Analysis\outputs\tables\dataset_sample_evidence.csv

----------------------------------------------------------------------
IMPORTANT
----------------------------------------------------------------------
No final geographic, temporal, or subject classification has been assigned automatically.
No common schema has been created.
No datasets have been integrated.
No raw source files have been modified.

✓ Phase 3 evidence collection complete.

In [30]:
# ============================================================
# CELL 29 — DATASET FAMILY CLASSIFICATION
# ============================================================

def classify_dataset_family(filename):
    """
    Candidate family classification based primarily on the
    dataset filename.

    This is a structural grouping step, NOT a final semantic
    validation of the underlying data.
    """

    name = filename.lower()

    # --------------------------------------------------------
    # District-wise crime datasets
    # --------------------------------------------------------

    if "district_wise" in name:
        return "DISTRICT_WISE_CRIME"

    # --------------------------------------------------------
    # Persons arrested / disposal
    # --------------------------------------------------------

    if (
        "persons_arrested" in name
        or "person_arrested" in name
        or "arrests_under" in name
    ):
        return "ARREST_DISPOSAL"

    # --------------------------------------------------------
    # Juvenile datasets
    # --------------------------------------------------------

    if (
        "juvenile" in name
        or "juveniles" in name
    ):
        return "JUVENILE"

    # --------------------------------------------------------
    # Property / vehicle
    # --------------------------------------------------------

    if (
        "property" in name
        or "auto_theft" in name
        or "serious_fraud" in name
        or "property_taken" in name
    ):
        return "PROPERTY_CRIME"

    # --------------------------------------------------------
    # Police personnel / police administration
    # --------------------------------------------------------

    if (
        "police" in name
        or "home_guards" in name
        or "auxilliary" in name
    ):
        return "POLICE_ADMINISTRATION"

    # --------------------------------------------------------
    # Victim demographic datasets
    # --------------------------------------------------------

    if (
        "victim" in name
        or "offenders_known" in name
        or "motive_or_cause" in name
        or "specific_purpose" in name
        or "use_of_fire" in name
    ):
        return "VICTIM_OFFENDER_CHARACTERISTICS"

    # --------------------------------------------------------
    # Court / trial / justice
    # --------------------------------------------------------

    if (
        "trial" in name
        or "court" in name
        or "custodial" in name
        or "escape" in name
        or "cases_under_crime" in name
    ):
        return "JUSTICE_COURT"

    # --------------------------------------------------------
    # Anti-corruption
    # --------------------------------------------------------

    if (
        "corruption" in name
        or "corruprion" in name
    ):
        return "ANTI_CORRUPTION"

    # --------------------------------------------------------
    # Police complaints / human rights
    # --------------------------------------------------------

    if (
        "complaint" in name
        or "human_rights" in name
    ):
        return "POLICE_ACCOUNTABILITY"

    # --------------------------------------------------------
    # Crime by place
    # --------------------------------------------------------

    if "place_of_occurrence" in name:
        return "CRIME_PLACE_OF_OCCURRENCE"

    # --------------------------------------------------------
    # Fallback
    # --------------------------------------------------------

    return "OTHER_SPECIALIZED"


dataset_profile_df["dataset_family"] = (
    dataset_profile_df["filename"]
    .apply(classify_dataset_family)
)

print("=" * 70)
print("DATASET FAMILY CLASSIFICATION")
print("=" * 70)

family_counts = (
    dataset_profile_df["dataset_family"]
    .value_counts()
    .sort_index()
)

display(
    family_counts.to_frame("file_count")
)

======================================================================
DATASET FAMILY CLASSIFICATION
======================================================================

                                 file_count
dataset_family
ANTI_CORRUPTION                           2
ARREST_DISPOSAL                          17
CRIME_PLACE_OF_OCCURRENCE                 3
DISTRICT_WISE_CRIME                      14
JUSTICE_COURT                             8
JUVENILE                                  7
OTHER_SPECIALIZED                         1
POLICE_ADMINISTRATION                    11
PROPERTY_CRIME                            6
VICTIM_OFFENDER_CHARACTERISTICS           7

In [31]:
# ============================================================
# CELL 30 — FILE-TO-FAMILY MAPPING
# ============================================================

family_mapping_df = (
    dataset_profile_df[
        [
            "filename",
            "row_count",
            "column_count",
            "dataset_family"
        ]
    ]
    .sort_values(
        [
            "dataset_family",
            "filename"
        ]
    )
    .reset_index(drop=True)
)

display(
    family_mapping_df
)

                                                                                            filename  row_count  column_count                   dataset_family
0                                                                       23_Anti_corruprion_cases.csv        346            29                  ANTI_CORRUPTION
1                                                                     24_Anti_corruption_arrests.csv        347            24                  ANTI_CORRUPTION
2   03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2012.csv        494            14                  ARREST_DISPOSAL
3   03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2013.csv        494            14                  ARREST_DISPOSAL
4   03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2014.csv       2028            57                  ARREST_DISPOSAL
..                                                                                               ...        ...           ...                              ...
71                                                              21_Offenders_known_to_the_victim.csv        350             7  VICTIM_OFFENDER_CHARACTERISTICS
72                                                                      32_Murder_victim_age_sex.csv       1018            11  VICTIM_OFFENDER_CHARACTERISTICS
73                                                               33_CH_not_murder_victim_age_sex.csv        936            10  VICTIM_OFFENDER_CHARACTERISTICS
74                                                           34_Use_of_fire_arms_in_murder_cases.csv        284             5  VICTIM_OFFENDER_CHARACTERISTICS
75                                               39_Specific_purpose_of_kidnapping_and_abduction.csv       3569            20  VICTIM_OFFENDER_CHARACTERISTICS

[76 rows x 4 columns]

In [32]:
# ============================================================
# CELL 31 — COMMON DIMENSION DETECTION
# ============================================================

COMMON_DIMENSION_PATTERNS = {
    "year": [
        r"^year$",
        r"year$"
    ],

    "state": [
        r"state",
        r"states",
        r"state/ut",
        r"states/uts"
    ],

    "district": [
        r"district"
    ],

    "crime_head": [
        r"crime head",
        r"crime_head",
        r"crime$"
    ],

    "area": [
        r"area",
        r"region",
        r"location",
        r"place"
    ]
}


def detect_dimension_columns(columns):

    detected = {
        key: []
        for key in COMMON_DIMENSION_PATTERNS
    }

    for column in columns:

        col = str(column).strip().lower()

        for dimension, patterns in (
            COMMON_DIMENSION_PATTERNS.items()
        ):

            for pattern in patterns:

                if re.search(
                    pattern,
                    col
                ):
                    detected[dimension].append(
                        str(column)
                    )
                    break

    return detected

In [33]:
# ============================================================
# CELL 32 — DIMENSION INVENTORY
# ============================================================

dimension_records = []

for file_path in csv_files:

    df, read_info = read_csv_for_inspection(
        file_path
    )

    if df is None:
        continue

    detected = detect_dimension_columns(
        df.columns
    )

    dimension_records.append({

        "filename":
            file_path.name,

        "dataset_family":
            classify_dataset_family(
                file_path.name
            ),

        "has_year":
            bool(detected["year"]),

        "year_columns":
            "; ".join(
                detected["year"]
            ),

        "has_state":
            bool(detected["state"]),

        "state_columns":
            "; ".join(
                detected["state"]
            ),

        "has_district":
            bool(detected["district"]),

        "district_columns":
            "; ".join(
                detected["district"]
            ),

        "has_crime_head":
            bool(detected["crime_head"]),

        "crime_head_columns":
            "; ".join(
                detected["crime_head"]
            ),

        "has_area":
            bool(detected["area"]),

        "area_columns":
            "; ".join(
                detected["area"]
            )
    })


dimension_inventory_df = pd.DataFrame(
    dimension_records
)

display(
    dimension_inventory_df
)

,filename,dataset_family,has_year,year_columns,has_state,state_columns,has_district,district_columns,has_crime_head,crime_head_columns,has_area,area_columns
0,01_District_wise_crimes_committed_IPC_2001_2012.csv,DISTRICT_WISE_CRIME,True,YEAR,True,STATE/UT,True,DISTRICT,False,,False,
1,01_District_wise_crimes_committed_IPC_2013.csv,DISTRICT_WISE_CRIME,True,YEAR,True,STATE/UT,True,DISTRICT,False,,False,
2,01_District_wise_crimes_committed_IPC_2014.csv,DISTRICT_WISE_CRIME,True,Year,True,States/UTs; Offences against State; Other offences against State,True,District,False,,True,"Other places related to work; Places other than 231, 232 & 233"
3,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv,DISTRICT_WISE_CRIME,True,Year,True,STATE/UT,True,DISTRICT,False,,False,
4,02_01_District_wise_crimes_committed_against_SC_2013.csv,DISTRICT_WISE_CRIME,True,Year,True,STATE/UT,True,DISTRICT,False,,False,
...,...,...,...,...,...,...,...,...,...,...,...,...
71,42_Cases_under_crime_against_women.csv,JUSTICE_COURT,True,Year; Cases_Pending_Investigation_from_previous_year; Cases_Pending_Trial_from_the_previous_year,False,,False,,False,,True,Area_Name
72,42_District_wise_crimes_committed_against_women_2001_2012.csv,DISTRICT_WISE_CRIME,True,Year,True,STATE/UT,True,DISTRICT,False,,False,
73,42_District_wise_crimes_committed_against_women_2013.csv,DISTRICT_WISE_CRIME,True,Year,True,STATE/UT,True,DISTRICT,False,,False,
74,42_District_wise_crimes_committed_against_women_2014.csv,DISTRICT_WISE_CRIME,True,Year,True,States/UTs,True,District,False,,True,In places related to work; In other Places
75,43_Arrests_under_crime_against_women.csv,ARREST_DISPOSAL,True,Year,False,,False,,False,,True,Area_Name

In [34]:
# ============================================================
# CELL 33 — DIMENSION COVERAGE
# ============================================================

dimension_summary = pd.DataFrame({

    "dimension": [
        "Year",
        "State/UT",
        "District",
        "Crime Head",
        "Generic Area/Location"
    ],

    "datasets_containing_dimension": [

        dimension_inventory_df["has_year"].sum(),

        dimension_inventory_df["has_state"].sum(),

        dimension_inventory_df["has_district"].sum(),

        dimension_inventory_df["has_crime_head"].sum(),

        dimension_inventory_df["has_area"].sum()
    ]
})

display(
    dimension_summary
)

               dimension  datasets_containing_dimension
0                   Year                             72
1               State/UT                             36
2               District                             14
3             Crime Head                             17
4  Generic Area/Location                             47

In [35]:
# ============================================================
# CELL 34 — DATASET COMPARABILITY MATRIX
# ============================================================

dimension_columns = [
    "has_year",
    "has_state",
    "has_district",
    "has_crime_head"
]

comparability_records = []

for i in range(
    len(dimension_inventory_df)
):

    for j in range(
        i + 1,
        len(dimension_inventory_df)
    ):

        a = dimension_inventory_df.iloc[i]
        b = dimension_inventory_df.iloc[j]

        shared_dimensions = []

        for dimension in dimension_columns:

            if (
                a[dimension]
                and b[dimension]
            ):
                shared_dimensions.append(
                    dimension.replace(
                        "has_",
                        ""
                    )
                )

        comparability_records.append({

            "dataset_a":
                a["filename"],

            "dataset_b":
                b["filename"],

            "family_a":
                a["dataset_family"],

            "family_b":
                b["dataset_family"],

            "shared_dimensions":
                ", ".join(
                    shared_dimensions
                ),

            "shared_dimension_count":
                len(shared_dimensions)
        })


comparability_df = pd.DataFrame(
    comparability_records
)

# Only display pairs with at least 2 shared dimensions
potential_comparisons = (
    comparability_df[
        comparability_df[
            "shared_dimension_count"
        ] >= 2
    ]
    .sort_values(
        "shared_dimension_count",
        ascending=False
    )
)

print("=" * 70)
print("POTENTIALLY COMPARABLE DATASET PAIRS")
print("=" * 70)

display(
    potential_comparisons.head(100)
)

======================================================================
POTENTIALLY COMPARABLE DATASET PAIRS
======================================================================

,dataset_a,dataset_b,family_a,family_b,shared_dimensions,shared_dimension_count
0,01_District_wise_crimes_committed_IPC_2001_2012.csv,01_District_wise_crimes_committed_IPC_2013.csv,DISTRICT_WISE_CRIME,DISTRICT_WISE_CRIME,"year, state, district",3
846,03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2013.csv,07_02_Persons_arrested_by_sex_and_age_group_SLL_2014.csv,ARREST_DISPOSAL,ARREST_DISPOSAL,"year, state, crime_head",3
639,03_District_wise_crimes_committed_against_children_2001_2012.csv,03_District_wise_crimes_committed_against_children_2013.csv,DISTRICT_WISE_CRIME,DISTRICT_WISE_CRIME,"year, state, district",3
701,03_District_wise_crimes_committed_against_children_2001_2012.csv,42_District_wise_crimes_committed_against_women_2001_2012.csv,DISTRICT_WISE_CRIME,DISTRICT_WISE_CRIME,"year, state, district",3
702,03_District_wise_crimes_committed_against_children_2001_2012.csv,42_District_wise_crimes_committed_against_women_2013.csv,DISTRICT_WISE_CRIME,DISTRICT_WISE_CRIME,"year, state, district",3
...,...,...,...,...,...,...
898,03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2014.csv,04_01_Person_arrested_and_their_disposal_by_police_and_court_SLL_crime_2013.csv,ARREST_DISPOSAL,ARREST_DISPOSAL,"year, state, crime_head",3
899,03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2014.csv,04_01_Person_arrested_and_their_disposal_by_police_and_court_SLL_crime_2014.csv,ARREST_DISPOSAL,ARREST_DISPOSAL,"year, state, crime_head",3
900,03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2014.csv,04_02_Person_arrested_and_their_disposal_by_police_and_court_IPC_crime_2012.csv,ARREST_DISPOSAL,ARREST_DISPOSAL,"year, state, crime_head",3
901,03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2014.csv,04_02_Person_arrested_and_their_disposal_by_police_and_court_IPC_crime_2013.csv,ARREST_DISPOSAL,ARREST_DISPOSAL,"year, state, crime_head",3
902,03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2014.csv,04_02_Person_arrested_and_their_disposal_by_police_and_court_IPC_crime_2014.csv,ARREST_DISPOSAL,ARREST_DISPOSAL,"year, state, crime_head",3

In [36]:
# ============================================================
# CELL 35 — GEOGRAPHIC INTEGRATION CANDIDATES
# ============================================================

geographic_candidates = (
    dimension_inventory_df[
        (
            dimension_inventory_df["has_year"]
        )
        &
        (
            dimension_inventory_df["has_state"]
        )
    ]
    .copy()
)

print("=" * 70)
print("YEAR + STATE/UT INTEGRATION CANDIDATES")
print("=" * 70)

display(
    geographic_candidates[
        [
            "filename",
            "dataset_family",
            "year_columns",
            "state_columns",
            "district_columns",
            "crime_head_columns"
        ]
    ]
)

======================================================================
YEAR + STATE/UT INTEGRATION CANDIDATES
======================================================================

,filename,dataset_family,year_columns,state_columns,district_columns,crime_head_columns
0,01_District_wise_crimes_committed_IPC_2001_2012.csv,DISTRICT_WISE_CRIME,YEAR,STATE/UT,DISTRICT,
1,01_District_wise_crimes_committed_IPC_2013.csv,DISTRICT_WISE_CRIME,YEAR,STATE/UT,DISTRICT,
2,01_District_wise_crimes_committed_IPC_2014.csv,DISTRICT_WISE_CRIME,Year,States/UTs; Offences against State; Other offences against State,District,
3,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv,DISTRICT_WISE_CRIME,Year,STATE/UT,DISTRICT,
4,02_01_District_wise_crimes_committed_against_SC_2013.csv,DISTRICT_WISE_CRIME,Year,STATE/UT,DISTRICT,
5,02_01_District_wise_crimes_committed_against_SC_2014.csv,DISTRICT_WISE_CRIME,Year,States/UTs,District,
6,02_District_wise_crimes_committed_against_ST_2001_2012.csv,DISTRICT_WISE_CRIME,Year,STATE/UT,DISTRICT,
7,02_District_wise_crimes_committed_against_ST_2013.csv,DISTRICT_WISE_CRIME,Year,STATE/UT,DISTRICT,
8,02_District_wise_crimes_committed_against_ST_2014.csv,DISTRICT_WISE_CRIME,Year,States/UTs,District,
9,03_District_wise_crimes_committed_against_children_2001_2012.csv,DISTRICT_WISE_CRIME,Year,STATE/UT,DISTRICT,
10,03_District_wise_crimes_committed_against_children_2013.csv,DISTRICT_WISE_CRIME,Year,STATE/UT,DISTRICT,
11,03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2012.csv,ARREST_DISPOSAL,Persons in custody or on bail during the stage of investigation at the beginning of the year; Persons arrested durin...,STATE/UT,,CRIME HEAD
12,03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2013.csv,ARREST_DISPOSAL,Persons in custody or on bail during the stage of investigation at the beginning of the year; Persons arrested durin...,STATE/UT,,CRIME HEAD
13,03_Persons_arrested_and_their_disposal_by_police_and_court_under_crime_against_children_2014.csv,ARREST_DISPOSAL,Year,States/UTs,,Crime Head
14,04_01_Person_arrested_and_their_disposal_by_police_and_court_SLL_crime_2012.csv,ARREST_DISPOSAL,Persons in custody or on bail during the stage of investigation at the beginning of the year; Persons arrested durin...,STATE/UT,,CRIME HEAD
15,04_01_Person_arrested_and_their_disposal_by_police_and_court_SLL_crime_2013.csv,ARREST_DISPOSAL,Persons in custody or on bail during the stage of investigation at the beginning of the year; Persons arrested durin...,STATE/UT,,CRIME HEAD
16,04_01_Person_arrested_and_their_disposal_by_police_and_court_SLL_crime_2014.csv,ARREST_DISPOSAL,Year,States/UTs,,Crime Head
17,04_02_Person_arrested_and_their_disposal_by_police_and_court_IPC_crime_2012.csv,ARREST_DISPOSAL,Persons in custody or on bail during the stage of investigation at the beginning of the year; Persons arrested durin...,STATE/UT,,CRIME HEAD
18,04_02_Person_arrested_and_their_disposal_by_police_and_court_IPC_crime_2013.csv,ARREST_DISPOSAL,Persons in custody or on bail during the stage of investigation at the beginning of the year; Persons arrested durin...,STATE/UT,,CRIME HEAD
19,04_02_Person_arrested_and_their_disposal_by_police_and_court_IPC_crime_2014.csv,ARREST_DISPOSAL,Year,States/UTs,,Crime Head
22,07_01_Persons_arrested_by_sex_and_age_group_IPC_2014.csv,ARREST_DISPOSAL,Year,States/UTs,,Crime Head
25,07_02_Persons_arrested_by_sex_and_age_group_SLL_2014.csv,ARREST_DISPOSAL,Year,States/UTs,,Crime Head
26,08_01_Juvenile_apprehended_state_IPC.csv,JUVENILE,Year,STATE/UT,,CRIME
27,08_02_Juvenile_apprehended_state_SLL.csv,JUVENILE,Year,STATE/UT,,CRIME
36,17_Case_reported_and_value_of_property_taken_away_by_place_of_occurrence_2001_2012.csv,PROPERTY_CRIME,YEAR,STATE/UT,,
37,17_Case_reported_and_value_of_property_taken_away_by_place_of_occurrence_2013.csv,PROPERTY_CRIME,YEAR,STATE/UT,,
38,17_Crime_by_place_of_occurrence_2001_2012.csv,CRIME_PLACE_OF_OCCURRENCE,YEAR,STATE/UT,,
39,17_Crime_by_place_of_occurrence_2013.csv,CRIME_PLACE_OF_OCCURRENCE,YEAR,STATE/UT,,
40,17_Crime_by_place_of_occurrence_2014.csv,CRIME_PLACE_OF_OCCURRENCE,Year,States/UTs,,
72,42_District_wise_crimes_committed_against_women_2001_2012.csv,DISTRICT_WISE_CRIME,Year,STATE/UT,DISTRICT,
73,42_District_wise_crimes_committed_against_women_2013.csv,DISTRICT_WISE_CRIME,Year,STATE/UT,DISTRICT,
74,42_District_wise_crimes_committed_against_women_2014.csv,DISTRICT_WISE_CRIME,Year,States/UTs,District,

In [37]:
# ============================================================
# CELL 36 — DISTRICT-LEVEL CANDIDATES
# ============================================================

district_candidates = (
    dimension_inventory_df[
        (
            dimension_inventory_df["has_year"]
        )
        &
        (
            dimension_inventory_df["has_state"]
        )
        &
        (
            dimension_inventory_df["has_district"]
        )
    ]
    .copy()
)

print("=" * 70)
print("DISTRICT-LEVEL DATASET CANDIDATES")
print("=" * 70)

display(
    district_candidates[
        [
            "filename",
            "dataset_family",
            "year_columns",
            "state_columns",
            "district_columns",
            "crime_head_columns"
        ]
    ]
)

======================================================================
DISTRICT-LEVEL DATASET CANDIDATES
======================================================================

,filename,dataset_family,year_columns,state_columns,district_columns,crime_head_columns
0,01_District_wise_crimes_committed_IPC_2001_2012.csv,DISTRICT_WISE_CRIME,YEAR,STATE/UT,DISTRICT,
1,01_District_wise_crimes_committed_IPC_2013.csv,DISTRICT_WISE_CRIME,YEAR,STATE/UT,DISTRICT,
2,01_District_wise_crimes_committed_IPC_2014.csv,DISTRICT_WISE_CRIME,Year,States/UTs; Offences against State; Other offences against State,District,
3,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv,DISTRICT_WISE_CRIME,Year,STATE/UT,DISTRICT,
4,02_01_District_wise_crimes_committed_against_SC_2013.csv,DISTRICT_WISE_CRIME,Year,STATE/UT,DISTRICT,
5,02_01_District_wise_crimes_committed_against_SC_2014.csv,DISTRICT_WISE_CRIME,Year,States/UTs,District,
6,02_District_wise_crimes_committed_against_ST_2001_2012.csv,DISTRICT_WISE_CRIME,Year,STATE/UT,DISTRICT,
7,02_District_wise_crimes_committed_against_ST_2013.csv,DISTRICT_WISE_CRIME,Year,STATE/UT,DISTRICT,
8,02_District_wise_crimes_committed_against_ST_2014.csv,DISTRICT_WISE_CRIME,Year,States/UTs,District,
9,03_District_wise_crimes_committed_against_children_2001_2012.csv,DISTRICT_WISE_CRIME,Year,STATE/UT,DISTRICT,
10,03_District_wise_crimes_committed_against_children_2013.csv,DISTRICT_WISE_CRIME,Year,STATE/UT,DISTRICT,
72,42_District_wise_crimes_committed_against_women_2001_2012.csv,DISTRICT_WISE_CRIME,Year,STATE/UT,DISTRICT,
73,42_District_wise_crimes_committed_against_women_2013.csv,DISTRICT_WISE_CRIME,Year,STATE/UT,DISTRICT,
74,42_District_wise_crimes_committed_against_women_2014.csv,DISTRICT_WISE_CRIME,Year,States/UTs,District,

In [38]:
# ============================================================
# CELL 37 — PRELIMINARY INTEGRATION DECISION
# ============================================================

def preliminary_integration_decision(row):

    family = row["dataset_family"]

    filename = row["filename"].lower()

    # --------------------------------------------------------
    # District-wise crime data
    # --------------------------------------------------------

    if family == "DISTRICT_WISE_CRIME":

        return (
            "DISTRICT_CRIME_CORE",
            "Candidate for district-level crime analysis"
        )

    # --------------------------------------------------------
    # Arrest/disposal
    # --------------------------------------------------------

    if family == "ARREST_DISPOSAL":

        return (
            "SEPARATE_ANALYTICAL_TABLE",
            "Different row grain: arrest/disposal statistics"
        )

    # --------------------------------------------------------
    # Property
    # --------------------------------------------------------

    if family == "PROPERTY_CRIME":

        return (
            "SEPARATE_ANALYTICAL_TABLE",
            "Property/value measures have different semantics"
        )

    # --------------------------------------------------------
    # Juvenile
    # --------------------------------------------------------

    if family == "JUVENILE":

        return (
            "SEPARATE_ANALYTICAL_TABLE",
            "Juvenile-specific population and measures"
        )

    # --------------------------------------------------------
    # Police administration
    # --------------------------------------------------------

    if family == "POLICE_ADMINISTRATION":

        return (
            "SEPARATE_ANALYTICAL_TABLE",
            "Police personnel/administration statistics"
        )

    # --------------------------------------------------------
    # Victim/offender characteristics
    # --------------------------------------------------------

    if family == "VICTIM_OFFENDER_CHARACTERISTICS":

        return (
            "SEPARATE_ANALYTICAL_TABLE",
            "Victim/offender characteristic statistics"
        )

    # --------------------------------------------------------
    # Justice / courts
    # --------------------------------------------------------

    if family == "JUSTICE_COURT":

        return (
            "SEPARATE_ANALYTICAL_TABLE",
            "Justice/court process statistics"
        )

    # --------------------------------------------------------
    # Anti-corruption
    # --------------------------------------------------------

    if family == "ANTI_CORRUPTION":

        return (
            "SEPARATE_ANALYTICAL_TABLE",
            "Specialized anti-corruption statistics"
        )

    # --------------------------------------------------------
    # Police accountability
    # --------------------------------------------------------

    if family == "POLICE_ACCOUNTABILITY":

        return (
            "SEPARATE_ANALYTICAL_TABLE",
            "Police complaints/accountability statistics"
        )

    # --------------------------------------------------------
    # Crime place
    # --------------------------------------------------------

    if family == "CRIME_PLACE_OF_OCCURRENCE":

        return (
            "SEPARATE_ANALYTICAL_TABLE",
            "Place-of-occurrence structure differs"
        )

    # --------------------------------------------------------
    # Everything else
    # --------------------------------------------------------

    return (
        "MANUAL_REVIEW",
        "Specialized dataset requiring semantic review"
    )


decision_values = (
    dataset_profile_df
    .apply(
        preliminary_integration_decision,
        axis=1
    )
)

dataset_profile_df[
    [
        "integration_status",
        "integration_reason"
    ]
] = pd.DataFrame(
    decision_values.tolist(),
    index=dataset_profile_df.index
)

display(
    dataset_profile_df[
        [
            "filename",
            "dataset_family",
            "integration_status",
            "integration_reason"
        ]
    ]
)

                                                         filename       dataset_family         integration_status                               integration_reason
0             01_District_wise_crimes_committed_IPC_2001_2012.csv  DISTRICT_WISE_CRIME        DISTRICT_CRIME_CORE      Candidate for district-level crime analysis
1                  01_District_wise_crimes_committed_IPC_2013.csv  DISTRICT_WISE_CRIME        DISTRICT_CRIME_CORE      Candidate for district-level crime analysis
2                  01_District_wise_crimes_committed_IPC_2014.csv  DISTRICT_WISE_CRIME        DISTRICT_CRIME_CORE      Candidate for district-level crime analysis
3   02_01_District_wise_crimes_committed_against_SC_2001_2012.csv  DISTRICT_WISE_CRIME        DISTRICT_CRIME_CORE      Candidate for district-level crime analysis
4        02_01_District_wise_crimes_committed_against_SC_2013.csv  DISTRICT_WISE_CRIME        DISTRICT_CRIME_CORE      Candidate for district-level crime analysis
..                                                            ...                  ...                        ...                                              ...
71                         42_Cases_under_crime_against_women.csv        JUSTICE_COURT  SEPARATE_ANALYTICAL_TABLE                 Justice/court process statistics
72  42_District_wise_crimes_committed_against_women_2001_2012.csv  DISTRICT_WISE_CRIME        DISTRICT_CRIME_CORE      Candidate for district-level crime analysis
73       42_District_wise_crimes_committed_against_women_2013.csv  DISTRICT_WISE_CRIME        DISTRICT_CRIME_CORE      Candidate for district-level crime analysis
74       42_District_wise_crimes_committed_against_women_2014.csv  DISTRICT_WISE_CRIME        DISTRICT_CRIME_CORE      Candidate for district-level crime analysis
75                       43_Arrests_under_crime_against_women.csv      ARREST_DISPOSAL  SEPARATE_ANALYTICAL_TABLE  Different row grain: arrest/disposal statistics

[76 rows x 4 columns]

In [39]:
# ============================================================
# CELL 38 — INTEGRATION DECISION SUMMARY
# ============================================================

decision_summary = (
    dataset_profile_df[
        "integration_status"
    ]
    .value_counts()
    .to_frame(
        "file_count"
    )
)

display(
    decision_summary
)

                           file_count
integration_status
SEPARATE_ANALYTICAL_TABLE          61
DISTRICT_CRIME_CORE                14
MANUAL_REVIEW                       1

In [40]:
# ============================================================
# CELL 39 — SAVE PHASE 4 AUDIT
# ============================================================

phase4_output = (
    TABLES_DIR /
    "phase4_dataset_integration_audit.csv"
)

dataset_profile_df.to_csv(
    phase4_output,
    index=False,
    encoding="utf-8-sig"
)

dimension_output = (
    TABLES_DIR /
    "phase4_dimension_inventory.csv"
)

dimension_inventory_df.to_csv(
    dimension_output,
    index=False,
    encoding="utf-8-sig"
)

comparison_output = (
    TABLES_DIR /
    "phase4_dataset_comparability.csv"
)

comparability_df.to_csv(
    comparison_output,
    index=False,
    encoding="utf-8-sig"
)

print("=" * 70)
print("PHASE 4 AUDIT FILES CREATED")
print("=" * 70)

print(
    f"\n{phase4_output.resolve()}"
)

print(
    f"\n{dimension_output.resolve()}"
)

print(
    f"\n{comparison_output.resolve()}"
)

======================================================================
PHASE 4 AUDIT FILES CREATED
======================================================================

D:\Major_Project\Crime_Analysis\outputs\tables\phase4_dataset_integration_audit.csv

D:\Major_Project\Crime_Analysis\outputs\tables\phase4_dimension_inventory.csv

D:\Major_Project\Crime_Analysis\outputs\tables\phase4_dataset_comparability.csv

In [41]:
# ============================================================
# CELL 40 — SELECT DISTRICT CRIME DATASETS
# ============================================================

district_files = [
    Path(RAW_DATA_DIR) / filename
    for filename in dataset_profile_df.loc[
        dataset_profile_df["integration_status"]
        == "DISTRICT_CRIME_CORE",
        "filename"
    ]
]

print("=" * 70)
print("DISTRICT CRIME DATASETS SELECTED")
print("=" * 70)

print(f"\nTotal selected: {len(district_files)}")

for i, path in enumerate(
    district_files,
    start=1
):
    print(f"{i:02d}. {path.name}")

======================================================================
DISTRICT CRIME DATASETS SELECTED
======================================================================

Total selected: 14
01. 01_District_wise_crimes_committed_IPC_2001_2012.csv
02. 01_District_wise_crimes_committed_IPC_2013.csv
03. 01_District_wise_crimes_committed_IPC_2014.csv
04. 02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
05. 02_01_District_wise_crimes_committed_against_SC_2013.csv
06. 02_01_District_wise_crimes_committed_against_SC_2014.csv
07. 02_District_wise_crimes_committed_against_ST_2001_2012.csv
08. 02_District_wise_crimes_committed_against_ST_2013.csv
09. 02_District_wise_crimes_committed_against_ST_2014.csv
10. 03_District_wise_crimes_committed_against_children_2001_2012.csv
11. 03_District_wise_crimes_committed_against_children_2013.csv
12. 42_District_wise_crimes_committed_against_women_2001_2012.csv
13. 42_District_wise_crimes_committed_against_women_2013.csv
14. 42_District_wise_crimes_committed_against_women_2014.csv

In [42]:
# ============================================================
# CELL 41 — DISTRICT DATASET COLUMN COMPARISON
# ============================================================

district_structure = []

for path in district_files:

    df, read_info = read_csv_for_inspection(
        path
    )

    if df is None:
        continue

    district_structure.append({

        "filename":
            path.name,

        "rows":
            len(df),

        "columns":
            len(df.columns),

        "state_column":
            next(
                (
                    c for c in df.columns
                    if str(c).strip().upper()
                    in [
                        "STATE/UT",
                        "STATES/UTS"
                    ]
                ),
                None
            ),

        "district_column":
            next(
                (
                    c for c in df.columns
                    if str(c).strip().upper()
                    == "DISTRICT"
                ),
                None
            ),

        "year_column":
            next(
                (
                    c for c in df.columns
                    if str(c).strip().upper()
                    == "YEAR"
                ),
                None
            ),

        "read_status":
            read_info.get(
                "status",
                "unknown"
            )
    })


district_structure_df = pd.DataFrame(
    district_structure
)

display(
    district_structure_df
)

                                                            filename  rows  columns state_column district_column year_column read_status
0                01_District_wise_crimes_committed_IPC_2001_2012.csv  9017       33     STATE/UT        DISTRICT        YEAR     success
1                     01_District_wise_crimes_committed_IPC_2013.csv   823       33     STATE/UT        DISTRICT        YEAR     success
2                     01_District_wise_crimes_committed_IPC_2014.csv   838       91   States/UTs        District        Year     success
3      02_01_District_wise_crimes_committed_against_SC_2001_2012.csv  9018       13     STATE/UT        DISTRICT        Year     success
4           02_01_District_wise_crimes_committed_against_SC_2013.csv   823       13     STATE/UT        DISTRICT        Year     success
5           02_01_District_wise_crimes_committed_against_SC_2014.csv   837       66   States/UTs        District        Year     success
6         02_District_wise_crimes_committed_against_ST_2001_2012.csv  9018       13     STATE/UT        DISTRICT        Year     success
7              02_District_wise_crimes_committed_against_ST_2013.csv   823       13     STATE/UT        DISTRICT        Year     success
8              02_District_wise_crimes_committed_against_ST_2014.csv   837       66   States/UTs        District        Year     success
9   03_District_wise_crimes_committed_against_children_2001_2012.csv  9015       15     STATE/UT        DISTRICT        Year     success
10       03_District_wise_crimes_committed_against_children_2013.csv   823       16     STATE/UT        DISTRICT        Year     success
11     42_District_wise_crimes_committed_against_women_2001_2012.csv  9017       10     STATE/UT        DISTRICT        Year     success
12          42_District_wise_crimes_committed_against_women_2013.csv   823       10     STATE/UT        DISTRICT        Year     success
13          42_District_wise_crimes_committed_against_women_2014.csv   837       62   States/UTs        District        Year     success

In [43]:
# ============================================================
# CELL 42 — NORMALIZE COMMON DIMENSIONS
# ============================================================

def normalize_dimension_columns(df):

    rename_map = {}

    for column in df.columns:

        normalized = (
            str(column)
            .strip()
            .upper()
        )

        if normalized in [
            "STATE/UT",
            "STATES/UTS"
        ]:
            rename_map[column] = "STATE"

        elif normalized == "DISTRICT":
            rename_map[column] = "DISTRICT"

        elif normalized == "YEAR":
            rename_map[column] = "YEAR"

    return df.rename(
        columns=rename_map
    )


normalized_district_data = {}

for path in district_files:

    df, read_info = read_csv_for_inspection(
        path
    )

    if df is None:
        continue

    df = normalize_dimension_columns(
        df
    )

    normalized_district_data[
        path.name
    ] = df

print(
    f"Normalized datasets: "
    f"{len(normalized_district_data)}"
)

Normalized datasets: 14

In [44]:
# ============================================================
# CELL 43 — CLEAN COMMON DIMENSION VALUES
# ============================================================

for filename, df in normalized_district_data.items():

    for column in [
        "STATE",
        "DISTRICT"
    ]:

        if column in df.columns:

            df[column] = (
                df[column]
                .astype("string")
                .str.strip()
            )

            df[column] = (
                df[column]
                .replace(
                    {
                        "":
                            pd.NA,
                        "NAN":
                            pd.NA,
                        "NULL":
                            pd.NA,
                        "N/A":
                            pd.NA
                    }
                )
            )

    if "YEAR" in df.columns:

        df["YEAR"] = pd.to_numeric(
            df["YEAR"],
            errors="coerce"
        )

print("Common dimensions cleaned.")

Common dimensions cleaned.

In [45]:
# ============================================================
# CELL 44 — ASSIGN CRIME GROUP
# ============================================================

def assign_crime_group(filename):

    name = filename.lower()

    if "_ipc_" in name:
        return "IPC"

    if "_sc_" in name:
        return "SC"

    if "_st_" in name:
        return "ST"

    if "children" in name:
        return "CHILDREN"

    if "against_women" in name:
        return "WOMEN"

    return "OTHER"


for filename, df in normalized_district_data.items():

    df["CRIME_GROUP"] = assign_crime_group(
        filename
    )

    df["SOURCE_FILE"] = filename

In [46]:
# ============================================================
# CELL 45 — CRIME GROUP SUMMARY
# ============================================================

group_summary = []

for filename, df in normalized_district_data.items():

    group_summary.append({

        "filename":
            filename,

        "crime_group":
            df["CRIME_GROUP"].iloc[0],

        "rows":
            len(df),

        "columns":
            len(df.columns)
    })


group_summary_df = pd.DataFrame(
    group_summary
)

display(
    group_summary_df
)

                                                            filename crime_group  rows  columns
0                01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC  9017       35
1                     01_District_wise_crimes_committed_IPC_2013.csv         IPC   823       35
2                     01_District_wise_crimes_committed_IPC_2014.csv         IPC   838       93
3      02_01_District_wise_crimes_committed_against_SC_2001_2012.csv          SC  9018       15
4           02_01_District_wise_crimes_committed_against_SC_2013.csv          SC   823       15
5           02_01_District_wise_crimes_committed_against_SC_2014.csv          SC   837       68
6         02_District_wise_crimes_committed_against_ST_2001_2012.csv          ST  9018       15
7              02_District_wise_crimes_committed_against_ST_2013.csv          ST   823       15
8              02_District_wise_crimes_committed_against_ST_2014.csv          ST   837       68
9   03_District_wise_crimes_committed_against_children_2001_2012.csv    CHILDREN  9015       17
10       03_District_wise_crimes_committed_against_children_2013.csv    CHILDREN   823       18
11     42_District_wise_crimes_committed_against_women_2001_2012.csv       WOMEN  9017       12
12          42_District_wise_crimes_committed_against_women_2013.csv       WOMEN   823       12
13          42_District_wise_crimes_committed_against_women_2014.csv       WOMEN   837       64

In [47]:
# ============================================================
# CELL 46 — YEAR COVERAGE
# ============================================================

year_records = []

for filename, df in normalized_district_data.items():

    if "YEAR" not in df.columns:
        continue

    year_records.append({

        "filename":
            filename,

        "min_year":
            df["YEAR"].min(),

        "max_year":
            df["YEAR"].max(),

        "unique_years":
            df["YEAR"].nunique()
    })


year_coverage_df = pd.DataFrame(
    year_records
)

display(
    year_coverage_df
)

                                                            filename  min_year  max_year  unique_years
0                01_District_wise_crimes_committed_IPC_2001_2012.csv      2001      2012            12
1                     01_District_wise_crimes_committed_IPC_2013.csv      2013      2013             1
2                     01_District_wise_crimes_committed_IPC_2014.csv      2014      2014             1
3      02_01_District_wise_crimes_committed_against_SC_2001_2012.csv      2001      2012            12
4           02_01_District_wise_crimes_committed_against_SC_2013.csv      2013      2013             1
5           02_01_District_wise_crimes_committed_against_SC_2014.csv      2014      2014             1
6         02_District_wise_crimes_committed_against_ST_2001_2012.csv      2001      2012            12
7              02_District_wise_crimes_committed_against_ST_2013.csv      2013      2013             1
8              02_District_wise_crimes_committed_against_ST_2014.csv      2014      2014             1
9   03_District_wise_crimes_committed_against_children_2001_2012.csv      2001      2012            12
10       03_District_wise_crimes_committed_against_children_2013.csv      2013      2013             1
11     42_District_wise_crimes_committed_against_women_2001_2012.csv      2001      2012            12
12          42_District_wise_crimes_committed_against_women_2013.csv      2013      2013             1
13          42_District_wise_crimes_committed_against_women_2014.csv      2014      2014             1

In [48]:
# ============================================================
# CELL 47 — GEOGRAPHIC QUALITY CHECK
# ============================================================

geo_records = []

for filename, df in normalized_district_data.items():

    state_missing = (
        df["STATE"].isna().sum()
        if "STATE" in df.columns
        else len(df)
    )

    district_missing = (
        df["DISTRICT"].isna().sum()
        if "DISTRICT" in df.columns
        else len(df)
    )

    year_missing = (
        df["YEAR"].isna().sum()
        if "YEAR" in df.columns
        else len(df)
    )

    geo_records.append({

        "filename":
            filename,

        "rows":
            len(df),

        "missing_state":
            state_missing,

        "missing_district":
            district_missing,

        "missing_year":
            year_missing,

        "state_missing_pct":
            round(
                100 * state_missing / len(df),
                2
            ),

        "district_missing_pct":
            round(
                100 * district_missing / len(df),
                2
            ),

        "year_missing_pct":
            round(
                100 * year_missing / len(df),
                2
            )
    })


geo_quality_df = pd.DataFrame(
    geo_records
)

display(
    geo_quality_df
)

                                                            filename  rows  missing_state  missing_district  missing_year  state_missing_pct  district_missing_pct  year_missing_pct
0                01_District_wise_crimes_committed_IPC_2001_2012.csv  9017              0                 0             0                0.0                   0.0               0.0
1                     01_District_wise_crimes_committed_IPC_2013.csv   823              0                 0             0                0.0                   0.0               0.0
2                     01_District_wise_crimes_committed_IPC_2014.csv   838              0                 0             0                0.0                   0.0               0.0
3      02_01_District_wise_crimes_committed_against_SC_2001_2012.csv  9018              0                 0             0                0.0                   0.0               0.0
4           02_01_District_wise_crimes_committed_against_SC_2013.csv   823              0                 0             0                0.0                   0.0               0.0
5           02_01_District_wise_crimes_committed_against_SC_2014.csv   837              0                 0             0                0.0                   0.0               0.0
6         02_District_wise_crimes_committed_against_ST_2001_2012.csv  9018              0                 0             0                0.0                   0.0               0.0
7              02_District_wise_crimes_committed_against_ST_2013.csv   823              0                 0             0                0.0                   0.0               0.0
8              02_District_wise_crimes_committed_against_ST_2014.csv   837              0                 0             0                0.0                   0.0               0.0
9   03_District_wise_crimes_committed_against_children_2001_2012.csv  9015              0                 0             0                0.0                   0.0               0.0
10       03_District_wise_crimes_committed_against_children_2013.csv   823              0                 0             0                0.0                   0.0               0.0
11     42_District_wise_crimes_committed_against_women_2001_2012.csv  9017              0                 0             0                0.0                   0.0               0.0
12          42_District_wise_crimes_committed_against_women_2013.csv   823              0                 0             0                0.0                   0.0               0.0
13          42_District_wise_crimes_committed_against_women_2014.csv   837              0                 0             0                0.0                   0.0               0.0

In [49]:
# ============================================================
# CELL 48 — DUPLICATE GEOGRAPHIC-TEMPORAL KEYS
# ============================================================

duplicate_records = []

for filename, df in normalized_district_data.items():

    key_columns = [
        "STATE",
        "DISTRICT",
        "YEAR"
    ]

    existing_keys = [
        c for c in key_columns
        if c in df.columns
    ]

    duplicate_count = (
        df.duplicated(
            subset=existing_keys,
            keep=False
        )
        .sum()
    )

    duplicate_records.append({

        "filename":
            filename,

        "key_columns":
            ", ".join(existing_keys),

        "duplicate_rows":
            int(duplicate_count),

        "duplicate_pct":
            round(
                100 * duplicate_count / len(df),
                2
            )
    })


duplicate_key_df = pd.DataFrame(
    duplicate_records
)

display(
    duplicate_key_df
)

                                                            filename            key_columns  duplicate_rows  duplicate_pct
0                01_District_wise_crimes_committed_IPC_2001_2012.csv  STATE, DISTRICT, YEAR               2           0.02
1                     01_District_wise_crimes_committed_IPC_2013.csv  STATE, DISTRICT, YEAR               0           0.00
2                     01_District_wise_crimes_committed_IPC_2014.csv  STATE, DISTRICT, YEAR               0           0.00
3      02_01_District_wise_crimes_committed_against_SC_2001_2012.csv  STATE, DISTRICT, YEAR               4           0.04
4           02_01_District_wise_crimes_committed_against_SC_2013.csv  STATE, DISTRICT, YEAR               0           0.00
5           02_01_District_wise_crimes_committed_against_SC_2014.csv  STATE, DISTRICT, YEAR               0           0.00
6         02_District_wise_crimes_committed_against_ST_2001_2012.csv  STATE, DISTRICT, YEAR               4           0.04
7              02_District_wise_crimes_committed_against_ST_2013.csv  STATE, DISTRICT, YEAR               0           0.00
8              02_District_wise_crimes_committed_against_ST_2014.csv  STATE, DISTRICT, YEAR               0           0.00
9   03_District_wise_crimes_committed_against_children_2001_2012.csv  STATE, DISTRICT, YEAR               2           0.02
10       03_District_wise_crimes_committed_against_children_2013.csv  STATE, DISTRICT, YEAR               0           0.00
11     42_District_wise_crimes_committed_against_women_2001_2012.csv  STATE, DISTRICT, YEAR               2           0.02
12          42_District_wise_crimes_committed_against_women_2013.csv  STATE, DISTRICT, YEAR               0           0.00
13          42_District_wise_crimes_committed_against_women_2014.csv  STATE, DISTRICT, YEAR               0           0.00

In [50]:
# ============================================================
# CELL 49 — SAMPLE EACH CRIME GROUP
# ============================================================

for group in sorted(
    group_summary_df[
        "crime_group"
    ].unique()
):

    matching = [
        filename
        for filename, df
        in normalized_district_data.items()
        if df["CRIME_GROUP"].iloc[0] == group
    ]

    if not matching:
        continue

    filename = matching[0]

    print("\n" + "=" * 70)
    print(f"GROUP: {group}")
    print(f"FILE : {filename}")
    print("=" * 70)

    display(
        normalized_district_data[
            filename
        ].head(5)
    )

======================================================================
GROUP: CHILDREN
FILE : 03_District_wise_crimes_committed_against_children_2001_2012.csv
======================================================================

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping and Abduction,Foeticide,Abetment of suicide,Exposure and abandonment,Procuration of minor girls,Buying of girls for prostitution,Selling of girls for prostitution,Prohibition of child marriage act,Other Crimes,Total,CRIME_GROUP,SOURCE_FILE
0,ANDHRA PRADESH,ADILABAD,2001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,CHILDREN,03_District_wise_crimes_committed_against_children_2001_2012.csv
1,ANDHRA PRADESH,ANANTAPUR,2001,19.0,12.0,29.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,66,CHILDREN,03_District_wise_crimes_committed_against_children_2001_2012.csv
2,ANDHRA PRADESH,CHITTOOR,2001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,CHILDREN,03_District_wise_crimes_committed_against_children_2001_2012.csv
3,ANDHRA PRADESH,CUDDAPAH,2001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,CHILDREN,03_District_wise_crimes_committed_against_children_2001_2012.csv
4,ANDHRA PRADESH,EAST GODAVARI,2001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,CHILDREN,03_District_wise_crimes_committed_against_children_2001_2012.csv

======================================================================
GROUP: IPC
FILE : 01_District_wise_crimes_committed_IPC_2001_2012.csv
======================================================================

,STATE,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS,KIDNAPPING AND ABDUCTION OF OTHERS,DACOITY,PREPARATION AND ASSEMBLY FOR DACOITY,ROBBERY,BURGLARY,THEFT,AUTO THEFT,OTHER THEFT,RIOTS,CRIMINAL BREACH OF TRUST,CHEATING,COUNTERFIETING,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES,CRIME_GROUP,SOURCE_FILE
0,ANDHRA PRADESH,ADILABAD,2001,101,60,17,50,0,50,46,30,16,9,0,41,198,199,22,177,78,16,104,1,30,1131,16,149,34,175,0,181,1518,4154,IPC,01_District_wise_crimes_committed_IPC_2001_2012.csv
1,ANDHRA PRADESH,ANANTAPUR,2001,151,125,1,23,0,23,53,30,23,8,0,16,191,366,57,309,168,11,65,8,69,1543,7,118,24,154,0,270,754,4125,IPC,01_District_wise_crimes_committed_IPC_2001_2012.csv
2,ANDHRA PRADESH,CHITTOOR,2001,101,57,2,27,0,27,59,34,25,4,0,14,237,723,164,559,156,33,209,9,38,2088,14,112,83,186,0,404,1262,5818,IPC,01_District_wise_crimes_committed_IPC_2001_2012.csv
3,ANDHRA PRADESH,CUDDAPAH,2001,80,53,1,20,0,20,25,20,5,1,0,4,98,173,36,137,164,12,37,2,23,795,17,126,38,57,0,233,1181,3140,IPC,01_District_wise_crimes_committed_IPC_2001_2012.csv
4,ANDHRA PRADESH,EAST GODAVARI,2001,82,67,1,23,0,23,49,26,23,4,0,25,437,1021,150,871,70,50,220,3,41,1244,12,109,58,247,0,431,2313,6507,IPC,01_District_wise_crimes_committed_IPC_2001_2012.csv

======================================================================
GROUP: SC
FILE : 02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
======================================================================

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping and Abduction,Dacoity,Robbery,Arson,Hurt,Prevention of atrocities (POA) Act,Protection of Civil Rights (PCR) Act,Other Crimes Against SCs,CRIME_GROUP,SOURCE_FILE
0,ANDHRA PRADESH,ADILABAD,2001,0,1,4,0,0,0,3,0,15,32,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
1,ANDHRA PRADESH,ANANTAPUR,2001,0,4,0,0,0,0,49,21,0,53,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
2,ANDHRA PRADESH,CHITTOOR,2001,3,3,0,0,0,0,38,36,0,34,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
3,ANDHRA PRADESH,CUDDAPAH,2001,0,3,0,0,0,0,20,52,0,25,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
4,ANDHRA PRADESH,EAST GODAVARI,2001,1,3,0,0,0,0,3,12,63,7,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv

======================================================================
GROUP: ST
FILE : 02_District_wise_crimes_committed_against_ST_2001_2012.csv
======================================================================

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping Abduction,Dacoity,Robbery,Arson,Hurt,Protection of Civil Rights (PCR) Act,Prevention of atrocities (POA) Act,Other Crimes Against STs,CRIME_GROUP,SOURCE_FILE
0,ANDHRA PRADESH,ADILABAD,2001,0,1,2,0,0,0,2,0,0,13,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
1,ANDHRA PRADESH,ANANTAPUR,2001,0,0,0,0,0,0,7,0,1,6,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
2,ANDHRA PRADESH,CHITTOOR,2001,0,0,0,0,0,0,2,0,0,0,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
3,ANDHRA PRADESH,CUDDAPAH,2001,0,0,0,0,0,0,2,0,2,0,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
4,ANDHRA PRADESH,EAST GODAVARI,2001,0,0,0,0,0,0,0,0,0,14,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv

======================================================================
GROUP: WOMEN
FILE : 42_District_wise_crimes_committed_against_women_2001_2012.csv
======================================================================

,STATE,DISTRICT,YEAR,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls,CRIME_GROUP,SOURCE_FILE
0,ANDHRA PRADESH,ADILABAD,2001,50,30,16,149,34,175,0,WOMEN,42_District_wise_crimes_committed_against_women_2001_2012.csv
1,ANDHRA PRADESH,ANANTAPUR,2001,23,30,7,118,24,154,0,WOMEN,42_District_wise_crimes_committed_against_women_2001_2012.csv
2,ANDHRA PRADESH,CHITTOOR,2001,27,34,14,112,83,186,0,WOMEN,42_District_wise_crimes_committed_against_women_2001_2012.csv
3,ANDHRA PRADESH,CUDDAPAH,2001,20,20,17,126,38,57,0,WOMEN,42_District_wise_crimes_committed_against_women_2001_2012.csv
4,ANDHRA PRADESH,EAST GODAVARI,2001,23,26,12,109,58,247,0,WOMEN,42_District_wise_crimes_committed_against_women_2001_2012.csv

In [51]:
# ============================================================
# CELL 50 — SAVE NORMALIZED DISTRICT DATA
# ============================================================

normalized_dir = (
    PROCESSED_DATA_DIR /
    "district_normalized"
)

normalized_dir.mkdir(
    parents=True,
    exist_ok=True
)

for filename, df in normalized_district_data.items():

    output_path = (
        normalized_dir /
        filename
    )

    df.to_csv(
        output_path,
        index=False,
        encoding="utf-8-sig"
    )

print("=" * 70)
print("NORMALIZED DISTRICT DATA SAVED")
print("=" * 70)

print(
    normalized_dir.resolve()
)

======================================================================
NORMALIZED DISTRICT DATA SAVED
======================================================================
D:\Major_Project\Crime_Analysis\data\processed\district_normalized

In [52]:
# ============================================================
# CELL 51 — INVESTIGATE DUPLICATE STATE-DISTRICT-YEAR KEYS
# ============================================================

print("=" * 80)
print("DUPLICATE KEY INVESTIGATION")
print("=" * 80)

duplicate_details = {}

for filename, df in normalized_district_data.items():

    key_columns = [
        "STATE",
        "DISTRICT",
        "YEAR"
    ]

    duplicate_mask = df.duplicated(
        subset=key_columns,
        keep=False
    )

    duplicate_rows = df[
        duplicate_mask
    ].copy()

    if len(duplicate_rows) == 0:
        continue

    duplicate_details[filename] = duplicate_rows

    print("\n" + "-" * 80)
    print(f"FILE: {filename}")
    print("-" * 80)

    print(
        f"Duplicate rows: {len(duplicate_rows)}"
    )

    # Display only keys first
    display(
        duplicate_rows[
            key_columns
        ].sort_values(
            key_columns
        )
    )

================================================================================
DUPLICATE KEY INVESTIGATION
================================================================================

--------------------------------------------------------------------------------
FILE: 01_District_wise_crimes_committed_IPC_2001_2012.csv
--------------------------------------------------------------------------------
Duplicate rows: 2

                STATE  DISTRICT  YEAR
6880  JAMMU & KASHMIR  RAILWAYS  2010
6881  JAMMU & KASHMIR  RAILWAYS  2010

--------------------------------------------------------------------------------
FILE: 02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
--------------------------------------------------------------------------------
Duplicate rows: 4

                STATE  DISTRICT  YEAR
204   JAMMU & KASHMIR  ANANTNAG  2001
205   JAMMU & KASHMIR  ANANTNAG  2001
3343         NAGALAND     TOTAL  2005
3344         NAGALAND     TOTAL  2005

--------------------------------------------------------------------------------
FILE: 02_District_wise_crimes_committed_against_ST_2001_2012.csv
--------------------------------------------------------------------------------
Duplicate rows: 4

                STATE  DISTRICT  YEAR
204   JAMMU & KASHMIR  ANANTNAG  2001
205   JAMMU & KASHMIR  ANANTNAG  2001
3343         NAGALAND     TOTAL  2005
3344         NAGALAND     TOTAL  2005

--------------------------------------------------------------------------------
FILE: 03_District_wise_crimes_committed_against_children_2001_2012.csv
--------------------------------------------------------------------------------
Duplicate rows: 2

         STATE DISTRICT  YEAR
3341  NAGALAND    TOTAL  2005
3342  NAGALAND    TOTAL  2005

--------------------------------------------------------------------------------
FILE: 42_District_wise_crimes_committed_against_women_2001_2012.csv
--------------------------------------------------------------------------------
Duplicate rows: 2

                STATE  DISTRICT  YEAR
6880  JAMMU & KASHMIR  RAILWAYS  2010
6881  JAMMU & KASHMIR  RAILWAYS  2010

In [53]:
# ============================================================
# CELL 52 — COMPLETE DUPLICATE RECORD INSPECTION
# ============================================================

for filename, duplicate_rows in duplicate_details.items():

    print("\n" + "=" * 90)
    print(f"DUPLICATE RECORDS: {filename}")
    print("=" * 90)

    display(
        duplicate_rows
    )

==========================================================================================
DUPLICATE RECORDS: 01_District_wise_crimes_committed_IPC_2001_2012.csv
==========================================================================================

,STATE,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS,KIDNAPPING AND ABDUCTION OF OTHERS,DACOITY,PREPARATION AND ASSEMBLY FOR DACOITY,ROBBERY,BURGLARY,THEFT,AUTO THEFT,OTHER THEFT,RIOTS,CRIMINAL BREACH OF TRUST,CHEATING,COUNTERFIETING,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES,CRIME_GROUP,SOURCE_FILE
6880,JAMMU & KASHMIR,RAILWAYS,2010,0,0,0,0,0,0,1,0,1,0,0,0,1,12,1,11,16,1,0,0,0,0,0,0,0,0,0,0,5,36,IPC,01_District_wise_crimes_committed_IPC_2001_2012.csv
6881,JAMMU & KASHMIR,RAILWAYS,2010,1,0,1,1,0,1,0,0,0,0,0,0,0,8,1,7,0,0,0,0,0,0,0,0,0,0,0,0,10,21,IPC,01_District_wise_crimes_committed_IPC_2001_2012.csv

==========================================================================================
DUPLICATE RECORDS: 02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
==========================================================================================

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping and Abduction,Dacoity,Robbery,Arson,Hurt,Prevention of atrocities (POA) Act,Protection of Civil Rights (PCR) Act,Other Crimes Against SCs,CRIME_GROUP,SOURCE_FILE
204,JAMMU & KASHMIR,ANANTNAG,2001,0,0,0,0,0,0,0,0,0,0,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
205,JAMMU & KASHMIR,ANANTNAG,2001,0,0,0,0,0,0,0,0,0,0,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
3343,NAGALAND,TOTAL,2005,0,0,0,0,0,0,0,0,0,0,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
3344,NAGALAND,TOTAL,2005,0,0,0,0,0,0,0,0,0,0,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv

==========================================================================================
DUPLICATE RECORDS: 02_District_wise_crimes_committed_against_ST_2001_2012.csv
==========================================================================================

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping Abduction,Dacoity,Robbery,Arson,Hurt,Protection of Civil Rights (PCR) Act,Prevention of atrocities (POA) Act,Other Crimes Against STs,CRIME_GROUP,SOURCE_FILE
204,JAMMU & KASHMIR,ANANTNAG,2001,0,0,0,0,0,0,0,0,0,0,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
205,JAMMU & KASHMIR,ANANTNAG,2001,0,0,0,0,0,0,0,0,0,0,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
3343,NAGALAND,TOTAL,2005,0,0,0,0,0,0,0,0,0,0,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
3344,NAGALAND,TOTAL,2005,0,0,0,0,0,0,0,0,0,0,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv

==========================================================================================
DUPLICATE RECORDS: 03_District_wise_crimes_committed_against_children_2001_2012.csv
==========================================================================================

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping and Abduction,Foeticide,Abetment of suicide,Exposure and abandonment,Procuration of minor girls,Buying of girls for prostitution,Selling of girls for prostitution,Prohibition of child marriage act,Other Crimes,Total,CRIME_GROUP,SOURCE_FILE
3341,NAGALAND,TOTAL,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,CHILDREN,03_District_wise_crimes_committed_against_children_2001_2012.csv
3342,NAGALAND,TOTAL,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,CHILDREN,03_District_wise_crimes_committed_against_children_2001_2012.csv

==========================================================================================
DUPLICATE RECORDS: 42_District_wise_crimes_committed_against_women_2001_2012.csv
==========================================================================================

,STATE,DISTRICT,YEAR,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls,CRIME_GROUP,SOURCE_FILE
6880,JAMMU & KASHMIR,RAILWAYS,2010,0,0,0,0,0,0,0,WOMEN,42_District_wise_crimes_committed_against_women_2001_2012.csv
6881,JAMMU & KASHMIR,RAILWAYS,2010,1,0,0,0,0,0,0,WOMEN,42_District_wise_crimes_committed_against_women_2001_2012.csv

In [54]:
# ============================================================
# CELL 53 — EXACT DUPLICATE CHECK
# ============================================================

exact_duplicate_summary = []

for filename, df in normalized_district_data.items():

    duplicate_mask = df.duplicated(
        keep=False
    )

    exact_duplicates = df[
        duplicate_mask
    ].duplicated(
        keep="first"
    ).sum()

    exact_duplicate_summary.append({

        "filename":
            filename,

        "duplicate_rows":
            int(
                df.duplicated(
                    subset=[
                        "STATE",
                        "DISTRICT",
                        "YEAR"
                    ],
                    keep=False
                ).sum()
            ),

        "exact_duplicate_rows":
            int(exact_duplicates)
    })


exact_duplicate_summary_df = pd.DataFrame(
    exact_duplicate_summary
)

display(
    exact_duplicate_summary_df[
        exact_duplicate_summary_df[
            "duplicate_rows"
        ] > 0
    ]
)

                                                            filename  duplicate_rows  exact_duplicate_rows
0                01_District_wise_crimes_committed_IPC_2001_2012.csv               2                     0
3      02_01_District_wise_crimes_committed_against_SC_2001_2012.csv               4                     2
6         02_District_wise_crimes_committed_against_ST_2001_2012.csv               4                     2
9   03_District_wise_crimes_committed_against_children_2001_2012.csv               2                     1
11     42_District_wise_crimes_committed_against_women_2001_2012.csv               2                     0

In [55]:
# ============================================================
# CELL 54 — DIFFERENCE ANALYSIS FOR DUPLICATE KEYS
# ============================================================

for filename, duplicate_rows in duplicate_details.items():

    print("\n" + "=" * 90)
    print(f"DUPLICATE DIFFERENCE ANALYSIS: {filename}")
    print("=" * 90)

    key_columns = [
        "STATE",
        "DISTRICT",
        "YEAR"
    ]

    non_key_columns = [
        c for c in duplicate_rows.columns
        if c not in key_columns
    ]

    # Group duplicate records by key
    for key, group in duplicate_rows.groupby(
        key_columns,
        dropna=False
    ):

        print("\nKEY:")
        print(key)

        differing_columns = []

        for column in non_key_columns:

            unique_values = (
                group[column]
                .astype("string")
                .fillna("<NA>")
                .unique()
            )

            if len(unique_values) > 1:
                differing_columns.append(
                    column
                )

        if differing_columns:

            print(
                "\nColumns with different values:"
            )

            for column in differing_columns:

                print(
                    f"  {column}: "
                    f"{group[column].tolist()}"
                )

        else:

            print(
                "\n✓ All non-key values are identical."
            )

==========================================================================================
DUPLICATE DIFFERENCE ANALYSIS: 01_District_wise_crimes_committed_IPC_2001_2012.csv
==========================================================================================

KEY:
('JAMMU & KASHMIR', 'RAILWAYS', 2010)

Columns with different values:
  MURDER: [0, 1]
  CULPABLE HOMICIDE NOT AMOUNTING TO MURDER: [0, 1]
  RAPE: [0, 1]
  OTHER RAPE: [0, 1]
  KIDNAPPING & ABDUCTION: [1, 0]
  KIDNAPPING AND ABDUCTION OF OTHERS: [1, 0]
  BURGLARY: [1, 0]
  THEFT: [12, 8]
  OTHER THEFT: [11, 7]
  RIOTS: [16, 0]
  CRIMINAL BREACH OF TRUST: [1, 0]
  OTHER IPC CRIMES: [5, 10]
  TOTAL IPC CRIMES: [36, 21]

==========================================================================================
DUPLICATE DIFFERENCE ANALYSIS: 02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
==========================================================================================

KEY:
('JAMMU & KASHMIR', 'ANANTNAG', 2001)

✓ All non-key values are identical.

KEY:
('NAGALAND', 'TOTAL', 2005)

✓ All non-key values are identical.

==========================================================================================
DUPLICATE DIFFERENCE ANALYSIS: 02_District_wise_crimes_committed_against_ST_2001_2012.csv
==========================================================================================

KEY:
('JAMMU & KASHMIR', 'ANANTNAG', 2001)

✓ All non-key values are identical.

KEY:
('NAGALAND', 'TOTAL', 2005)

✓ All non-key values are identical.

==========================================================================================
DUPLICATE DIFFERENCE ANALYSIS: 03_District_wise_crimes_committed_against_children_2001_2012.csv
==========================================================================================

KEY:
('NAGALAND', 'TOTAL', 2005)

✓ All non-key values are identical.

==========================================================================================
DUPLICATE DIFFERENCE ANALYSIS: 42_District_wise_crimes_committed_against_women_2001_2012.csv
==========================================================================================

KEY:
('JAMMU & KASHMIR', 'RAILWAYS', 2010)

Columns with different values:
  Rape: [0, 1]

In [56]:
# ============================================================
# CELL 55 — IDENTIFY THE HIDDEN DIMENSION IN DUPLICATES
# ============================================================

print("=" * 80)
print("HIDDEN-DIMENSION INVESTIGATION")
print("=" * 80)

for filename, duplicate_rows in duplicate_details.items():

    print("\n" + "=" * 90)
    print(f"FILE: {filename}")
    print("=" * 90)

    key_columns = [
        "STATE",
        "DISTRICT",
        "YEAR"
    ]

    # --------------------------------------------------------
    # For every duplicate key, inspect ALL columns that might
    # distinguish the records.
    # --------------------------------------------------------

    for key, group in duplicate_rows.groupby(
        key_columns,
        dropna=False
    ):

        if len(group) <= 1:
            continue

        print("\n" + "-" * 80)
        print("DUPLICATE KEY:")
        print(key)
        print("-" * 80)

        # Find columns with different values
        differing_columns = []

        for column in group.columns:

            if column in key_columns:
                continue

            unique_values = (
                group[column]
                .astype("string")
                .fillna("<NA>")
                .unique()
            )

            if len(unique_values) > 1:
                differing_columns.append(
                    column
                )

        if differing_columns:

            print(
                "\nColumns distinguishing the records:"
            )

            for column in differing_columns:

                print(
                    f"\n{column}:"
                )

                print(
                    group[
                        key_columns + [column]
                    ].to_string(
                        index=False
                    )
                )

        else:

            print(
                "\n⚠ No differing non-key columns found."
            )

================================================================================
HIDDEN-DIMENSION INVESTIGATION
================================================================================

==========================================================================================
FILE: 01_District_wise_crimes_committed_IPC_2001_2012.csv
==========================================================================================

--------------------------------------------------------------------------------
DUPLICATE KEY:
('JAMMU & KASHMIR', 'RAILWAYS', 2010)
--------------------------------------------------------------------------------

Columns distinguishing the records:

MURDER:
          STATE DISTRICT  YEAR  MURDER
JAMMU & KASHMIR RAILWAYS  2010       0
JAMMU & KASHMIR RAILWAYS  2010       1

CULPABLE HOMICIDE NOT AMOUNTING TO MURDER:
          STATE DISTRICT  YEAR  CULPABLE HOMICIDE NOT AMOUNTING TO MURDER
JAMMU & KASHMIR RAILWAYS  2010                                          0
JAMMU & KASHMIR RAILWAYS  2010                                          1

RAPE:
          STATE DISTRICT  YEAR  RAPE
JAMMU & KASHMIR RAILWAYS  2010     0
JAMMU & KASHMIR RAILWAYS  2010     1

OTHER RAPE:
          STATE DISTRICT  YEAR  OTHER RAPE
JAMMU & KASHMIR RAILWAYS  2010           0
JAMMU & KASHMIR RAILWAYS  2010           1

KIDNAPPING & ABDUCTION:
          STATE DISTRICT  YEAR  KIDNAPPING & ABDUCTION
JAMMU & KASHMIR RAILWAYS  2010                       1
JAMMU & KASHMIR RAILWAYS  2010                       0

KIDNAPPING AND ABDUCTION OF OTHERS:
          STATE DISTRICT  YEAR  KIDNAPPING AND ABDUCTION OF OTHERS
JAMMU & KASHMIR RAILWAYS  2010                                   1
JAMMU & KASHMIR RAILWAYS  2010                                   0

BURGLARY:
          STATE DISTRICT  YEAR  BURGLARY
JAMMU & KASHMIR RAILWAYS  2010         1
JAMMU & KASHMIR RAILWAYS  2010         0

THEFT:
          STATE DISTRICT  YEAR  THEFT
JAMMU & KASHMIR RAILWAYS  2010     12
JAMMU & KASHMIR RAILWAYS  2010      8

OTHER THEFT:
          STATE DISTRICT  YEAR  OTHER THEFT
JAMMU & KASHMIR RAILWAYS  2010           11
JAMMU & KASHMIR RAILWAYS  2010            7

RIOTS:
          STATE DISTRICT  YEAR  RIOTS
JAMMU & KASHMIR RAILWAYS  2010     16
JAMMU & KASHMIR RAILWAYS  2010      0

CRIMINAL BREACH OF TRUST:
          STATE DISTRICT  YEAR  CRIMINAL BREACH OF TRUST
JAMMU & KASHMIR RAILWAYS  2010                         1
JAMMU & KASHMIR RAILWAYS  2010                         0

OTHER IPC CRIMES:
          STATE DISTRICT  YEAR  OTHER IPC CRIMES
JAMMU & KASHMIR RAILWAYS  2010                 5
JAMMU & KASHMIR RAILWAYS  2010                10

TOTAL IPC CRIMES:
          STATE DISTRICT  YEAR  TOTAL IPC CRIMES
JAMMU & KASHMIR RAILWAYS  2010                36
JAMMU & KASHMIR RAILWAYS  2010                21

==========================================================================================
FILE: 02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
==========================================================================================

--------------------------------------------------------------------------------
DUPLICATE KEY:
('JAMMU & KASHMIR', 'ANANTNAG', 2001)
--------------------------------------------------------------------------------

⚠ No differing non-key columns found.

--------------------------------------------------------------------------------
DUPLICATE KEY:
('NAGALAND', 'TOTAL', 2005)
--------------------------------------------------------------------------------

⚠ No differing non-key columns found.

==========================================================================================
FILE: 02_District_wise_crimes_committed_against_ST_2001_2012.csv
==========================================================================================

--------------------------------------------------------------------------------
DUPLICATE KEY:
('JAMMU & KASHMIR', 'ANANTNAG', 2001)
--------------------------------------------------------------------------------

⚠ No differing non-key columns found.

--------------------------------------------------------------------------------
DUPLICATE KEY:
('NAGALAND', 'TOTAL', 2005)
--------------------------------------------------------------------------------

⚠ No differing non-key columns found.

==========================================================================================
FILE: 03_District_wise_crimes_committed_against_children_2001_2012.csv
==========================================================================================

--------------------------------------------------------------------------------
DUPLICATE KEY:
('NAGALAND', 'TOTAL', 2005)
--------------------------------------------------------------------------------

⚠ No differing non-key columns found.

==========================================================================================
FILE: 42_District_wise_crimes_committed_against_women_2001_2012.csv
==========================================================================================

--------------------------------------------------------------------------------
DUPLICATE KEY:
('JAMMU & KASHMIR', 'RAILWAYS', 2010)
--------------------------------------------------------------------------------

Columns distinguishing the records:

Rape:
          STATE DISTRICT  YEAR  Rape
JAMMU & KASHMIR RAILWAYS  2010     0
JAMMU & KASHMIR RAILWAYS  2010     1

In [57]:
# ============================================================
# CELL 56 — CATEGORICAL HIDDEN-DIMENSION CHECK
# ============================================================

for filename, duplicate_rows in duplicate_details.items():

    print("\n" + "=" * 90)
    print(f"CATEGORICAL ANALYSIS: {filename}")
    print("=" * 90)

    key_columns = [
        "STATE",
        "DISTRICT",
        "YEAR"
    ]

    categorical_columns = [
        column
        for column in duplicate_rows.columns
        if column not in key_columns
        and (
            duplicate_rows[column].dtype == "object"
            or str(
                duplicate_rows[column].dtype
            ).startswith("string")
        )
    ]

    if categorical_columns:

        print(
            "\nCategorical columns found:"
        )

        for column in categorical_columns:

            print(
                f"\n{column}:"
            )

            print(
                duplicate_rows[
                    column
                ].value_counts(
                    dropna=False
                )
            )

    else:

        print(
            "\nNo categorical columns detected."
        )

==========================================================================================
CATEGORICAL ANALYSIS: 01_District_wise_crimes_committed_IPC_2001_2012.csv
==========================================================================================

Categorical columns found:

CRIME_GROUP:
CRIME_GROUP
IPC    2
Name: count, dtype: int64

SOURCE_FILE:
SOURCE_FILE
01_District_wise_crimes_committed_IPC_2001_2012.csv    2
Name: count, dtype: int64

==========================================================================================
CATEGORICAL ANALYSIS: 02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
==========================================================================================

Categorical columns found:

CRIME_GROUP:
CRIME_GROUP
SC    4
Name: count, dtype: int64

SOURCE_FILE:
SOURCE_FILE
02_01_District_wise_crimes_committed_against_SC_2001_2012.csv    4
Name: count, dtype: int64

==========================================================================================
CATEGORICAL ANALYSIS: 02_District_wise_crimes_committed_against_ST_2001_2012.csv
==========================================================================================

Categorical columns found:

CRIME_GROUP:
CRIME_GROUP
ST    4
Name: count, dtype: int64

SOURCE_FILE:
SOURCE_FILE
02_District_wise_crimes_committed_against_ST_2001_2012.csv    4
Name: count, dtype: int64

==========================================================================================
CATEGORICAL ANALYSIS: 03_District_wise_crimes_committed_against_children_2001_2012.csv
==========================================================================================

Categorical columns found:

CRIME_GROUP:
CRIME_GROUP
CHILDREN    2
Name: count, dtype: int64

SOURCE_FILE:
SOURCE_FILE
03_District_wise_crimes_committed_against_children_2001_2012.csv    2
Name: count, dtype: int64

==========================================================================================
CATEGORICAL ANALYSIS: 42_District_wise_crimes_committed_against_women_2001_2012.csv
==========================================================================================

Categorical columns found:

CRIME_GROUP:
CRIME_GROUP
WOMEN    2
Name: count, dtype: int64

SOURCE_FILE:
SOURCE_FILE
42_District_wise_crimes_committed_against_women_2001_2012.csv    2
Name: count, dtype: int64

In [58]:
# ============================================================
# CELL 57 — INVESTIGATE TOTAL ROWS
# ============================================================

for filename, df in normalized_district_data.items():

    if "DISTRICT" not in df.columns:
        continue

    total_mask = (
        df["DISTRICT"]
        .astype("string")
        .str.strip()
        .str.upper()
        .eq("TOTAL")
    )

    total_rows = df[
        total_mask
    ].copy()

    if len(total_rows) == 0:
        continue

    print("\n" + "=" * 80)
    print(f"TOTAL ROWS: {filename}")
    print("=" * 80)

    print(
        f"Number of TOTAL rows: "
        f"{len(total_rows)}"
    )

    display(
        total_rows[
            [
                "STATE",
                "DISTRICT",
                "YEAR"
            ]
        ].head(30)
    )

================================================================================
TOTAL ROWS: 01_District_wise_crimes_committed_IPC_2001_2012.csv
================================================================================
Number of TOTAL rows: 408

                 STATE DISTRICT  YEAR
28      ANDHRA PRADESH    TOTAL  2001
42   ARUNACHAL PRADESH    TOTAL  2001
70               ASSAM    TOTAL  2001
115              BIHAR    TOTAL  2001
135       CHHATTISGARH    TOTAL  2001
138                GOA    TOTAL  2001
169            GUJARAT    TOTAL  2001
190            HARYANA    TOTAL  2001
204   HIMACHAL PRADESH    TOTAL  2001
228    JAMMU & KASHMIR    TOTAL  2001
253          JHARKHAND    TOTAL  2001
285          KARNATAKA    TOTAL  2001
302             KERALA    TOTAL  2001
351     MADHYA PRADESH    TOTAL  2001
397        MAHARASHTRA    TOTAL  2001
407            MANIPUR    TOTAL  2001
415          MEGHALAYA    TOTAL  2001
424            MIZORAM    TOTAL  2001
435           NAGALAND    TOTAL  2001
470             ODISHA    TOTAL  2001
495             PUNJAB    TOTAL  2001
529          RAJASTHAN    TOTAL  2001
534             SIKKIM    TOTAL  2001
573         TAMIL NADU    TOTAL  2001
578            TRIPURA    TOTAL  2001
650      UTTAR PRADESH    TOTAL  2001
664        UTTARAKHAND    TOTAL  2001
688        WEST BENGAL    TOTAL  2001
691      A & N ISLANDS    TOTAL  2001
693         CHANDIGARH    TOTAL  2001

================================================================================
TOTAL ROWS: 01_District_wise_crimes_committed_IPC_2014.csv
================================================================================
Number of TOTAL rows: 36

                 STATE DISTRICT  YEAR
20      Andhra Pradesh    Total  2014
40   Arunachal Pradesh    Total  2014
69               Assam    Total  2014
116              Bihar    Total  2014
145       Chhattisgarh    Total  2014
149                Goa    Total  2014
191            Gujarat    Total  2014
216            Haryana    Total  2014
232   Himachal Pradesh    Total  2014
263    Jammu & Kashmir    Total  2014
290          Jharkhand    Total  2014
327          Karnataka    Total  2014
349             Kerala    Total  2014
405     Madhya Pradesh    Total  2014
452        Maharashtra    Total  2014
463            Manipur    Total  2014
475          Meghalaya    Total  2014
485            Mizoram    Total  2014
497           Nagaland    Total  2014
534             Odisha    Total  2014
563             Punjab    Total  2014
606          Rajasthan    Total  2014
612             Sikkim    Total  2014
655         Tamil Nadu    Total  2014
669          Telangana    Total  2014
679            Tripura    Total  2014
756      Uttar Pradesh    Total  2014
770        Uttarakhand    Total  2014
801        West Bengal    Total  2014
805        A&N Islands    Total  2014

================================================================================
TOTAL ROWS: 02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
================================================================================
Number of TOTAL rows: 421

                 STATE DISTRICT  YEAR
28      ANDHRA PRADESH    TOTAL  2001
42   ARUNACHAL PRADESH    TOTAL  2001
70               ASSAM    TOTAL  2001
115              BIHAR    TOTAL  2001
134       CHHATTISGARH    TOTAL  2001
137                GOA    TOTAL  2001
168            GUJARAT    TOTAL  2001
189            HARYANA    TOTAL  2001
203   HIMACHAL PRADESH    TOTAL  2001
228    JAMMU & KASHMIR    TOTAL  2001
253          JHARKHAND    TOTAL  2001
285          KARNATAKA    TOTAL  2001
302             KERALA    TOTAL  2001
351     MADHYA PRADESH    TOTAL  2001
397        MAHARASHTRA    TOTAL  2001
407            MANIPUR    TOTAL  2001
415          MEGHALAYA    TOTAL  2001
424            MIZORAM    TOTAL  2001
435           NAGALAND    TOTAL  2001
470             ODISHA    TOTAL  2001
495             PUNJAB    TOTAL  2001
529          RAJASTHAN    TOTAL  2001
534             SIKKIM    TOTAL  2001
573         TAMIL NADU    TOTAL  2001
578            TRIPURA    TOTAL  2001
650      UTTAR PRADESH    TOTAL  2001
664        UTTARAKHAND    TOTAL  2001
688        WEST BENGAL    TOTAL  2001
691      A & N ISLANDS    TOTAL  2001
693         CHANDIGARH    TOTAL  2001

================================================================================
TOTAL ROWS: 02_01_District_wise_crimes_committed_against_SC_2013.csv
================================================================================
Number of TOTAL rows: 35

                 STATE DISTRICT  YEAR
33      Andhra Pradesh    TOTAL  2013
52   Arunachal Pradesh    TOTAL  2013
86               Assam    TOTAL  2013
131              Bihar    TOTAL  2013
160       Chhattisgarh    TOTAL  2013
163                Goa    TOTAL  2013
198            Gujarat    TOTAL  2013
223            Haryana    TOTAL  2013
239   Himachal Pradesh    TOTAL  2013
270    Jammu & Kashmir    TOTAL  2013
297          Jharkhand    TOTAL  2013
333          Karnataka    TOTAL  2013
354             Kerala    TOTAL  2013
409     Madhya Pradesh    TOTAL  2013
455        Maharashtra    TOTAL  2013
466            Manipur    TOTAL  2013
478          Meghalaya    TOTAL  2013
489            Mizoram    TOTAL  2013
501           Nagaland    TOTAL  2013
538             Odisha    TOTAL  2013
567             Punjab    TOTAL  2013
611          Rajasthan    TOTAL  2013
616             Sikkim    TOTAL  2013
656         Tamil Nadu    TOTAL  2013
666            Tripura    TOTAL  2013
743      Uttar Pradesh    TOTAL  2013
757        Uttarakhand    TOTAL  2013
787        West Bengal    TOTAL  2013
791        A&N Islands    TOTAL  2013
793         Chandigarh    TOTAL  2013

================================================================================
TOTAL ROWS: 02_01_District_wise_crimes_committed_against_SC_2014.csv
================================================================================
Number of TOTAL rows: 36

                 STATE DISTRICT  YEAR
20      Andhra Pradesh    Total  2014
40   Arunachal Pradesh    Total  2014
68               Assam    Total  2014
115              Bihar    Total  2014
144       Chhattisgarh    Total  2014
148                Goa    Total  2014
190            Gujarat    Total  2014
215            Haryana    Total  2014
231   Himachal Pradesh    Total  2014
262    Jammu & Kashmir    Total  2014
289          Jharkhand    Total  2014
326          Karnataka    Total  2014
348             Kerala    Total  2014
404     Madhya Pradesh    Total  2014
451        Maharashtra    Total  2014
462            Manipur    Total  2014
474          Meghalaya    Total  2014
484            Mizoram    Total  2014
496           Nagaland    Total  2014
533             Odisha    Total  2014
562             Punjab    Total  2014
605          Rajasthan    Total  2014
611             Sikkim    Total  2014
654         Tamil Nadu    Total  2014
668          Telangana    Total  2014
678            Tripura    Total  2014
755      Uttar Pradesh    Total  2014
769        Uttarakhand    Total  2014
800        West Bengal    Total  2014
804        A&N Islands    Total  2014

================================================================================
TOTAL ROWS: 02_District_wise_crimes_committed_against_ST_2001_2012.csv
================================================================================
Number of TOTAL rows: 421

                 STATE DISTRICT  YEAR
28      ANDHRA PRADESH    TOTAL  2001
42   ARUNACHAL PRADESH    TOTAL  2001
70               ASSAM    TOTAL  2001
115              BIHAR    TOTAL  2001
134       CHHATTISGARH    TOTAL  2001
137                GOA    TOTAL  2001
168            GUJARAT    TOTAL  2001
189            HARYANA    TOTAL  2001
203   HIMACHAL PRADESH    TOTAL  2001
228    JAMMU & KASHMIR    TOTAL  2001
253          JHARKHAND    TOTAL  2001
285          KARNATAKA    TOTAL  2001
302             KERALA    TOTAL  2001
351     MADHYA PRADESH    TOTAL  2001
397        MAHARASHTRA    TOTAL  2001
407            MANIPUR    TOTAL  2001
415          MEGHALAYA    TOTAL  2001
424            MIZORAM    TOTAL  2001
435           NAGALAND    TOTAL  2001
470             ODISHA    TOTAL  2001
495             PUNJAB    TOTAL  2001
529          RAJASTHAN    TOTAL  2001
534             SIKKIM    TOTAL  2001
573         TAMIL NADU    TOTAL  2001
578            TRIPURA    TOTAL  2001
650      UTTAR PRADESH    TOTAL  2001
664        UTTARAKHAND    TOTAL  2001
688        WEST BENGAL    TOTAL  2001
691      A & N ISLANDS    TOTAL  2001
693         CHANDIGARH    TOTAL  2001

================================================================================
TOTAL ROWS: 02_District_wise_crimes_committed_against_ST_2014.csv
================================================================================
Number of TOTAL rows: 36

                 STATE DISTRICT  YEAR
20      Andhra Pradesh    Total  2014
40   Arunachal Pradesh    Total  2014
68               Assam    Total  2014
115              Bihar    Total  2014
144       Chhattisgarh    Total  2014
148                Goa    Total  2014
190            Gujarat    Total  2014
215            Haryana    Total  2014
231   Himachal Pradesh    Total  2014
262    Jammu & Kashmir    Total  2014
289          Jharkhand    Total  2014
326          Karnataka    Total  2014
348             Kerala    Total  2014
404     Madhya Pradesh    Total  2014
451        Maharashtra    Total  2014
462            Manipur    Total  2014
474          Meghalaya    Total  2014
484            Mizoram    Total  2014
496           Nagaland    Total  2014
533             Odisha    Total  2014
562             Punjab    Total  2014
605          Rajasthan    Total  2014
611             Sikkim    Total  2014
654         Tamil Nadu    Total  2014
668          Telangana    Total  2014
678            Tripura    Total  2014
755      Uttar Pradesh    Total  2014
769        Uttarakhand    Total  2014
800        West Bengal    Total  2014
804        A&N Islands    Total  2014

================================================================================
TOTAL ROWS: 03_District_wise_crimes_committed_against_children_2001_2012.csv
================================================================================
Number of TOTAL rows: 412

                 STATE DISTRICT  YEAR
28      ANDHRA PRADESH    TOTAL  2001
42   ARUNACHAL PRADESH    TOTAL  2001
70               ASSAM    TOTAL  2001
115              BIHAR    TOTAL  2001
137                GOA    TOTAL  2001
168            GUJARAT    TOTAL  2001
189            HARYANA    TOTAL  2001
203   HIMACHAL PRADESH    TOTAL  2001
227    JAMMU & KASHMIR    TOTAL  2001
252          JHARKHAND    TOTAL  2001
284          KARNATAKA    TOTAL  2001
301             KERALA    TOTAL  2001
350     MADHYA PRADESH    TOTAL  2001
396        MAHARASHTRA    TOTAL  2001
406            MANIPUR    TOTAL  2001
414          MEGHALAYA    TOTAL  2001
423            MIZORAM    TOTAL  2001
434           NAGALAND    TOTAL  2001
469             ODISHA    TOTAL  2001
494             PUNJAB    TOTAL  2001
528          RAJASTHAN    TOTAL  2001
533             SIKKIM    TOTAL  2001
572         TAMIL NADU    TOTAL  2001
577            TRIPURA    TOTAL  2001
649      UTTAR PRADESH    TOTAL  2001
663        UTTARAKHAND    TOTAL  2001
687        WEST BENGAL    TOTAL  2001
690      A & N ISLANDS    TOTAL  2001
692         CHANDIGARH    TOTAL  2001
694       D & N HAVELI    TOTAL  2001

================================================================================
TOTAL ROWS: 03_District_wise_crimes_committed_against_children_2013.csv
================================================================================
Number of TOTAL rows: 35

                 STATE DISTRICT  YEAR
33      Andhra Pradesh    TOTAL  2013
52   Arunachal Pradesh    TOTAL  2013
86               Assam    TOTAL  2013
131              Bihar    TOTAL  2013
160       Chhattisgarh    TOTAL  2013
163                Goa    TOTAL  2013
198            Gujarat    TOTAL  2013
223            Haryana    TOTAL  2013
239   Himachal Pradesh    TOTAL  2013
270    Jammu & Kashmir    TOTAL  2013
297          Jharkhand    TOTAL  2013
333          Karnataka    TOTAL  2013
354             Kerala    TOTAL  2013
409     Madhya Pradesh    TOTAL  2013
455        Maharashtra    TOTAL  2013
466            Manipur    TOTAL  2013
478          Meghalaya    TOTAL  2013
489            Mizoram    TOTAL  2013
501           Nagaland    TOTAL  2013
538             Odisha    TOTAL  2013
567             Punjab    TOTAL  2013
611          Rajasthan    TOTAL  2013
616             Sikkim    TOTAL  2013
656         Tamil Nadu    TOTAL  2013
666            Tripura    TOTAL  2013
743      Uttar Pradesh    TOTAL  2013
757        Uttarakhand    TOTAL  2013
787        West Bengal    TOTAL  2013
791        A&N Islands    TOTAL  2013
793         Chandigarh    TOTAL  2013

================================================================================
TOTAL ROWS: 42_District_wise_crimes_committed_against_women_2001_2012.csv
================================================================================
Number of TOTAL rows: 408

                 STATE DISTRICT  YEAR
28      ANDHRA PRADESH    TOTAL  2001
42   ARUNACHAL PRADESH    TOTAL  2001
70               ASSAM    TOTAL  2001
115              BIHAR    TOTAL  2001
135       CHHATTISGARH    TOTAL  2001
138                GOA    TOTAL  2001
169            GUJARAT    TOTAL  2001
190            HARYANA    TOTAL  2001
204   HIMACHAL PRADESH    TOTAL  2001
228    JAMMU & KASHMIR    TOTAL  2001
253          JHARKHAND    TOTAL  2001
285          KARNATAKA    TOTAL  2001
302             KERALA    TOTAL  2001
351     MADHYA PRADESH    TOTAL  2001
397        MAHARASHTRA    TOTAL  2001
407            MANIPUR    TOTAL  2001
415          MEGHALAYA    TOTAL  2001
424            MIZORAM    TOTAL  2001
435           NAGALAND    TOTAL  2001
470             ODISHA    TOTAL  2001
495             PUNJAB    TOTAL  2001
529          RAJASTHAN    TOTAL  2001
534             SIKKIM    TOTAL  2001
573         TAMIL NADU    TOTAL  2001
578            TRIPURA    TOTAL  2001
650      UTTAR PRADESH    TOTAL  2001
664        UTTARAKHAND    TOTAL  2001
688        WEST BENGAL    TOTAL  2001
691      A & N ISLANDS    TOTAL  2001
693         CHANDIGARH    TOTAL  2001

================================================================================
TOTAL ROWS: 42_District_wise_crimes_committed_against_women_2014.csv
================================================================================
Number of TOTAL rows: 36

                 STATE DISTRICT  YEAR
20      Andhra Pradesh    Total  2014
40   Arunachal Pradesh    Total  2014
68               Assam    Total  2014
115              Bihar    Total  2014
144       Chhattisgarh    Total  2014
148                Goa    Total  2014
190            Gujarat    Total  2014
215            Haryana    Total  2014
231   Himachal Pradesh    Total  2014
262    Jammu & Kashmir    Total  2014
289          Jharkhand    Total  2014
326          Karnataka    Total  2014
348             Kerala    Total  2014
404     Madhya Pradesh    Total  2014
451        Maharashtra    Total  2014
462            Manipur    Total  2014
474          Meghalaya    Total  2014
484            Mizoram    Total  2014
496           Nagaland    Total  2014
533             Odisha    Total  2014
562             Punjab    Total  2014
605          Rajasthan    Total  2014
611             Sikkim    Total  2014
654         Tamil Nadu    Total  2014
668          Telangana    Total  2014
678            Tripura    Total  2014
755      Uttar Pradesh    Total  2014
769        Uttarakhand    Total  2014
800        West Bengal    Total  2014
804        A&N Islands    Total  2014

In [59]:
# ============================================================
# CELL 58 — SPECIAL DISTRICT VALUE AUDIT
# ============================================================

special_terms = [
    "TOTAL",
    "RAILWAYS",
    "CITY",
    "COMMISSIONERATE",
    "RURAL",
    "URBAN"
]

special_records = []

for filename, df in normalized_district_data.items():

    if "DISTRICT" not in df.columns:
        continue

    district_values = (
        df["DISTRICT"]
        .astype("string")
        .str.strip()
    )

    for term in special_terms:

        matches = district_values[
            district_values
            .str.upper()
            .str.contains(
                term,
                na=False
            )
        ]

        if len(matches) > 0:

            special_records.append({

                "filename":
                    filename,

                "term":
                    term,

                "matching_rows":
                    len(matches),

                "unique_values":
                    "; ".join(
                        sorted(
                            matches
                            .dropna()
                            .unique()
                            .tolist()
                        )[:20]
                    )
            })


special_district_df = pd.DataFrame(
    special_records
)

display(
    special_district_df
)

,filename,term,matching_rows,unique_values
0,01_District_wise_crimes_committed_IPC_2001_2012.csv,TOTAL,420,DELHI UT TOTAL; TOTAL
1,01_District_wise_crimes_committed_IPC_2001_2012.csv,RAILWAYS,41,RAILWAYS; RAILWAYS JAMMU; RAILWAYS KASHMIR; RAILWAYS KATRA; RAILWAYS KMR
2,01_District_wise_crimes_committed_IPC_2001_2012.csv,CITY,53,GUWAHATI CITY; HOWRAH CITY; HYDERABAD CITY; JODHPUR CITY; KOTA CITY; MANGALORE CITY; VIJAYAWADA CITY
3,01_District_wise_crimes_committed_IPC_2001_2012.csv,RURAL,310,AHMEDABAD RURAL; AMBALA RURAL; AMRAVATI RURAL; AMRITSAR RURAL; AURANGABAD RURAL; BANGALORE RURAL; COIMBATORE RURAL; ...
4,01_District_wise_crimes_committed_IPC_2001_2012.csv,URBAN,73,AMBALA URBAN; CHENNAISUBURBAN; COIMBATORE URBAN; GUNTUR URBAN; MADURAI URBAN; SALEM URBAN; THIRUNELVELI URBAN; TIRUP...
...,...,...,...,...
65,42_District_wise_crimes_committed_against_women_2014.csv,TOTAL,36,Total
66,42_District_wise_crimes_committed_against_women_2014.csv,RAILWAYS,5,K.Railways; Railways; Railways Jammu; Railways Kashmir; Railways Katra
67,42_District_wise_crimes_committed_against_women_2014.csv,CITY,20,Ahmedabad City; Belagavi City; Bengaluru City; Coimbatore City; Guwahati City; Hubballi Dharwad City; Hyderabad City...
68,42_District_wise_crimes_committed_against_women_2014.csv,RURAL,26,Ahmedabad Rural; Ambala (Rural); Amravati Rural; Amritsar Rural; Aurangabad Rural; Ernakulam Rural; Howrah Rural; Ja...
69,42_District_wise_crimes_committed_against_women_2014.csv,URBAN,4,Ambala (Urban); Guntur Urban; Tirupathi Urban; Warangal Urban

In [60]:
# ============================================================
# CELL 59 — STATE/YEAR/DISTRICT CARDINALITY
# ============================================================

for filename, df in normalized_district_data.items():

    if not all(
        column in df.columns
        for column in [
            "STATE",
            "DISTRICT",
            "YEAR"
        ]
    ):
        continue

    cardinality = (
        df.groupby(
            [
                "STATE",
                "YEAR"
            ],
            dropna=False
        )["DISTRICT"]
        .nunique()
        .reset_index(
            name="unique_district_count"
        )
        .sort_values(
            "unique_district_count"
        )
    )

    suspicious = cardinality[
        cardinality[
            "unique_district_count"
        ] <= 2
    ]

    if len(suspicious) > 0:

        print("\n" + "=" * 80)
        print(f"CARDINALITY CHECK: {filename}")
        print("=" * 80)

        display(
            suspicious.head(20)
        )

================================================================================
CARDINALITY CHECK: 01_District_wise_crimes_committed_IPC_2001_2012.csv
================================================================================

            STATE  YEAR  unique_district_count
71     CHANDIGARH  2012                      2
86   D & N HAVELI  2003                      2
316    PUDUCHERRY  2005                      2
315    PUDUCHERRY  2004                      2
314    PUDUCHERRY  2003                      2
313    PUDUCHERRY  2002                      2
312    PUDUCHERRY  2001                      2
70     CHANDIGARH  2011                      2
84   D & N HAVELI  2001                      2
95   D & N HAVELI  2012                      2
94   D & N HAVELI  2011                      2
93   D & N HAVELI  2010                      2
92   D & N HAVELI  2009                      2
91   D & N HAVELI  2008                      2
90   D & N HAVELI  2007                      2
89   D & N HAVELI  2006                      2
88   D & N HAVELI  2005                      2
87   D & N HAVELI  2004                      2
61     CHANDIGARH  2002                      2
62     CHANDIGARH  2003                      2

================================================================================
CARDINALITY CHECK: 01_District_wise_crimes_committed_IPC_2013.csv
================================================================================

          STATE  YEAR  unique_district_count
18  Lakshadweep  2013                      2
7    D&N Haveli  2013                      2
5    Chandigarh  2013                      2

================================================================================
CARDINALITY CHECK: 01_District_wise_crimes_committed_IPC_2014.csv
================================================================================

          STATE  YEAR  unique_district_count
18  Lakshadweep  2014                      2
7    D&N Haveli  2014                      2
5    Chandigarh  2014                      2

================================================================================
CARDINALITY CHECK: 02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
================================================================================

            STATE  YEAR  unique_district_count
61     CHANDIGARH  2002                      2
62     CHANDIGARH  2003                      2
86   D & N HAVELI  2003                      2
60     CHANDIGARH  2001                      2
316    PUDUCHERRY  2005                      2
315    PUDUCHERRY  2004                      2
314    PUDUCHERRY  2003                      2
313    PUDUCHERRY  2002                      2
71     CHANDIGARH  2012                      2
63     CHANDIGARH  2004                      2
84   D & N HAVELI  2001                      2
94   D & N HAVELI  2011                      2
93   D & N HAVELI  2010                      2
92   D & N HAVELI  2009                      2
91   D & N HAVELI  2008                      2
90   D & N HAVELI  2007                      2
89   D & N HAVELI  2006                      2
88   D & N HAVELI  2005                      2
87   D & N HAVELI  2004                      2
95   D & N HAVELI  2012                      2

================================================================================
CARDINALITY CHECK: 02_01_District_wise_crimes_committed_against_SC_2013.csv
================================================================================

          STATE  YEAR  unique_district_count
18  Lakshadweep  2013                      2
7    D&N Haveli  2013                      2
5    Chandigarh  2013                      2

================================================================================
CARDINALITY CHECK: 02_01_District_wise_crimes_committed_against_SC_2014.csv
================================================================================

          STATE  YEAR  unique_district_count
18  Lakshadweep  2014                      2
7    D&N Haveli  2014                      2
5    Chandigarh  2014                      2

================================================================================
CARDINALITY CHECK: 02_District_wise_crimes_committed_against_ST_2001_2012.csv
================================================================================

            STATE  YEAR  unique_district_count
61     CHANDIGARH  2002                      2
62     CHANDIGARH  2003                      2
86   D & N HAVELI  2003                      2
60     CHANDIGARH  2001                      2
316    PUDUCHERRY  2005                      2
315    PUDUCHERRY  2004                      2
314    PUDUCHERRY  2003                      2
313    PUDUCHERRY  2002                      2
71     CHANDIGARH  2012                      2
63     CHANDIGARH  2004                      2
84   D & N HAVELI  2001                      2
94   D & N HAVELI  2011                      2
93   D & N HAVELI  2010                      2
92   D & N HAVELI  2009                      2
91   D & N HAVELI  2008                      2
90   D & N HAVELI  2007                      2
89   D & N HAVELI  2006                      2
88   D & N HAVELI  2005                      2
87   D & N HAVELI  2004                      2
95   D & N HAVELI  2012                      2

================================================================================
CARDINALITY CHECK: 02_District_wise_crimes_committed_against_ST_2013.csv
================================================================================

          STATE  YEAR  unique_district_count
18  Lakshadweep  2013                      2
7    D&N Haveli  2013                      2
5    Chandigarh  2013                      2

================================================================================
CARDINALITY CHECK: 02_District_wise_crimes_committed_against_ST_2014.csv
================================================================================

          STATE  YEAR  unique_district_count
18  Lakshadweep  2014                      2
7    D&N Haveli  2014                      2
5    Chandigarh  2014                      2

================================================================================
CARDINALITY CHECK: 03_District_wise_crimes_committed_against_children_2001_2012.csv
================================================================================

            STATE  YEAR  unique_district_count
61     CHANDIGARH  2002                      2
62     CHANDIGARH  2003                      2
86   D & N HAVELI  2003                      2
60     CHANDIGARH  2001                      2
316    PUDUCHERRY  2005                      2
315    PUDUCHERRY  2004                      2
314    PUDUCHERRY  2003                      2
313    PUDUCHERRY  2002                      2
71     CHANDIGARH  2012                      2
63     CHANDIGARH  2004                      2
84   D & N HAVELI  2001                      2
94   D & N HAVELI  2011                      2
93   D & N HAVELI  2010                      2
92   D & N HAVELI  2009                      2
91   D & N HAVELI  2008                      2
90   D & N HAVELI  2007                      2
89   D & N HAVELI  2006                      2
88   D & N HAVELI  2005                      2
87   D & N HAVELI  2004                      2
95   D & N HAVELI  2012                      2

================================================================================
CARDINALITY CHECK: 03_District_wise_crimes_committed_against_children_2013.csv
================================================================================

          STATE  YEAR  unique_district_count
18  Lakshadweep  2013                      2
7    D&N Haveli  2013                      2
5    Chandigarh  2013                      2

================================================================================
CARDINALITY CHECK: 42_District_wise_crimes_committed_against_women_2001_2012.csv
================================================================================

            STATE  YEAR  unique_district_count
71     CHANDIGARH  2012                      2
86   D & N HAVELI  2003                      2
316    PUDUCHERRY  2005                      2
315    PUDUCHERRY  2004                      2
314    PUDUCHERRY  2003                      2
313    PUDUCHERRY  2002                      2
312    PUDUCHERRY  2001                      2
70     CHANDIGARH  2011                      2
84   D & N HAVELI  2001                      2
95   D & N HAVELI  2012                      2
94   D & N HAVELI  2011                      2
93   D & N HAVELI  2010                      2
92   D & N HAVELI  2009                      2
91   D & N HAVELI  2008                      2
90   D & N HAVELI  2007                      2
89   D & N HAVELI  2006                      2
88   D & N HAVELI  2005                      2
87   D & N HAVELI  2004                      2
61     CHANDIGARH  2002                      2
62     CHANDIGARH  2003                      2

================================================================================
CARDINALITY CHECK: 42_District_wise_crimes_committed_against_women_2013.csv
================================================================================

          STATE  YEAR  unique_district_count
18  Lakshadweep  2013                      2
7    D&N Haveli  2013                      2
5    Chandigarh  2013                      2

================================================================================
CARDINALITY CHECK: 42_District_wise_crimes_committed_against_women_2014.csv
================================================================================

          STATE  YEAR  unique_district_count
18  Lakshadweep  2014                      2
7    D&N Haveli  2014                      2
5    Chandigarh  2014                      2

In [63]:
# ============================================================
# CELL 60 — INSPECT DUPLICATE ROW CONTEXT
# FIXED VERSION
# ============================================================

print("=" * 90)
print("RAW/NORMALIZED ROW CONTEXT AROUND DUPLICATE KEYS")
print("=" * 90)


for filename, duplicate_rows in duplicate_details.items():

    print("\n" + "=" * 90)
    print(f"FILE: {filename}")
    print("=" * 90)

    # --------------------------------------------------------
    # IMPORTANT:
    # Use the already-normalized dataframe.
    #
    # This dataframe has:
    # STATE
    # DISTRICT
    # YEAR
    # --------------------------------------------------------

    if filename not in normalized_district_data:

        print(
            f"⚠ Normalized dataframe not found: "
            f"{filename}"
        )

        continue

    df = normalized_district_data[
        filename
    ].copy()

    key_columns = [
        "STATE",
        "DISTRICT",
        "YEAR"
    ]

    # --------------------------------------------------------
    # Make sure required columns exist
    # --------------------------------------------------------

    missing_columns = [
        column
        for column in key_columns
        if column not in df.columns
    ]

    if missing_columns:

        print(
            f"⚠ Missing columns: "
            f"{missing_columns}"
        )

        continue

    # --------------------------------------------------------
    # Get unique duplicate keys
    # --------------------------------------------------------

    duplicate_keys = (
        duplicate_rows[
            key_columns
        ]
        .drop_duplicates()
        .itertuples(
            index=False,
            name=None
        )
    )

    # --------------------------------------------------------
    # Inspect every duplicate key
    # --------------------------------------------------------

    for key in duplicate_keys:

        print("\n" + "-" * 80)
        print(
            f"DUPLICATE KEY: {key}"
        )
        print("-" * 80)

        # ----------------------------------------------------
        # Find matching rows in normalized dataframe
        # ----------------------------------------------------

        mask = pd.Series(
            True,
            index=df.index
        )

        for column, value in zip(
            key_columns,
            key
        ):

            if pd.isna(value):

                mask &= df[column].isna()

            else:

                mask &= (
                    df[column]
                    .astype("string")
                    .str.strip()
                    .eq(
                        str(value).strip()
                    )
                )

        matching_indices = (
            df.index[mask]
            .tolist()
        )

        print(
            "Matching dataframe indices:",
            matching_indices
        )

        # ----------------------------------------------------
        # Show surrounding rows
        # ----------------------------------------------------

        for idx in matching_indices:

            start = max(
                0,
                idx - 2
            )

            end = min(
                len(df),
                idx + 3
            )

            print(
                f"\nContext around dataframe "
                f"index {idx}:"
            )

            context_df = df.iloc[
                start:end
            ].copy()

            display(
                context_df
            )

==========================================================================================
RAW/NORMALIZED ROW CONTEXT AROUND DUPLICATE KEYS
==========================================================================================

==========================================================================================
FILE: 01_District_wise_crimes_committed_IPC_2001_2012.csv
==========================================================================================

--------------------------------------------------------------------------------
DUPLICATE KEY: ('JAMMU & KASHMIR', 'RAILWAYS', 2010)
--------------------------------------------------------------------------------
Matching dataframe indices: [6880, 6881]

Context around dataframe index 6880:

,STATE,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS,KIDNAPPING AND ABDUCTION OF OTHERS,DACOITY,PREPARATION AND ASSEMBLY FOR DACOITY,ROBBERY,BURGLARY,THEFT,AUTO THEFT,OTHER THEFT,RIOTS,CRIMINAL BREACH OF TRUST,CHEATING,COUNTERFIETING,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES,CRIME_GROUP,SOURCE_FILE
6878,JAMMU & KASHMIR,POONCH,2010,12,37,1,20,0,20,39,34,5,0,0,0,23,31,3,28,132,4,8,0,0,54,0,30,10,16,0,4,529,950,IPC,01_District_wise_crimes_committed_IPC_2001_2012.csv
6879,JAMMU & KASHMIR,PULWAMA,2010,4,10,2,8,0,8,33,31,2,1,0,4,37,80,10,70,172,3,7,3,8,55,0,11,13,0,0,2,164,617,IPC,01_District_wise_crimes_committed_IPC_2001_2012.csv
6880,JAMMU & KASHMIR,RAILWAYS,2010,0,0,0,0,0,0,1,0,1,0,0,0,1,12,1,11,16,1,0,0,0,0,0,0,0,0,0,0,5,36,IPC,01_District_wise_crimes_committed_IPC_2001_2012.csv
6881,JAMMU & KASHMIR,RAILWAYS,2010,1,0,1,1,0,1,0,0,0,0,0,0,0,8,1,7,0,0,0,0,0,0,0,0,0,0,0,0,10,21,IPC,01_District_wise_crimes_committed_IPC_2001_2012.csv
6882,JAMMU & KASHMIR,RAJOURI,2010,15,36,6,36,0,36,47,42,5,2,0,0,44,52,20,32,33,10,15,0,22,30,0,26,4,44,0,38,1000,1460,IPC,01_District_wise_crimes_committed_IPC_2001_2012.csv

Context around dataframe index 6881:

,STATE,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS,KIDNAPPING AND ABDUCTION OF OTHERS,DACOITY,PREPARATION AND ASSEMBLY FOR DACOITY,ROBBERY,BURGLARY,THEFT,AUTO THEFT,OTHER THEFT,RIOTS,CRIMINAL BREACH OF TRUST,CHEATING,COUNTERFIETING,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES,CRIME_GROUP,SOURCE_FILE
6879,JAMMU & KASHMIR,PULWAMA,2010,4,10,2,8,0,8,33,31,2,1,0,4,37,80,10,70,172,3,7,3,8,55,0,11,13,0,0,2,164,617,IPC,01_District_wise_crimes_committed_IPC_2001_2012.csv
6880,JAMMU & KASHMIR,RAILWAYS,2010,0,0,0,0,0,0,1,0,1,0,0,0,1,12,1,11,16,1,0,0,0,0,0,0,0,0,0,0,5,36,IPC,01_District_wise_crimes_committed_IPC_2001_2012.csv
6881,JAMMU & KASHMIR,RAILWAYS,2010,1,0,1,1,0,1,0,0,0,0,0,0,0,8,1,7,0,0,0,0,0,0,0,0,0,0,0,0,10,21,IPC,01_District_wise_crimes_committed_IPC_2001_2012.csv
6882,JAMMU & KASHMIR,RAJOURI,2010,15,36,6,36,0,36,47,42,5,2,0,0,44,52,20,32,33,10,15,0,22,30,0,26,4,44,0,38,1000,1460,IPC,01_District_wise_crimes_committed_IPC_2001_2012.csv
6883,JAMMU & KASHMIR,RAMBAN,2010,3,9,0,6,0,6,17,17,0,0,0,0,24,37,20,17,17,3,10,1,1,2,0,11,2,0,0,2,491,636,IPC,01_District_wise_crimes_committed_IPC_2001_2012.csv

==========================================================================================
FILE: 02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
==========================================================================================

--------------------------------------------------------------------------------
DUPLICATE KEY: ('JAMMU & KASHMIR', 'ANANTNAG', 2001)
--------------------------------------------------------------------------------
Matching dataframe indices: [204, 205]

Context around dataframe index 204:

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping and Abduction,Dacoity,Robbery,Arson,Hurt,Prevention of atrocities (POA) Act,Protection of Civil Rights (PCR) Act,Other Crimes Against SCs,CRIME_GROUP,SOURCE_FILE
202,HIMACHAL PRADESH,UNA,2001,0,0,0,0,0,0,1,4,0,8,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
203,HIMACHAL PRADESH,TOTAL,2001,1,7,0,0,0,0,1,41,4,56,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
204,JAMMU & KASHMIR,ANANTNAG,2001,0,0,0,0,0,0,0,0,0,0,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
205,JAMMU & KASHMIR,ANANTNAG,2001,0,0,0,0,0,0,0,0,0,0,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
206,JAMMU & KASHMIR,AWANTIPORA,2001,0,0,0,0,0,0,0,0,0,0,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv

Context around dataframe index 205:

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping and Abduction,Dacoity,Robbery,Arson,Hurt,Prevention of atrocities (POA) Act,Protection of Civil Rights (PCR) Act,Other Crimes Against SCs,CRIME_GROUP,SOURCE_FILE
203,HIMACHAL PRADESH,TOTAL,2001,1,7,0,0,0,0,1,41,4,56,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
204,JAMMU & KASHMIR,ANANTNAG,2001,0,0,0,0,0,0,0,0,0,0,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
205,JAMMU & KASHMIR,ANANTNAG,2001,0,0,0,0,0,0,0,0,0,0,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
206,JAMMU & KASHMIR,AWANTIPORA,2001,0,0,0,0,0,0,0,0,0,0,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
207,JAMMU & KASHMIR,BARAMULLA,2001,0,0,0,0,0,0,0,0,0,0,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv

--------------------------------------------------------------------------------
DUPLICATE KEY: ('NAGALAND', 'TOTAL', 2005)
--------------------------------------------------------------------------------
Matching dataframe indices: [3343, 3344]

Context around dataframe index 3343:

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping and Abduction,Dacoity,Robbery,Arson,Hurt,Prevention of atrocities (POA) Act,Protection of Civil Rights (PCR) Act,Other Crimes Against SCs,CRIME_GROUP,SOURCE_FILE
3341,NAGALAND,WOKHA,2005,0,0,0,0,0,0,0,0,0,0,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
3342,NAGALAND,ZUNHEBOTO,2005,0,0,0,0,0,0,0,0,0,0,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
3343,NAGALAND,TOTAL,2005,0,0,0,0,0,0,0,0,0,0,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
3344,NAGALAND,TOTAL,2005,0,0,0,0,0,0,0,0,0,0,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
3345,ODISHA,ANGUL,2005,0,2,0,0,0,0,14,13,0,8,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv

Context around dataframe index 3344:

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping and Abduction,Dacoity,Robbery,Arson,Hurt,Prevention of atrocities (POA) Act,Protection of Civil Rights (PCR) Act,Other Crimes Against SCs,CRIME_GROUP,SOURCE_FILE
3342,NAGALAND,ZUNHEBOTO,2005,0,0,0,0,0,0,0,0,0,0,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
3343,NAGALAND,TOTAL,2005,0,0,0,0,0,0,0,0,0,0,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
3344,NAGALAND,TOTAL,2005,0,0,0,0,0,0,0,0,0,0,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
3345,ODISHA,ANGUL,2005,0,2,0,0,0,0,14,13,0,8,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
3346,ODISHA,BALASORE,2005,0,1,0,0,1,0,46,0,0,8,SC,02_01_District_wise_crimes_committed_against_SC_2001_2012.csv

==========================================================================================
FILE: 02_District_wise_crimes_committed_against_ST_2001_2012.csv
==========================================================================================

--------------------------------------------------------------------------------
DUPLICATE KEY: ('JAMMU & KASHMIR', 'ANANTNAG', 2001)
--------------------------------------------------------------------------------
Matching dataframe indices: [204, 205]

Context around dataframe index 204:

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping Abduction,Dacoity,Robbery,Arson,Hurt,Protection of Civil Rights (PCR) Act,Prevention of atrocities (POA) Act,Other Crimes Against STs,CRIME_GROUP,SOURCE_FILE
202,HIMACHAL PRADESH,UNA,2001,0,0,0,0,0,0,0,0,0,0,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
203,HIMACHAL PRADESH,TOTAL,2001,0,0,0,0,0,0,0,0,2,2,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
204,JAMMU & KASHMIR,ANANTNAG,2001,0,0,0,0,0,0,0,0,0,0,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
205,JAMMU & KASHMIR,ANANTNAG,2001,0,0,0,0,0,0,0,0,0,0,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
206,JAMMU & KASHMIR,AWANTIPORA,2001,0,0,0,0,0,0,0,0,0,0,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv

Context around dataframe index 205:

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping Abduction,Dacoity,Robbery,Arson,Hurt,Protection of Civil Rights (PCR) Act,Prevention of atrocities (POA) Act,Other Crimes Against STs,CRIME_GROUP,SOURCE_FILE
203,HIMACHAL PRADESH,TOTAL,2001,0,0,0,0,0,0,0,0,2,2,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
204,JAMMU & KASHMIR,ANANTNAG,2001,0,0,0,0,0,0,0,0,0,0,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
205,JAMMU & KASHMIR,ANANTNAG,2001,0,0,0,0,0,0,0,0,0,0,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
206,JAMMU & KASHMIR,AWANTIPORA,2001,0,0,0,0,0,0,0,0,0,0,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
207,JAMMU & KASHMIR,BARAMULLA,2001,0,0,0,0,0,0,0,0,0,0,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv

--------------------------------------------------------------------------------
DUPLICATE KEY: ('NAGALAND', 'TOTAL', 2005)
--------------------------------------------------------------------------------
Matching dataframe indices: [3343, 3344]

Context around dataframe index 3343:

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping Abduction,Dacoity,Robbery,Arson,Hurt,Protection of Civil Rights (PCR) Act,Prevention of atrocities (POA) Act,Other Crimes Against STs,CRIME_GROUP,SOURCE_FILE
3341,NAGALAND,WOKHA,2005,0,0,0,0,0,0,0,0,0,0,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
3342,NAGALAND,ZUNHEBOTO,2005,0,0,0,0,0,0,0,0,0,0,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
3343,NAGALAND,TOTAL,2005,0,0,0,0,0,0,0,0,0,0,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
3344,NAGALAND,TOTAL,2005,0,0,0,0,0,0,0,0,0,0,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
3345,ODISHA,ANGUL,2005,0,1,0,0,0,0,1,0,9,3,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv

Context around dataframe index 3344:

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping Abduction,Dacoity,Robbery,Arson,Hurt,Protection of Civil Rights (PCR) Act,Prevention of atrocities (POA) Act,Other Crimes Against STs,CRIME_GROUP,SOURCE_FILE
3342,NAGALAND,ZUNHEBOTO,2005,0,0,0,0,0,0,0,0,0,0,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
3343,NAGALAND,TOTAL,2005,0,0,0,0,0,0,0,0,0,0,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
3344,NAGALAND,TOTAL,2005,0,0,0,0,0,0,0,0,0,0,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
3345,ODISHA,ANGUL,2005,0,1,0,0,0,0,1,0,9,3,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv
3346,ODISHA,BALASORE,2005,0,5,0,0,1,0,20,0,0,3,ST,02_District_wise_crimes_committed_against_ST_2001_2012.csv

==========================================================================================
FILE: 03_District_wise_crimes_committed_against_children_2001_2012.csv
==========================================================================================

--------------------------------------------------------------------------------
DUPLICATE KEY: ('NAGALAND', 'TOTAL', 2005)
--------------------------------------------------------------------------------
Matching dataframe indices: [3341, 3342]

Context around dataframe index 3341:

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping and Abduction,Foeticide,Abetment of suicide,Exposure and abandonment,Procuration of minor girls,Buying of girls for prostitution,Selling of girls for prostitution,Prohibition of child marriage act,Other Crimes,Total,CRIME_GROUP,SOURCE_FILE
3339,NAGALAND,WOKHA,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,CHILDREN,03_District_wise_crimes_committed_against_children_2001_2012.csv
3340,NAGALAND,ZUNHEBOTO,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,CHILDREN,03_District_wise_crimes_committed_against_children_2001_2012.csv
3341,NAGALAND,TOTAL,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,CHILDREN,03_District_wise_crimes_committed_against_children_2001_2012.csv
3342,NAGALAND,TOTAL,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,CHILDREN,03_District_wise_crimes_committed_against_children_2001_2012.csv
3343,ODISHA,ANGUL,2005,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,17,CHILDREN,03_District_wise_crimes_committed_against_children_2001_2012.csv

Context around dataframe index 3342:

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping and Abduction,Foeticide,Abetment of suicide,Exposure and abandonment,Procuration of minor girls,Buying of girls for prostitution,Selling of girls for prostitution,Prohibition of child marriage act,Other Crimes,Total,CRIME_GROUP,SOURCE_FILE
3340,NAGALAND,ZUNHEBOTO,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,CHILDREN,03_District_wise_crimes_committed_against_children_2001_2012.csv
3341,NAGALAND,TOTAL,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,CHILDREN,03_District_wise_crimes_committed_against_children_2001_2012.csv
3342,NAGALAND,TOTAL,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,CHILDREN,03_District_wise_crimes_committed_against_children_2001_2012.csv
3343,ODISHA,ANGUL,2005,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,17,CHILDREN,03_District_wise_crimes_committed_against_children_2001_2012.csv
3344,ODISHA,BALASORE,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,CHILDREN,03_District_wise_crimes_committed_against_children_2001_2012.csv

==========================================================================================
FILE: 42_District_wise_crimes_committed_against_women_2001_2012.csv
==========================================================================================

--------------------------------------------------------------------------------
DUPLICATE KEY: ('JAMMU & KASHMIR', 'RAILWAYS', 2010)
--------------------------------------------------------------------------------
Matching dataframe indices: [6880, 6881]

Context around dataframe index 6880:

,STATE,DISTRICT,YEAR,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls,CRIME_GROUP,SOURCE_FILE
6878,JAMMU & KASHMIR,POONCH,2010,20,34,0,30,10,16,0,WOMEN,42_District_wise_crimes_committed_against_women_2001_2012.csv
6879,JAMMU & KASHMIR,PULWAMA,2010,8,31,0,11,13,0,0,WOMEN,42_District_wise_crimes_committed_against_women_2001_2012.csv
6880,JAMMU & KASHMIR,RAILWAYS,2010,0,0,0,0,0,0,0,WOMEN,42_District_wise_crimes_committed_against_women_2001_2012.csv
6881,JAMMU & KASHMIR,RAILWAYS,2010,1,0,0,0,0,0,0,WOMEN,42_District_wise_crimes_committed_against_women_2001_2012.csv
6882,JAMMU & KASHMIR,RAJOURI,2010,36,42,0,26,4,44,0,WOMEN,42_District_wise_crimes_committed_against_women_2001_2012.csv

Context around dataframe index 6881:

,STATE,DISTRICT,YEAR,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls,CRIME_GROUP,SOURCE_FILE
6879,JAMMU & KASHMIR,PULWAMA,2010,8,31,0,11,13,0,0,WOMEN,42_District_wise_crimes_committed_against_women_2001_2012.csv
6880,JAMMU & KASHMIR,RAILWAYS,2010,0,0,0,0,0,0,0,WOMEN,42_District_wise_crimes_committed_against_women_2001_2012.csv
6881,JAMMU & KASHMIR,RAILWAYS,2010,1,0,0,0,0,0,0,WOMEN,42_District_wise_crimes_committed_against_women_2001_2012.csv
6882,JAMMU & KASHMIR,RAJOURI,2010,36,42,0,26,4,44,0,WOMEN,42_District_wise_crimes_committed_against_women_2001_2012.csv
6883,JAMMU & KASHMIR,RAMBAN,2010,6,17,0,11,2,0,0,WOMEN,42_District_wise_crimes_committed_against_women_2001_2012.csv

In [64]:
# ============================================================
# CELL 60B — RAW SOURCE CONTEXT
# ============================================================

print("=" * 90)
print("RAW SOURCE CONTEXT")
print("=" * 90)


for filename, duplicate_rows in duplicate_details.items():

    print("\n" + "=" * 90)
    print(f"RAW FILE: {filename}")
    print("=" * 90)

    file_path = RAW_DATA_DIR / filename

    # --------------------------------------------------------
    # Read raw source
    # --------------------------------------------------------

    raw_df, read_info = read_csv_for_inspection(
        file_path
    )

    if raw_df is None:

        print(
            "⚠ Could not read raw file."
        )

        continue

    # --------------------------------------------------------
    # Normalize raw column names ONLY for searching.
    # Data values are not changed.
    # --------------------------------------------------------

    raw_df = normalize_dimension_columns(
        raw_df
    )

    key_columns = [
        "STATE",
        "DISTRICT",
        "YEAR"
    ]

    missing_columns = [
        column
        for column in key_columns
        if column not in raw_df.columns
    ]

    if missing_columns:

        print(
            f"⚠ Required columns missing: "
            f"{missing_columns}"
        )

        print(
            "Available columns:"
        )

        print(
            raw_df.columns.tolist()
        )

        continue

    # --------------------------------------------------------
    # Unique duplicate keys
    # --------------------------------------------------------

    duplicate_keys = (
        duplicate_rows[
            key_columns
        ]
        .drop_duplicates()
        .itertuples(
            index=False,
            name=None
        )
    )

    # --------------------------------------------------------
    # Inspect each duplicate key
    # --------------------------------------------------------

    for key in duplicate_keys:

        mask = pd.Series(
            True,
            index=raw_df.index
        )

        for column, value in zip(
            key_columns,
            key
        ):

            if pd.isna(value):

                mask &= raw_df[column].isna()

            else:

                mask &= (
                    raw_df[column]
                    .astype("string")
                    .str.strip()
                    .eq(
                        str(value).strip()
                    )
                )

        matching_indices = (
            raw_df.index[mask]
            .tolist()
        )

        print("\n" + "-" * 80)
        print(
            f"DUPLICATE KEY: {key}"
        )
        print(
            f"RAW ROW INDICES: "
            f"{matching_indices}"
        )
        print("-" * 80)

        for idx in matching_indices:

            start = max(
                0,
                idx - 2
            )

            end = min(
                len(raw_df),
                idx + 3
            )

            print(
                f"\nRaw source context "
                f"around row {idx}:"
            )

            display(
                raw_df.iloc[
                    start:end
                ]
            )

==========================================================================================
RAW SOURCE CONTEXT
==========================================================================================

==========================================================================================
RAW FILE: 01_District_wise_crimes_committed_IPC_2001_2012.csv
==========================================================================================

--------------------------------------------------------------------------------
DUPLICATE KEY: ('JAMMU & KASHMIR', 'RAILWAYS', 2010)
RAW ROW INDICES: [6880, 6881]
--------------------------------------------------------------------------------

Raw source context around row 6880:

,STATE,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS,KIDNAPPING AND ABDUCTION OF OTHERS,DACOITY,PREPARATION AND ASSEMBLY FOR DACOITY,ROBBERY,BURGLARY,THEFT,AUTO THEFT,OTHER THEFT,RIOTS,CRIMINAL BREACH OF TRUST,CHEATING,COUNTERFIETING,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
6878,JAMMU & KASHMIR,POONCH,2010,12,37,1,20,0,20,39,34,5,0,0,0,23,31,3,28,132,4,8,0,0,54,0,30,10,16,0,4,529,950
6879,JAMMU & KASHMIR,PULWAMA,2010,4,10,2,8,0,8,33,31,2,1,0,4,37,80,10,70,172,3,7,3,8,55,0,11,13,0,0,2,164,617
6880,JAMMU & KASHMIR,RAILWAYS,2010,0,0,0,0,0,0,1,0,1,0,0,0,1,12,1,11,16,1,0,0,0,0,0,0,0,0,0,0,5,36
6881,JAMMU & KASHMIR,RAILWAYS,2010,1,0,1,1,0,1,0,0,0,0,0,0,0,8,1,7,0,0,0,0,0,0,0,0,0,0,0,0,10,21
6882,JAMMU & KASHMIR,RAJOURI,2010,15,36,6,36,0,36,47,42,5,2,0,0,44,52,20,32,33,10,15,0,22,30,0,26,4,44,0,38,1000,1460

Raw source context around row 6881:

,STATE,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS,KIDNAPPING AND ABDUCTION OF OTHERS,DACOITY,PREPARATION AND ASSEMBLY FOR DACOITY,ROBBERY,BURGLARY,THEFT,AUTO THEFT,OTHER THEFT,RIOTS,CRIMINAL BREACH OF TRUST,CHEATING,COUNTERFIETING,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
6879,JAMMU & KASHMIR,PULWAMA,2010,4,10,2,8,0,8,33,31,2,1,0,4,37,80,10,70,172,3,7,3,8,55,0,11,13,0,0,2,164,617
6880,JAMMU & KASHMIR,RAILWAYS,2010,0,0,0,0,0,0,1,0,1,0,0,0,1,12,1,11,16,1,0,0,0,0,0,0,0,0,0,0,5,36
6881,JAMMU & KASHMIR,RAILWAYS,2010,1,0,1,1,0,1,0,0,0,0,0,0,0,8,1,7,0,0,0,0,0,0,0,0,0,0,0,0,10,21
6882,JAMMU & KASHMIR,RAJOURI,2010,15,36,6,36,0,36,47,42,5,2,0,0,44,52,20,32,33,10,15,0,22,30,0,26,4,44,0,38,1000,1460
6883,JAMMU & KASHMIR,RAMBAN,2010,3,9,0,6,0,6,17,17,0,0,0,0,24,37,20,17,17,3,10,1,1,2,0,11,2,0,0,2,491,636

==========================================================================================
RAW FILE: 02_01_District_wise_crimes_committed_against_SC_2001_2012.csv
==========================================================================================

--------------------------------------------------------------------------------
DUPLICATE KEY: ('JAMMU & KASHMIR', 'ANANTNAG', 2001)
RAW ROW INDICES: [204, 205]
--------------------------------------------------------------------------------

Raw source context around row 204:

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping and Abduction,Dacoity,Robbery,Arson,Hurt,Prevention of atrocities (POA) Act,Protection of Civil Rights (PCR) Act,Other Crimes Against SCs
202,HIMACHAL PRADESH,UNA,2001,0,0,0,0,0,0,1,4,0,8
203,HIMACHAL PRADESH,TOTAL,2001,1,7,0,0,0,0,1,41,4,56
204,JAMMU & KASHMIR,ANANTNAG,2001,0,0,0,0,0,0,0,0,0,0
205,JAMMU & KASHMIR,ANANTNAG,2001,0,0,0,0,0,0,0,0,0,0
206,JAMMU & KASHMIR,AWANTIPORA,2001,0,0,0,0,0,0,0,0,0,0

Raw source context around row 205:

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping and Abduction,Dacoity,Robbery,Arson,Hurt,Prevention of atrocities (POA) Act,Protection of Civil Rights (PCR) Act,Other Crimes Against SCs
203,HIMACHAL PRADESH,TOTAL,2001,1,7,0,0,0,0,1,41,4,56
204,JAMMU & KASHMIR,ANANTNAG,2001,0,0,0,0,0,0,0,0,0,0
205,JAMMU & KASHMIR,ANANTNAG,2001,0,0,0,0,0,0,0,0,0,0
206,JAMMU & KASHMIR,AWANTIPORA,2001,0,0,0,0,0,0,0,0,0,0
207,JAMMU & KASHMIR,BARAMULLA,2001,0,0,0,0,0,0,0,0,0,0

--------------------------------------------------------------------------------
DUPLICATE KEY: ('NAGALAND', 'TOTAL', 2005)
RAW ROW INDICES: [3343, 3344]
--------------------------------------------------------------------------------

Raw source context around row 3343:

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping and Abduction,Dacoity,Robbery,Arson,Hurt,Prevention of atrocities (POA) Act,Protection of Civil Rights (PCR) Act,Other Crimes Against SCs
3341,NAGALAND,WOKHA,2005,0,0,0,0,0,0,0,0,0,0
3342,NAGALAND,ZUNHEBOTO,2005,0,0,0,0,0,0,0,0,0,0
3343,NAGALAND,TOTAL,2005,0,0,0,0,0,0,0,0,0,0
3344,NAGALAND,TOTAL,2005,0,0,0,0,0,0,0,0,0,0
3345,ODISHA,ANGUL,2005,0,2,0,0,0,0,14,13,0,8

Raw source context around row 3344:

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping and Abduction,Dacoity,Robbery,Arson,Hurt,Prevention of atrocities (POA) Act,Protection of Civil Rights (PCR) Act,Other Crimes Against SCs
3342,NAGALAND,ZUNHEBOTO,2005,0,0,0,0,0,0,0,0,0,0
3343,NAGALAND,TOTAL,2005,0,0,0,0,0,0,0,0,0,0
3344,NAGALAND,TOTAL,2005,0,0,0,0,0,0,0,0,0,0
3345,ODISHA,ANGUL,2005,0,2,0,0,0,0,14,13,0,8
3346,ODISHA,BALASORE,2005,0,1,0,0,1,0,46,0,0,8

==========================================================================================
RAW FILE: 02_District_wise_crimes_committed_against_ST_2001_2012.csv
==========================================================================================

--------------------------------------------------------------------------------
DUPLICATE KEY: ('JAMMU & KASHMIR', 'ANANTNAG', 2001)
RAW ROW INDICES: [204, 205]
--------------------------------------------------------------------------------

Raw source context around row 204:

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping Abduction,Dacoity,Robbery,Arson,Hurt,Protection of Civil Rights (PCR) Act,Prevention of atrocities (POA) Act,Other Crimes Against STs
202,HIMACHAL PRADESH,UNA,2001,0,0,0,0,0,0,0,0,0,0
203,HIMACHAL PRADESH,TOTAL,2001,0,0,0,0,0,0,0,0,2,2
204,JAMMU & KASHMIR,ANANTNAG,2001,0,0,0,0,0,0,0,0,0,0
205,JAMMU & KASHMIR,ANANTNAG,2001,0,0,0,0,0,0,0,0,0,0
206,JAMMU & KASHMIR,AWANTIPORA,2001,0,0,0,0,0,0,0,0,0,0

Raw source context around row 205:

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping Abduction,Dacoity,Robbery,Arson,Hurt,Protection of Civil Rights (PCR) Act,Prevention of atrocities (POA) Act,Other Crimes Against STs
203,HIMACHAL PRADESH,TOTAL,2001,0,0,0,0,0,0,0,0,2,2
204,JAMMU & KASHMIR,ANANTNAG,2001,0,0,0,0,0,0,0,0,0,0
205,JAMMU & KASHMIR,ANANTNAG,2001,0,0,0,0,0,0,0,0,0,0
206,JAMMU & KASHMIR,AWANTIPORA,2001,0,0,0,0,0,0,0,0,0,0
207,JAMMU & KASHMIR,BARAMULLA,2001,0,0,0,0,0,0,0,0,0,0

--------------------------------------------------------------------------------
DUPLICATE KEY: ('NAGALAND', 'TOTAL', 2005)
RAW ROW INDICES: [3343, 3344]
--------------------------------------------------------------------------------

Raw source context around row 3343:

         STATE   DISTRICT  YEAR  Murder  Rape  Kidnapping Abduction  Dacoity  Robbery  Arson  Hurt  Protection of Civil Rights (PCR) Act  Prevention of atrocities (POA) Act  Other Crimes Against STs
3341  NAGALAND      WOKHA  2005       0     0                     0        0        0      0     0                                     0                                   0                         0
3342  NAGALAND  ZUNHEBOTO  2005       0     0                     0        0        0      0     0                                     0                                   0                         0
3343  NAGALAND      TOTAL  2005       0     0                     0        0        0      0     0                                     0                                   0                         0
3344  NAGALAND      TOTAL  2005       0     0                     0        0        0      0     0                                     0                                   0                         0
3345    ODISHA      ANGUL  2005       0     1                     0        0        0      0     1                                     0                                   9                         3

Raw source context around row 3344:

         STATE   DISTRICT  YEAR  Murder  Rape  Kidnapping Abduction  Dacoity  Robbery  Arson  Hurt  Protection of Civil Rights (PCR) Act  Prevention of atrocities (POA) Act  Other Crimes Against STs
3342  NAGALAND  ZUNHEBOTO  2005       0     0                     0        0        0      0     0                                     0                                   0                         0
3343  NAGALAND      TOTAL  2005       0     0                     0        0        0      0     0                                     0                                   0                         0
3344  NAGALAND      TOTAL  2005       0     0                     0        0        0      0     0                                     0                                   0                         0
3345    ODISHA      ANGUL  2005       0     1                     0        0        0      0     1                                     0                                   9                         3
3346    ODISHA   BALASORE  2005       0     5                     0        0        1      0    20                                     0                                   0                         3

==========================================================================================
RAW FILE: 03_District_wise_crimes_committed_against_children_2001_2012.csv
==========================================================================================

--------------------------------------------------------------------------------
DUPLICATE KEY: ('NAGALAND', 'TOTAL', 2005)
RAW ROW INDICES: [3341, 3342]
--------------------------------------------------------------------------------

Raw source context around row 3341:

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping and Abduction,Foeticide,Abetment of suicide,Exposure and abandonment,Procuration of minor girls,Buying of girls for prostitution,Selling of girls for prostitution,Prohibition of child marriage act,Other Crimes,Total
3339,NAGALAND,WOKHA,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3340,NAGALAND,ZUNHEBOTO,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3341,NAGALAND,TOTAL,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3342,NAGALAND,TOTAL,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3343,ODISHA,ANGUL,2005,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,17

Raw source context around row 3342:

,STATE,DISTRICT,YEAR,Murder,Rape,Kidnapping and Abduction,Foeticide,Abetment of suicide,Exposure and abandonment,Procuration of minor girls,Buying of girls for prostitution,Selling of girls for prostitution,Prohibition of child marriage act,Other Crimes,Total
3340,NAGALAND,ZUNHEBOTO,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3341,NAGALAND,TOTAL,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3342,NAGALAND,TOTAL,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3343,ODISHA,ANGUL,2005,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,17
3344,ODISHA,BALASORE,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

==========================================================================================
RAW FILE: 42_District_wise_crimes_committed_against_women_2001_2012.csv
==========================================================================================

--------------------------------------------------------------------------------
DUPLICATE KEY: ('JAMMU & KASHMIR', 'RAILWAYS', 2010)
RAW ROW INDICES: [6880, 6881]
--------------------------------------------------------------------------------

Raw source context around row 6880:

,STATE,DISTRICT,YEAR,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
6878,JAMMU & KASHMIR,POONCH,2010,20,34,0,30,10,16,0
6879,JAMMU & KASHMIR,PULWAMA,2010,8,31,0,11,13,0,0
6880,JAMMU & KASHMIR,RAILWAYS,2010,0,0,0,0,0,0,0
6881,JAMMU & KASHMIR,RAILWAYS,2010,1,0,0,0,0,0,0
6882,JAMMU & KASHMIR,RAJOURI,2010,36,42,0,26,4,44,0

Raw source context around row 6881:

,STATE,DISTRICT,YEAR,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
6879,JAMMU & KASHMIR,PULWAMA,2010,8,31,0,11,13,0,0
6880,JAMMU & KASHMIR,RAILWAYS,2010,0,0,0,0,0,0,0
6881,JAMMU & KASHMIR,RAILWAYS,2010,1,0,0,0,0,0,0
6882,JAMMU & KASHMIR,RAJOURI,2010,36,42,0,26,4,44,0
6883,JAMMU & KASHMIR,RAMBAN,2010,6,17,0,11,2,0,0

In [65]:
# ============================================================
# CELL 61 — DEFINITIVE DUPLICATE CLASSIFICATION
# ============================================================

duplicate_audit_records = []

for filename, df in normalized_district_data.items():

    key_columns = [
        "STATE",
        "DISTRICT",
        "YEAR"
    ]

    # --------------------------------------------------------
    # Find duplicate keys
    # --------------------------------------------------------

    duplicate_mask = df.duplicated(
        subset=key_columns,
        keep=False
    )

    duplicate_df = df[
        duplicate_mask
    ].copy()

    if duplicate_df.empty:
        continue

    # --------------------------------------------------------
    # Analyze each duplicated key
    # --------------------------------------------------------

    for key, group in duplicate_df.groupby(
        key_columns,
        dropna=False
    ):

        # Remove key columns for comparison
        comparison_columns = [
            c
            for c in group.columns
            if c not in key_columns
        ]

        # ----------------------------------------------------
        # Check whether complete rows are identical
        # ----------------------------------------------------

        unique_records = (
            group[
                comparison_columns
            ]
            .drop_duplicates()
        )

        if len(unique_records) == 1:

            duplicate_type = (
                "EXACT_DUPLICATE"
            )

        else:

            duplicate_type = (
                "CONFLICTING_DUPLICATE"
            )

        duplicate_audit_records.append({

            "filename":
                filename,

            "state":
                key[0],

            "unit_name":
                key[1],

            "year":
                key[2],

            "row_count":
                len(group),

            "unique_record_count":
                len(unique_records),

            "duplicate_type":
                duplicate_type
        })


duplicate_audit_df = pd.DataFrame(
    duplicate_audit_records
)

print("=" * 80)
print("DEFINITIVE DUPLICATE CLASSIFICATION")
print("=" * 80)

display(
    duplicate_audit_df
)

================================================================================
DEFINITIVE DUPLICATE CLASSIFICATION
================================================================================

                                                           filename            state unit_name  year  row_count  unique_record_count         duplicate_type
0               01_District_wise_crimes_committed_IPC_2001_2012.csv  JAMMU & KASHMIR  RAILWAYS  2010          2                    2  CONFLICTING_DUPLICATE
1     02_01_District_wise_crimes_committed_against_SC_2001_2012.csv  JAMMU & KASHMIR  ANANTNAG  2001          2                    1        EXACT_DUPLICATE
2     02_01_District_wise_crimes_committed_against_SC_2001_2012.csv         NAGALAND     TOTAL  2005          2                    1        EXACT_DUPLICATE
3        02_District_wise_crimes_committed_against_ST_2001_2012.csv  JAMMU & KASHMIR  ANANTNAG  2001          2                    1        EXACT_DUPLICATE
4        02_District_wise_crimes_committed_against_ST_2001_2012.csv         NAGALAND     TOTAL  2005          2                    1        EXACT_DUPLICATE
5  03_District_wise_crimes_committed_against_children_2001_2012.csv         NAGALAND     TOTAL  2005          2                    1        EXACT_DUPLICATE
6     42_District_wise_crimes_committed_against_women_2001_2012.csv  JAMMU & KASHMIR  RAILWAYS  2010          2                    2  CONFLICTING_DUPLICATE

In [66]:
# ============================================================
# CELL 62 — DUPLICATE TYPE SUMMARY
# ============================================================

duplicate_type_summary = (
    duplicate_audit_df[
        "duplicate_type"
    ]
    .value_counts()
    .to_frame(
        "key_count"
    )
)

display(
    duplicate_type_summary
)

                       key_count
duplicate_type
EXACT_DUPLICATE                5
CONFLICTING_DUPLICATE          2

In [67]:
# ============================================================
# CELL 63 — CONFLICTING DUPLICATES ONLY
# ============================================================

conflicting_duplicates = (
    duplicate_audit_df[
        duplicate_audit_df[
            "duplicate_type"
        ]
        == "CONFLICTING_DUPLICATE"
    ]
    .sort_values(
        [
            "filename",
            "state",
            "unit_name",
            "year"
        ]
    )
)

print("=" * 80)
print("CONFLICTING DUPLICATES")
print("=" * 80)

display(
    conflicting_duplicates
)

================================================================================
CONFLICTING DUPLICATES
================================================================================

                                                        filename            state unit_name  year  row_count  unique_record_count         duplicate_type
0            01_District_wise_crimes_committed_IPC_2001_2012.csv  JAMMU & KASHMIR  RAILWAYS  2010          2                    2  CONFLICTING_DUPLICATE
6  42_District_wise_crimes_committed_against_women_2001_2012.csv  JAMMU & KASHMIR  RAILWAYS  2010          2                    2  CONFLICTING_DUPLICATE

In [68]:
# ============================================================
# CELL 64 — EXACT DUPLICATES ONLY
# ============================================================

exact_duplicates = (
    duplicate_audit_df[
        duplicate_audit_df[
            "duplicate_type"
        ]
        == "EXACT_DUPLICATE"
    ]
    .sort_values(
        [
            "filename",
            "state",
            "unit_name",
            "year"
        ]
    )
)

print("=" * 80)
print("EXACT DUPLICATES")
print("=" * 80)

display(
    exact_duplicates
)

================================================================================
EXACT DUPLICATES
================================================================================

                                                           filename            state unit_name  year  row_count  unique_record_count   duplicate_type
1     02_01_District_wise_crimes_committed_against_SC_2001_2012.csv  JAMMU & KASHMIR  ANANTNAG  2001          2                    1  EXACT_DUPLICATE
2     02_01_District_wise_crimes_committed_against_SC_2001_2012.csv         NAGALAND     TOTAL  2005          2                    1  EXACT_DUPLICATE
3        02_District_wise_crimes_committed_against_ST_2001_2012.csv  JAMMU & KASHMIR  ANANTNAG  2001          2                    1  EXACT_DUPLICATE
4        02_District_wise_crimes_committed_against_ST_2001_2012.csv         NAGALAND     TOTAL  2005          2                    1  EXACT_DUPLICATE
5  03_District_wise_crimes_committed_against_children_2001_2012.csv         NAGALAND     TOTAL  2005          2                    1  EXACT_DUPLICATE

In [69]:
# ============================================================
# CELL 65 — ADD SOURCE ROW IDENTIFIERS
# ============================================================

for filename, df in normalized_district_data.items():

    # Preserve the original row position
    df["SOURCE_ROW_ID"] = range(
        len(df)
    )

    # Unique identifier across all source files
    df["SOURCE_RECORD_ID"] = (
        filename
        + "::"
        + df["SOURCE_ROW_ID"]
        .astype(str)
    )

print(
    "✓ SOURCE_ROW_ID and SOURCE_RECORD_ID "
    "added to all district datasets."
)

✓ SOURCE_ROW_ID and SOURCE_RECORD_ID added to all district datasets.

In [70]:
# ============================================================
# CELL 66 — ADD DUPLICATE QUALITY FLAGS
# ============================================================

for filename, df in normalized_district_data.items():

    key_columns = [
        "STATE",
        "DISTRICT",
        "YEAR"
    ]

    duplicate_mask = df.duplicated(
        subset=key_columns,
        keep=False
    )

    df["DUPLICATE_KEY_FLAG"] = (
        duplicate_mask
    )

    df["DATA_QUALITY_FLAG"] = (
        "UNIQUE"
    )

    df.loc[
        duplicate_mask,
        "DATA_QUALITY_FLAG"
    ] = "DUPLICATE_KEY_REVIEW"

In [71]:
# ============================================================
# CELL 67 — CLASSIFY REPORTING UNIT
# ============================================================

def classify_unit_type(unit_value):

    if pd.isna(unit_value):
        return "MISSING"

    value = str(
        unit_value
    ).strip().upper()

    if value == "TOTAL":
        return "AGGREGATE"

    if "RAILWAY" in value:
        return "SPECIAL_UNIT"

    if "CITY" in value:
        return "SPECIAL_UNIT"

    if "RURAL" in value:
        return "SPECIAL_UNIT"

    if "URBAN" in value:
        return "SPECIAL_UNIT"

    return "DISTRICT_OR_REPORTING_UNIT"


for filename, df in normalized_district_data.items():

    df["UNIT_NAME"] = (
        df["DISTRICT"]
        .astype("string")
        .str.strip()
    )

    df["UNIT_TYPE"] = (
        df["UNIT_NAME"]
        .apply(
            classify_unit_type
        )
    )

print(
    "✓ UNIT_NAME and UNIT_TYPE added."
)

✓ UNIT_NAME and UNIT_TYPE added.

In [72]:
# ============================================================
# CELL 68 — FINAL DISTRICT AUDIT SUMMARY
# ============================================================

all_district_audit = []

for filename, df in normalized_district_data.items():

    all_district_audit.append({

        "filename":
            filename,

        "rows":
            len(df),

        "unique_rows":
            len(
                df.drop_duplicates()
            ),

        "duplicate_key_rows":
            int(
                df[
                    "DUPLICATE_KEY_FLAG"
                ].sum()
            ),

        "aggregate_rows":
            int(
                (
                    df["UNIT_TYPE"]
                    == "AGGREGATE"
                ).sum()
            ),

        "special_unit_rows":
            int(
                (
                    df["UNIT_TYPE"]
                    == "SPECIAL_UNIT"
                ).sum()
            ),

        "ordinary_reporting_rows":
            int(
                (
                    df["UNIT_TYPE"]
                    == "DISTRICT_OR_REPORTING_UNIT"
                ).sum()
            )
    })


district_audit_summary = pd.DataFrame(
    all_district_audit
)

display(
    district_audit_summary
)

                                                            filename  rows  unique_rows  duplicate_key_rows  aggregate_rows  special_unit_rows  ordinary_reporting_rows
0                01_District_wise_crimes_committed_IPC_2001_2012.csv  9017         9017                   2             408                477                     8132
1                     01_District_wise_crimes_committed_IPC_2013.csv   823          823                   0               0                 53                      770
2                     01_District_wise_crimes_committed_IPC_2014.csv   838          838                   0              36                 73                      729
3      02_01_District_wise_crimes_committed_against_SC_2001_2012.csv  9018         9018                   4             421                477                     8120
4           02_01_District_wise_crimes_committed_against_SC_2013.csv   823          823                   0              35                 53                      735
5           02_01_District_wise_crimes_committed_against_SC_2014.csv   837          837                   0              36                 73                      728
6         02_District_wise_crimes_committed_against_ST_2001_2012.csv  9018         9018                   4             421                477                     8120
7              02_District_wise_crimes_committed_against_ST_2013.csv   823          823                   0               0                 53                      770
8              02_District_wise_crimes_committed_against_ST_2014.csv   837          837                   0              36                 73                      728
9   03_District_wise_crimes_committed_against_children_2001_2012.csv  9015         9015                   2             412                474                     8129
10       03_District_wise_crimes_committed_against_children_2013.csv   823          823                   0              35                 53                      735
11     42_District_wise_crimes_committed_against_women_2001_2012.csv  9017         9017                   2             408                477                     8132
12          42_District_wise_crimes_committed_against_women_2013.csv   823          823                   0               0                 53                      770
13          42_District_wise_crimes_committed_against_women_2014.csv   837          837                   0              36                 73                      728

In [73]:
# ============================================================
# CELL 69 — REMOVE EXACT DUPLICATE COPIES
# ============================================================

cleaned_district_data = {}

exact_duplicate_removed_records = []

for filename, df in normalized_district_data.items():

    df = df.copy()

    original_rows = len(df)

    # --------------------------------------------------------
    # Remove only completely identical records.
    #
    # IMPORTANT:
    # We do NOT use STATE + DISTRICT + YEAR here.
    # --------------------------------------------------------

    df_clean = df.drop_duplicates(
        keep="first"
    ).copy()

    removed_rows = (
        original_rows -
        len(df_clean)
    )

    cleaned_district_data[
        filename
    ] = df_clean

    exact_duplicate_removed_records.append({

        "filename":
            filename,

        "original_rows":
            original_rows,

        "rows_after_exact_dedup":
            len(df_clean),

        "exact_duplicate_rows_removed":
            removed_rows
    })


exact_dedup_summary = pd.DataFrame(
    exact_duplicate_removed_records
)

print("=" * 80)
print("EXACT DUPLICATE REMOVAL")
print("=" * 80)

display(
    exact_dedup_summary[
        exact_dedup_summary[
            "exact_duplicate_rows_removed"
        ] > 0
    ]
)

print(
    "\nTotal exact duplicate rows removed:",
    exact_dedup_summary[
        "exact_duplicate_rows_removed"
    ].sum()
)

================================================================================
EXACT DUPLICATE REMOVAL
================================================================================

Empty DataFrame
Columns: [filename, original_rows, rows_after_exact_dedup, exact_duplicate_rows_removed]
Index: []

Total exact duplicate rows removed: 0

In [74]:
# ============================================================
# CELL 70 — FLAG CONFLICTING SOURCE RECORDS
# ============================================================

conflicting_keys = (
    conflicting_duplicates[
        [
            "filename",
            "state",
            "unit_name",
            "year"
        ]
    ]
    .copy()
)

print("=" * 80)
print("CONFLICTING SOURCE RECORDS")
print("=" * 80)

display(
    conflicting_keys
)

================================================================================
CONFLICTING SOURCE RECORDS
================================================================================

                                                        filename            state unit_name  year
0            01_District_wise_crimes_committed_IPC_2001_2012.csv  JAMMU & KASHMIR  RAILWAYS  2010
6  42_District_wise_crimes_committed_against_women_2001_2012.csv  JAMMU & KASHMIR  RAILWAYS  2010

In [75]:
# ============================================================
# CELL 71 — SOURCE QUALITY STATUS
# ============================================================

for filename, df in cleaned_district_data.items():

    # Default status
    df["SOURCE_QUALITY_STATUS"] = "VALID"

    # --------------------------------------------------------
    # Exact duplicate information
    # --------------------------------------------------------

    # Re-check duplicate keys
    key_columns = [
        "STATE",
        "DISTRICT",
        "YEAR"
    ]

    duplicate_key_mask = df.duplicated(
        subset=key_columns,
        keep=False
    )

    # --------------------------------------------------------
    # Conflicting keys
    # --------------------------------------------------------

    conflict_mask = pd.Series(
        False,
        index=df.index
    )

    for _, conflict in conflicting_keys[
        conflicting_keys["filename"]
        == filename
    ].iterrows():

        match = (
            df["STATE"].astype("string")
            .eq(
                str(
                    conflict["state"]
                )
            )
            &
            df["DISTRICT"].astype("string")
            .eq(
                str(
                    conflict["unit_name"]
                )
            )
            &
            df["YEAR"].eq(
                conflict["year"]
            )
        )

        conflict_mask |= match

    df.loc[
        duplicate_key_mask,
        "SOURCE_QUALITY_STATUS"
    ] = "DUPLICATE_KEY"

    df.loc[
        conflict_mask,
        "SOURCE_QUALITY_STATUS"
    ] = "CONFLICTING_SOURCE_RECORD"

print(
    "✓ Source quality status assigned."
)

✓ Source quality status assigned.

In [76]:
# ============================================================
# CELL 72 — BUILD CORE DISTRICT DATA
# ============================================================

core_district_data = {}

excluded_district_records = []

for filename, df in cleaned_district_data.items():

    # --------------------------------------------------------
    # Core modelling population
    # --------------------------------------------------------

    core_mask = (
        df["UNIT_TYPE"]
        == "DISTRICT_OR_REPORTING_UNIT"
    )

    valid_mask = (
        df["SOURCE_QUALITY_STATUS"]
        == "VALID"
    )

    final_mask = (
        core_mask
        &
        valid_mask
    )

    core_df = df[
        final_mask
    ].copy()

    excluded_df = df[
        ~final_mask
    ].copy()

    core_district_data[
        filename
    ] = core_df

    excluded_district_records.append({

        "filename":
            filename,

        "total_rows":
            len(df),

        "core_rows":
            len(core_df),

        "excluded_rows":
            len(excluded_df),

        "aggregate_rows":
            int(
                (
                    df["UNIT_TYPE"]
                    == "AGGREGATE"
                ).sum()
            ),

        "special_unit_rows":
            int(
                (
                    df["UNIT_TYPE"]
                    == "SPECIAL_UNIT"
                ).sum()
            ),

        "conflicting_rows":
            int(
                (
                    df[
                        "SOURCE_QUALITY_STATUS"
                    ]
                    == "CONFLICTING_SOURCE_RECORD"
                ).sum()
            )
    })


core_exclusion_summary = pd.DataFrame(
    excluded_district_records
)

display(
    core_exclusion_summary
)

                                                            filename  total_rows  core_rows  excluded_rows  aggregate_rows  special_unit_rows  conflicting_rows
0                01_District_wise_crimes_committed_IPC_2001_2012.csv        9017       8132            885             408                477                 2
1                     01_District_wise_crimes_committed_IPC_2013.csv         823        770             53               0                 53                 0
2                     01_District_wise_crimes_committed_IPC_2014.csv         838        729            109              36                 73                 0
3      02_01_District_wise_crimes_committed_against_SC_2001_2012.csv        9018       8118            900             421                477                 0
4           02_01_District_wise_crimes_committed_against_SC_2013.csv         823        735             88              35                 53                 0
5           02_01_District_wise_crimes_committed_against_SC_2014.csv         837        728            109              36                 73                 0
6         02_District_wise_crimes_committed_against_ST_2001_2012.csv        9018       8118            900             421                477                 0
7              02_District_wise_crimes_committed_against_ST_2013.csv         823        770             53               0                 53                 0
8              02_District_wise_crimes_committed_against_ST_2014.csv         837        728            109              36                 73                 0
9   03_District_wise_crimes_committed_against_children_2001_2012.csv        9015       8129            886             412                474                 0
10       03_District_wise_crimes_committed_against_children_2013.csv         823        735             88              35                 53                 0
11     42_District_wise_crimes_committed_against_women_2001_2012.csv        9017       8132            885             408                477                 2
12          42_District_wise_crimes_committed_against_women_2013.csv         823        770             53               0                 53                 0
13          42_District_wise_crimes_committed_against_women_2014.csv         837        728            109              36                 73                 0

In [77]:
# ============================================================
# CELL 73 — CORE DATA RETENTION AUDIT
# ============================================================

original_total = sum(
    len(df)
    for df in normalized_district_data.values()
)

cleaned_total = sum(
    len(df)
    for df in cleaned_district_data.values()
)

core_total = sum(
    len(df)
    for df in core_district_data.values()
)

print("=" * 80)
print("DATA RETENTION AUDIT")
print("=" * 80)

print(
    f"\nOriginal normalized rows : "
    f"{original_total:,}"
)

print(
    f"After exact dedup        : "
    f"{cleaned_total:,}"
)

print(
    f"Core district rows       : "
    f"{core_total:,}"
)

print(
    f"Rows excluded from core  : "
    f"{cleaned_total - core_total:,}"
)

================================================================================
DATA RETENTION AUDIT
================================================================================

Original normalized rows : 52,549
After exact dedup        : 52,549
Core district rows       : 47,322
Rows excluded from core  : 5,227

In [78]:
# ============================================================
# CELL 74 — CORE KEY UNIQUENESS CHECK
# ============================================================

core_key_results = []

for filename, df in core_district_data.items():

    key_columns = [
        "STATE",
        "UNIT_NAME",
        "YEAR"
    ]

    duplicate_count = (
        df.duplicated(
            subset=key_columns,
            keep=False
        )
        .sum()
    )

    core_key_results.append({

        "filename":
            filename,

        "core_rows":
            len(df),

        "duplicate_core_key_rows":
            int(duplicate_count),

        "core_key_unique":
            duplicate_count == 0
    })


core_key_audit = pd.DataFrame(
    core_key_results
)

display(
    core_key_audit
)

                                                            filename  core_rows  duplicate_core_key_rows  core_key_unique
0                01_District_wise_crimes_committed_IPC_2001_2012.csv       8132                        0             True
1                     01_District_wise_crimes_committed_IPC_2013.csv        770                        0             True
2                     01_District_wise_crimes_committed_IPC_2014.csv        729                        0             True
3      02_01_District_wise_crimes_committed_against_SC_2001_2012.csv       8118                        0             True
4           02_01_District_wise_crimes_committed_against_SC_2013.csv        735                        0             True
5           02_01_District_wise_crimes_committed_against_SC_2014.csv        728                        0             True
6         02_District_wise_crimes_committed_against_ST_2001_2012.csv       8118                        0             True
7              02_District_wise_crimes_committed_against_ST_2013.csv        770                        0             True
8              02_District_wise_crimes_committed_against_ST_2014.csv        728                        0             True
9   03_District_wise_crimes_committed_against_children_2001_2012.csv       8129                        0             True
10       03_District_wise_crimes_committed_against_children_2013.csv        735                        0             True
11     42_District_wise_crimes_committed_against_women_2001_2012.csv       8132                        0             True
12          42_District_wise_crimes_committed_against_women_2013.csv        770                        0             True
13          42_District_wise_crimes_committed_against_women_2014.csv        728                        0             True

In [79]:
# ============================================================
# CELL 75 — SAVE CLEANED DISTRICT SOURCES
# ============================================================

cleaned_dir = (
    PROCESSED_DATA_DIR /
    "district_cleaned"
)

cleaned_dir.mkdir(
    parents=True,
    exist_ok=True
)

for filename, df in cleaned_district_data.items():

    output_path = (
        cleaned_dir /
        filename
    )

    df.to_csv(
        output_path,
        index=False,
        encoding="utf-8-sig"
    )

print("=" * 80)
print("CLEANED DISTRICT SOURCES SAVED")
print("=" * 80)

print(
    cleaned_dir.resolve()
)

================================================================================
CLEANED DISTRICT SOURCES SAVED
================================================================================
D:\Major_Project\Crime_Analysis\data\processed\district_cleaned

In [80]:
# ============================================================
# CELL 76 — SAVE CORE MODELLING SOURCES
# ============================================================

core_dir = (
    PROCESSED_DATA_DIR /
    "district_core"
)

core_dir.mkdir(
    parents=True,
    exist_ok=True
)

for filename, df in core_district_data.items():

    output_path = (
        core_dir /
        filename
    )

    df.to_csv(
        output_path,
        index=False,
        encoding="utf-8-sig"
    )

print("=" * 80)
print("CORE DISTRICT SOURCES SAVED")
print("=" * 80)

print(
    core_dir.resolve()
)

================================================================================
CORE DISTRICT SOURCES SAVED
================================================================================
D:\Major_Project\Crime_Analysis\data\processed\district_core

In [81]:
# ============================================================
# CELL 77 — PREPARE CORE DATASETS FOR INTEGRATION
# ============================================================

integration_tables = {}

integration_key = [
    "STATE",
    "UNIT_NAME",
    "YEAR"
]

for filename, df in core_district_data.items():

    temp = df.copy()

    # --------------------------------------------------------
    # Keep the integration key
    # --------------------------------------------------------

    keep_key = [
        column
        for column in integration_key
        if column in temp.columns
    ]

    # --------------------------------------------------------
    # Identify crime-measure columns
    # --------------------------------------------------------

    excluded_columns = {
        "STATE",
        "DISTRICT",
        "UNIT_NAME",
        "YEAR",
        "CRIME_GROUP",
        "SOURCE_FILE",
        "SOURCE_ROW_ID",
        "SOURCE_RECORD_ID",
        "DUPLICATE_KEY_FLAG",
        "DATA_QUALITY_FLAG",
        "SOURCE_QUALITY_STATUS",
        "UNIT_TYPE"
    }

    measure_columns = [
        column
        for column in temp.columns
        if column not in excluded_columns
    ]

    # --------------------------------------------------------
    # Add crime-group prefix to every measure
    # --------------------------------------------------------

    crime_group = (
        temp["CRIME_GROUP"]
        .iloc[0]
    )

    rename_map = {}

    for column in measure_columns:

        rename_map[column] = (
            f"{crime_group}_{column}"
        )

    temp = temp[
        keep_key + measure_columns
    ].rename(
        columns=rename_map
    )

    # --------------------------------------------------------
    # Store prepared table
    # --------------------------------------------------------

    integration_tables[
        filename
    ] = temp

print("=" * 80)
print("INTEGRATION TABLES PREPARED")
print("=" * 80)

print(
    f"\nTables prepared: "
    f"{len(integration_tables)}"
)

for filename, df in integration_tables.items():

    print(
        f"{filename}: "
        f"{df.shape[0]:,} rows × "
        f"{df.shape[1]:,} columns"
    )

================================================================================
INTEGRATION TABLES PREPARED
================================================================================

Tables prepared: 14
01_District_wise_crimes_committed_IPC_2001_2012.csv: 8,132 rows × 33 columns
01_District_wise_crimes_committed_IPC_2013.csv: 770 rows × 33 columns
01_District_wise_crimes_committed_IPC_2014.csv: 729 rows × 91 columns
02_01_District_wise_crimes_committed_against_SC_2001_2012.csv: 8,118 rows × 13 columns
02_01_District_wise_crimes_committed_against_SC_2013.csv: 735 rows × 13 columns
02_01_District_wise_crimes_committed_against_SC_2014.csv: 728 rows × 66 columns
02_District_wise_crimes_committed_against_ST_2001_2012.csv: 8,118 rows × 13 columns
02_District_wise_crimes_committed_against_ST_2013.csv: 770 rows × 13 columns
02_District_wise_crimes_committed_against_ST_2014.csv: 728 rows × 66 columns
03_District_wise_crimes_committed_against_children_2001_2012.csv: 8,129 rows × 15 columns
03_District_wise_crimes_committed_against_children_2013.csv: 735 rows × 16 columns
42_District_wise_crimes_committed_against_women_2001_2012.csv: 8,132 rows × 10 columns
42_District_wise_crimes_committed_against_women_2013.csv: 770 rows × 10 columns
42_District_wise_crimes_committed_against_women_2014.csv: 728 rows × 62 columns

In [82]:
# ============================================================
# CELL 78 — CHECK FEATURE NAME COLLISIONS
# ============================================================

all_measure_columns = []

for filename, df in integration_tables.items():

    measure_columns = [
        column
        for column in df.columns
        if column not in integration_key
    ]

    all_measure_columns.extend(
        measure_columns
    )

column_counts = (
    pd.Series(
        all_measure_columns
    )
    .value_counts()
)

column_collisions = (
    column_counts[
        column_counts > 1
    ]
)

print("=" * 80)
print("FEATURE NAME COLLISION CHECK")
print("=" * 80)

if len(column_collisions) == 0:

    print(
        "\n✓ No feature-name collisions."
    )

else:

    print(
        "\n⚠ Feature-name collisions found:"
    )

    display(
        column_collisions
    )

================================================================================
FEATURE NAME COLLISION CHECK
================================================================================

⚠ Feature-name collisions found:

WOMEN_Cruelty by Husband or his Relatives        3
WOMEN_Dowry Deaths                               3
WOMEN_Rape                                       3
CHILDREN_Procuration of minor girls              2
SC_Murder                                        2
                                                ..
IPC_KIDNAPPING & ABDUCTION                       2
IPC_DACOITY                                      2
IPC_CUSTODIAL RAPE                               2
IPC_RAPE                                         2
IPC_CULPABLE HOMICIDE NOT AMOUNTING TO MURDER    2
Name: count, Length: 68, dtype: int64

In [83]:
# ============================================================
# CELL 79 — COMBINE FILES WITHIN EACH CRIME GROUP
# ============================================================

group_tables = {}

for filename, df in integration_tables.items():

    crime_group = (
        core_district_data[
            filename
        ]["CRIME_GROUP"]
        .iloc[0]
    )

    if crime_group not in group_tables:

        group_tables[
            crime_group
        ] = []

    group_tables[
        crime_group
    ].append(
        df
    )


combined_group_tables = {}

for crime_group, tables in group_tables.items():

    combined = pd.concat(
        tables,
        axis=0,
        ignore_index=True
    )

    combined_group_tables[
        crime_group
    ] = combined


print("=" * 80)
print("COMBINED CRIME GROUP TABLES")
print("=" * 80)

for crime_group, df in (
    combined_group_tables.items()
):

    print(
        f"{crime_group}: "
        f"{len(df):,} rows × "
        f"{len(df.columns):,} columns"
    )

================================================================================
COMBINED CRIME GROUP TABLES
================================================================================
IPC: 9,631 rows × 121 columns
SC: 9,581 rows × 76 columns
ST: 9,616 rows × 76 columns
CHILDREN: 8,864 rows × 17 columns
WOMEN: 9,630 rows × 66 columns

In [84]:
# ============================================================
# CELL 80 — GROUP KEY UNIQUENESS
# ============================================================

group_key_audit = []

for crime_group, df in (
    combined_group_tables.items()
):

    duplicate_count = (
        df.duplicated(
            subset=integration_key,
            keep=False
        )
        .sum()
    )

    group_key_audit.append({

        "crime_group":
            crime_group,

        "rows":
            len(df),

        "duplicate_key_rows":
            int(duplicate_count),

        "unique_keys":
            df[
                integration_key
            ].drop_duplicates().shape[0],

        "key_unique":
            duplicate_count == 0
    })


group_key_audit_df = pd.DataFrame(
    group_key_audit
)

display(
    group_key_audit_df
)

  crime_group  rows  duplicate_key_rows  unique_keys  key_unique
0         IPC  9631                   0         9631        True
1          SC  9581                   0         9581        True
2          ST  9616                   0         9616        True
3    CHILDREN  8864                   0         8864        True
4       WOMEN  9630                   0         9630        True

In [85]:
# ============================================================
# CELL 81 — HORIZONTAL INTEGRATION
# ============================================================

integrated_df = None

merge_order = [
    "IPC",
    "SC",
    "ST",
    "CHILDREN",
    "WOMEN"
]

for crime_group in merge_order:

    if crime_group not in combined_group_tables:
        continue

    group_df = (
        combined_group_tables[
            crime_group
        ]
        .copy()
    )

    if integrated_df is None:

        integrated_df = group_df

    else:

        integrated_df = integrated_df.merge(
            group_df,
            on=integration_key,
            how="outer",
            validate="one_to_one"
        )

    print(
        f"After {crime_group}: "
        f"{integrated_df.shape[0]:,} rows × "
        f"{integrated_df.shape[1]:,} columns"
    )

After IPC: 9,631 rows × 121 columns
After SC: 9,811 rows × 194 columns
After ST: 9,811 rows × 267 columns
After CHILDREN: 9,829 rows × 281 columns
After WOMEN: 9,856 rows × 344 columns

In [86]:
# ============================================================
# CELL 82 — INTEGRATION COVERAGE
# ============================================================

coverage_records = []

for crime_group in merge_order:

    if crime_group not in combined_group_tables:
        continue

    group_df = combined_group_tables[
        crime_group
    ]

    group_keys = set(
        map(
            tuple,
            group_df[
                integration_key
            ]
            .drop_duplicates()
            .values
        )
    )

    integrated_keys = set(
        map(
            tuple,
            integrated_df[
                integration_key
            ]
            .drop_duplicates()
            .values
        )
    )

    coverage_records.append({

        "crime_group":
            crime_group,

        "source_keys":
            len(group_keys),

        "integrated_keys":
            len(integrated_keys),

        "coverage_pct":
            round(
                100 *
                len(
                    group_keys &
                    integrated_keys
                )
                /
                len(integrated_keys),
                2
            )
    })


coverage_df = pd.DataFrame(
    coverage_records
)

display(
    coverage_df
)

  crime_group  source_keys  integrated_keys  coverage_pct
0         IPC         9631             9856         97.72
1          SC         9581             9856         97.21
2          ST         9616             9856         97.56
3    CHILDREN         8864             9856         89.94
4       WOMEN         9630             9856         97.71

In [87]:
# ============================================================
# CELL 83 — GROUP-LEVEL MISSINGNESS
# ============================================================

missingness_records = []

for crime_group in merge_order:

    prefix = f"{crime_group}_"

    group_columns = [
        column
        for column in integrated_df.columns
        if column.startswith(prefix)
    ]

    if not group_columns:
        continue

    missing_cells = (
        integrated_df[
            group_columns
        ]
        .isna()
        .sum()
        .sum()
    )

    total_cells = (
        integrated_df.shape[0]
        *
        len(group_columns)
    )

    missingness_records.append({

        "crime_group":
            crime_group,

        "feature_count":
            len(group_columns),

        "missing_cells":
            int(missing_cells),

        "missing_pct":
            round(
                100 *
                missing_cells /
                total_cells,
                2
            )
    })


missingness_by_group = pd.DataFrame(
    missingness_records
)

display(
    missingness_by_group
)

  crime_group  feature_count  missing_cells  missing_pct
0         IPC            118         831796        71.52
1          SC             73         585094        81.32
2          ST             73         584744        81.27
3    CHILDREN             14          30991        22.46
4       WOMEN             63         515662        83.05

In [88]:
# ============================================================
# CELL 85 — SAVE INTEGRATED DISTRICT DATASET
# ============================================================

integrated_output = (
    PROCESSED_DATA_DIR /
    "district_integrated_raw.csv"
)

integrated_df.to_csv(
    integrated_output,
    index=False,
    encoding="utf-8-sig"
)

print("=" * 80)
print("INTEGRATED DISTRICT DATASET SAVED")
print("=" * 80)

print(
    f"\nPath:"
)

print(
    integrated_output.resolve()
)

print(
    f"\nShape:"
    f" {integrated_df.shape[0]:,} rows × "
    f"{integrated_df.shape[1]:,} columns"
)

================================================================================
INTEGRATED DISTRICT DATASET SAVED
================================================================================

Path:
D:\Major_Project\Crime_Analysis\data\processed\district_integrated_raw.csv

Shape: 9,856 rows × 344 columns

In [89]:
# ============================================================
# CELL 86 — FINAL INTEGRATION AUDIT
# ============================================================

print("=" * 80)
print("FINAL DISTRICT INTEGRATION AUDIT")
print("=" * 80)

print(
    f"\nIntegrated rows    : "
    f"{len(integrated_df):,}"
)

print(
    f"Integrated columns : "
    f"{len(integrated_df.columns):,}"
)

print(
    f"Unique keys        : "
    f"{integrated_df[integration_key].drop_duplicates().shape[0]:,}"
)

print(
    f"Duplicate keys     : "
    f"{integrated_df.duplicated(integration_key).sum():,}"
)

print(
    f"Missing cells      : "
    f"{integrated_df.isna().sum().sum():,}"
)

print(
    f"Memory usage       : "
    f"{integrated_df.memory_usage(deep=True).sum() / 1024**2:.2f} MB"
)

print("\n✓ Integration completed.")

================================================================================
FINAL DISTRICT INTEGRATION AUDIT
================================================================================

Integrated rows    : 9,856
Integrated columns : 344
Unique keys        : 9,856
Duplicate keys     : 0
Missing cells      : 2,548,287
Memory usage       : 26.96 MB

✓ Integration completed.

In [90]:
# ============================================================
# CELL 87 — STRUCTURAL VS WITHIN-GROUP MISSINGNESS
# ============================================================

print("=" * 80)
print("STRUCTURAL VS WITHIN-GROUP MISSINGNESS")
print("=" * 80)

missingness_diagnosis = []

for crime_group in merge_order:

    if crime_group not in combined_group_tables:
        continue

    group_df = combined_group_tables[
        crime_group
    ].copy()

    # --------------------------------------------------------
    # Keys that actually exist in this crime group
    # --------------------------------------------------------

    group_keys = (
        group_df[
            integration_key
        ]
        .drop_duplicates()
    )

    group_key_set = set(
        map(
            tuple,
            group_keys.values
        )
    )

    # --------------------------------------------------------
    # Features belonging to this group
    # --------------------------------------------------------

    prefix = f"{crime_group}_"

    group_columns = [
        column
        for column in integrated_df.columns
        if column.startswith(prefix)
    ]

    # --------------------------------------------------------
    # Determine whether each integrated row has a source
    # record for this crime group.
    # --------------------------------------------------------

    row_keys = list(
        map(
            tuple,
            integrated_df[
                integration_key
            ].values
        )
    )

    group_present = pd.Series(
        [
            key in group_key_set
            for key in row_keys
        ],
        index=integrated_df.index
    )

    group_absent_rows = (
        ~group_present
    ).sum()

    group_present_rows = (
        group_present
    ).sum()

    # --------------------------------------------------------
    # Missing values among rows WHERE THE GROUP EXISTS
    # --------------------------------------------------------

    if group_present_rows > 0:

        present_data = integrated_df.loc[
            group_present,
            group_columns
        ]

        within_group_missing_cells = (
            present_data
            .isna()
            .sum()
            .sum()
        )

        total_present_cells = (
            present_data.shape[0]
            *
            present_data.shape[1]
        )

        within_group_missing_pct = (
            100
            *
            within_group_missing_cells
            /
            total_present_cells
        )

    else:

        within_group_missing_cells = 0
        within_group_missing_pct = 0

    # --------------------------------------------------------
    # Structural missingness
    # --------------------------------------------------------

    structural_missing_cells = (
        group_absent_rows
        *
        len(group_columns)
    )

    total_integrated_cells = (
        len(integrated_df)
        *
        len(group_columns)
    )

    structural_missing_pct = (
        100
        *
        structural_missing_cells
        /
        total_integrated_cells
    )

    missingness_diagnosis.append({

        "crime_group":
            crime_group,

        "integrated_rows":
            len(integrated_df),

        "group_present_rows":
            int(group_present_rows),

        "group_absent_rows":
            int(group_absent_rows),

        "feature_count":
            len(group_columns),

        "structural_missing_pct":
            round(
                structural_missing_pct,
                2
            ),

        "within_group_missing_pct":
            round(
                within_group_missing_pct,
                2
            )
    })


missingness_diagnosis_df = pd.DataFrame(
    missingness_diagnosis
)

display(
    missingness_diagnosis_df
)

================================================================================
STRUCTURAL VS WITHIN-GROUP MISSINGNESS
================================================================================

  crime_group  integrated_rows  group_present_rows  group_absent_rows  feature_count  structural_missing_pct  within_group_missing_pct
0         IPC             9856                9631                225            118                    2.28                     70.86
1          SC             9856                9581                275             73                    2.79                     80.78
2          ST             9856                9616                240             73                    2.44                     80.80
3    CHILDREN             9856                8864                992             14                   10.06                     13.78
4       WOMEN             9856                9630                226             63                    2.29                     82.65

In [91]:
# ============================================================
# CELL 88 — CRIME GROUP COVERAGE BY YEAR
# ============================================================

year_coverage_records = []

for crime_group in merge_order:

    if crime_group not in combined_group_tables:
        continue

    group_df = combined_group_tables[
        crime_group
    ]

    coverage = (
        group_df
        .groupby("YEAR")
        .size()
        .reset_index(
            name="source_rows"
        )
    )

    coverage[
        "crime_group"
    ] = crime_group

    year_coverage_records.append(
        coverage
    )


year_coverage_df = pd.concat(
    year_coverage_records,
    ignore_index=True
)

year_coverage_df = (
    year_coverage_df[
        [
            "crime_group",
            "YEAR",
            "source_rows"
        ]
    ]
    .sort_values(
        [
            "YEAR",
            "crime_group"
        ]
    )
)

display(
    year_coverage_df
)

   crime_group  YEAR  source_rows
42    CHILDREN  2001          651
0          IPC  2001          651
14          SC  2001          648
28          ST  2001          648
55       WOMEN  2001          651
..         ...   ...          ...
67       WOMEN  2013          770
13         IPC  2014          729
27          SC  2014          728
41          ST  2014          728
68       WOMEN  2014          728

[69 rows x 3 columns]

In [92]:
# ============================================================
# CELL 89 — CRIME GROUP AVAILABILITY MATRIX
# ============================================================

group_availability = integrated_df[
    integration_key
].copy()

for crime_group in merge_order:

    if crime_group not in combined_group_tables:
        continue

    group_keys = set(
        map(
            tuple,
            combined_group_tables[
                crime_group
            ][integration_key]
            .drop_duplicates()
            .values
        )
    )

    row_keys = list(
        map(
            tuple,
            integrated_df[
                integration_key
            ].values
        )
    )

    group_availability[
        f"{crime_group}_AVAILABLE"
    ] = [
        key in group_keys
        for key in row_keys
    ]


display(
    group_availability.head(20)
)

             STATE          UNIT_NAME  YEAR  IPC_AVAILABLE  SC_AVAILABLE  ST_AVAILABLE  CHILDREN_AVAILABLE  WOMEN_AVAILABLE
0   ANDHRA PRADESH           ADILABAD  2001           True          True          True                True             True
1   ANDHRA PRADESH          ANANTAPUR  2001           True          True          True                True             True
2   ANDHRA PRADESH           CHITTOOR  2001           True          True          True                True             True
3   ANDHRA PRADESH           CUDDAPAH  2001           True          True          True                True             True
4   ANDHRA PRADESH      EAST GODAVARI  2001           True          True          True                True             True
5   ANDHRA PRADESH      GUNTAKAL RLY.  2001           True          True          True                True             True
6   ANDHRA PRADESH             GUNTUR  2001           True          True          True                True             True
7   ANDHRA PRADESH         KARIMNAGAR  2001           True          True          True                True             True
8   ANDHRA PRADESH            KHAMMAM  2001           True          True          True                True             True
9   ANDHRA PRADESH            KRISHNA  2001           True          True          True                True             True
10  ANDHRA PRADESH            KURNOOL  2001           True          True          True                True             True
11  ANDHRA PRADESH      MAHABOOBNAGAR  2001           True          True          True                True             True
12  ANDHRA PRADESH              MEDAK  2001           True          True          True                True             True
13  ANDHRA PRADESH           NALGONDA  2001           True          True          True                True             True
14  ANDHRA PRADESH            NELLORE  2001           True          True          True                True             True
15  ANDHRA PRADESH          NIZAMABAD  2001           True          True          True                True             True
16  ANDHRA PRADESH          PRAKASHAM  2001           True          True          True                True             True
17  ANDHRA PRADESH        RANGA REDDY  2001           True          True          True                True             True
18  ANDHRA PRADESH  SECUNDERABAD RLY.  2001           True          True          True                True             True
19  ANDHRA PRADESH         SRIKAKULAM  2001           True          True          True                True             True

In [93]:
# ============================================================
# CELL 90 — AVAILABILITY COMBINATIONS
# ============================================================

availability_columns = [
    f"{group}_AVAILABLE"
    for group in merge_order
]

availability_patterns = (
    group_availability[
        availability_columns
    ]
    .astype(int)
    .astype(str)
    .agg(
        "".join,
        axis=1
    )
)

availability_summary = (
    availability_patterns
    .value_counts()
    .reset_index()
)

availability_summary.columns = [
    "availability_pattern",
    "row_count"
]

display(
    availability_summary
)

   availability_pattern  row_count
0                 11111       8664
1                 11101        737
2                 10000        184
3                 01111        151
4                 10101         35
5                 01110         28
6                 00001         27
7                 00010         13
8                 10001          8
9                 00011          5
10                10011          3
11                01100          1

In [96]:
# ============================================================
# CELL 93 — ADD SOURCE AVAILABILITY FLAGS
# ============================================================

for column in availability_columns:

    integrated_df[column] = (
        group_availability[column]
        .values
    )

print(
    "✓ Crime-group availability flags added."
)

display(
    integrated_df[
        integration_key
        + availability_columns
    ].head(10)
)

✓ Crime-group availability flags added.

            STATE      UNIT_NAME  YEAR  IPC_AVAILABLE  SC_AVAILABLE  ST_AVAILABLE  CHILDREN_AVAILABLE  WOMEN_AVAILABLE
0  ANDHRA PRADESH       ADILABAD  2001           True          True          True                True             True
1  ANDHRA PRADESH      ANANTAPUR  2001           True          True          True                True             True
2  ANDHRA PRADESH       CHITTOOR  2001           True          True          True                True             True
3  ANDHRA PRADESH       CUDDAPAH  2001           True          True          True                True             True
4  ANDHRA PRADESH  EAST GODAVARI  2001           True          True          True                True             True
5  ANDHRA PRADESH  GUNTAKAL RLY.  2001           True          True          True                True             True
6  ANDHRA PRADESH         GUNTUR  2001           True          True          True                True             True
7  ANDHRA PRADESH     KARIMNAGAR  2001           True          True          True                True             True
8  ANDHRA PRADESH        KHAMMAM  2001           True          True          True                True             True
9  ANDHRA PRADESH        KRISHNA  2001           True          True          True                True             True

In [94]:
# ============================================================
# CELL 91 — WITHIN-SOURCE MISSING VALUES
# ============================================================

within_source_missing_records = []

for crime_group, df in combined_group_tables.items():

    feature_columns = [
        column
        for column in df.columns
        if column not in integration_key
    ]

    for column in feature_columns:

        missing_count = int(
            df[column].isna().sum()
        )

        within_source_missing_records.append({

            "crime_group":
                crime_group,

            "feature":
                column,

            "rows":
                len(df),

            "missing_count":
                missing_count,

            "missing_pct":
                round(
                    100
                    *
                    missing_count
                    /
                    len(df),
                    2
                )
        })


within_source_missing_df = pd.DataFrame(
    within_source_missing_records
)

display(
    within_source_missing_df
    .sort_values(
        "missing_pct",
        ascending=False
    )
    .head(50)
)

    crime_group                                                           feature  rows  missing_count  missing_pct
340       WOMEN                                  WOMEN_Total Crimes against Women  9630           8902        92.44
312       WOMEN                   WOMEN_Culpable Homicide not amounting to Murder  9630           8902        92.44
285       WOMEN                                              WOMEN_Custodial Rape  9630           8902        92.44
286       WOMEN                                         WOMEN_Custodial_Gang Rape  9630           8902        92.44
287       WOMEN                                        WOMEN_Custodial_Other Rape  9630           8902        92.44
288       WOMEN                                   WOMEN_Rape other than Custodial  9630           8902        92.44
289       WOMEN                                              WOMEN_Rape_Gang Rape  9630           8902        92.44
290       WOMEN                                                 WOMEN_Rape_Others  9630           8902        92.44
291       WOMEN                                      WOMEN_Attempt to commit Rape  9630           8902        92.44
292       WOMEN                                WOMEN_Kidnapping & Abduction_Total  9630           8902        92.44
293       WOMEN                                       WOMEN_Kidnaping & Abduction  9630           8902        92.44
294       WOMEN                    WOMEN_Kidnaping & Abduction in order to Murder  9630           8902        92.44
295       WOMEN                                       WOMEN_Kidnapping for Ransom  9630           8902        92.44
296       WOMEN  WOMEN_Kidnapping & Abduction of Women to compel her for marriage  9630           8902        92.44
297       WOMEN                                WOMEN_Kidnaping & Abduction_Others  9630           8902        92.44
298       WOMEN   WOMEN_Assault on Women with intent to outrage her Modesty_Total  9630           8902        92.44
299       WOMEN                                           WOMEN_Sexual Harassment  9630           8902        92.44
300       WOMEN                     WOMEN_Assault on women with intent to Disrobe  9630           8902        92.44
301       WOMEN                                                   WOMEN_Voyeurism  9630           8902        92.44
302       WOMEN                                                    WOMEN_Stalking  9630           8902        92.44
303       WOMEN                                                      WOMEN_Others  9630           8902        92.44
304       WOMEN                        WOMEN_Insult to the Modesty of Women_Total  9630           8902        92.44
305       WOMEN                                          WOMEN_At Office premises  9630           8902        92.44
306       WOMEN                                   WOMEN_In places related to work  9630           8902        92.44
307       WOMEN                                  WOMEN_In Public Transport system  9630           8902        92.44
308       WOMEN                                             WOMEN_In other Places  9630           8902        92.44
309       WOMEN                   WOMEN_Importation of Girls from Foreign Country  9630           8902        92.44
311       WOMEN                                    WOMEN_Attempt to commit Murder  9630           8902        92.44
310       WOMEN                                                      WOMEN_Murder  9630           8902        92.44
313       WOMEN                         WOMEN_Attempt to commit Culpable Homicide  9630           8902        92.44
327       WOMEN                                          WOMEN_UnNatural Offences  9630           8902        92.44
314       WOMEN                                               WOMEN_Grievous Hurt  9630           8902        92.44
315       WOMEN                                                        WOMEN_Hurt  9630           8902        92.44
316       WOMEN                                                 WOMEN_Acid attack  9630           8902        92.44
317       WOMEN                                      WOMEN_Attempt to Acid Attack  9630           8902        92.44
318       WOMEN              WOMEN_Deaths caused with intent to cause miscarriage  9630           8902        92.44
320       WOMEN                                               WOMEN_Dacoity_Total  9630           8902        92.44
321       WOMEN                                         WOMEN_Dacoity with Murder  9630           8902        92.44
322       WOMEN                                               WOMEN_Other Dacoity  9630           8902        92.44
323       WOMEN                                                     WOMEN_Robbery  9630           8902        92.44
324       WOMEN                                                       WOMEN_Arson  9630           8902        92.44
325       WOMEN                                            WOMEN_HumanTrafficking  9630           8902        92.44
326       WOMEN                               WOMEN_Abetment of Suicides of Women  9630           8902        92.44
319       WOMEN                WOMEN_Causing miscarriage without consent of women  9630           8902        92.44
328       WOMEN                                            WOMEN_Other IPC Crimes  9630           8902        92.44
335       WOMEN                                         WOMEN_ITP Under Section 6  9630           8902        92.44
329       WOMEN                                 WOMEN_Dowry Prohibition Act, 1961  9630           8902        92.44
338       WOMEN                                    WOMEN_ITP Under Other Sections  9630           8902        92.44
337       WOMEN                                         WOMEN_ITP Under Section 8  9630           8902        92.44
336       WOMEN                                         WOMEN_ITP Under Section 7  9630           8902        92.44

In [95]:
# ============================================================
# CELL 92 — WITHIN-SOURCE MISSINGNESS SUMMARY
# ============================================================

within_source_summary = (
    within_source_missing_df
    .groupby("crime_group")
    .agg(
        features_with_missing_values=(
            "missing_count",
            lambda x: int(
                (x > 0).sum()
            )
        ),

        total_missing_cells=(
            "missing_count",
            "sum"
        ),

        maximum_feature_missing_pct=(
            "missing_pct",
            "max"
        ),

        average_feature_missing_pct=(
            "missing_pct",
            "mean"
        )
    )
    .reset_index()
)

within_source_summary[
    "average_feature_missing_pct"
] = within_source_summary[
    "average_feature_missing_pct"
].round(2)

display(
    within_source_summary
)

  crime_group  features_with_missing_values  total_missing_cells  maximum_feature_missing_pct  average_feature_missing_pct
0    CHILDREN                            13                17103                        91.71                        13.78
1         IPC                           118               805246                        92.43                        70.86
2          SC                            73               565019                        92.40                        80.78
3          ST                            73               567224                        92.43                        80.81
4       WOMEN                            60               501424                        92.44                        82.65

In [97]:
# ============================================================
# CELL 94 — FEATURE AVAILABILITY ACROSS SOURCE FILES
# ============================================================

feature_availability_records = []

for filename, df in integration_tables.items():

    # Get the crime group
    crime_group = (
        core_district_data[
            filename
        ]["CRIME_GROUP"]
        .iloc[0]
    )

    # Features actually present in this source file
    source_features = [
        column
        for column in df.columns
        if column not in integration_key
    ]

    for feature in source_features:

        feature_availability_records.append({

            "filename":
                filename,

            "crime_group":
                crime_group,

            "feature":
                feature,

            "source_rows":
                len(df),

            "missing_values_in_source":
                int(
                    df[feature]
                    .isna()
                    .sum()
                ),

            "missing_pct_in_source":
                round(
                    100
                    * df[feature].isna().mean(),
                    2
                )
        })


feature_availability_df = pd.DataFrame(
    feature_availability_records
)

print("=" * 80)
print("FEATURE AVAILABILITY ACROSS SOURCE FILES")
print("=" * 80)

display(
    feature_availability_df.head(50)
)

================================================================================
FEATURE AVAILABILITY ACROSS SOURCE FILES
================================================================================

                                               filename crime_group                                                  feature  source_rows  missing_values_in_source  missing_pct_in_source
0   01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                                               IPC_MURDER         8132                         0                    0.0
1   01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                                    IPC_ATTEMPT TO MURDER         8132                         0                    0.0
2   01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC            IPC_CULPABLE HOMICIDE NOT AMOUNTING TO MURDER         8132                         0                    0.0
3   01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                                                 IPC_RAPE         8132                         0                    0.0
4   01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                                       IPC_CUSTODIAL RAPE         8132                         0                    0.0
5   01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                                           IPC_OTHER RAPE         8132                         0                    0.0
6   01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                               IPC_KIDNAPPING & ABDUCTION         8132                         0                    0.0
7   01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC          IPC_KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS         8132                         0                    0.0
8   01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                   IPC_KIDNAPPING AND ABDUCTION OF OTHERS         8132                         0                    0.0
9   01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                                              IPC_DACOITY         8132                         0                    0.0
10  01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                 IPC_PREPARATION AND ASSEMBLY FOR DACOITY         8132                         0                    0.0
11  01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                                              IPC_ROBBERY         8132                         0                    0.0
12  01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                                             IPC_BURGLARY         8132                         0                    0.0
13  01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                                                IPC_THEFT         8132                         0                    0.0
14  01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                                           IPC_AUTO THEFT         8132                         0                    0.0
15  01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                                          IPC_OTHER THEFT         8132                         0                    0.0
16  01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                                                IPC_RIOTS         8132                         0                    0.0
17  01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                             IPC_CRIMINAL BREACH OF TRUST         8132                         0                    0.0
18  01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                                             IPC_CHEATING         8132                         0                    0.0
19  01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                                       IPC_COUNTERFIETING         8132                         0                    0.0
20  01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                                                IPC_ARSON         8132                         0                    0.0
21  01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                                   IPC_HURT/GREVIOUS HURT         8132                         0                    0.0
22  01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                                         IPC_DOWRY DEATHS         8132                         0                    0.0
23  01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC  IPC_ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY         8132                         0                    0.0
24  01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                           IPC_INSULT TO MODESTY OF WOMEN         8132                         0                    0.0
25  01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                  IPC_CRUELTY BY HUSBAND OR HIS RELATIVES         8132                         0                    0.0
26  01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC          IPC_IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES         8132                         0                    0.0
27  01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                          IPC_CAUSING DEATH BY NEGLIGENCE         8132                         0                    0.0
28  01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                                     IPC_OTHER IPC CRIMES         8132                         0                    0.0
29  01_District_wise_crimes_committed_IPC_2001_2012.csv         IPC                                     IPC_TOTAL IPC CRIMES         8132                         0                    0.0
30       01_District_wise_crimes_committed_IPC_2013.csv         IPC                                               IPC_MURDER          770                         0                    0.0
31       01_District_wise_crimes_committed_IPC_2013.csv         IPC                                    IPC_ATTEMPT TO MURDER          770                         0                    0.0
32       01_District_wise_crimes_committed_IPC_2013.csv         IPC            IPC_CULPABLE HOMICIDE NOT AMOUNTING TO MURDER          770                         0                    0.0
33       01_District_wise_crimes_committed_IPC_2013.csv         IPC                                                 IPC_RAPE          770                         0                    0.0
34       01_District_wise_crimes_committed_IPC_2013.csv         IPC                                       IPC_CUSTODIAL RAPE          770                         0                    0.0
35       01_District_wise_crimes_committed_IPC_2013.csv         IPC                                           IPC_OTHER RAPE          770                         0                    0.0
36       01_District_wise_crimes_committed_IPC_2013.csv         IPC                               IPC_KIDNAPPING & ABDUCTION          770                         0                    0.0
37       01_District_wise_crimes_committed_IPC_2013.csv         IPC          IPC_KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS          770                         0                    0.0
38       01_District_wise_crimes_committed_IPC_2013.csv         IPC                   IPC_KIDNAPPING AND ABDUCTION OF OTHERS          770                         0                    0.0
39       01_District_wise_crimes_committed_IPC_2013.csv         IPC                                              IPC_DACOITY          770                         0                    0.0
40       01_District_wise_crimes_committed_IPC_2013.csv         IPC                 IPC_PREPARATION AND ASSEMBLY FOR DACOITY          770                         0                    0.0
41       01_District_wise_crimes_committed_IPC_2013.csv         IPC                                              IPC_ROBBERY          770                         0                    0.0
42       01_District_wise_crimes_committed_IPC_2013.csv         IPC                                             IPC_BURGLARY          770                         0                    0.0
43       01_District_wise_crimes_committed_IPC_2013.csv         IPC                                                IPC_THEFT          770                         0                    0.0
44       01_District_wise_crimes_committed_IPC_2013.csv         IPC                                           IPC_AUTO THEFT          770                         0                    0.0
45       01_District_wise_crimes_committed_IPC_2013.csv         IPC                                          IPC_OTHER THEFT          770                         0                    0.0
46       01_District_wise_crimes_committed_IPC_2013.csv         IPC                                                IPC_RIOTS          770                         0                    0.0
47       01_District_wise_crimes_committed_IPC_2013.csv         IPC                             IPC_CRIMINAL BREACH OF TRUST          770                         0                    0.0
48       01_District_wise_crimes_committed_IPC_2013.csv         IPC                                             IPC_CHEATING          770                         0                    0.0
49       01_District_wise_crimes_committed_IPC_2013.csv         IPC                                       IPC_COUNTERFIETING          770                         0                    0.0

In [98]:
# ============================================================
# CELL 95 — SCHEMA EVOLUTION AUDIT
# ============================================================

schema_evolution_records = []

for crime_group in merge_order:

    group_data = (
        feature_availability_df[
            feature_availability_df[
                "crime_group"
            ]
            == crime_group
        ]
    )

    if group_data.empty:
        continue

    feature_file_counts = (
        group_data
        .groupby("feature")["filename"]
        .nunique()
        .reset_index(
            name="source_file_count"
        )
    )

    total_files = (
        group_data["filename"]
        .nunique()
    )

    feature_file_counts[
        "total_group_files"
    ] = total_files

    feature_file_counts[
        "availability_pct"
    ] = (
        100
        * feature_file_counts[
            "source_file_count"
        ]
        /
        total_files
    ).round(2)

    feature_file_counts[
        "crime_group"
    ] = crime_group

    schema_evolution_records.append(
        feature_file_counts
    )


schema_evolution_df = pd.concat(
    schema_evolution_records,
    ignore_index=True
)

display(
    schema_evolution_df
    .sort_values(
        [
            "crime_group",
            "availability_pct"
        ]
    )
)

                                       feature  source_file_count  total_group_files  availability_pct crime_group
268                        CHILDREN_Infanticid                  1                  2             50.00    CHILDREN
270                            CHILDREN_Murder                  1                  2             50.00    CHILDREN
272                      CHILDREN_Other murder                  1                  2             50.00    CHILDREN
264               CHILDREN_Abetment of suicide                  2                  2            100.00    CHILDREN
265  CHILDREN_Buying of girls for prostitution                  2                  2            100.00    CHILDREN
..                                         ...                ...                ...               ...         ...
316           WOMEN_Insult to modesty of Women                  2                  3             66.67       WOMEN
323             WOMEN_Kidnapping and Abduction                  2                  3             66.67       WOMEN
291  WOMEN_Cruelty by Husband or his Relatives                  3                  3            100.00       WOMEN
299                         WOMEN_Dowry Deaths                  3                  3            100.00       WOMEN
331                                 WOMEN_Rape                  3                  3            100.00       WOMEN

[341 rows x 5 columns]

In [99]:
# ============================================================
# CELL 96 — SCHEMA ABSENCE VS REAL SOURCE NaN
# ============================================================

schema_missingness_records = []

for crime_group in merge_order:

    group_files = [
        filename
        for filename in integration_tables
        if (
            core_district_data[
                filename
            ]["CRIME_GROUP"].iloc[0]
            == crime_group
        )
    ]

    for filename in group_files:

        df = integration_tables[
            filename
        ]

        for feature in df.columns:

            if feature in integration_key:
                continue

            schema_missingness_records.append({

                "crime_group":
                    crime_group,

                "filename":
                    filename,

                "feature":
                    feature,

                "source_rows":
                    len(df),

                "source_nan_count":
                    int(
                        df[feature]
                        .isna()
                        .sum()
                    ),

                "source_nan_pct":
                    round(
                        100
                        * df[feature].isna().mean(),
                        2
                    )
            })


source_nan_audit = pd.DataFrame(
    schema_missingness_records
)

display(
    source_nan_audit
    .sort_values(
        "source_nan_pct",
        ascending=False
    )
    .head(50)
)

    crime_group                                                          filename                                                            feature  source_rows  source_nan_count  source_nan_pct
320    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv                                CHILDREN_Procuration of minor girls         8129                10            0.12
315    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv                                                      CHILDREN_Rape         8129                10            0.12
323    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv                         CHILDREN_Prohibition of child marriage act         8129                10            0.12
322    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv                         CHILDREN_Selling of girls for prostitution         8129                10            0.12
321    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv                          CHILDREN_Buying of girls for prostitution         8129                10            0.12
319    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv                                  CHILDREN_Exposure and abandonment         8129                10            0.12
318    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv                                       CHILDREN_Abetment of suicide         8129                10            0.12
317    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv                                                 CHILDREN_Foeticide         8129                10            0.12
316    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv                                  CHILDREN_Kidnapping and Abduction         8129                10            0.12
314    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv                                                    CHILDREN_Murder         8129                10            0.12
324    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv                                              CHILDREN_Other Crimes         8129                10            0.12
270          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                         ST_POA_Dacoity with Murder          728                 0            0.00
272          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                                     ST_POA_Robbery          728                 0            0.00
273          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                                       ST_POA_Arson          728                 0            0.00
274          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                               ST_POA_Grievous Hurt          728                 0            0.00
275          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                                        ST_POA_Hurt          728                 0            0.00
276          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                                 ST_POA_Acid attack          728                 0            0.00
271          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                               ST_POA_Other Dacoity          728                 0            0.00
277          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                      ST_POA_Attempt to Acid Attack          728                 0            0.00
278          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                                       ST_POA_Riots          728                 0            0.00
279          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                            ST_POA_Other IPC crimes          728                 0            0.00
0           IPC               01_District_wise_crimes_committed_IPC_2001_2012.csv                                                         IPC_MURDER         8132                 0            0.00
281          ST             02_District_wise_crimes_committed_against_ST_2014.csv             ST_Total of SC/ST (Prevention of Atrocities) Act ,1989          728                 0            0.00
269          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                                     ST_POA_Dacoity          728                 0            0.00
268          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                            ST_POA_Other Kidnapping          728                 0            0.00
267          ST             02_District_wise_crimes_committed_against_ST_2014.csv  ST_POA_Kidnapping & Abduction of Women to compel her for marriage          728                 0            0.00
266          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                       ST_POA_Kidnapping for Ransom          728                 0            0.00
265          ST             02_District_wise_crimes_committed_against_ST_2014.csv                    ST_POA_Kidnaping & Abduction in order to Murder          728                 0            0.00
264          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                 ST_POA_Kidnaping & Abduction_Total          728                 0            0.00
263          ST             02_District_wise_crimes_committed_against_ST_2014.csv                           ST_POA_Kidnapping & Abduction_GrandTotal          728                 0            0.00
262          ST             02_District_wise_crimes_committed_against_ST_2014.csv                              ST_POA_Insult to the Modesty of women          728                 0            0.00
280          ST             02_District_wise_crimes_committed_against_ST_2014.csv                 ST_POA_SC / ST (Prevention of Atrocities) Act only          728                 0            0.00
287          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                           ST_IPC_Sexual Harassment          728                 0            0.00
282          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                                      ST_IPC_Murder          728                 0            0.00
293          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                      ST_IPC_Kidnapping & Abduction          728                 0            0.00
301          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                               ST_IPC_Other Dacoity          728                 0            0.00
300          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                         ST_IPC_Dacoity with Murder          728                 0            0.00
299          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                                     ST_IPC_Dacoity          728                 0            0.00
298          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                            ST_IPC_Other Kidnapping          728                 0            0.00
297          ST             02_District_wise_crimes_committed_against_ST_2014.csv  ST_IPC_Kidnapping & Abduction of Women to compel her for marriage          728                 0            0.00
296          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                       ST_IPC_Kidnapping for Ransom          728                 0            0.00
295          ST             02_District_wise_crimes_committed_against_ST_2014.csv                    ST_IPC_Kidnaping & Abduction in order to Murder          728                 0            0.00
294          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                       ST_IPC_Kidnaping & Abduction          728                 0            0.00
292          ST             02_District_wise_crimes_committed_against_ST_2014.csv                              ST_IPC_Insult to the Modesty of women          728                 0            0.00
283          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                    ST_IPC_Attempt to commit Murder          728                 0            0.00
291          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                     ST_IPC_Other Sexual Harassment          728                 0            0.00
290          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                                    ST_IPC_Stalking          728                 0            0.00
289          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                                   ST_IPC_Voyeurism          728                 0            0.00
288          ST             02_District_wise_crimes_committed_against_ST_2014.csv                     ST_IPC_Assault on women with intent to Disrobe          728                 0            0.00
303          ST             02_District_wise_crimes_committed_against_ST_2014.csv                                                       ST_IPC_Arson          728                 0            0.00

In [100]:
# ============================================================
# CELL 97 — GENUINE SOURCE-LEVEL MISSINGNESS
# ============================================================

genuine_missing_summary = (
    source_nan_audit[
        source_nan_audit[
            "source_nan_count"
        ] > 0
    ]
    .sort_values(
        "source_nan_pct",
        ascending=False
    )
)

print("=" * 80)
print("SOURCE-LEVEL MISSING VALUES")
print("=" * 80)

display(
    genuine_missing_summary.head(100)
)

================================================================================
SOURCE-LEVEL MISSING VALUES
================================================================================

    crime_group                                                          filename                                     feature  source_rows  source_nan_count  source_nan_pct
314    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv                             CHILDREN_Murder         8129                10            0.12
315    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv                               CHILDREN_Rape         8129                10            0.12
316    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv           CHILDREN_Kidnapping and Abduction         8129                10            0.12
317    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv                          CHILDREN_Foeticide         8129                10            0.12
318    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv                CHILDREN_Abetment of suicide         8129                10            0.12
319    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv           CHILDREN_Exposure and abandonment         8129                10            0.12
320    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv         CHILDREN_Procuration of minor girls         8129                10            0.12
321    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv   CHILDREN_Buying of girls for prostitution         8129                10            0.12
322    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv  CHILDREN_Selling of girls for prostitution         8129                10            0.12
323    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv  CHILDREN_Prohibition of child marriage act         8129                10            0.12
324    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv                       CHILDREN_Other Crimes         8129                10            0.12

In [101]:

# ============================================================
# CELL 98 — SAMPLE ACTUAL SOURCE NaN RECORDS
# ============================================================

for _, row in (
    genuine_missing_summary
    .head(10)
    .iterrows()
):

    filename = row["filename"]
    feature = row["feature"]

    df = integration_tables[
        filename
    ]

    missing_rows = df[
        df[feature].isna()
    ]

    if missing_rows.empty:
        continue

    print("\n" + "=" * 90)
    print(
        f"FILE: {filename}"
    )
    print(
        f"FEATURE: {feature}"
    )
    print(
        f"Missing rows: {len(missing_rows)}"
    )
    print("=" * 90)

    display(
        missing_rows[
            integration_key + [feature]
        ].head(10)
    )

==========================================================================================
FILE: 03_District_wise_crimes_committed_against_children_2001_2012.csv
FEATURE: CHILDREN_Murder
Missing rows: 10
==========================================================================================

          STATE   UNIT_NAME  YEAR  CHILDREN_Murder
8256      ASSAM       BAKSA  2012              NaN
8258      ASSAM        BIEO  2012              NaN
8260      ASSAM      C.I.D.  2012              NaN
8262      ASSAM     CHIRANG  2012              NaN
8267      ASSAM      G.R.P.  2012              NaN
8272      ASSAM      HAMREN  2012              NaN
8283      ASSAM      R.P.O.  2012              NaN
8287      ASSAM    UDALGURI  2012              NaN
8472  JHARKHAND      BOKARO  2012              NaN
8712     ODISHA  JHARSUGUDA  2012              NaN

==========================================================================================
FILE: 03_District_wise_crimes_committed_against_children_2001_2012.csv
FEATURE: CHILDREN_Rape
Missing rows: 10
==========================================================================================

          STATE   UNIT_NAME  YEAR  CHILDREN_Rape
8256      ASSAM       BAKSA  2012            NaN
8258      ASSAM        BIEO  2012            NaN
8260      ASSAM      C.I.D.  2012            NaN
8262      ASSAM     CHIRANG  2012            NaN
8267      ASSAM      G.R.P.  2012            NaN
8272      ASSAM      HAMREN  2012            NaN
8283      ASSAM      R.P.O.  2012            NaN
8287      ASSAM    UDALGURI  2012            NaN
8472  JHARKHAND      BOKARO  2012            NaN
8712     ODISHA  JHARSUGUDA  2012            NaN

==========================================================================================
FILE: 03_District_wise_crimes_committed_against_children_2001_2012.csv
FEATURE: CHILDREN_Kidnapping and Abduction
Missing rows: 10
==========================================================================================

          STATE   UNIT_NAME  YEAR  CHILDREN_Kidnapping and Abduction
8256      ASSAM       BAKSA  2012                                NaN
8258      ASSAM        BIEO  2012                                NaN
8260      ASSAM      C.I.D.  2012                                NaN
8262      ASSAM     CHIRANG  2012                                NaN
8267      ASSAM      G.R.P.  2012                                NaN
8272      ASSAM      HAMREN  2012                                NaN
8283      ASSAM      R.P.O.  2012                                NaN
8287      ASSAM    UDALGURI  2012                                NaN
8472  JHARKHAND      BOKARO  2012                                NaN
8712     ODISHA  JHARSUGUDA  2012                                NaN

==========================================================================================
FILE: 03_District_wise_crimes_committed_against_children_2001_2012.csv
FEATURE: CHILDREN_Foeticide
Missing rows: 10
==========================================================================================

          STATE   UNIT_NAME  YEAR  CHILDREN_Foeticide
8256      ASSAM       BAKSA  2012                 NaN
8258      ASSAM        BIEO  2012                 NaN
8260      ASSAM      C.I.D.  2012                 NaN
8262      ASSAM     CHIRANG  2012                 NaN
8267      ASSAM      G.R.P.  2012                 NaN
8272      ASSAM      HAMREN  2012                 NaN
8283      ASSAM      R.P.O.  2012                 NaN
8287      ASSAM    UDALGURI  2012                 NaN
8472  JHARKHAND      BOKARO  2012                 NaN
8712     ODISHA  JHARSUGUDA  2012                 NaN

==========================================================================================
FILE: 03_District_wise_crimes_committed_against_children_2001_2012.csv
FEATURE: CHILDREN_Abetment of suicide
Missing rows: 10
==========================================================================================

          STATE   UNIT_NAME  YEAR  CHILDREN_Abetment of suicide
8256      ASSAM       BAKSA  2012                           NaN
8258      ASSAM        BIEO  2012                           NaN
8260      ASSAM      C.I.D.  2012                           NaN
8262      ASSAM     CHIRANG  2012                           NaN
8267      ASSAM      G.R.P.  2012                           NaN
8272      ASSAM      HAMREN  2012                           NaN
8283      ASSAM      R.P.O.  2012                           NaN
8287      ASSAM    UDALGURI  2012                           NaN
8472  JHARKHAND      BOKARO  2012                           NaN
8712     ODISHA  JHARSUGUDA  2012                           NaN

==========================================================================================
FILE: 03_District_wise_crimes_committed_against_children_2001_2012.csv
FEATURE: CHILDREN_Exposure and abandonment
Missing rows: 10
==========================================================================================

          STATE   UNIT_NAME  YEAR  CHILDREN_Exposure and abandonment
8256      ASSAM       BAKSA  2012                                NaN
8258      ASSAM        BIEO  2012                                NaN
8260      ASSAM      C.I.D.  2012                                NaN
8262      ASSAM     CHIRANG  2012                                NaN
8267      ASSAM      G.R.P.  2012                                NaN
8272      ASSAM      HAMREN  2012                                NaN
8283      ASSAM      R.P.O.  2012                                NaN
8287      ASSAM    UDALGURI  2012                                NaN
8472  JHARKHAND      BOKARO  2012                                NaN
8712     ODISHA  JHARSUGUDA  2012                                NaN

==========================================================================================
FILE: 03_District_wise_crimes_committed_against_children_2001_2012.csv
FEATURE: CHILDREN_Procuration of minor girls
Missing rows: 10
==========================================================================================

          STATE   UNIT_NAME  YEAR  CHILDREN_Procuration of minor girls
8256      ASSAM       BAKSA  2012                                  NaN
8258      ASSAM        BIEO  2012                                  NaN
8260      ASSAM      C.I.D.  2012                                  NaN
8262      ASSAM     CHIRANG  2012                                  NaN
8267      ASSAM      G.R.P.  2012                                  NaN
8272      ASSAM      HAMREN  2012                                  NaN
8283      ASSAM      R.P.O.  2012                                  NaN
8287      ASSAM    UDALGURI  2012                                  NaN
8472  JHARKHAND      BOKARO  2012                                  NaN
8712     ODISHA  JHARSUGUDA  2012                                  NaN

==========================================================================================
FILE: 03_District_wise_crimes_committed_against_children_2001_2012.csv
FEATURE: CHILDREN_Buying of girls for prostitution
Missing rows: 10
==========================================================================================

          STATE   UNIT_NAME  YEAR  CHILDREN_Buying of girls for prostitution
8256      ASSAM       BAKSA  2012                                        NaN
8258      ASSAM        BIEO  2012                                        NaN
8260      ASSAM      C.I.D.  2012                                        NaN
8262      ASSAM     CHIRANG  2012                                        NaN
8267      ASSAM      G.R.P.  2012                                        NaN
8272      ASSAM      HAMREN  2012                                        NaN
8283      ASSAM      R.P.O.  2012                                        NaN
8287      ASSAM    UDALGURI  2012                                        NaN
8472  JHARKHAND      BOKARO  2012                                        NaN
8712     ODISHA  JHARSUGUDA  2012                                        NaN

==========================================================================================
FILE: 03_District_wise_crimes_committed_against_children_2001_2012.csv
FEATURE: CHILDREN_Selling of girls for prostitution
Missing rows: 10
==========================================================================================

          STATE   UNIT_NAME  YEAR  CHILDREN_Selling of girls for prostitution
8256      ASSAM       BAKSA  2012                                         NaN
8258      ASSAM        BIEO  2012                                         NaN
8260      ASSAM      C.I.D.  2012                                         NaN
8262      ASSAM     CHIRANG  2012                                         NaN
8267      ASSAM      G.R.P.  2012                                         NaN
8272      ASSAM      HAMREN  2012                                         NaN
8283      ASSAM      R.P.O.  2012                                         NaN
8287      ASSAM    UDALGURI  2012                                         NaN
8472  JHARKHAND      BOKARO  2012                                         NaN
8712     ODISHA  JHARSUGUDA  2012                                         NaN

==========================================================================================
FILE: 03_District_wise_crimes_committed_against_children_2001_2012.csv
FEATURE: CHILDREN_Prohibition of child marriage act
Missing rows: 10
==========================================================================================

          STATE   UNIT_NAME  YEAR  CHILDREN_Prohibition of child marriage act
8256      ASSAM       BAKSA  2012                                         NaN
8258      ASSAM        BIEO  2012                                         NaN
8260      ASSAM      C.I.D.  2012                                         NaN
8262      ASSAM     CHIRANG  2012                                         NaN
8267      ASSAM      G.R.P.  2012                                         NaN
8272      ASSAM      HAMREN  2012                                         NaN
8283      ASSAM      R.P.O.  2012                                         NaN
8287      ASSAM    UDALGURI  2012                                         NaN
8472  JHARKHAND      BOKARO  2012                                         NaN
8712     ODISHA  JHARSUGUDA  2012                                         NaN

In [102]:
# ============================================================
# CELL 99 — FEATURE SCHEMA SUMMARY
# ============================================================

schema_summary_records = []

for crime_group in merge_order:

    group_schema = (
        schema_evolution_df[
            schema_evolution_df[
                "crime_group"
            ]
            == crime_group
        ]
    )

    schema_summary_records.append({

        "crime_group":
            crime_group,

        "source_files":
            group_schema[
                "total_group_files"
            ].max(),

        "unique_features":
            group_schema[
                "feature"
            ].nunique(),

        "features_in_all_files":
            int(
                (
                    group_schema[
                        "availability_pct"
                    ]
                    == 100
                ).sum()
            ),

        "features_in_some_files":
            int(
                (
                    group_schema[
                        "availability_pct"
                    ]
                    < 100
                ).sum()
            )
    })


schema_summary_df = pd.DataFrame(
    schema_summary_records
)

display(
    schema_summary_df
)

  crime_group  source_files  unique_features  features_in_all_files  features_in_some_files
0         IPC             3              118                      0                     118
1          SC             3               73                      0                      73
2          ST             3               73                      0                      73
3    CHILDREN             2               14                     11                       3
4       WOMEN             3               63                      3                      60

In [103]:
# ============================================================
# CELL 100 — FEATURE METADATA
# ============================================================

feature_metadata_records = []

for crime_group in merge_order:

    group_schema = (
        schema_evolution_df[
            schema_evolution_df[
                "crime_group"
            ] == crime_group
        ]
        .copy()
    )

    for _, row in group_schema.iterrows():

        feature_metadata_records.append({

            "crime_group":
                crime_group,

            "feature":
                row["feature"],

            "source_file_count":
                int(
                    row["source_file_count"]
                ),

            "total_group_files":
                int(
                    row["total_group_files"]
                ),

            "availability_pct":
                float(
                    row["availability_pct"]
                ),

            "available_in_all_files":
                bool(
                    row["availability_pct"]
                    == 100
                )
        })


feature_metadata_df = pd.DataFrame(
    feature_metadata_records
)

print("=" * 80)
print("FEATURE METADATA")
print("=" * 80)

display(
    feature_metadata_df.head(30)
)

================================================================================
FEATURE METADATA
================================================================================

   crime_group                                                               feature  source_file_count  total_group_files  availability_pct  available_in_all_files
0          IPC                                                             IPC_ARSON                  2                  3             66.67                   False
1          IPC               IPC_ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY                  2                  3             66.67                   False
2          IPC                                                 IPC_ATTEMPT TO MURDER                  2                  3             66.67                   False
3          IPC                                                        IPC_AUTO THEFT                  2                  3             66.67                   False
4          IPC                                                       IPC_Acid attack                  1                  3             33.33                   False
5          IPC                                                             IPC_Arson                  1                  3             33.33                   False
6          IPC               IPC_Assault on Women with intent to outrage her Modesty                  1                  3             33.33                   False
7          IPC  IPC_Assault or use of criminal force to women with intent to Disrobe                  1                  3             33.33                   False
8          IPC                                                IPC_At Office premises                  1                  3             33.33                   False
9          IPC                                            IPC_Attempt to Acid Attack                  1                  3             33.33                   False
10         IPC                               IPC_Attempt to commit Culpable Homicide                  1                  3             33.33                   False
11         IPC                                          IPC_Attempt to commit Murder                  1                  3             33.33                   False
12         IPC                                            IPC_Attempt to commit Rape                  1                  3             33.33                   False
13         IPC                                                        IPC_Auto Theft                  1                  3             33.33                   False
14         IPC                                                          IPC_BURGLARY                  2                  3             66.67                   False
15         IPC                                       IPC_CAUSING DEATH BY NEGLIGENCE                  2                  3             66.67                   False
16         IPC                                                          IPC_CHEATING                  2                  3             66.67                   False
17         IPC                                                    IPC_COUNTERFIETING                  2                  3             66.67                   False
18         IPC                                          IPC_CRIMINAL BREACH OF TRUST                  2                  3             66.67                   False
19         IPC                               IPC_CRUELTY BY HUSBAND OR HIS RELATIVES                  2                  3             66.67                   False
20         IPC                         IPC_CULPABLE HOMICIDE NOT AMOUNTING TO MURDER                  2                  3             66.67                   False
21         IPC                                                    IPC_CUSTODIAL RAPE                  2                  3             66.67                   False
22         IPC                                       IPC_Causing Death by Negligence                  1                  3             33.33                   False
23         IPC                                                          IPC_Cheating                  1                  3             33.33                   False
24         IPC                  IPC_Counterfeit Offences related to Counterfeit Coin                  1                  3             33.33                   False
25         IPC                                 IPC_Counterfeit currency & Bank notes                  1                  3             33.33                   False
26         IPC                                                    IPC_Counterfeiting                  1                  3             33.33                   False
27         IPC                                   IPC_Counterfeiting Government Stamp                  1                  3             33.33                   False
28         IPC                          IPC_Counterfeiting currency notes/Bank notes                  1                  3             33.33                   False
29         IPC                                          IPC_Criminal Breach of Trust                  1                  3             33.33                   False

In [104]:
# ============================================================
# CELL 101 — FEATURE COVERAGE CLASSIFICATION
# ============================================================

def classify_feature_coverage(
    availability_pct
):

    if availability_pct == 100:
        return "COMMON_ACROSS_ALL_SOURCE_FILES"

    if availability_pct > 0:
        return "SCHEMA_VARIABLE_ACROSS_SOURCE_FILES"

    return "NOT_AVAILABLE"


feature_metadata_df[
    "feature_coverage_type"
] = (
    feature_metadata_df[
        "availability_pct"
    ]
    .apply(
        classify_feature_coverage
    )
)

display(
    feature_metadata_df[
        [
            "crime_group",
            "feature",
            "availability_pct",
            "feature_coverage_type"
        ]
    ]
)

    crime_group                                                  feature  availability_pct                feature_coverage_type
0           IPC                                                IPC_ARSON             66.67  SCHEMA_VARIABLE_ACROSS_SOURCE_FILES
1           IPC  IPC_ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY             66.67  SCHEMA_VARIABLE_ACROSS_SOURCE_FILES
2           IPC                                    IPC_ATTEMPT TO MURDER             66.67  SCHEMA_VARIABLE_ACROSS_SOURCE_FILES
3           IPC                                           IPC_AUTO THEFT             66.67  SCHEMA_VARIABLE_ACROSS_SOURCE_FILES
4           IPC                                          IPC_Acid attack             33.33  SCHEMA_VARIABLE_ACROSS_SOURCE_FILES
..          ...                                                      ...               ...                                  ...
336       WOMEN                                  WOMEN_Sexual Harassment             33.33  SCHEMA_VARIABLE_ACROSS_SOURCE_FILES
337       WOMEN                                           WOMEN_Stalking             33.33  SCHEMA_VARIABLE_ACROSS_SOURCE_FILES
338       WOMEN                         WOMEN_Total Crimes against Women             33.33  SCHEMA_VARIABLE_ACROSS_SOURCE_FILES
339       WOMEN                                 WOMEN_UnNatural Offences             33.33  SCHEMA_VARIABLE_ACROSS_SOURCE_FILES
340       WOMEN                                          WOMEN_Voyeurism             33.33  SCHEMA_VARIABLE_ACROSS_SOURCE_FILES

[341 rows x 4 columns]

In [105]:
# ============================================================
# CELL 102 — FEATURE COVERAGE SUMMARY
# ============================================================

feature_coverage_summary = (
    feature_metadata_df
    .groupby(
        [
            "crime_group",
            "feature_coverage_type"
        ]
    )
    .size()
    .reset_index(
        name="feature_count"
    )
)

display(
    feature_coverage_summary
)

  crime_group                feature_coverage_type  feature_count
0    CHILDREN       COMMON_ACROSS_ALL_SOURCE_FILES             11
1    CHILDREN  SCHEMA_VARIABLE_ACROSS_SOURCE_FILES              3
2         IPC  SCHEMA_VARIABLE_ACROSS_SOURCE_FILES            118
3          SC  SCHEMA_VARIABLE_ACROSS_SOURCE_FILES             73
4          ST  SCHEMA_VARIABLE_ACROSS_SOURCE_FILES             73
5       WOMEN       COMMON_ACROSS_ALL_SOURCE_FILES              3
6       WOMEN  SCHEMA_VARIABLE_ACROSS_SOURCE_FILES             60

In [106]:
# ============================================================
# CELL 103 — FEATURE-YEAR AVAILABILITY
# ============================================================

feature_year_records = []

for filename, df in integration_tables.items():

    crime_group = (
        core_district_data[
            filename
        ]["CRIME_GROUP"]
        .iloc[0]
    )

    # Determine years actually present in this source
    years = sorted(
        df["YEAR"]
        .dropna()
        .unique()
    )

    feature_columns = [
        column
        for column in df.columns
        if column not in integration_key
    ]

    for feature in feature_columns:

        for year in years:

            year_data = df[
                df["YEAR"] == year
            ]

            feature_year_records.append({

                "crime_group":
                    crime_group,

                "filename":
                    filename,

                "feature":
                    feature,

                "year":
                    year,

                "rows_for_year":
                    len(year_data),

                "missing_count":
                    int(
                        year_data[
                            feature
                        ].isna().sum()
                    ),

                "feature_present_in_schema":
                    True
            })


feature_year_availability_df = pd.DataFrame(
    feature_year_records
)

display(
    feature_year_availability_df.head(50)
)

   crime_group                                             filename                                        feature  year  rows_for_year  missing_count  feature_present_in_schema
0          IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                     IPC_MURDER  2001            651              0                       True
1          IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                     IPC_MURDER  2002            654              0                       True
2          IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                     IPC_MURDER  2003            660              0                       True
3          IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                     IPC_MURDER  2004            661              0                       True
4          IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                     IPC_MURDER  2005            665              0                       True
5          IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                     IPC_MURDER  2006            667              0                       True
6          IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                     IPC_MURDER  2007            669              0                       True
7          IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                     IPC_MURDER  2008            685              0                       True
8          IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                     IPC_MURDER  2009            690              0                       True
9          IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                     IPC_MURDER  2010            697              0                       True
10         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                     IPC_MURDER  2011            709              0                       True
11         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                     IPC_MURDER  2012            724              0                       True
12         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                          IPC_ATTEMPT TO MURDER  2001            651              0                       True
13         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                          IPC_ATTEMPT TO MURDER  2002            654              0                       True
14         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                          IPC_ATTEMPT TO MURDER  2003            660              0                       True
15         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                          IPC_ATTEMPT TO MURDER  2004            661              0                       True
16         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                          IPC_ATTEMPT TO MURDER  2005            665              0                       True
17         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                          IPC_ATTEMPT TO MURDER  2006            667              0                       True
18         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                          IPC_ATTEMPT TO MURDER  2007            669              0                       True
19         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                          IPC_ATTEMPT TO MURDER  2008            685              0                       True
20         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                          IPC_ATTEMPT TO MURDER  2009            690              0                       True
21         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                          IPC_ATTEMPT TO MURDER  2010            697              0                       True
22         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                          IPC_ATTEMPT TO MURDER  2011            709              0                       True
23         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                          IPC_ATTEMPT TO MURDER  2012            724              0                       True
24         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv  IPC_CULPABLE HOMICIDE NOT AMOUNTING TO MURDER  2001            651              0                       True
25         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv  IPC_CULPABLE HOMICIDE NOT AMOUNTING TO MURDER  2002            654              0                       True
26         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv  IPC_CULPABLE HOMICIDE NOT AMOUNTING TO MURDER  2003            660              0                       True
27         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv  IPC_CULPABLE HOMICIDE NOT AMOUNTING TO MURDER  2004            661              0                       True
28         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv  IPC_CULPABLE HOMICIDE NOT AMOUNTING TO MURDER  2005            665              0                       True
29         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv  IPC_CULPABLE HOMICIDE NOT AMOUNTING TO MURDER  2006            667              0                       True
30         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv  IPC_CULPABLE HOMICIDE NOT AMOUNTING TO MURDER  2007            669              0                       True
31         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv  IPC_CULPABLE HOMICIDE NOT AMOUNTING TO MURDER  2008            685              0                       True
32         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv  IPC_CULPABLE HOMICIDE NOT AMOUNTING TO MURDER  2009            690              0                       True
33         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv  IPC_CULPABLE HOMICIDE NOT AMOUNTING TO MURDER  2010            697              0                       True
34         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv  IPC_CULPABLE HOMICIDE NOT AMOUNTING TO MURDER  2011            709              0                       True
35         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv  IPC_CULPABLE HOMICIDE NOT AMOUNTING TO MURDER  2012            724              0                       True
36         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                       IPC_RAPE  2001            651              0                       True
37         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                       IPC_RAPE  2002            654              0                       True
38         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                       IPC_RAPE  2003            660              0                       True
39         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                       IPC_RAPE  2004            661              0                       True
40         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                       IPC_RAPE  2005            665              0                       True
41         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                       IPC_RAPE  2006            667              0                       True
42         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                       IPC_RAPE  2007            669              0                       True
43         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                       IPC_RAPE  2008            685              0                       True
44         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                       IPC_RAPE  2009            690              0                       True
45         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                       IPC_RAPE  2010            697              0                       True
46         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                       IPC_RAPE  2011            709              0                       True
47         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                       IPC_RAPE  2012            724              0                       True
48         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                             IPC_CUSTODIAL RAPE  2001            651              0                       True
49         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                             IPC_CUSTODIAL RAPE  2002            654              0                       True

In [107]:
# ============================================================
# CELL 104 — FEATURE TEMPORAL COVERAGE
# ============================================================

feature_temporal_coverage = (
    feature_year_availability_df
    .groupby(
        [
            "crime_group",
            "feature"
        ]
    )
    .agg(
        first_available_year=(
            "year",
            "min"
        ),

        last_available_year=(
            "year",
            "max"
        ),

        years_available=(
            "year",
            "nunique"
        )
    )
    .reset_index()
)

display(
    feature_temporal_coverage
)

    crime_group                                    feature  first_available_year  last_available_year  years_available
0      CHILDREN               CHILDREN_Abetment of suicide                  2001                 2013               13
1      CHILDREN  CHILDREN_Buying of girls for prostitution                  2001                 2013               13
2      CHILDREN          CHILDREN_Exposure and abandonment                  2001                 2013               13
3      CHILDREN                         CHILDREN_Foeticide                  2001                 2013               13
4      CHILDREN                        CHILDREN_Infanticid                  2013                 2013                1
..          ...                                        ...                   ...                  ...              ...
336       WOMEN                    WOMEN_Sexual Harassment                  2014                 2014                1
337       WOMEN                             WOMEN_Stalking                  2014                 2014                1
338       WOMEN           WOMEN_Total Crimes against Women                  2014                 2014                1
339       WOMEN                   WOMEN_UnNatural Offences                  2014                 2014                1
340       WOMEN                            WOMEN_Voyeurism                  2014                 2014                1

[341 rows x 5 columns]

In [108]:
# ============================================================
# CELL 105 — SAVE SCHEMA METADATA
# ============================================================

schema_output_dir = (
    OUTPUTS_DIR /
    "tables"
)

schema_output_dir.mkdir(
    parents=True,
    exist_ok=True
)

feature_metadata_path = (
    schema_output_dir /
    "integrated_feature_metadata.csv"
)

feature_temporal_path = (
    schema_output_dir /
    "feature_temporal_coverage.csv"
)

feature_metadata_df.to_csv(
    feature_metadata_path,
    index=False,
    encoding="utf-8-sig"
)

feature_temporal_coverage.to_csv(
    feature_temporal_path,
    index=False,
    encoding="utf-8-sig"
)

print("=" * 80)
print("SCHEMA METADATA SAVED")
print("=" * 80)

print(
    "\nFeature metadata:"
)

print(
    feature_metadata_path.resolve()
)

print(
    "\nFeature temporal coverage:"
)

print(
    feature_temporal_path.resolve()
)

NameError: name 'OUTPUTS_DIR' is not defined

In [109]:
# ============================================================
# CELL 105 — SAVE SCHEMA METADATA
# ============================================================

# Use the existing tables directory created earlier
schema_output_dir = TABLES_DIR

schema_output_dir.mkdir(
    parents=True,
    exist_ok=True
)

# ------------------------------------------------------------
# Output paths
# ------------------------------------------------------------

feature_metadata_path = (
    schema_output_dir /
    "integrated_feature_metadata.csv"
)

feature_temporal_path = (
    schema_output_dir /
    "feature_temporal_coverage.csv"
)

# ------------------------------------------------------------
# Save feature metadata
# ------------------------------------------------------------

feature_metadata_df.to_csv(
    feature_metadata_path,
    index=False,
    encoding="utf-8-sig"
)

# ------------------------------------------------------------
# Save temporal coverage
# ------------------------------------------------------------

feature_temporal_coverage.to_csv(
    feature_temporal_path,
    index=False,
    encoding="utf-8-sig"
)

# ------------------------------------------------------------
# Verification
# ------------------------------------------------------------

print("=" * 80)
print("SCHEMA METADATA SAVED")
print("=" * 80)

print(
    "\nFeature metadata:"
)

print(
    feature_metadata_path.resolve()
)

print(
    "\nFeature temporal coverage:"
)

print(
    feature_temporal_path.resolve()
)

print("\n✓ Both metadata files saved successfully.")

================================================================================
SCHEMA METADATA SAVED
================================================================================

Feature metadata:
D:\Major_Project\Crime_Analysis\outputs\tables\integrated_feature_metadata.csv

Feature temporal coverage:
D:\Major_Project\Crime_Analysis\outputs\tables\feature_temporal_coverage.csv

✓ Both metadata files saved successfully.

In [110]:
# ============================================================
# CELL 106 — CANONICAL FEATURE INVENTORY
# ============================================================

import re

def normalize_feature_label(feature_name, crime_group=None):

    value = str(feature_name).strip()

    # Remove crime-group prefix if present
    if crime_group:
        prefix = f"{crime_group}_"

        if value.upper().startswith(prefix.upper()):
            value = value[len(prefix):]

    # Normalize text mechanically
    value = value.upper()

    value = re.sub(
        r"[^A-Z0-9]+",
        "_",
        value
    )

    value = re.sub(
        r"_+",
        "_",
        value
    )

    value = value.strip("_")

    return value


feature_inventory_records = []

for filename, df in integration_tables.items():

    crime_group = (
        core_district_data[
            filename
        ]["CRIME_GROUP"]
        .iloc[0]
    )

    for feature in df.columns:

        if feature in integration_key:
            continue

        normalized_label = (
            normalize_feature_label(
                feature,
                crime_group
            )
        )

        feature_inventory_records.append({

            "crime_group":
                crime_group,

            "filename":
                filename,

            "source_feature":
                feature,

            "normalized_feature":
                normalized_label
        })


feature_inventory_df = pd.DataFrame(
    feature_inventory_records
)

print("=" * 80)
print("CANONICAL FEATURE INVENTORY")
print("=" * 80)

display(
    feature_inventory_df.head(50)
)

================================================================================
CANONICAL FEATURE INVENTORY
================================================================================

   crime_group                                             filename                                           source_feature                                   normalized_feature
0          IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                               IPC_MURDER                                               MURDER
1          IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                    IPC_ATTEMPT TO MURDER                                    ATTEMPT_TO_MURDER
2          IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv            IPC_CULPABLE HOMICIDE NOT AMOUNTING TO MURDER            CULPABLE_HOMICIDE_NOT_AMOUNTING_TO_MURDER
3          IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                                 IPC_RAPE                                                 RAPE
4          IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                       IPC_CUSTODIAL RAPE                                       CUSTODIAL_RAPE
5          IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                           IPC_OTHER RAPE                                           OTHER_RAPE
6          IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                               IPC_KIDNAPPING & ABDUCTION                                 KIDNAPPING_ABDUCTION
7          IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv          IPC_KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS          KIDNAPPING_AND_ABDUCTION_OF_WOMEN_AND_GIRLS
8          IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                   IPC_KIDNAPPING AND ABDUCTION OF OTHERS                   KIDNAPPING_AND_ABDUCTION_OF_OTHERS
9          IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                              IPC_DACOITY                                              DACOITY
10         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                 IPC_PREPARATION AND ASSEMBLY FOR DACOITY                 PREPARATION_AND_ASSEMBLY_FOR_DACOITY
11         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                              IPC_ROBBERY                                              ROBBERY
12         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                             IPC_BURGLARY                                             BURGLARY
13         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                                IPC_THEFT                                                THEFT
14         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                           IPC_AUTO THEFT                                           AUTO_THEFT
15         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                          IPC_OTHER THEFT                                          OTHER_THEFT
16         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                                IPC_RIOTS                                                RIOTS
17         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                             IPC_CRIMINAL BREACH OF TRUST                             CRIMINAL_BREACH_OF_TRUST
18         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                             IPC_CHEATING                                             CHEATING
19         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                       IPC_COUNTERFIETING                                       COUNTERFIETING
20         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                                IPC_ARSON                                                ARSON
21         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                   IPC_HURT/GREVIOUS HURT                                   HURT_GREVIOUS_HURT
22         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                         IPC_DOWRY DEATHS                                         DOWRY_DEATHS
23         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv  IPC_ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY  ASSAULT_ON_WOMEN_WITH_INTENT_TO_OUTRAGE_HER_MODESTY
24         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                           IPC_INSULT TO MODESTY OF WOMEN                           INSULT_TO_MODESTY_OF_WOMEN
25         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                  IPC_CRUELTY BY HUSBAND OR HIS RELATIVES                  CRUELTY_BY_HUSBAND_OR_HIS_RELATIVES
26         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv          IPC_IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES          IMPORTATION_OF_GIRLS_FROM_FOREIGN_COUNTRIES
27         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                          IPC_CAUSING DEATH BY NEGLIGENCE                          CAUSING_DEATH_BY_NEGLIGENCE
28         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                     IPC_OTHER IPC CRIMES                                     OTHER_IPC_CRIMES
29         IPC  01_District_wise_crimes_committed_IPC_2001_2012.csv                                     IPC_TOTAL IPC CRIMES                                     TOTAL_IPC_CRIMES
30         IPC       01_District_wise_crimes_committed_IPC_2013.csv                                               IPC_MURDER                                               MURDER
31         IPC       01_District_wise_crimes_committed_IPC_2013.csv                                    IPC_ATTEMPT TO MURDER                                    ATTEMPT_TO_MURDER
32         IPC       01_District_wise_crimes_committed_IPC_2013.csv            IPC_CULPABLE HOMICIDE NOT AMOUNTING TO MURDER            CULPABLE_HOMICIDE_NOT_AMOUNTING_TO_MURDER
33         IPC       01_District_wise_crimes_committed_IPC_2013.csv                                                 IPC_RAPE                                                 RAPE
34         IPC       01_District_wise_crimes_committed_IPC_2013.csv                                       IPC_CUSTODIAL RAPE                                       CUSTODIAL_RAPE
35         IPC       01_District_wise_crimes_committed_IPC_2013.csv                                           IPC_OTHER RAPE                                           OTHER_RAPE
36         IPC       01_District_wise_crimes_committed_IPC_2013.csv                               IPC_KIDNAPPING & ABDUCTION                                 KIDNAPPING_ABDUCTION
37         IPC       01_District_wise_crimes_committed_IPC_2013.csv          IPC_KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS          KIDNAPPING_AND_ABDUCTION_OF_WOMEN_AND_GIRLS
38         IPC       01_District_wise_crimes_committed_IPC_2013.csv                   IPC_KIDNAPPING AND ABDUCTION OF OTHERS                   KIDNAPPING_AND_ABDUCTION_OF_OTHERS
39         IPC       01_District_wise_crimes_committed_IPC_2013.csv                                              IPC_DACOITY                                              DACOITY
40         IPC       01_District_wise_crimes_committed_IPC_2013.csv                 IPC_PREPARATION AND ASSEMBLY FOR DACOITY                 PREPARATION_AND_ASSEMBLY_FOR_DACOITY
41         IPC       01_District_wise_crimes_committed_IPC_2013.csv                                              IPC_ROBBERY                                              ROBBERY
42         IPC       01_District_wise_crimes_committed_IPC_2013.csv                                             IPC_BURGLARY                                             BURGLARY
43         IPC       01_District_wise_crimes_committed_IPC_2013.csv                                                IPC_THEFT                                                THEFT
44         IPC       01_District_wise_crimes_committed_IPC_2013.csv                                           IPC_AUTO THEFT                                           AUTO_THEFT
45         IPC       01_District_wise_crimes_committed_IPC_2013.csv                                          IPC_OTHER THEFT                                          OTHER_THEFT
46         IPC       01_District_wise_crimes_committed_IPC_2013.csv                                                IPC_RIOTS                                                RIOTS
47         IPC       01_District_wise_crimes_committed_IPC_2013.csv                             IPC_CRIMINAL BREACH OF TRUST                             CRIMINAL_BREACH_OF_TRUST
48         IPC       01_District_wise_crimes_committed_IPC_2013.csv                                             IPC_CHEATING                                             CHEATING
49         IPC       01_District_wise_crimes_committed_IPC_2013.csv                                       IPC_COUNTERFIETING                                       COUNTERFIETING

In [111]:
# ============================================================
# CELL 107 — EXACT NORMALIZED FEATURE MATCHES
# ============================================================

normalized_feature_matches = (
    feature_inventory_df
    .groupby(
        [
            "crime_group",
            "normalized_feature"
        ]
    )
    .agg(
        source_feature_count=(
            "source_feature",
            "nunique"
        ),

        source_features=(
            "source_feature",
            lambda x: " | ".join(
                sorted(
                    x.astype(str).unique()
                )
            )
        ),

        source_files=(
            "filename",
            lambda x: " | ".join(
                sorted(
                    x.astype(str).unique()
                )
            )
        )
    )
    .reset_index()
)

# Only show features appearing under multiple
# source representations/files
exact_cross_source_matches = (
    normalized_feature_matches[
        normalized_feature_matches[
            "source_feature_count"
        ] > 1
    ]
    .sort_values(
        [
            "crime_group",
            "normalized_feature"
        ]
    )
)

print("=" * 80)
print("EXACT NORMALIZED CROSS-SOURCE MATCHES")
print("=" * 80)

display(
    exact_cross_source_matches
)

================================================================================
EXACT NORMALIZED CROSS-SOURCE MATCHES
================================================================================

,crime_group,normalized_feature,source_feature_count,source_features,source_files
15,IPC,ARSON,2,IPC_ARSON | IPC_Arson,01_District_wise_crimes_committed_IPC_2001_2012.csv | 01_District_wise_crimes_committed_IPC_2013.csv | 01_District_w...
16,IPC,ASSAULT_ON_WOMEN_WITH_INTENT_TO_OUTRAGE_HER_MODESTY,2,IPC_ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY | IPC_Assault on Women with intent to outrage her Modesty,01_District_wise_crimes_committed_IPC_2001_2012.csv | 01_District_wise_crimes_committed_IPC_2013.csv | 01_District_w...
24,IPC,AUTO_THEFT,2,IPC_AUTO THEFT | IPC_Auto Theft,01_District_wise_crimes_committed_IPC_2001_2012.csv | 01_District_wise_crimes_committed_IPC_2013.csv | 01_District_w...
26,IPC,CAUSING_DEATH_BY_NEGLIGENCE,2,IPC_CAUSING DEATH BY NEGLIGENCE | IPC_Causing Death by Negligence,01_District_wise_crimes_committed_IPC_2001_2012.csv | 01_District_wise_crimes_committed_IPC_2013.csv | 01_District_w...
27,IPC,CHEATING,2,IPC_CHEATING | IPC_Cheating,01_District_wise_crimes_committed_IPC_2001_2012.csv | 01_District_wise_crimes_committed_IPC_2013.csv | 01_District_w...
34,IPC,CRIMINAL_BREACH_OF_TRUST,2,IPC_CRIMINAL BREACH OF TRUST | IPC_Criminal Breach of Trust,01_District_wise_crimes_committed_IPC_2001_2012.csv | 01_District_wise_crimes_committed_IPC_2013.csv | 01_District_w...
37,IPC,CRUELTY_BY_HUSBAND_OR_HIS_RELATIVES,2,IPC_CRUELTY BY HUSBAND OR HIS RELATIVES | IPC_Cruelty by Husband or his Relatives,01_District_wise_crimes_committed_IPC_2001_2012.csv | 01_District_wise_crimes_committed_IPC_2013.csv | 01_District_w...
38,IPC,CULPABLE_HOMICIDE_NOT_AMOUNTING_TO_MURDER,2,IPC_CULPABLE HOMICIDE NOT AMOUNTING TO MURDER | IPC_Culpable Homicide not amounting to Murder,01_District_wise_crimes_committed_IPC_2001_2012.csv | 01_District_wise_crimes_committed_IPC_2013.csv | 01_District_w...
41,IPC,CUSTODIAL_RAPE,2,IPC_CUSTODIAL RAPE | IPC_Custodial Rape,01_District_wise_crimes_committed_IPC_2001_2012.csv | 01_District_wise_crimes_committed_IPC_2013.csv | 01_District_w...
42,IPC,DACOITY,2,IPC_DACOITY | IPC_Dacoity,01_District_wise_crimes_committed_IPC_2001_2012.csv | 01_District_wise_crimes_committed_IPC_2013.csv | 01_District_w...
47,IPC,DOWRY_DEATHS,2,IPC_DOWRY DEATHS | IPC_Dowry Deaths,01_District_wise_crimes_committed_IPC_2001_2012.csv | 01_District_wise_crimes_committed_IPC_2013.csv | 01_District_w...
62,IPC,KIDNAPPING_ABDUCTION,2,IPC_KIDNAPPING & ABDUCTION | IPC_Kidnapping & Abduction,01_District_wise_crimes_committed_IPC_2001_2012.csv | 01_District_wise_crimes_committed_IPC_2013.csv | 01_District_w...
72,IPC,MURDER,2,IPC_MURDER | IPC_Murder,01_District_wise_crimes_committed_IPC_2001_2012.csv | 01_District_wise_crimes_committed_IPC_2013.csv | 01_District_w...
77,IPC,OTHER_IPC_CRIMES,2,IPC_OTHER IPC CRIMES | IPC_Other IPC crimes,01_District_wise_crimes_committed_IPC_2001_2012.csv | 01_District_wise_crimes_committed_IPC_2013.csv | 01_District_w...
88,IPC,RAPE,2,IPC_RAPE | IPC_Rape,01_District_wise_crimes_committed_IPC_2001_2012.csv | 01_District_wise_crimes_committed_IPC_2013.csv | 01_District_w...
92,IPC,RIOTS,2,IPC_RIOTS | IPC_Riots,01_District_wise_crimes_committed_IPC_2001_2012.csv | 01_District_wise_crimes_committed_IPC_2013.csv | 01_District_w...
103,IPC,ROBBERY,2,IPC_ROBBERY | IPC_Robbery,01_District_wise_crimes_committed_IPC_2001_2012.csv | 01_District_wise_crimes_committed_IPC_2013.csv | 01_District_w...
107,IPC,THEFT,2,IPC_THEFT | IPC_Theft,01_District_wise_crimes_committed_IPC_2001_2012.csv | 01_District_wise_crimes_committed_IPC_2013.csv | 01_District_w...

In [112]:
# ============================================================
# CELL 108 — FEATURE INVENTORY BY SOURCE FILE
# ============================================================

feature_by_file = (
    feature_inventory_df[
        [
            "crime_group",
            "filename",
            "source_feature",
            "normalized_feature"
        ]
    ]
    .sort_values(
        [
            "crime_group",
            "filename",
            "source_feature"
        ]
    )
)

display(
    feature_by_file
)

    crime_group                                                          filename                             source_feature                normalized_feature
318    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv               CHILDREN_Abetment of suicide               ABETMENT_OF_SUICIDE
321    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv  CHILDREN_Buying of girls for prostitution  BUYING_OF_GIRLS_FOR_PROSTITUTION
319    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv          CHILDREN_Exposure and abandonment          EXPOSURE_AND_ABANDONMENT
317    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv                         CHILDREN_Foeticide                         FOETICIDE
316    CHILDREN  03_District_wise_crimes_committed_against_children_2001_2012.csv          CHILDREN_Kidnapping and Abduction          KIDNAPPING_AND_ABDUCTION
..          ...                                                               ...                                        ...                               ...
369       WOMEN          42_District_wise_crimes_committed_against_women_2014.csv                    WOMEN_Sexual Harassment                 SEXUAL_HARASSMENT
372       WOMEN          42_District_wise_crimes_committed_against_women_2014.csv                             WOMEN_Stalking                          STALKING
411       WOMEN          42_District_wise_crimes_committed_against_women_2014.csv           WOMEN_Total Crimes against Women        TOTAL_CRIMES_AGAINST_WOMEN
398       WOMEN          42_District_wise_crimes_committed_against_women_2014.csv                   WOMEN_UnNatural Offences                UNNATURAL_OFFENCES
371       WOMEN          42_District_wise_crimes_committed_against_women_2014.csv                            WOMEN_Voyeurism                         VOYEURISM

[412 rows x 4 columns]

In [113]:
# ============================================================
# CELL 110 — FEATURE MAPPING TEMPLATE
# ============================================================

feature_mapping_df = (
    feature_inventory_df[
        [
            "crime_group",
            "source_feature",
            "normalized_feature"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        [
            "crime_group",
            "normalized_feature"
        ]
    )
    .copy()
)

# Default:
# preserve the normalized feature name as the candidate
# canonical feature.
feature_mapping_df[
    "canonical_feature"
] = (
    feature_mapping_df[
        "normalized_feature"
    ]
)

# Manual review status
feature_mapping_df[
    "mapping_status"
] = "AUTO_NORMALIZED_ONLY"

# Keep the source variable unchanged
feature_mapping_df[
    "mapping_notes"
] = ""

print("=" * 80)
print("FEATURE MAPPING TEMPLATE")
print("=" * 80)

display(
    feature_mapping_df
)

================================================================================
FEATURE MAPPING TEMPLATE
================================================================================

    crime_group                             source_feature                normalized_feature                 canonical_feature        mapping_status mapping_notes
318    CHILDREN               CHILDREN_Abetment of suicide               ABETMENT_OF_SUICIDE               ABETMENT_OF_SUICIDE  AUTO_NORMALIZED_ONLY
321    CHILDREN  CHILDREN_Buying of girls for prostitution  BUYING_OF_GIRLS_FOR_PROSTITUTION  BUYING_OF_GIRLS_FOR_PROSTITUTION  AUTO_NORMALIZED_ONLY
319    CHILDREN          CHILDREN_Exposure and abandonment          EXPOSURE_AND_ABANDONMENT          EXPOSURE_AND_ABANDONMENT  AUTO_NORMALIZED_ONLY
317    CHILDREN                         CHILDREN_Foeticide                         FOETICIDE                         FOETICIDE  AUTO_NORMALIZED_ONLY
326    CHILDREN                        CHILDREN_Infanticid                        INFANTICID                        INFANTICID  AUTO_NORMALIZED_ONLY
..          ...                                        ...                               ...                               ...                   ...           ...
369       WOMEN                    WOMEN_Sexual Harassment                 SEXUAL_HARASSMENT                 SEXUAL_HARASSMENT  AUTO_NORMALIZED_ONLY
372       WOMEN                             WOMEN_Stalking                          STALKING                          STALKING  AUTO_NORMALIZED_ONLY
411       WOMEN           WOMEN_Total Crimes against Women        TOTAL_CRIMES_AGAINST_WOMEN        TOTAL_CRIMES_AGAINST_WOMEN  AUTO_NORMALIZED_ONLY
398       WOMEN                   WOMEN_UnNatural Offences                UNNATURAL_OFFENCES                UNNATURAL_OFFENCES  AUTO_NORMALIZED_ONLY
371       WOMEN                            WOMEN_Voyeurism                         VOYEURISM                         VOYEURISM  AUTO_NORMALIZED_ONLY

[341 rows x 6 columns]

In [114]:
# ============================================================
# CELL 111 — SAVE FEATURE MAPPING TEMPLATE
# ============================================================

feature_mapping_path = (
    TABLES_DIR /
    "feature_mapping_template.csv"
)

feature_mapping_df.to_csv(
    feature_mapping_path,
    index=False,
    encoding="utf-8-sig"
)

print("=" * 80)
print("FEATURE MAPPING TEMPLATE SAVED")
print("=" * 80)

print(
    feature_mapping_path.resolve()
)

================================================================================
FEATURE MAPPING TEMPLATE SAVED
================================================================================
D:\Major_Project\Crime_Analysis\outputs\tables\feature_mapping_template.csv

In [115]:
# ============================================================
# CELL 112 — APPLY SAFE CANONICAL FEATURE NAMES
# ============================================================

# Make a working copy
canonical_feature_mapping = (
    feature_mapping_df.copy()
)

# ------------------------------------------------------------
# Only exact mechanical normalization is automatically
# accepted at this stage.
# ------------------------------------------------------------

canonical_feature_mapping[
    "canonical_feature"
] = (
    canonical_feature_mapping[
        "normalized_feature"
    ]
)

canonical_feature_mapping[
    "mapping_status"
] = "EXACT_NORMALIZED_MATCH"

# ------------------------------------------------------------
# No semantic assumptions have been made.
# ------------------------------------------------------------

canonical_feature_mapping[
    "mapping_notes"
] = (
    "Canonicalized by exact mechanical "
    "name normalization only."
)

print("=" * 80)
print("SAFE CANONICAL FEATURE MAPPING")
print("=" * 80)

display(
    canonical_feature_mapping
)

================================================================================
SAFE CANONICAL FEATURE MAPPING
================================================================================

,crime_group,source_feature,normalized_feature,canonical_feature,mapping_status,mapping_notes
318,CHILDREN,CHILDREN_Abetment of suicide,ABETMENT_OF_SUICIDE,ABETMENT_OF_SUICIDE,EXACT_NORMALIZED_MATCH,Canonicalized by exact mechanical name normalization only.
321,CHILDREN,CHILDREN_Buying of girls for prostitution,BUYING_OF_GIRLS_FOR_PROSTITUTION,BUYING_OF_GIRLS_FOR_PROSTITUTION,EXACT_NORMALIZED_MATCH,Canonicalized by exact mechanical name normalization only.
319,CHILDREN,CHILDREN_Exposure and abandonment,EXPOSURE_AND_ABANDONMENT,EXPOSURE_AND_ABANDONMENT,EXACT_NORMALIZED_MATCH,Canonicalized by exact mechanical name normalization only.
317,CHILDREN,CHILDREN_Foeticide,FOETICIDE,FOETICIDE,EXACT_NORMALIZED_MATCH,Canonicalized by exact mechanical name normalization only.
326,CHILDREN,CHILDREN_Infanticid,INFANTICID,INFANTICID,EXACT_NORMALIZED_MATCH,Canonicalized by exact mechanical name normalization only.
...,...,...,...,...,...,...
369,WOMEN,WOMEN_Sexual Harassment,SEXUAL_HARASSMENT,SEXUAL_HARASSMENT,EXACT_NORMALIZED_MATCH,Canonicalized by exact mechanical name normalization only.
372,WOMEN,WOMEN_Stalking,STALKING,STALKING,EXACT_NORMALIZED_MATCH,Canonicalized by exact mechanical name normalization only.
411,WOMEN,WOMEN_Total Crimes against Women,TOTAL_CRIMES_AGAINST_WOMEN,TOTAL_CRIMES_AGAINST_WOMEN,EXACT_NORMALIZED_MATCH,Canonicalized by exact mechanical name normalization only.
398,WOMEN,WOMEN_UnNatural Offences,UNNATURAL_OFFENCES,UNNATURAL_OFFENCES,EXACT_NORMALIZED_MATCH,Canonicalized by exact mechanical name normalization only.
371,WOMEN,WOMEN_Voyeurism,VOYEURISM,VOYEURISM,EXACT_NORMALIZED_MATCH,Canonicalized by exact mechanical name normalization only.

In [116]:
# ============================================================
# CELL 113 — CANONICAL FEATURE COLLISION AUDIT
# ============================================================

canonical_collision_audit = (
    canonical_feature_mapping
    .groupby(
        [
            "crime_group",
            "canonical_feature"
        ]
    )
    .agg(
        source_feature_count=(
            "source_feature",
            "nunique"
        ),

        source_features=(
            "source_feature",
            lambda x: " | ".join(
                sorted(
                    x.astype(str).unique()
                )
            )
        )
    )
    .reset_index()
)

canonical_collisions = (
    canonical_collision_audit[
        canonical_collision_audit[
            "source_feature_count"
        ] > 1
    ]
    .sort_values(
        [
            "crime_group",
            "canonical_feature"
        ]
    )
)

print("=" * 80)
print("CANONICAL FEATURE COLLISION AUDIT")
print("=" * 80)

print(
    f"\nCanonical features with "
    f"multiple source representations: "
    f"{len(canonical_collisions)}"
)

display(
    canonical_collisions
)

================================================================================
CANONICAL FEATURE COLLISION AUDIT
================================================================================

Canonical features with multiple source representations: 18

,crime_group,canonical_feature,source_feature_count,source_features
15,IPC,ARSON,2,IPC_ARSON | IPC_Arson
16,IPC,ASSAULT_ON_WOMEN_WITH_INTENT_TO_OUTRAGE_HER_MODESTY,2,IPC_ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY | IPC_Assault on Women with intent to outrage her Modesty
24,IPC,AUTO_THEFT,2,IPC_AUTO THEFT | IPC_Auto Theft
26,IPC,CAUSING_DEATH_BY_NEGLIGENCE,2,IPC_CAUSING DEATH BY NEGLIGENCE | IPC_Causing Death by Negligence
27,IPC,CHEATING,2,IPC_CHEATING | IPC_Cheating
34,IPC,CRIMINAL_BREACH_OF_TRUST,2,IPC_CRIMINAL BREACH OF TRUST | IPC_Criminal Breach of Trust
37,IPC,CRUELTY_BY_HUSBAND_OR_HIS_RELATIVES,2,IPC_CRUELTY BY HUSBAND OR HIS RELATIVES | IPC_Cruelty by Husband or his Relatives
38,IPC,CULPABLE_HOMICIDE_NOT_AMOUNTING_TO_MURDER,2,IPC_CULPABLE HOMICIDE NOT AMOUNTING TO MURDER | IPC_Culpable Homicide not amounting to Murder
41,IPC,CUSTODIAL_RAPE,2,IPC_CUSTODIAL RAPE | IPC_Custodial Rape
42,IPC,DACOITY,2,IPC_DACOITY | IPC_Dacoity
47,IPC,DOWRY_DEATHS,2,IPC_DOWRY DEATHS | IPC_Dowry Deaths
62,IPC,KIDNAPPING_ABDUCTION,2,IPC_KIDNAPPING & ABDUCTION | IPC_Kidnapping & Abduction
72,IPC,MURDER,2,IPC_MURDER | IPC_Murder
77,IPC,OTHER_IPC_CRIMES,2,IPC_OTHER IPC CRIMES | IPC_Other IPC crimes
88,IPC,RAPE,2,IPC_RAPE | IPC_Rape
92,IPC,RIOTS,2,IPC_RIOTS | IPC_Riots
103,IPC,ROBBERY,2,IPC_ROBBERY | IPC_Robbery
107,IPC,THEFT,2,IPC_THEFT | IPC_Theft

In [117]:
# ============================================================
# CELL 114 — AMBIGUOUS CANONICAL COLLISIONS
# ============================================================

ambiguous_collisions = (
    canonical_collisions[
        canonical_collisions[
            "source_feature_count"
        ] > 1
    ]
    .copy()
)

# Mark for review
ambiguous_collisions[
    "review_required"
] = True

ambiguous_collisions[
    "review_reason"
] = (
    "Multiple source column names "
    "map to the same normalized feature. "
    "Verify semantic equivalence before "
    "using as a single modelling feature."
)

display(
    ambiguous_collisions
)

,crime_group,canonical_feature,source_feature_count,source_features,review_required,review_reason
15,IPC,ARSON,2,IPC_ARSON | IPC_Arson,True,Multiple source column names map to the same normalized feature. Verify semantic equivalence before using as a singl...
16,IPC,ASSAULT_ON_WOMEN_WITH_INTENT_TO_OUTRAGE_HER_MODESTY,2,IPC_ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY | IPC_Assault on Women with intent to outrage her Modesty,True,Multiple source column names map to the same normalized feature. Verify semantic equivalence before using as a singl...
24,IPC,AUTO_THEFT,2,IPC_AUTO THEFT | IPC_Auto Theft,True,Multiple source column names map to the same normalized feature. Verify semantic equivalence before using as a singl...
26,IPC,CAUSING_DEATH_BY_NEGLIGENCE,2,IPC_CAUSING DEATH BY NEGLIGENCE | IPC_Causing Death by Negligence,True,Multiple source column names map to the same normalized feature. Verify semantic equivalence before using as a singl...
27,IPC,CHEATING,2,IPC_CHEATING | IPC_Cheating,True,Multiple source column names map to the same normalized feature. Verify semantic equivalence before using as a singl...
34,IPC,CRIMINAL_BREACH_OF_TRUST,2,IPC_CRIMINAL BREACH OF TRUST | IPC_Criminal Breach of Trust,True,Multiple source column names map to the same normalized feature. Verify semantic equivalence before using as a singl...
37,IPC,CRUELTY_BY_HUSBAND_OR_HIS_RELATIVES,2,IPC_CRUELTY BY HUSBAND OR HIS RELATIVES | IPC_Cruelty by Husband or his Relatives,True,Multiple source column names map to the same normalized feature. Verify semantic equivalence before using as a singl...
38,IPC,CULPABLE_HOMICIDE_NOT_AMOUNTING_TO_MURDER,2,IPC_CULPABLE HOMICIDE NOT AMOUNTING TO MURDER | IPC_Culpable Homicide not amounting to Murder,True,Multiple source column names map to the same normalized feature. Verify semantic equivalence before using as a singl...
41,IPC,CUSTODIAL_RAPE,2,IPC_CUSTODIAL RAPE | IPC_Custodial Rape,True,Multiple source column names map to the same normalized feature. Verify semantic equivalence before using as a singl...
42,IPC,DACOITY,2,IPC_DACOITY | IPC_Dacoity,True,Multiple source column names map to the same normalized feature. Verify semantic equivalence before using as a singl...
47,IPC,DOWRY_DEATHS,2,IPC_DOWRY DEATHS | IPC_Dowry Deaths,True,Multiple source column names map to the same normalized feature. Verify semantic equivalence before using as a singl...
62,IPC,KIDNAPPING_ABDUCTION,2,IPC_KIDNAPPING & ABDUCTION | IPC_Kidnapping & Abduction,True,Multiple source column names map to the same normalized feature. Verify semantic equivalence before using as a singl...
72,IPC,MURDER,2,IPC_MURDER | IPC_Murder,True,Multiple source column names map to the same normalized feature. Verify semantic equivalence before using as a singl...
77,IPC,OTHER_IPC_CRIMES,2,IPC_OTHER IPC CRIMES | IPC_Other IPC crimes,True,Multiple source column names map to the same normalized feature. Verify semantic equivalence before using as a singl...
88,IPC,RAPE,2,IPC_RAPE | IPC_Rape,True,Multiple source column names map to the same normalized feature. Verify semantic equivalence before using as a singl...
92,IPC,RIOTS,2,IPC_RIOTS | IPC_Riots,True,Multiple source column names map to the same normalized feature. Verify semantic equivalence before using as a singl...
103,IPC,ROBBERY,2,IPC_ROBBERY | IPC_Robbery,True,Multiple source column names map to the same normalized feature. Verify semantic equivalence before using as a singl...
107,IPC,THEFT,2,IPC_THEFT | IPC_Theft,True,Multiple source column names map to the same normalized feature. Verify semantic equivalence before using as a singl...

In [118]:
# ============================================================
# CELL 115 — SAVE SAFE CANONICAL MAPPING
# ============================================================

canonical_mapping_path = (
    TABLES_DIR /
    "canonical_feature_mapping.csv"
)

canonical_feature_mapping.to_csv(
    canonical_mapping_path,
    index=False,
    encoding="utf-8-sig"
)

print("=" * 80)
print("CANONICAL FEATURE MAPPING SAVED")
print("=" * 80)

print(
    canonical_mapping_path.resolve()
)

================================================================================
CANONICAL FEATURE MAPPING SAVED
================================================================================
D:\Major_Project\Crime_Analysis\outputs\tables\canonical_feature_mapping.csv

In [121]:
# ============================================================
# CELL 116 — IDENTIFY CANONICAL COLUMN GROUPS
# ============================================================

canonical_column_groups = {}

for crime_group in merge_order:

    # --------------------------------------------------------
    # Mapping records belonging to this crime group
    # --------------------------------------------------------

    group_mapping = (
        canonical_feature_mapping[
            canonical_feature_mapping[
                "crime_group"
            ] == crime_group
        ]
        .copy()
    )

    # --------------------------------------------------------
    # Each canonical feature may have one or more
    # source representations.
    # --------------------------------------------------------

    for canonical_feature in (
        group_mapping[
            "canonical_feature"
        ]
        .dropna()
        .unique()
    ):

        source_features = (
            group_mapping[
                group_mapping[
                    "canonical_feature"
                ] == canonical_feature
            ][
                "source_feature"
            ]
            .dropna()
            .astype(str)
            .unique()
            .tolist()
        )

        # ----------------------------------------------------
        # IMPORTANT:
        #
        # source_feature already contains the crime-group
        # prefix in your integrated dataset.
        #
        # Example:
        # IPC_Murder
        # IPC_MURDER
        #
        # Therefore we DO NOT prepend IPC_ again.
        # ----------------------------------------------------

        actual_columns = [
            column
            for column in source_features
            if column in integrated_df.columns
        ]

        if actual_columns:

            canonical_key = (
                f"{crime_group}_{canonical_feature}"
            )

            canonical_column_groups[
                canonical_key
            ] = actual_columns


# ============================================================
# DISPLAY RESULTS
# ============================================================

print("=" * 80)
print("CANONICAL COLUMN GROUPS")
print("=" * 80)

total_groups = len(
    canonical_column_groups
)

multi_column_groups = 0

print(
    f"\nCanonical groups identified: "
    f"{total_groups}"
)

for canonical_name, columns in (
    canonical_column_groups.items()
):

    if len(columns) > 1:

        multi_column_groups += 1

        print(
            f"\n{canonical_name}"
        )

        print(
            "  Source columns:"
        )

        for column in columns:

            print(
                f"    - {column}"
            )

print(
    f"\nCanonical groups with multiple "
    f"source representations: "
    f"{multi_column_groups}"
)

================================================================================
CANONICAL COLUMN GROUPS
================================================================================

Canonical groups identified: 323

IPC_ARSON
  Source columns:
    - IPC_ARSON
    - IPC_Arson

IPC_ASSAULT_ON_WOMEN_WITH_INTENT_TO_OUTRAGE_HER_MODESTY
  Source columns:
    - IPC_ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY
    - IPC_Assault on Women with intent to outrage her Modesty

IPC_AUTO_THEFT
  Source columns:
    - IPC_AUTO THEFT
    - IPC_Auto Theft

IPC_CAUSING_DEATH_BY_NEGLIGENCE
  Source columns:
    - IPC_CAUSING DEATH BY NEGLIGENCE
    - IPC_Causing Death by Negligence

IPC_CHEATING
  Source columns:
    - IPC_CHEATING
    - IPC_Cheating

IPC_CRIMINAL_BREACH_OF_TRUST
  Source columns:
    - IPC_CRIMINAL BREACH OF TRUST
    - IPC_Criminal Breach of Trust

IPC_CRUELTY_BY_HUSBAND_OR_HIS_RELATIVES
  Source columns:
    - IPC_CRUELTY BY HUSBAND OR HIS RELATIVES
    - IPC_Cruelty by Husband or his Relatives

IPC_CULPABLE_HOMICIDE_NOT_AMOUNTING_TO_MURDER
  Source columns:
    - IPC_CULPABLE HOMICIDE NOT AMOUNTING TO MURDER
    - IPC_Culpable Homicide not amounting to Murder

IPC_CUSTODIAL_RAPE
  Source columns:
    - IPC_CUSTODIAL RAPE
    - IPC_Custodial Rape

IPC_DACOITY
  Source columns:
    - IPC_DACOITY
    - IPC_Dacoity

IPC_DOWRY_DEATHS
  Source columns:
    - IPC_DOWRY DEATHS
    - IPC_Dowry Deaths

IPC_KIDNAPPING_ABDUCTION
  Source columns:
    - IPC_KIDNAPPING & ABDUCTION
    - IPC_Kidnapping & Abduction

IPC_MURDER
  Source columns:
    - IPC_MURDER
    - IPC_Murder

IPC_OTHER_IPC_CRIMES
  Source columns:
    - IPC_OTHER IPC CRIMES
    - IPC_Other IPC crimes

IPC_RAPE
  Source columns:
    - IPC_RAPE
    - IPC_Rape

IPC_RIOTS
  Source columns:
    - IPC_RIOTS
    - IPC_Riots

IPC_ROBBERY
  Source columns:
    - IPC_ROBBERY
    - IPC_Robbery

IPC_THEFT
  Source columns:
    - IPC_THEFT
    - IPC_Theft

Canonical groups with multiple source representations: 18

In [122]:
# ============================================================
# CELL 117 — CANONICAL VALUE CONFLICT AUDIT
# ============================================================

canonical_conflicts = []

for canonical_name, columns in (
    canonical_column_groups.items()
):

    # Only groups with multiple source representations
    if len(columns) <= 1:
        continue

    subset = integrated_df[
        columns
    ]

    # --------------------------------------------------------
    # Compare non-null values row by row
    # --------------------------------------------------------

    conflict_count = 0

    for _, row in subset.iterrows():

        non_null_values = (
            row.dropna()
            .tolist()
        )

        # One or zero values cannot conflict
        if len(non_null_values) <= 1:
            continue

        normalized_values = []

        for value in non_null_values:

            try:
                normalized_values.append(
                    float(value)
                )

            except (
                ValueError,
                TypeError
            ):
                normalized_values.append(
                    str(value).strip()
                )

        if len(
            set(normalized_values)
        ) > 1:

            conflict_count += 1

    # --------------------------------------------------------
    # Record only actual conflicts
    # --------------------------------------------------------

    if conflict_count > 0:

        canonical_conflicts.append({

            "canonical_feature":
                canonical_name,

            "source_column_count":
                len(columns),

            "source_columns":
                " | ".join(columns),

            "conflicting_rows":
                conflict_count
        })


canonical_conflicts_df = pd.DataFrame(
    canonical_conflicts
)

print("=" * 80)
print("CANONICAL VALUE CONFLICT AUDIT")
print("=" * 80)

if canonical_conflicts_df.empty:

    print(
        "\n✓ NO CONFLICTING VALUES FOUND."
    )

    print(
        "\nThe multiple source representations "
        "can be safely coalesced."
    )

else:

    print(
        f"\n⚠ CONFLICTING VALUES FOUND: "
        f"{len(canonical_conflicts_df)} "
        f"canonical features"
    )

    display(
        canonical_conflicts_df
    )

================================================================================
CANONICAL VALUE CONFLICT AUDIT
================================================================================

✓ NO CONFLICTING VALUES FOUND.

The multiple source representations can be safely coalesced.

In [123]:
# ============================================================
# CELL 118 — CONSOLIDATE EXACT-EQUIVALENT FEATURES
# ============================================================

canonical_integrated_df = integrated_df.copy()

consolidation_log = []

for canonical_name, columns in (
    canonical_column_groups.items()
):

    # --------------------------------------------------------
    # Single source representation
    # --------------------------------------------------------

    if len(columns) == 1:

        source_column = columns[0]

        # Rename to canonical name where necessary
        if source_column != canonical_name:

            canonical_integrated_df.rename(
                columns={
                    source_column:
                    canonical_name
                },
                inplace=True
            )

            action = "RENAMED"

        else:

            action = "UNCHANGED"

        consolidation_log.append({

            "canonical_feature":
                canonical_name,

            "source_columns":
                source_column,

            "source_column_count":
                1,

            "action":
                action
        })

        continue

    # --------------------------------------------------------
    # Multiple equivalent source representations
    # --------------------------------------------------------

    # Combine the columns from left to right.
    # Since Cell 117 confirmed no conflicts,
    # the first available non-null value is safe.
    
    combined_series = (
        canonical_integrated_df[
            columns
        ]
        .bfill(axis=1)
        .iloc[:, 0]
    )

    canonical_integrated_df[
        canonical_name
    ] = combined_series

    # Remove the old source representations
    columns_to_drop = [
        column
        for column in columns
        if column != canonical_name
    ]

    canonical_integrated_df.drop(
        columns=columns_to_drop,
        inplace=True,
        errors="ignore"
    )

    consolidation_log.append({

        "canonical_feature":
            canonical_name,

        "source_columns":
            " | ".join(columns),

        "source_column_count":
            len(columns),

        "action":
            "COALESCED"
    })


consolidation_log_df = pd.DataFrame(
    consolidation_log
)

print("=" * 80)
print("CANONICAL FEATURE CONSOLIDATION")
print("=" * 80)

print(
    f"\nCanonical groups processed: "
    f"{len(consolidation_log_df)}"
)

print(
    "\nActions:"
)

print(
    consolidation_log_df[
        "action"
    ].value_counts()
)

display(
    consolidation_log_df
)

================================================================================
CANONICAL FEATURE CONSOLIDATION
================================================================================

Canonical groups processed: 323

Actions:
action
RENAMED      303
COALESCED     18
UNCHANGED      2
Name: count, dtype: int64

,canonical_feature,source_columns,source_column_count,action
0,IPC_ACID_ATTACK,IPC_Acid attack,1,RENAMED
1,IPC_ARSON,IPC_ARSON | IPC_Arson,2,COALESCED
2,IPC_ASSAULT_ON_WOMEN_WITH_INTENT_TO_OUTRAGE_HER_MODESTY,IPC_ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY | IPC_Assault on Women with intent to outrage her Modesty,2,COALESCED
3,IPC_ASSAULT_OR_USE_OF_CRIMINAL_FORCE_TO_WOMEN_WITH_INTENT_TO_DISROBE,IPC_Assault or use of criminal force to women with intent to Disrobe,1,RENAMED
4,IPC_ATTEMPT_TO_ACID_ATTACK,IPC_Attempt to Acid Attack,1,RENAMED
...,...,...,...,...
318,WOMEN_SEXUAL_HARASSMENT,WOMEN_Sexual Harassment,1,RENAMED
319,WOMEN_STALKING,WOMEN_Stalking,1,RENAMED
320,WOMEN_TOTAL_CRIMES_AGAINST_WOMEN,WOMEN_Total Crimes against Women,1,RENAMED
321,WOMEN_UNNATURAL_OFFENCES,WOMEN_UnNatural Offences,1,RENAMED
322,WOMEN_VOYEURISM,WOMEN_Voyeurism,1,RENAMED

In [124]:
# ============================================================
# CELL 119 — POST-CONSOLIDATION ROW AUDIT
# ============================================================

print("=" * 80)
print("POST-CONSOLIDATION AUDIT")
print("=" * 80)

before_rows = integrated_df.shape[0]
before_columns = integrated_df.shape[1]

after_rows = canonical_integrated_df.shape[0]
after_columns = canonical_integrated_df.shape[1]

print(
    f"\nBefore consolidation:"
)

print(
    f"  Rows    : {before_rows:,}"
)

print(
    f"  Columns : {before_columns:,}"
)

print(
    f"\nAfter consolidation:"
)

print(
    f"  Rows    : {after_rows:,}"
)

print(
    f"  Columns : {after_columns:,}"
)

print(
    f"\nRow difference:"
    f" {after_rows - before_rows:,}"
)

print(
    f"\nColumn reduction:"
    f" {before_columns - after_columns:,}"
)

duplicate_keys = (
    canonical_integrated_df
    .duplicated(
        integration_key
    )
    .sum()
)

print(
    f"\nDuplicate integration keys:"
    f" {duplicate_keys:,}"
)

# ------------------------------------------------------------
# Hard validation
# ------------------------------------------------------------

assert after_rows == before_rows, (
    "ERROR: Row count changed during "
    "canonical consolidation."
)

assert duplicate_keys == 0, (
    "ERROR: Duplicate integration keys "
    "appeared after consolidation."
)

print(
    "\n✓ Row count preserved."
)

print(
    "✓ Integration keys remain unique."
)

================================================================================
POST-CONSOLIDATION AUDIT
================================================================================

Before consolidation:
  Rows    : 9,856
  Columns : 349

After consolidation:
  Rows    : 9,856
  Columns : 331

Row difference: 0

Column reduction: 18

Duplicate integration keys: 0

✓ Row count preserved.
✓ Integration keys remain unique.

In [129]:
# ============================================================
# CELL 120 — CANONICAL IPC FEATURE CHECK
# ============================================================

ipc_columns = [
    column
    for column in canonical_integrated_df.columns
    if column.startswith("IPC_")
]

print("=" * 80)
print("CANONICAL IPC FEATURES")
print("=" * 80)

print(
    f"\nIPC feature count: "
    f"{len(ipc_columns)}"
)

for column in ipc_columns:
    print(
        f"  {column}"
    )

================================================================================
CANONICAL IPC FEATURES
================================================================================

IPC feature count: 101
  IPC_MURDER
  IPC_ATTEMPT_TO_MURDER
  IPC_RAPE
  IPC_OTHER_RAPE
  IPC_KIDNAPPING_AND_ABDUCTION_OF_WOMEN_AND_GIRLS
  IPC_KIDNAPPING_AND_ABDUCTION_OF_OTHERS
  IPC_DACOITY
  IPC_PREPARATION_AND_ASSEMBLY_FOR_DACOITY
  IPC_ROBBERY
  IPC_BURGLARY
  IPC_THEFT
  IPC_OTHER_THEFT
  IPC_RIOTS
  IPC_CHEATING
  IPC_COUNTERFIETING
  IPC_ARSON
  IPC_HURT_GREVIOUS_HURT
  IPC_INSULT_TO_MODESTY_OF_WOMEN
  IPC_IMPORTATION_OF_GIRLS_FROM_FOREIGN_COUNTRIES
  IPC_TOTAL_IPC_CRIMES
  IPC_ATTEMPT_TO_COMMIT_MURDER
  IPC_ATTEMPT_TO_COMMIT_CULPABLE_HOMICIDE
  IPC_CUSTODIAL_GANG_RAPE
  IPC_CUSTODIAL_OTHER_RAPE
  IPC_RAPE_OTHER_THAN_CUSTODIAL
  IPC_RAPE_GANG_RAPE
  IPC_RAPE_OTHERS
  IPC_ATTEMPT_TO_COMMIT_RAPE
  IPC_KIDNAPPING_ABDUCTION_TOTAL
  IPC_KIDNAPPING_ABDUCTION_IN_ORDER_TO_MURDER
  IPC_KIDNAPPING_FOR_RANSOM
  IPC_KIDNAPPING_ABDUCTION_OF_WOMEN_TO_COMPEL_HER_FOR_MARRIAGE
  IPC_OTHER_KIDNAPPING
  IPC_DACOITY_WITH_MURDER
  IPC_OTHER_DACOITY
  IPC_MAKING_PREPARATION_AND_ASSEMBLY_FOR_COMMITTING_DACOITY
  IPC_CRIMINAL_TRESPASS_BURGLARY
  IPC_CRIMINAL_TRESPASS_OR_BURGLARY
  IPC_HOUSE_TRESPASS_HOUSE_BREAKING
  IPC_OTHER_THEFTS
  IPC_UNLAWFUL_ASSEMBLY
  IPC_RIOTS_COMMUNAL
  IPC_RIOTS_INDUSTRIAL
  IPC_RIOTS_POLITICAL
  IPC_RIOTS_CASTE_CONFLICT
  IPC_RIOTS_SC_STS_VS_NON_SCS_STS
  IPC_RIOTS_OTHER_CASTE_CONFLICT
  IPC_RIOTS_AGRARIAN
  IPC_RIOTS_STUDENTS
  IPC_RIOTS_SECTARIAN
  IPC_RIOTS_OTHERS
  IPC_FORGERY
  IPC_COUNTERFEITING
  IPC_COUNTERFEIT_OFFENCES_RELATED_TO_COUNTERFEIT_COIN
  IPC_COUNTERFEITING_GOVERNMENT_STAMP
  IPC_COUNTERFEIT_CURRENCY_BANK_NOTES
  IPC_COUNTERFEITING_CURRENCY_NOTES_BANK_NOTES
  IPC_USING_FORGED_OR_COUNTERFEITING_CURRENCY_BANK_NOTES
  IPC_POSSESSION_OF_FORGED_OR_COUNTERFEITING_CURRENCY_BANK_NOTES
  IPC_MAKING_OR_POSSESSING_MATERIALS_FOR_FORGED_CURRENCY_BANK_NOTES
  IPC_MAKING_OR_USING_DOCUMENTS_RESEMBLING_CURRENCY
  IPC_GRIEVOUS_HURT
  IPC_HURT
  IPC_ACID_ATTACK
  IPC_ATTEMPT_TO_ACID_ATTACK
  IPC_SEXUAL_HARASSMENT
  IPC_ASSAULT_OR_USE_OF_CRIMINAL_FORCE_TO_WOMEN_WITH_INTENT_TO_DISROBE
  IPC_VOYEURISM
  IPC_STALKING
  IPC_OTHER_ASSAULT_ON_WOMEN
  IPC_INSULT_TO_THE_MODESTY_OF_WOMEN
  IPC_AT_OFFICE_PREMISES
  IPC_OTHER_PLACES_RELATED_TO_WORK
  IPC_IN_PUBLIC_TRANSPORT_SYSTEM
  IPC_PLACES_OTHER_THAN_231_232_233
  IPC_IMPORTATION_OF_GIRLS_FROM_FOREIGN_COUNTRY
  IPC_DEATHS_DUE_TO_NEGLIGENT_DRIVING_ACT
  IPC_DEATHS_DUE_TO_OTHER_CAUSES
  IPC_OFFENCES_AGAINST_STATE
  IPC_SEDITION
  IPC_OTHER_OFFENCES_AGAINST_STATE
  IPC_OFFENCES_PROMOTING_ENMITY_BETWEEN_DIFFERENT_GROUPS
  IPC_PROMOTING_ENMITY_BETWEEN_DIFFERENT_GROUPS
  IPC_IMPUTATION_ASSERTIONS_PREJUDICIAL_TO_NATIONAL_INTEGRATION
  IPC_EXTORTION
  IPC_DISCLOSURE_OF_IDENTITY_OF_VICTIMS
  IPC_INCIDENCE_OF_RASH_DRIVING
  IPC_HUMANTRAFFICKING
  IPC_UNNATURAL_OFFENCE
  IPC_TOTAL_COGNIZABLE_IPC_CRIMES
  IPC_AVAILABLE
  IPC_ASSAULT_ON_WOMEN_WITH_INTENT_TO_OUTRAGE_HER_MODESTY
  IPC_AUTO_THEFT
  IPC_CAUSING_DEATH_BY_NEGLIGENCE
  IPC_CRIMINAL_BREACH_OF_TRUST
  IPC_CRUELTY_BY_HUSBAND_OR_HIS_RELATIVES
  IPC_CULPABLE_HOMICIDE_NOT_AMOUNTING_TO_MURDER
  IPC_CUSTODIAL_RAPE
  IPC_DOWRY_DEATHS
  IPC_KIDNAPPING_ABDUCTION
  IPC_OTHER_IPC_CRIMES

In [128]:
# ============================================================
# CELL 121 — SAVE CANONICAL INTEGRATED DATASET
# ============================================================

canonical_integrated_path = (
    PROCESSED_DATA_DIR /
    "district_integrated_canonical.csv"
)

canonical_integrated_df.to_csv(
    canonical_integrated_path,
    index=False,
    encoding="utf-8-sig"
)

print("=" * 80)
print("CANONICAL INTEGRATED DATASET SAVED")
print("=" * 80)

print(
    "\nPath:"
)

print(
    canonical_integrated_path.resolve()
)

print(
    f"\nShape:"
    f" {canonical_integrated_df.shape[0]:,} rows × "
    f"{canonical_integrated_df.shape[1]:,} columns"
)

================================================================================
CANONICAL INTEGRATED DATASET SAVED
================================================================================

Path:
D:\Major_Project\Crime_Analysis\data\processed\district_integrated_canonical.csv

Shape: 9,856 rows × 331 columns

In [132]:
# ============================================================
# CELL 122 — FINAL DATASET VALIDATION
# ============================================================

print("=" * 80)
print("FINAL CANONICAL DATASET VALIDATION")
print("=" * 80)

# ------------------------------------------------------------
# Required key columns
# ------------------------------------------------------------

required_keys = [
    "STATE",
    "UNIT_NAME",
    "YEAR"
]

missing_keys = [
    col
    for col in required_keys
    if col not in canonical_integrated_df.columns
]

assert not missing_keys, (
    f"Missing required key columns: {missing_keys}"
)

# ------------------------------------------------------------
# Row/key validation
# ------------------------------------------------------------

duplicate_keys = (
    canonical_integrated_df
    .duplicated(required_keys)
    .sum()
)

assert duplicate_keys == 0, (
    "Duplicate STATE + UNIT_NAME + YEAR keys found."
)

# ------------------------------------------------------------
# Basic statistics
# ------------------------------------------------------------

row_count = len(canonical_integrated_df)

column_count = len(
    canonical_integrated_df.columns
)

unique_key_count = (
    canonical_integrated_df[
        required_keys
    ]
    .drop_duplicates()
    .shape[0]
)

missing_cell_count = int(
    canonical_integrated_df
    .isna()
    .sum()
    .sum()
)

memory_mb = (
    canonical_integrated_df
    .memory_usage(deep=True)
    .sum()
    / (1024 ** 2)
)

# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

print(
    f"\nRows              : {row_count:,}"
)

print(
    f"Columns           : {column_count:,}"
)

print(
    f"Unique keys       : {unique_key_count:,}"
)

print(
    f"Duplicate keys    : {duplicate_keys:,}"
)

print(
    f"Missing cells     : {missing_cell_count:,}"
)

print(
    f"Memory usage      : {memory_mb:.2f} MB"
)

print(
    "\n✓ Canonical dataset passed validation."
)

================================================================================
FINAL CANONICAL DATASET VALIDATION
================================================================================

Rows              : 9,856
Columns           : 331
Unique keys       : 9,856
Duplicate keys    : 0
Missing cells     : 2,370,879
Memory usage      : 25.65 MB

✓ Canonical dataset passed validation.

In [134]:
# ============================================================
# CELL 123 — SAVE FINAL PROJECT OUTPUTS
# ============================================================

# ------------------------------------------------------------
# Final canonical dataset
# ------------------------------------------------------------

final_canonical_path = (
    PROCESSED_DATA_DIR /
    "district_integrated_final.csv"
)

canonical_integrated_df.to_csv(
    final_canonical_path,
    index=False,
    encoding="utf-8-sig"
)

# ------------------------------------------------------------
# Final data dictionary
# ------------------------------------------------------------

final_dictionary = pd.DataFrame({

    "column_name":
        canonical_integrated_df.columns,

    "data_type": [
        str(
            canonical_integrated_df[col].dtype
        )
        for col in canonical_integrated_df.columns
    ],

    "missing_count": [
        int(
            canonical_integrated_df[col].isna().sum()
        )
        for col in canonical_integrated_df.columns
    ],

    "missing_pct": [
        round(
            100 *
            canonical_integrated_df[col].isna().mean(),
            2
        )
        for col in canonical_integrated_df.columns
    ],

    "unique_values": [
        int(
            canonical_integrated_df[col].nunique(
                dropna=True
            )
        )
        for col in canonical_integrated_df.columns
    ]
})

dictionary_path = (
    TABLES_DIR /
    "final_data_dictionary.csv"
)

final_dictionary.to_csv(
    dictionary_path,
    index=False,
    encoding="utf-8-sig"
)

# ------------------------------------------------------------
# Final integration report
# ------------------------------------------------------------

final_report = pd.DataFrame([{
    "dataset":
        "India District Crime Integrated Dataset",

    "rows":
        len(canonical_integrated_df),

    "columns":
        len(canonical_integrated_df.columns),

    "unique_keys":
        canonical_integrated_df[
            required_keys
        ].drop_duplicates().shape[0],

    "duplicate_keys":
        int(duplicate_keys),

    "total_missing_cells":
        int(
            canonical_integrated_df
            .isna()
            .sum()
            .sum()
        )
}])

report_path = (
    TABLES_DIR /
    "final_integration_report.csv"
)

final_report.to_csv(
    report_path,
    index=False,
    encoding="utf-8-sig"
)

# ------------------------------------------------------------
# Final output
# ------------------------------------------------------------

print("=" * 80)
print("FINAL PROJECT DATASET CREATED")
print("=" * 80)

print(
    "\nDataset:"
)

print(
    final_canonical_path.resolve()
)

print(
    "\nData dictionary:"
)

print(
    dictionary_path.resolve()
)

print(
    "\nIntegration report:"
)

print(
    report_path.resolve()
)

print(
    "\n✓ PHASE 1 — DATA INTEGRATION COMPLETE."
)

================================================================================
FINAL PROJECT DATASET CREATED
================================================================================

Dataset:
D:\Major_Project\Crime_Analysis\data\processed\district_integrated_final.csv

Data dictionary:
D:\Major_Project\Crime_Analysis\outputs\tables\final_data_dictionary.csv

Integration report:
D:\Major_Project\Crime_Analysis\outputs\tables\final_integration_report.csv

✓ PHASE 1 — DATA INTEGRATION COMPLETE.

In [135]:
# ============================================================
# CELL 124 — FINAL CHECKPOINT
# ============================================================

print("=" * 80)
print("PROJECT DATA INTEGRATION — FINAL CHECKPOINT")
print("=" * 80)

print("""
✓ 76 raw CSV files audited
✓ 14 district-level datasets identified
✓ Dataset families classified
✓ Geographic dimensions normalized
✓ Temporal dimensions normalized
✓ Duplicate records investigated
✓ Conflicting duplicates investigated
✓ Core keys validated
✓ 5 crime families integrated
✓ 9,856 unique district-year records created
✓ Schema evolution documented
✓ Feature temporal coverage documented
✓ Canonical feature names created
✓ 18 duplicate source representations consolidated
✓ No canonical value conflicts
✓ 331-column canonical dataset created
✓ Final dataset saved
✓ Data dictionary saved
✓ Integration report saved

NEXT PHASE:
EDA → Feature Engineering → ML/DL → Evaluation
""")

print(
    f"FINAL DATASET: "
    f"{canonical_integrated_df.shape[0]:,} rows × "
    f"{canonical_integrated_df.shape[1]:,} columns"
)

================================================================================
PROJECT DATA INTEGRATION — FINAL CHECKPOINT
================================================================================

✓ 76 raw CSV files audited
✓ 14 district-level datasets identified
✓ Dataset families classified
✓ Geographic dimensions normalized
✓ Temporal dimensions normalized
✓ Duplicate records investigated
✓ Conflicting duplicates investigated
✓ Core keys validated
✓ 5 crime families integrated
✓ 9,856 unique district-year records created
✓ Schema evolution documented
✓ Feature temporal coverage documented
✓ Canonical feature names created
✓ 18 duplicate source representations consolidated
✓ No canonical value conflicts
✓ 331-column canonical dataset created
✓ Final dataset saved
✓ Data dictionary saved
✓ Integration report saved

NEXT PHASE:
EDA → Feature Engineering → ML/DL → Evaluation

FINAL DATASET: 9,856 rows × 331 columns